content/fast/use-imagemin-to-compress-images/codelab-imagemin-webpack.md

Fix: $ webpack --config webpack.config.js --mode production
/app/node_modules/webpack-cli/bin/cli.js:244
throw err;
^
Error: Cannot find module 'imagemin-mozjpeg'

Install the Mozjpeg plugin

---

content/fast/use-imagemin-to-compress-images/codelab-imagemin-gulp.md

Codelab was linking to grunt glitch, and it should be gulp glitch.

Codelab linking to wrong glitch!

---

.travis.yml
README.md
package.json

Check that PRs don't break the build command.

Add travis.

---

content/fast/use-lazysizes-to-lazyload-images/codelab-use-lazysizes-to-lazyload-images.md

The note is in html, but the link was in markdown-- so I've changed that.

Fixing broken link in codelab-use-lazysizes-to-lazyload-images.md

---

content/fast/avoid-invisible-text/codelab-avoid-invisible-text.md

This PR fix #521 adding a cleaner example

Fix #521 - Use classList in codelab-avoid-invisible-text

---

lib/config/contributors.js

The file name is: https://github.com/GoogleChrome/web.dev/blob/master/content/images/contributors/no-photo.jpg

contributors.js: use correct filename for missing author image

---

lib/deps/yaml-prefix.js

This should make `npm run build` work again on Windows.
I think the way the build is currently implemented is it's manually stripping the yaml out of the markdown and then parsing the files separately. There's a nicer module that does this, [js-yaml-front-matter](https://github.com/dworthen/js-yaml-front-matter), that I've used before. But adding it would be a bigger refactor of these scripts. Putting that off for another day 🌅

Fix build on Windows.

---

content/reliable/identify-resources-via-network-panel/index.md

Fixes #223.
Addresses (most) of the feedback there from @alankent.
There are some style-related comments that I'm not sure need to be fixed, e.g. the use of contractions seems okay. The reference to "dark forces" affecting the network wasn't my wording to begin with (maybe it was Meggin?) so I'm hesitant to change it.

"Identify resources loaded from the network" cleanup

---

content/reliable/network-connections-unreliable/index.md

The change to `marked` in the previous PR fixed a few of these issues. But this one seemed to persist and needs slightly different syntax to work.

Fix broken italics.

---

lib/config/filters.js
lib/config/generators.js

Related to #580
It looks like we tweaked the name of a project in a recent PR and inadvertently updated its URL.

Add redirects.yaml to build step.

---

lib/config/generators.js

It turns out we just need to copy the _redirects.yaml over, we don't need to also add meta tags to the page.

Don't add redirects meta tag to html

---

CODEOWNERS

Adds a CODEOWNERS file to go along with branch protection settings.
Read more here:
https://help.github.com/articles/about-code-owners/

Add code owners.

---

content/fast/serve-modern-code-to-modern-browsers/codelab-serve-modern-code.md

`type="module"` are added to all `.mjs`, and `nomodule` attributes are added to `.js`

Correct .mjs, .js typo

---

content/robots.txt

This is a recommendation from search console. I'll update the devsite template to use the `noindex` meta tag.

Use noindex instead of robots.txt to block search pages.

---

content/discoverable/fix-http-status-codes/codelab-fix-sneaky-404.md

Not sure what happened but I noticed this glitch started 404ing. Looks like the name was updated maybe? This PR should fix it.
Glitch is here:
https://glitch.com/~fix-sneaky-404

Fix missing glitch

---

content/secure/same-origin-policy/index.md

Fixes double-quotes merged into links at https://web.dev/secure/same-origin-policy as displayed below:

Secure Guide - Doc fix for double-quotes merged into links 

---

content/fast/reduce-network-payloads-using-text-compression/codelab-text-compression.md
content/fast/reduce-network-payloads-using-text-compression/index.md

Webpac v4 now uses Terser as a default minification tool, not UglifyJS.
This updates a codelab to change mentions of UglifyJS to Terser.

change mention of uglifyjs to terser

---

CODEOWNERS

- Scopes down the list of code owners to just rob, sam, and meggin.

Update codeowners so it's a much smaller list.

---

CODEOWNERS

- Cut down on spam by only having Rob as a default codeowner

Remove Sam from default codeowners

---

content/secure/cross-origin-resource-sharing/index.md

The cross-origin-resource-sharing article had a word spelled 'shearing' when it was meant to be 'sharing'

fix typo in CORS article

---

app.yaml

This should redirect incoming HTTP responses to HTTPS
- Updated default handler in `app.yaml`
I gave this a quick test and it looks like it works, but please sanity check!

Redirect to HTTPS by default

---

src/site/_includes/codelab.njk

- Codelabs were including the learning path in the URL but all URLs should be flat now.

Fix path links in codelabs.

---

src/site/content/en/measure/index.njk

Fixes #755.
- Update the language in the measure page based on #755.
This does not include all of the changes in #755 because we'd need to write some updated CSS for those and unfortunately we missed the cut for I/O. But this at least explains how the Lighthouse scoring works and updates all of the existing static text.
I removed all of the links to various Lighthouse formats because I didn't think it really helped much and we're already linking to the Lighthouse landing page.

Improve the language on the measure page.

---

src/site/content/en/blog/hands-on-portals/index.md

Deleting the fig caption "Fig. 1 — Portals demo showing navigation between chapters" since 1) The caption is not correct (chapters is for the manga demo in CDS) and 2) Nothing is referring to it anymore due to #892 .

Nit fix - deleting stale fig caption

---

src/site/content/en/fast/use-lazysizes-to-lazyload-images/index.md

- Adding an `alt` attribute to each `img` tag within the article
More information:
Following a discussion we had on Twitter. I would like to propose the addition of a `alt` attribute to each instance of an image tag.
I know that this attribute is not related to the lazy-loading system described in this article but it could be a good practice to always display the alt attribute in tutorial.
This attribute is mandatory on an accessibility point-of-view to either provide a textual alternative or to declare the image as decorative with an empty alt.
Also, if the presence would trigger questions, we can always make a link to the article about this from the same platform:
https://web.dev/labels-and-text-alternatives/#include-text-alternatives-for-images-and …

Add `alt` attribute to each image tag

---

src/site/content/en/react/code-splitting-suspense/index.md

Fixes #915
- Adds a new section that describes using an error boundary to handle lazy-loading failures.
---
If this PR adds **new content** please fill out the form below.
If this PR changes existing content you can delete the form.
---

Adds guidance about error boundaries to React.lazy docs

---

src/site/content/en/blog/proxx-announce/index.md

- The [proxx anouncement blog](https://web.dev/proxx-announce/) didn't have the link of the github repo. I have added that to the blog.
---
👋 Thanks for submitting this PR! Please take a moment to let us know what's been added.

Added missing proxx github repo link

---

src/site/content/en/fast/codelab-serve-images-correct-dimensions/index.md
src/site/content/en/fast/serve-images-with-correct-dimensions/index.md
src/site/content/en/fast/serve-responsive-images/index.md

Fixes #576.
Previous ImageMagick command did not work on Windows. This command works on Mac & Windows.

Fixes #576 (imagemagick commmand broken on windows)

---

src/site/_includes/codelab.njk

Adds the ability pass a previewsize to a codelab, giving the author the ability to control whether or not a preview is shown 👍 
- accept a previewSize param from frontmatter

enables customizing previewSize from front matter

---

src/site/content/en/react/virtualize-long-lists-react-window/index.md

Fixes # . (Not mentioned in Issues)
In https://web.dev/virtualize-long-lists-react-window/
- Fix the usage of InfiniteLoader
---
Thanks for the wonderful article which is useful in real use cases!
My proposal is about the usage of the library mentioned in the article which title is `Virtualize large lists with react-window`.
---
I think the usage of `react-window-infinite-loader` is wrong.
`itemCount` should be the size of the remote data. If it's unknown, it should be a larger value than the current value. The codes in the article didn't work well.
It is mentioned in the official readme.
https://github.com/bvaughn/react-window-infinite-loader#example-usage
https://github.com/bvaughn/react-window-infinite-loader#creating-an-infinite-loading-list

Fix the usage of react-window-infinite-loader

---

src/site/content/en/fast/defer-non-critical-css/index.md

Adding reference to the [Extract critical CSS guide](https://web.dev/extract-critical-css/), so developers can continue navigating to that article, after reading the [Defer Unused CSS](https://web.dev/defer-non-critical-css) one.

Link "Defer unused CSS" guide to "Extract critical CSS" guide.

---

src/site/content/en/blog/youtube-media-capabilities/index.md

Remove double "While this told the developer" from the youtube-media-capabilities blog posts.

Fix double sentence in youtube-media-capabilities

---

src/site/content/en/blog/samesite-cookies-explained/index.md

- Examples have been moved to their own repo at https://github.com/GoogleChromeLabs/samesite-examples
- Reference added for Safari bug along with explanation
- Added `alt` text for images
-Switched to `.example` for mock domains
- Cleaned up formatting

Update examples for "SameSite cookies explained blog"

---

src/styles/generic/_lists.scss

Fixes an issue where nested ordered lists were forcing the outer list to increment.
See example on: https://web.dev/value-of-speed/
- Only increment lists when the immediate child is an li, ignoring nested sublists.

Don't increment numbered lists when there are nested lists.

---

src/site/content/en/lighthouse-accessibility/aria-allowed-attr/index.md
src/site/content/en/lighthouse-accessibility/focus-traps/index.md

fix typo: "elememnt" -> "element"

---

src/site/content/en/blog/google-search-sw/index.md

Hey @robdodson—I think something happened in the course of [force-pushing](https://github.com/GoogleChrome/web.dev/pull/989#commits-pushed-f4cb485) the last-minute changes to the Google Search SW case study. I just noticed that the text matches my original language, before all of @Meggin's (excellent) edits, so I think you accidentally used my original commit as the base.
Fortunately, I still had a copy of the text with all of the edits in a local branch, and I've created this PR to get the edits reinstated.

Restore the edits to the Google Search case study

---

.gitignore
src/site/content/en/fast/codelab-text-compression/index.md

Remove unnecessary `strong` tags in articles.
- Removes strong tags
- Updates `.gitignore`
live url: https://web.dev/codelab-text-compression

Remove strong stags

---

package.json

Fixes the license expression warning.
`yarn start`
Looking forward, peace! ✌️

👌 IMPROVE: Valid SPDX License Expression

---

src/site/content/en/blog/speed-at-scale/index.md
src/site/content/en/fast/fast.11tydata.js

Also renamed section from "Enforce Performance Budgets" to "Set Performance Budgets".

Move perf budgets to start of /fast

---

src/site/content/en/about/index.njk
src/site/content/en/reliable/codelab-service-workers/index.md
src/site/content/en/reliable/reliable.11tydata.js
src/site/content/en/reliable/runtime-caching-with-workbox/index.md
src/site/content/en/reliable/service-workers-cache-storage/index.md

- Consistently use "reliable/reliability" rather than "resilient/resilience" across the site.

Fix all instances of "resilient/resilience"

---

src/site/content/en/blog/prefers-color-scheme/index.md

`currentColor` is also supported in `<svg><use href="…"></use></svg>` apart from inline SVG. This patch adds this bit of information. Thanks, @xeenon!

Add referenced SVG tip to prefers-color-scheme article

---

src/site/content/en/fast/codelab-text-compression-brotli/index.md

This commit fixes issue #829 by specifying the Content-Type header for Brotli responses.
Fixes # 829.
- 
- 
-

Brotli fix

---

src/site/_includes/codelab.njk

Fixes #807, #404.
- Force-hide the codelab footer on devsite using an inline style element.
On DevSite every page uses the same layout so we don't have a good signifier of when a codelab is displaying. We could use client-side JS to add a class to the body but devsite tends to load its JS quite slow so there would potentially be some weird FOUC issues with this. When we migrate off of devsite we should be able to remove this workaround.

Hide codelab footer on devsite.

---

src/site/content/en/fast/serve-modern-code-to-modern-browsers/index.md

Fixes #1116 
- Adds a note about double-fetching to serve modern code guide and links to Jason's article on the subject

Adds note about double fetching to serve modern code guide

---

src/site/content/en/accessible/use-semantic-html/index.md

Fixes #1020 .
- Update the text to clarify when to use an anchor or a button.

Clarify a versus button usage.

---

src/site/content/en/accessible/style-focus/index.md

Fixes grammar issue in 2e2ef6204ff7416433ac5ebfd2aeae547a87e17b.
The updated information to fix #1047 looks great, but I noticed a tiny grammar issue that this PR fixes. 🙂 
> "Because the behavior of focus ~~be~~ **is** inconsistent, ..."
---
Here's a reference from Grammarly:

Change verb to correct grammar

---

.eleventy.js
src/site/_collections/post-descending.js
src/site/_collections/posts-with-lighthouse.js
src/site/_collections/recent-posts.js
src/site/_filters/live-posts.js
src/site/_includes/components/ArticleNavigation.js
src/site/_includes/layout.njk
src/site/_includes/partials/post.njk
src/site/_includes/partials/topic.njk
src/site/_includes/path.njk
src/site/content/en/blog/index.njk
src/site/content/en/feed.njk

Fixes #725
- Adds a `livePosts` filter. If a post has a `draft: true` flag in its YAML, or its `date` is greater than today then it will be marked as a `draft` and removed from eleventy collections.
- If a post is marked as a `draft` then its layout will get a meta noindex flag to prevent search crawling.
**Caveats**
It's important to note that eleventy will still produce a copy of the post in the `dist/` directory and this copy will still get published on the server. However, nothing will be linking to it. This does mean that if someone is able to _guess_ the URL and type it in manually that they could see the content. But since the post will already be checked in to our GitHub repo at this point that seems like it's not a big deal.
If authors want …

Add scheduled and draft posts.

---

src/site/content/en/handbook/quick-start/index.md

- Link to new content template on handbook Quick start page.

Update content template link in handbook

---

src/site/content/en/angular/accessible-angular-with-codelyzer/index.md
src/site/content/en/angular/get-started-optimize-angular/index.md
src/site/content/en/angular/precaching-with-the-angular-service-worker/index.md
src/site/content/en/blog/predictive-prefetching/index.md
src/site/content/en/handbook/audience/index.md
src/site/content/en/handbook/content-types/index.md
src/site/content/en/handbook/grammar/index.md
src/site/content/en/handbook/inclusion-and-accessibility/index.md
src/site/content/en/handbook/markup-code/index.md
src/site/content/en/handbook/markup-media/index.md
src/site/content/en/handbook/markup-post-codelab/index.md
src/site/content/en/handbook/markup-sample-app/index.md
src/site/content/en/handbook/quick-start/index.md
src/site/content/en/handbook/style/index.md
src/site/content/en/handbook/use-media/index.md
src/site/content/en/handbook/web-dev-components/index.md
src/site/content/en/handbook/write-code-samples/index.md
src/site/content/en/reliable/codelab-http-cache/codelab-http-cache.md

Remove quotation marks around linked article titles, [per GDDSC](https://developers.google.com/style/cross-references#formatting-cross-references). (A misleading example on another GDDSC page made it seem like quotation marks were desired. That example has since been removed.)

Update link formatting

---

src/site/_includes/styles.njk
src/site/content/en/blog/layout-instability-api/index.md
src/styles/components/_asides.scss

This PR includes changes to the Layout Instability API in Chrome 77, including:
- Renaming the `entryType` value to `layout-shift`
- Adding the `buffered: true` flag
- Using `type` instead of `entryTypes` (required for the buffered flag)
- Adding `entry.hadRecentInput` to the example
It also includes a small change to the `_asides.scss` partial to fix some issues with styling code blocks within asides.
/cc @skobes @npm1 @ericandrewlewis

Layout Instability API updates for Chrome 77

---

src/site/content/en/lighthouse-performance/uses-text-compression/index.md

`content-heading` didn't make sense in this context (it was talking about content encodings, not headers), don't know if it even exists. (in the illustration, it pointed to `content-encoding` too.)
* Changed `content-heading` to `content-encoding`
Thanks.

Changed `content-heading` to `content-encoding`

---

src/site/content/en/blog/layout-instability-api/index.md

This PR updates the Layout Instability API post to use the aside shortcodes consistently (based on what was discussed in a chat conversation between me, @robdodson, and @mfriesenhahn).

Use the aside shortcodes consistently in the Layout Instability API article

---

src/site/_includes/content/houdini.njk

This is an industry-wide project name. (https://developer.mozilla.org/en-US/docs/Web/Houdini). The first article that will need this will be part of Chrome 77, so this will need to be merged before Aug 8.

Add blurb for future Houdini articles.

---

src/site/_includes/content/origin-trials.njk

Fixes #1183
- Adds a link to the origin trials registration page to the origin trials blurb.

Add registration link to origin trial blurb.

---

src/lib/app.js
src/lib/components/UrlChooser/_styles.scss
src/lib/components/UrlChooser/index.js
src/lib/components/UrlChooserContainer/index.js
src/lib/components/_all.scss
src/lib/fb.js
src/lib/store.js
src/site/content/en/measure/index.njk

Adds `web-url-chooser` and `web-url-chooser-container` to choose URL to Audit. Pulls and saves to Firestore.
This diverges from the DevSite model a bit. Entering a URL has a reasonably complex state machine (e.g., once you "Switch URL", you cannot get your old URL back), and now it's tied to real-time storage (as opposed to in DevSite, which polled occasionally).

add web-url-chooser{,-container} to choose audit URL

---

src/site/_filters/live-posts.js

Context: https://github.com/GoogleChrome/web.dev/pull/1222#issuecomment-516343087
Previously if you set a `date` for your post that was in the future it would not show up on the site. This is a "feature" but it also feels like a bug. Because we have to manually publish the site anyway it doesn't seem like we get a lot of value out of a scheduled posts feature and it is potentially confusing for authors. Let's disable it and just keep the `draft` flag.
- Disables the scheduled posts feature added in #1169.  
- Keep the `draft: true` functionality since that's opt-in.

Disable scheduled posts.

---

src/site/content/en/blog/prefers-color-scheme/index.md

- This makes an `h2.clearfix` linkable by adding an `id`.

Add missing `id` to `h2.clearfix`

---

src/site/content/en/angular/faster-angular-change-detection/index.md

Because of the high memory consumption of the embedded StackBlitz editors the page was crashing on iOS Safari. With this change, we show videos instead of editors and link to StackBlitz.

Replace StackBlitz demos with videos

---

.eleventy.js
src/site/_filters/remove-drafts.js
src/site/_includes/components/PathCard.js
src/site/_includes/path.njk

Fixes #1265.
- Adds a `removeDrafts` filter function which can be used to filter an array of learing path topics. For example, if one of the topics arrays in the accessible learning path (https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/accessible/accessible.11tydata.js) contained draft posts, it would filter those posts out of the array.
- Updates learning path pages to not show topics if all of the posts within the topic are drafts.
- Updates learning path cards to not count draft posts in the total number of resources.

Filter draft posts out of topics and collection counts.

---

.eleventy.js
package-lock.json
package.json

Fixes #1257 
Adds support for specifying custom anchors in headers using the same style as WebFu 
`## hello {: #anchor }`
This PR adds a new node dependency ([markdown-it-attrs](https://www.npmjs.com/package/markdown-it-attrs)), which is designed explicitly for this purpose. I customized the default use so that it matches the same syntax as WebFu (`{: #anchor }`).

Add support for specifying anchors in headers

---

src/site/content/en/angular/virtualize-lists-with-angular-cdk/index.md

Fixes #1260.
- Escape curlies in angular posts so devsite doesn't try to parse them.

Escape curly braces in Angular virtual list post.

---

src/site/content/en/handbook/web-dev-components/index.md

Fixes #1212.
- Escapes curly braces in handbook so devsite will be happy.

Escape asides in handbook.

---

src/site/content/en/lighthouse-seo/meta-description/index.md

not a big deal here.
I just wanted to have the html tag mentioned before we mention its attribute.

meta-description: add early mention of HTML tag

---

src/site/content/en/blog/largest-contentful-paint/index.md

This PR fixes a few incorrect things in the Largest Contentful Paint article that I discovered after publishing.
/cc: @npm1 @yoavweiss (so one of them can review for accuracy before we merge)

Fix some incorrect information in the LCP article

---

src/site/content/en/blog/native-lazy-loading/index.md

Using a custom data attribute instead of a CSS class, teaches young developers to avoid CSS classes for things they were never meant to be used for.  
If a young developer starts using classes as hooks for their JavaScript code, some day in the future some other young developer will *optimize* the HTML and remove that *unused* CSS class that is nowhere to be found in any stylesheet.

Tweak example for feature detection and using lazysizes

---

src/site/content/en/blog/largest-contentful-paint/index.md

This PR fixes a small error in the code sample of the Largest Contentful Paint article.

Fix LCP code sample error

---

src/site/content/en/fast/efficiently-load-third-party-javascript/index.md

There's an ongoing discussion about recommended limits for preconnect, but we're definitely not going to recommend a hard number. I've double-checked everything, this the last fix I need to get in (the sooner the better).
- Fix errors and remove hard numbers from the recommendation.

[hot-fix] Update preconnect recommendations

---

.eleventy.js
src/site/content/en/blog/index.njk

Fixes #1327 
- Use eleventy's [data deep merge](https://www.11ty.io/docs/config/#data-deep-merge) to merge tags data. Previously if a post contained its own tags it would override the tags inherited from its directory and would break prev/next navigation.
- Prevent the blog landing page itself from inheriting the `post` tag and appearing as a pseudo-post on the blog.

Deep merge tag data.

---

src/site/_data/postHost.js
src/site/content/en/en.11tydata.js
src/site/content/en/index.njk
src/site/content/en/learn/index.njk
src/site/content/en/learn/learn.11tydata.js

Fixes an issue introduced by #1329. Because there were multiple directory files that used the term `paths` they were all getting merged together. This would show duplicate paths on the /learn page.
- Scope directory data files so they refer to their page name.

Avoid duplicating paths from merged data.

---

src/styles/components/_stats.scss

Improve horizontal spacing of the stats widget on desktop when there are >3 stats. See PR #1335 for a use case.

Fix stat alignment

---

.eleventy.js
package-lock.json
package.json
src/site/_filters/expand-contributors.js
src/site/_includes/components/Actions.js
src/site/_includes/partials/post.njk

Update Twitter share text to mention authors.
Native lazy-loading for the web by @hdjirdeh, @addyosmani, and @mathias https://web.dev/native-lazy-loading/
Examples of posts with 1, 2, and 3 authors:

Add "by screenname" to tweets

---

src/site/content/en/blog/multi-origin-pwas/index.md

- Spell out “i.e.” to “that is”.
- Correct “url” to “URL”.

Spell out “i.e.”, correct ”URL” character case

---

src/site/content/en/handbook/use-media/index.md

Added guideline to make thumbnail images match hero images, barring minor differences to account for the differing aspect ratios.

Add guidance about thumbnail images

---

src/site/content/en/lighthouse-performance/uses-webp-images/index.md

Fixes #1433
- Fixed typo ( calcualtes -> calculates ) in uses-webp-images  page.

[ Bug 1433 ] - typo fixed calcualtes -> calculates

---

package-lock.json
package.json
sass.sh

Instead of #1446. Make node-sass optional for where it cannot compile.

add node-sass, make optional

---

src/site/content/en/blog/backdrop-filter/index.md
src/site/content/en/blog/hands-on-portals/index.md
src/site/content/en/blog/layout-instability-api/index.md
src/site/content/en/fast/codelab-replace-gifs-with-video/index.md
src/site/content/en/fast/replace-gifs-with-videos/index.md

Fixes #1407
- Updates the replace-animated-gifs article with mp4 instructions that work in Safari.
- Updates any articles relying on mp4s to ones that actually work :)

Fix broken mp4s and gif conversion instructions.

---

src/lib/actions.js

I made a typo on the measure page for signed out users.

fix invalid var name for signed out case

---

src/site/content/en/lighthouse-performance/uses-webp-images/index.md

Fixes #.
- Fix typo `calcualtes` in headline `How Lighthouse calculates potential savings`

Fix typo in lighthouse-performance/uses-webp-images/ 

---

src/site/_data/site.js
src/site/_includes/components/Banner.js
src/site/_includes/layout.njk

- Creates a single entrypoint in site.js to enable banners. 
- Adds a banner for CDS sign ups.

Create a single entrypoint for banners. Enable CDS banner.

---

src/site/content/en/blog/prefers-color-scheme/index.md

Headings with inline code or clearfix didn't have the hover anchor. This PR fixes this problem.

[web.dev/prefers-color-scheme] Fix headings with inline code or clearfix

---

.eleventy.js
src/site/_data/site.js
src/site/_includes/components/helpers.js
src/site/_includes/components/tags/Image.js
src/site/_includes/components/tags/README.md
src/styles/components/_images.scss

Adding @samthor as a reviewer since it'll be Monday his time tomorrow :)
- Add `Image` and `Figure` custom tags so we can migrate to using an image CDN with srcset and webp fanciness.
To keep things from getting super complicated, I'd like to land this PR first. Then follow up with a second PR to add srcset/webp goodness. And then follow up with a final PR that converts all existing images over to the new tags.
Example usage in Markdown files:
```
{%
Image
src="./label-a11y-lint.png",
alt="hello",
maxWidth="300px"
%}
```
```
{%
Figure
src="./label-a11y-lint.png",
alt="hello",
type="fullbleed screenshot",
maxWidth="300px"
%}
Figcaption text goes here! Can be **markdown**.
{% endFigure %}
```

Add Image and Figure custom tags.

---

src/site/content/en/lighthouse-performance/redirects/index.md

Fixes #
- fix typo `upading` in section "How to eliminate redirects"

Fix typo in lighthouse-performance / redirects

---

src/site/content/en/blog/more-capable-form-controls/index.md

https://google.github.io/styleguide/jsguide.html#features-classes-fields
CC: @arthurevans
- The post mixes leading and trailing underscores, this PR fixes this.

Consistently use trailing underscore for @private fields

---

src/site/content/en/react/virtualize-long-lists-react-window/index.md

[Virtualize large lists with react-window] Trivial typo fix

---

gulpfile.js
package-lock.json
package.json
rollup.config.js
src/lib/bootstrap-config.js
src/lib/bootstrap.js
src/site/_includes/layout.njk

Adds the Web Components loader to our source tree. Resolves #1376.
Note that our JS actually isn't being loaded now either (since it has a `.hexcode.js`) suffix. That's a separate issue.

include the webcomponents polyfill

---

server.js

Right now, we can serve e.g. Measure under:
* /measure
* /measure/
* /measure/index.html
This PR serves 302s so that the first case is canonical. This will help us for SW caching. It's also worth noting that /measure/ would _load_ with our webserver, but Navaid trims trailing slashes for _nav_.

Make content URLs canonical

---

src/site/content/en/blog/fixing-layout-instability/index.md

Just found a small typo, instead of `display: swap` must be `font-display: swap`.

Fix css property font-display in the article

---

src/site/content/en/fast/incorporate-performance-budgets-into-your-build-tools/index.md

-  Updates `author` to `authors` in the [Incorporate performance budgets into your build process](https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/fast/incorporate-performance-budgets-into-your-build-tools/index.md) so the author(@mihajlija) shows in the article.
The screenshots below show the issue that this PR is tackling.

fix: Use authors instead of author in content source file

---

.github/workflows/issue-closed-workflow.yml

- Adds a GitHub action to ping @kaycebasques when a content proposal ticket gets closed. It should remind Kayce to send the feedback survey.

Add survey reminder action.

---

src/site/content/en/fast/using-lighthouse-bot-to-set-a-performance-budget/index.md

- Removes the `td` closing tag from the [yaml file example](https://web.dev/using-lighthouse-bot-to-set-a-performance-budget/) 
Current:
Fix: https://deploy-preview-1606--web-dev-staging.netlify.com/using-lighthouse-bot-to-set-a-performance-budget/

fix: Remove td tag from yaml file

---

src/site/_includes/components/ArticleNavigation.js
src/styles/components/_article-navigation.scss
src/styles/generic/_code.scss

Fixes #1594
- Ensure next article shortcode renders markdown for code snippets.
- Add CSS to make next article widget inline code look nice.
- Tweak heading styles to also make inline code look nice.

Make inline code work in next article widget and headings.

---

src/site/_drafts/intrinsic-layout-overview/index.md
src/site/content/en/blog/backdrop-filter/index.md
src/site/content/en/blog/use-thumbor/index.md

- Adds rel="noopener" to external links using target="_blank" due to it's [performance and security benefits](https://developers.google.com/web/tools/lighthouse/audits/noopener)

Add rel="noopener" to external links using target="_blank"

---

src/site/_includes/content/origin-trials.njk
src/site/content/en/accessible/control-focus-with-tabindex/index.md

It looks like we created this include but it isn't used anywhere yet. We should probably do a separate PR to add it to existing articles :)
**Changes proposed in this pull request:**
-  Remove the `Aside` from the origin-trial include.
If folks would like to use this include within an Aside they can still do so:
```
{% Aside %}
{% include 'content/origin-trials.njk' %}
{% endAside %}
```
cc @petele @jpmedley

Remove aside from ot include.

---

src/site/content/en/blog/get-installed-related-apps/index.md

Not sure how we missed the fact this wasn't marked as `DRAFT`!

Re-enable draft for getInstalledRelatedApps

---

src/lib/components/Search/_styles.scss

Just my opinion but I think we can make this look nicer.
* we were using the default `<input>` font—migrate to use the page's font (matches DevSite)
* replace the blue focus outline with an _underline_
Looks a bit like this:
Using an underline rather than a surrounding box for focus makes the appear animation less jarring—if it's a whole box, you don't see the right side of the focus until the animation is done. The underline makes the input box seem more like it's growing. (DevSite grows the `<input>` itself but we don't, for whatever reason).

Tweaks style of search box

---

server.js
src/lib/router.js

As per your requests, Rob :)
We still have to work around Navaid's awkwardness. To be fair, if you remove all links to "/foo" (and "/foo/index.html", although I don't they actually exist anywhere) inside our codebase, some of this isn't needed—but I feel like folks might accidentally add them back in.

migrate to supporting /measure/ (trailing slash) pages

---

src/site/content/en/lighthouse-pwa/works-offline/index.md

Fixes #1694.
- Fix link to Lighthouse audit source code for `works-offline`.

Fix works-offline audit source link

---

src/site/_data/postHost.js
src/site/_filters/live-paths.js
src/site/_includes/path.njk
src/site/content/en/en.11tydata.js
src/site/content/en/learn/learn.11tydata.js

Related to #1656
- Quick fix to let paths be marked as drafts. To mark a learning path as a draft, add `draft: true` to the learning path's `path` property in its 11tydata.js file.
Example:
```
module.exports = {
// Tags are inherited by all posts.
tags: ['pathItem', 'accessible'],
path: {
draft: true,
...
},
};
```

Let paths be marked as drafts.

---

src/site/_includes/components/Banner.js
src/site/_includes/styles.njk
src/site/content/en/handbook/web-dev-components/index.md
src/styles/components/_banner.scss

- Add an optional `body` argument to the banner component that adds a `w-banner--body` class, which makes the banner look OK when used in the body of a post.
- Add temporary `w-banner--body` styles to `styles.njk` (to be removed after migration off DevSite).
- (Hopefully) fix code samples on `web-dev-components` so they don't break staging.

Add body variant to banner component

---

src/site/content/en/handbook/web-dev-components/index.md

One line fix for the link to the instructions component that has been broken for months.

Fix a broken link in the handbook

---

src/site/content/en/lighthouse-performance/uses-webp-images/index.md

- Replaces manual codelab markup with YAML in `codelab-serve-images-webp`

Correct manual codelab markup in webp audit post

---

src/lib/components/Search/index.js

Fixes a few issues.
* Hitting "Enter" with no search results caused a JS error
* Adds a message indicating that no results were found with a link to Googs
* Simplifies the `focusout` handler by just invoking `.click()` programatically

fix searching with no results

---

src/lib/components/Header/_styles.scss
src/lib/components/Header/index.js
src/lib/components/ProfileSwitcher/_styles.scss
src/lib/components/Search/_styles.scss
src/lib/router.js
src/lib/store.js
src/site/_includes/layout.njk

@robdodson I think some of these changes might have just been broken in your DevSite code removal.
* Restores the blue underline indicating which top-level page the user is on (JS + CSS changes)
* This also makes `web-search` have a white background so it covers this while open
* Removes the default grey background in responsive mode for "Sign In" and the search open/close toggle
* Make the "SIGN IN" button have `cursor: pointer` (matchs DevSite, where it's technically a link)

Header style tweaks for v2

---

server.js
src/lib/router.js
src/lib/store.js
src/lib/sw.js
src/site/content/en/404.njk
src/site/content/en/offline.njk
src/styles/components/_page-header.scss

Adds a 404 and offline page. Serves the offline page via SW only.
Notes:
* this is a bit hard to test because the SW only responds to "/foo/", yet most links are still "/foo". (Express is doing the redirect)—see TODOs in sw
* we serve the 404 html for things like missing PNG assets
* we should later annotate the offline page so that the frontend code can re-request when it gets an 'online' event.

V2+sw stuff

---

src/site/content/en/accessible/control-focus-with-tabindex/index.md
src/site/content/en/lighthouse-accessibility/accesskeys/index.md
src/site/content/en/lighthouse-accessibility/bypass/index.md
src/site/content/en/lighthouse-accessibility/tabindex/index.md

Fixes #1721.
- Quality pass on `accesskeys`, `tabindex`, and `bypass`. (`duplicate-id-active` and `heading-order` are new posts that were recently reviewed.)
- Remove the origin-trial aside from `control-focus-with-tabindex`.

Update LH a11y navigation audit posts

---

src/lib/actions.js
src/lib/lighthouse-service.js

Fixes #1375 
- Let signed out users get access to historic data for a url.
TODO:
- If a user signs in, compare the URLs and promote whichever one is in the input field.

V2+historic data

---

src/site/content/en/blog/badging-api/index.md
src/site/content/en/blog/contact-picker/index.md
src/site/content/en/blog/get-installed-related-apps/index.md
src/site/content/en/blog/image-support-for-async-clipboard/index.md
src/site/content/en/blog/native-file-system/index.md
src/site/content/en/blog/shape-detection/index.md
src/site/content/en/blog/wakelock/index.md

- Removes `draft: true` from Fugu articles
- Updates post `tag`s for consistency
Needs to go live in conjunction with https://github.com/google/WebFundamentals/pull/8252

Remove 'draft' from Fugu articles

---

src/lib/app.js
src/lib/bootstrap.js
src/lib/components/ProfileSwitcher/_styles.scss
src/lib/components/ProfileSwitcher/index.js
src/lib/components/ProfileSwitcherContainer/index.js
src/lib/components/Search/index.js
src/lib/components/SigninButton/index.js
src/lib/fb.js
src/lib/store.js
src/styles/components/_page-header.scss

This tries to fix causes of FOUC.
* We store whether we think the user was previously signed in inside `localStorage` which propagates to the global state, so it's available before Firebase tells us anything
* Fades in the user's profile picture only after it loads (and shows a placeholder silhouette until then)
* Fixes a bug with `<web-search>` (it would "click" on the thing you focused on _outside_ itself)
* Expands the allowed content on the Measure page so that FOUC is less annoying on large screens (the top line of text now doesn't wrap)

Prettify header and user image

---

src/lib/actions.js
src/lib/components/UrlChooserContainer/index.js
src/lib/fb.js

Related to #1375.
* Retains the active URL if you'd run Lighthouse on it before signing in. This does *not* write that to your profile, however (that wouldn't be _too_ hard, but perhaps a touch racey).
* Clears any previous Lighthouse result on signout. This won't stop an in-flight run (as that's indicated via `activeLighthouseUrl`).
The changes to `fb.js` are a lot of comments, but I think it's definitely worth it.

retain previous URL on signin

---

src/lib/router.js
src/styles/generic/_shared.scss

Fixes #1600 and #1601.
Unrelated but I'm inclined to remove Navaid since we're working around more of it. For instance, I'd love to retain scroll position in history state, so that the 'back' button feels more natural (going "back" will just reset scroll to zero). But that's [not possible](https://github.com/lukeed/navaid/issues/6).

nav tweaks

---

src/lib/components/Actions/index.js

Web Share was crashing.
also, Web Share on Safari for Desktop is amazingly limited—I have all the options turned off so all I see is AirDrop and Messages, neither of which I use. 🤨
cc @robdodson

bad variable name in webshare

---

src/site/_includes/components/Hero.js
src/site/_includes/components/PostCard.js
src/site/_includes/components/tags/Image.js
src/site/_utils/get-image-path.js
src/site/_utils/get-srcset-range.js

- Use imgix to srcset hero images and post card images when we're in a prod environment.
- `format=auto` will serve webp images if the browser supports it.
- `fit=max` means imgix won't try to scale up an image if the source is smaller than the requested dimensions (IOW, it won't stretch a 1600px image to be 3200px).

Add imgix to hero and post cards

---

.eleventy.js
src/site/_data/site.js
src/site/_drafts/_template-codelab/index.md
src/site/_drafts/_template-post/index.md
src/site/_includes/components/Meta.js
src/site/_includes/layout.njk
src/site/content/en/404.njk
src/site/content/en/blog/index.njk
src/site/content/en/offline.njk

Fixes #1713
- Add a new `Meta` shortcode to handle all the fiddly logic associated with meta tags and fallbacks.
- Hide /404/ and /offline/ from search indexing.
- Add missing description to blog 😬

Add shortcode for page meta tags and hide 404/offline pages from Search

---

src/lib/fb.js
src/site/_includes/layout.njk

Fixes #1734.
----
Also I see that apparently you can use the npm module of firebase instead of script tags: https://firebase.google.com/docs/perf-mon/get-started-web (see "using module bundler")
I can followup with this with if you like.

Add firebase performance monitoring

---

src/site/_data/site.js
src/site/_includes/layout.njk

- Add custom dimensions to analytics. Our property already has dimensions specified by devsite but we probably won't use those immediately or possibly ever:
- Revs the tracking version to 3 (it's currently at '2' for the live version of web.dev).

Add custom dimensions to analytics.

---

server.js
src/lib/bootstrap.js
src/lib/loader.js
src/lib/store.js
src/lib/sw.js
src/lib/utils/meta.js
src/lib/utils/router.js
src/site/_includes/layout.njk
src/site/content/en/404.njk
src/site/content/en/offline.njk

Fixes #1749.
* Actually makes our 404's return as 404's (they were 200-ing)
* Marks 404 and offline pages as "special" via meta tag
* Returns the offline page properly for `fetch()`-loading
* Ensures that only one request via router can be pending at once
* Reloads the offline page if we detect the `online` event.

Makes offline page reload when back online

---

build.js
compile-css.js
package-lock.json
package.json
redirect-handler.js
src/lib/sw.js

Most of #1370. 
* Caches misc images and assets on install
* The build script must run after other scripts (in production) in order to pick up asset hashes
* Stores pages in Workbox with ".../index.html" trailer to pick up Workbox's default support for that (as "/" will load "/index.html", but **not** the other way around)
* Caches images (e.g., author profiles) at runtime
* .... doesn't cache hero images (since they're assets under individual articles)—although I thought this moves to imgix in #1741

V2+cache more

---

src/lib/bootstrap-config.js
src/lib/bootstrap.js
src/lib/components/Header/_styles.scss
src/lib/components/SideNav/_styles.scss
src/lib/components/SideNav/index.js
src/site/_includes/layout.njk
src/styles/generic/_page.scss

This fixes some issues for older browsers.
* change `path` => `root` for the Web Components loader (oops)
* set `overflow-x: hidden` because Edge was allowing scrolling for some reason ¯‍\‍_‍(‍ツ‍)‍_‍/‍¯
* use `<body class="unresolved">` to work around lack of support for `:defined`—this isn't actually perfect because we lazy-load element code
* ... so also remove `unresolved` on `<web-side-nav>` on its own until after its first render (prevents screenshot below)
I can't really test this without deploying, so this is done on my Mac first.

V2+edge misc fixes

---

package-lock.json
package.json
src/lib/loader.js
src/lib/sw.js

Forces a claim and reload of all clients if the Service Worker "architecture" changes.
This doesn't stop e.g. SPA router fetch navigation from possibly breaking a bit, but I think in both DevSite and our code, failures in routing just cause a real reload.
I quite like how this has worked out. It tests well from the current v2 branch (SW with no arch version) to this branch, causing all pages to reload.
Also fixes `normalizeUrl` as it was trying to normalize a URL even if it had a search param. e.g., "/foo?blah=1" was becoming "/foo?blah=1/".

V2+reload pages new arch

---

src/lib/components/Search/index.js

Fixes #1790 
- Make sure when we tab out of search that we're going fully outside of the component. Previously it was focusing the first anchor in the box and then effectively clicking on it.

Fixes #1790. Let folks tab out of search box.

---

src/site/content/en/blog/samesite-cookie-recipes/index.md
src/site/content/en/blog/samesite-cookies-explained/index.md

Corrections to #1460.
- Link to Chrome blog post
- Link to more official Edge announcement
- Mention `XMLHttpRequest` in remote resources
- Correct WebView section to explain that it will not be enforced
- Link to incompatible clients list as opposed to just mentioning Safari

Corrections on browser behavior

---

src/styles/pages/_measure.scss

Fixes #1794 
- This PR puts the web-progress-bar in front of the card dividers
CLA Name : Dali Haeusler
Excited to contribute to a google product even if it's small cheers

update/ .web-progress-bar (Progress bar in front of card dividers)

---

src/site/_data/contributors.json

- Add github account for user "gernberg"

Add github link to contributors for gernberg

---

src/styles/generic/_code.scss

`<pre>` elements are currently inheriting the `font-size` of parent elements in some cases (e.g., when inside an `<ol>`). Also, `<code>` elements currently have a fractional `font-size` (16.2px), which can cause minor rendering differences across browsers.
- Convert code font font sizes to rem.

Change code font-size to rem

---

.travis.yml

the default is 50.
depth of only 1 breaks a ancestor hash lookup we do in lhci
this shouldn't matter much for CI time either. (especially now that lhci added ~3min to the total times 😉)

travis: adjust git depth

---

.github/CODEOWNERS

@kaycebasques @samthor fyi. Adding a few I missed after poking around the repo more. In general the top level rule should tag sam and I as required reviewers for most things. But I'd like to try as much as possible to avoid scenarios where a malicious actor tries to sneak a protected file type into the content directory.

Add more file types to codeowners.

---

src/styles/components/_images.scss

Fixes #1282. Output tags inside figcaption the same as pure text.

Fixes #1282. Output tags inside figcaption the same as pure text

---

src/lib/analytics.js
src/lib/loader.js
src/site/_includes/layout.njk

Possibly fixes #1795.
Simplifies the GA behavior.
* Moves the Analytics code above importing our code (I think this would never be a problem because modules are deferred, but it just seems less ambiguous about whether `ga` is available)
* Sets the new page as we change URL and explicitly call `ga("set", "page", ...)`, which I think is needed (cc @philipwalton )

send pageview for new pages

---

src/styles/generic/_code.scss

@mfriesenhahn does this look good to you? I think the recent change may have bumped the font size down for code in headers. Example: https://web.dev/duplicate-id/

Fix code in headers.

---

package.json
src/site/content/en/react/react.11tydata.js

Fixes #1837
- Don't use the image CDN for staging.
The way imgix (our image CDN) works is it acts as a proxy to images on web.dev. This means when you request an image from imgix, _it must already be live on the web.dev server_.
When we stage a post, the image has not been deployed to web.dev yet, so imgix doesn't find it, so it returns a 404. This change just uses the relative reference to the image for staging purposes (essentially the same as local dev).

Fix hero images on staging.

---

src/site/content/en/blog/wakelock/index.md

Follow-up action now that https://github.com/w3c/wake-lock/issues/226 is closed.
Fixes https://github.com/GoogleChrome/web.dev/issues/1742.
- Updates the Wake Lock article now that w3c/wake-lock#226 is closed.

Update Wake Lock article

---

src/lib/components/Header/_styles.scss
src/lib/components/SigninButton/_styles.scss
src/lib/components/_all.scss
src/site/_includes/components/Instruction.js
src/site/_includes/partials/footer.njk
src/site/content/en/handbook/web-dev-components/index.md
src/styles/components/_buttons.scss
src/styles/components/_compare.scss
src/styles/components/_footer.scss
src/styles/generic/_blockquote.scss
src/styles/generic/_code.scss
src/styles/generic/_lists.scss
src/styles/generic/_tables.scss

Fixes layout bugs introduced by migration off devsite.
Changes made by visually comparing pre- and post-migration versions of:
- `handbook/web-dev-components`
- `handbook/markup-media`
- `handbook/markup-code`
**Note:** UI element states _not_ tested.
- Correct line-height of header tabs.
- Reinstate top margin on **Measure** sign-in button.
- Vertically align inline buttons.
- Revert font-size changes in Compare widget.
- Fix top margin for block quotes.
- Horizontally flip block quote icon so it's an open quote, not a close quote. (Bug predated devsite migration.)
- Fix margins for paragraphs nested in list items.
- Revert minor table layout changes.
- Fix color, font-size, and padding for code font.
- Fix broken line breaks in Instruction widget. …

Fix v2 layout bugs

---

src/lib/loader.js
src/site/_includes/components/Meta.js

- A quick fix to update page descriptions juuuuuuuust in case googlebot is running JS on our site and navigating it as if it's a SPA. Ultimately we should replace this with merging all of the meta tags from the new document, but I wanted to throw this in real quick as a bandaid.

Update page description when we load new content.

---

src/site/content/en/blog/samesite-cookies-explained/index.md

Cookies without a `SameSite` attribute will be treated as `SameSite=Lax`. According to the docs https://www.chromium.org/updates/same-site and https://tools.ietf.org/html/draft-west-cookie-incrementalism-00 the default without `SameSite` attribute will act at `SameSite=Lax` NOT `SameSite=None`

Cookies without a `SameSite` default fix

---

src/lib/loader.js
src/lib/utils/router.js

Fixes #1859.
We were actually just eating it on _load_, nothing to do with nav specifically.

don't eat hash

---

src/site/content/en/lighthouse-performance/interactive/index.md

Google developers states 50 milliseconds and web.dev states 5 seconds. I think this might be a typo?
Google Developers - https://developers.google.com/web/tools/lighthouse/audits/time-to-interactive
wed.dev - https://web.dev/interactive/

Page responds to user input in 50 milliseconds not 5 seconds

---

src/site/content/en/lighthouse-performance/time-to-first-byte/index.md

Hi, 
I have noticed current "Adaptive Serving with Network Information API" URL "adaptive-service-based-on-network-quality" is going to 404 and the correct URL should be https://web.dev/adaptive-serving-based-on-network-quality/
*serving instead of *service
Thanks
Manjeet
- 
- 
-

adaptive-service-based-on-network-quality url 404

---

src/site/content/en/metrics/tti/index.md

#1856 was merged when some changes for the TTI doc was in flux, so this PR reverts that change to be consistent with the other docs. We can revisit the change for all the docs in a subsequent PR.

Revert TTI doc changes for consistency

---

src/site/_drafts/_template-post/index.md

Fixes #1839
- Don't use numbered figcaptions in template post.

Remove Fig. from template post.

---

src/site/content/en/blog/web-share-target/index.md
src/site/content/en/blog/web-share/index.md

The link should be https://web.dev/web-share-target/
CC: @petele @jpmedley

Web share article: Correct link to web share target article

---

src/site/content/en/blog/image-support-for-async-clipboard/index.md

Thanks, @jakearchibald.
- Use modern syntax

[Async Clipboard] Use modern syntax

---

src/site/content/en/blog/web-bundles/index.md

Without tail `/`, `gen-bundle` command throws error.
- 
- 
-

fix go/bundle example for current usage

---

src/site/content/en/fast/performance-budgets-101/index.md

The previous one was redirecting to the "old" Lighthouse Bot
Fixes #1889
- update the link to Lighthouse CI tool

Update the Lighthouse CI url

---

src/site/content/en/blog/periodic-background-sync/index.md

As @jakearchibald pointed out, `periodicSync.register()` and `periodicSync.unregister()` return `Promise<void>` as per the [proposed spec](https://github.com/WICG/BackgroundSync/blob/9dd088910ed9ebf162a2acf67495f6daa8da65be/explainers/periodicsync-WebIDL.md#definition-of-the-interface), so adding in the `await` is necessary to ensure the `catch` is triggered.
It's not 100% needed in the `unregister()` example, but it does make it clearer that it's also returning a promise.
(The original at https://developers.google.com/web/updates/2019/08/periodic-background-sync has this issue too, but I'm assuming that will eventually just redirect here?)

Add await to PBS examples

---

.eleventy.js
src/site/_includes/components/Blockquote.js
src/site/content/en/handbook/web-dev-components/index.md
src/styles/generic/_code.scss

- Add a shortcode for blockquotes.
- Adjust code font size in `<cite>` elements so it's proportional.

Add blockquote shortcode

---

tools/lhci/.lighthouserc
tools/lhci/run-lighthouse-ci.sh

- Moves the script to the safer, non-breaking change `0.3.x` tag
- Cleans up the script to take advantage of `startServerCommand`
~~WIP: looks like LHCI was already failing with the commiter timestamp change, so wait for that to be fixed before merging~~ should be fixed in 0.3.1 :)

misc: update lhci to 0.3.x

---

src/lib/lighthouse-service.js

- While we were transitioning off of devsite I created a named version of the lighthouse-keeper service. Today I migrated all traffic to this version. This updates the source to also use the default name instead of the specific version number.

chore: rev lighthouse-keeper version.

---

src/site/_includes/components/ArticleNavigation.js
src/site/_includes/components/PathCard.js
src/site/_includes/partials/item.njk
src/site/_includes/partials/topic.njk
src/site/_includes/path.njk
src/styles/components/_all.scss
src/styles/components/_topic.scss

Fixes #1137.
Inside of a collection topics can support subtopics (embedded collections?)
Here's what it would look like _if_ we had subtopics in the Angular collection:
No where currently uses subtopics, but effectively topic objects in the topics array of a post (like [`angular.11tydata.js`](https://github.com/GoogleChrome/web.dev/blob/4ec23419bbdac156ea5fb6410821db2306304bd4/src/site/content/en/angular/angular.11tydata.js#L15)) now support a `subtopics` field, which is just an array of objects of the below data structure:
```TypeScript
type SubTopic = {
title: string;
pathItems: string[];
}
```

feat: add support for `subtopics` inside of site content `topics`, fixes #1137

---

src/site/content/en/blog/native-file-system/index.md

Fixes #1944
- Removes the call to `truncate()` from the post as it's no longer required.

Remove `truncate` from native file system post

---

src/lib/components/Snackbar/_styles.scss

Fixes #1930.
Only apply `max-width` on sizes larger than smart phones so that the cookies snackbar takes up the full width of larger smart phones.

fix(Snackbar): set max-width to only on sizes larger than smart phones, fixes #1930

---

src/styles/components/_card.scss

Fixes #1653.
In order to keep the cards in the blog view the same height, regardless of if in mobile view (single card per row) or in desktop view (multiple cards per row) I've given the cards a set height (which is the height of a thumbnail card when the bp is less than md). When md or larger it'll default to auto where cards without a thumbnail will match the height of the other cards (with a thumbnail).

fix(w-card): set fixed height of `.w-card` when on breakpoints smaller than smart phones, fixes #1653

---

.eleventy.js
src/images/icons/file_copy.svg
src/lib/app.js
src/lib/components/CopyCode/index.js
src/lib/components/CopyCode/styles.scss
src/lib/components/_all.scss

Fixes #1871
Add custom element that wraps fenced code blocks and gives them a button to copy the code. I would love @kaycebasques thoughts on how it looks though.

feat(CopyCode): add custom element to allow code blocks to be copied, fixes #1871

---

src/site/content/en/blog/samesite-cookies-explained/index.md

Shows that in Chrome 80 Cookies with `SameSite` set to `None` require a secure context and `SameSite` defaults to `Lax`.
https://chromium.googlesource.com/chromium/src/+/2fbb8e5c2bce66bede14cbfe9c6b427b835f67d9

Update release information re SameSite cookies.

---

src/site/content/en/blog/notification-triggers/index.md

The OT will happen in 80, not 78. This is the only change.
CC: @jpmedley

[Notification Triggers] Update Chrome version for OT

---

src/site/content/en/blog/prefers-color-scheme/index.md

@tomayac this article is currently #2 for `prefers-color-scheme` Search query:
Title keywords seem to have a big impact on documentation rankings in Search. I'm curious to see if this nudges the article up to number 1. Any reason on your side why the title can't change?

Add "prefers-color-scheme" to title

---

src/site/_includes/components/PostCard.js
src/styles/components/_author.scss
src/styles/components/_post-card.scss

Fixes #1330
Display author(s) and date of post in a card, it'd look like this:
2+ Authors => We don't show any images.
2 Authors => Display images, there's a white border radius to separate authors.
1 Author => Display image, there's a white border radius as when there are 2 authors, however you don't really notice it so it doesn't matter.
0 Authors => Just show the date.

feat(PostCard): display author(s) and date of post in a card, fixes #1330

---

.eleventy.js

Fixes #1917
Add some rendered rules in order to wrap table elements with a `<div class="w-table-wrapper">`. This does not work with an HTML table, as from what I understand HTML doesn't go through the custom element renderers (I think it's just passed through?).
So possibly we could implement a rule for HTML and modify it, but I think that would be ugly... Maybe something like jsdom to pull out tables and add the div? (Something like this...)
```JavaScript
const jsdom = require("jsdom");
const htmlRule = (html) => {
const dom = new JSDOM(html);
dom.window.document.querySelectorAll("table").forEach((table) => {
const parent = table.parentNode;
if (!(parent instanceof HTMLDivElement && parent.classList.contains("w-table-wrapper"))) {
const newParent = …
```

fix(table): tables written in markdown are automatically wrapped by `<div class="w-table-wrapper">`, fixes #1917

---

src/site/content/en/handbook/word-list/index.md

Note that in code 'referer' is misspelled, a fact that was not caught before  being widely implemented in web servers and browsers. https://tools.ietf.org/html/rfc7231#section-5.5.2

Update Word list

---

src/lib/components/SnackbarContainer/index.js

Fixes #1771
On connection of the component add an event listener for before the PWA install prompt appears. Stop it and save it until the user has accepted cookies.

feat(SnackbarContainer): only allow PWA install prompt if cookies accepted, fixes #1771

---

src/site/content/en/lighthouse-accessibility/accessibility-scoring/index.md
src/site/content/en/lighthouse-performance/critical-request-chains/index.md
src/site/content/en/lighthouse-pwa/installable-manifest/index.md
src/site/content/en/lighthouse-pwa/load-fast-enough-for-pwa/index.md

There are multiple URLs on web.dev that 404 or no longer found. This fixes a few of them.

Fix multiple broken URLs that result in 404s

---

src/site/content/en/blog/contact-picker/index.md

Fixes #1907  
- Removes origin trial information from article because the feature is shipping.

Update Contact Picker article for Chrome 80.

---

src/site/content/en/index.njk

This was a request from @harleenkbatra08.
We'd like to run an ad campaign to direct folks to the embed on the frontpage so I've added an id as well.
Also had to switch away from the YouTube component because it doesn't support playlist embedding. This PR needs to go out today 😅

Add CDS playlist to front page of site and deeplink id.

---

src/styles/generic/_shared.scss

Fixes #1976
- Prevent top navigation from overlapping with headers when we deep link.

Make deep links scroll properly.

---

src/site/content/en/installable/add-manifest/index.md

See the note [here](https://www.w3.org/TR/appmanifest/#using-a-link-element-to-link-to-a-manifest)  and the discussion [here](https://github.com/w3c/manifest/issues/689)

Cohere with the spec

---

src/site/content/en/metrics/lcp/index.md

This PR fixes an occurrence of FCP that should have been LCP: https://twitter.com/tobias_willmann/status/1208010670081552385
It also fixes a few paragraphs that don't have proper line wrapping.

Fix incorrect reference from FCP to LCP

---

.github/workflows/continuous-integration-workflow.yml

- Build and deploy the site anytime a commit lands on master. The commit can either be from a push or merging a PR.
- Build and deploy the site on a regular schedule (Mon-Thur, 15:00 UTC / 7:00am PST). Our peak traffic seems to be around 6-7am PST. Doing it at 7 seems to be a good balance because it hopefully captures the most users, and also ensures that our team will be oncall soon in case something goes wrong.

Add ci workflow.

---

src/lib/components/BaseElement/index.js
src/lib/components/Tabs/index.js

Make sure ids are unique when Tabs custom element is used multiple times on a page. 
I added a salt generator utility to BaseElement to generate unique ids - let me know if there is a better place for it!

Make sure ids are unique in custom elements

---

src/lib/components/Tabs/_styles.scss
src/site/_includes/components/AssessmentHint.js
src/site/content/en/accessible/control-focus-with-tabindex/index.md
src/site/content/en/accessible/labels-and-text-alternatives/index.md
src/site/content/en/accessible/use-semantic-html/index.md
src/site/content/en/fast/defer-non-critical-css/index.md
src/site/content/en/reliable/codelab-explore-network-panel/index.md
src/site/content/en/secure/same-origin-policy/index.md

- Add first four self-assessment sets in:
- `control-focus-with-tabindex`
- `use-semantic-html`
- `labels-and-text-alternatives`
- `same-origin-policy`
- Add horizontal scrolling when tabs overflow viewport. (Matches behavior of Material tabs, except scrollbar is visible to improve discoverability and usability for mouse users.)
- Add Markdown parsing to AssessmentHint `<summary>` element.
- Tidy editorial issues in `same-origin-policy` post.
- Tidy editorial issues in `codelab-explore-network-panel` post. (Was going to add a set to this post but decided against it after tidying.)
- Fix instruction list formatting in `defer-non-critical-css`. (Same as above.)

Add self-assessments batch 1

---

src/site/content/en/blog/native-lazy-loading/index.md

Fixes #1448.
- Adds paragraph on lazy loading images within `<picture>`

adds paragraph on loading images with picture tag

---

src/lib/components/LighthouseScoresMeta/_styles.scss
src/lib/components/LighthouseScoresMeta/index.js

Fixes #1118 (partially)
Clean up the "last audit" section on /measure on mobile. 
Before:
After:

Clean up the "last audit" section on /measure on mobile.

---

src/site/content/en/feed.njk

Fixes #2039
- Code samples didn't show up in the RSS feed since they were wrapped in `<web-copy-code>`. This PR wraps them in a `<div>` instead.

Fix code samples in RSS feed

---

src/site/content/en/accessible/control-focus-with-tabindex/index.md
src/styles/components/_details.scss
src/styles/components/_self-assessment-hint.scss

- Fixes collisions between `<summary>` text and the chevron hover state in Details and AssessmentHint widgets.
- Addresses feedback from @kaycebasques on PR #2052:
- Added a paragraph to `control-focus-with-tabindex` to make explicit that adding a `tabindex` value to an element doesn't affect its children.
- Reframed item 4 in the `control-focus-with-tabindex` set to hopefully (!) clarify the task.

Address issues in 1st self-assessment sets

---

src/lib/app.js
src/lib/components/SnackbarContainer/index.js

Fixes #2023
The `if (!this.acceptedCookies)` would always be `true` on initial start of the app because the initial state didn't use the `localStorage` value. So we trigger a check if the user has accepted the cookies, which updates the store before we get the store's state in the component and run the check.
Now you will be greeted with the prompt after you accept cookies (which we could stop), and every subsequent visit should behave as normal. This only impacts the user until they accept cookies.
@robdodson @devnook PTAL

fix(SnackbarContainer): check`localStorage` before intercepting install prompt, fixes #2023

---

src/lib/components/CopyCode/styles.scss
src/lib/components/Tabs/_styles.scss
src/styles/components/_buttons.scss
src/styles/components/_details.scss
src/styles/components/_self-assessment-hint.scss
src/styles/components/_tooltips.scss
src/styles/tools/_mixins.scss

iOS makes `:hover` styles stick while an element is focused, which was causing issues with the chevron animations in the Details and AssessmentHint components.
- Add a `hover()` mixin that can be used when components need to show hover states only on devices that support `:hover`.
- Apply the `hover()` mixin to the AssessmentHint, Details, Tabs, and Tooltip components. 
- Hide tab highlight color on AssessmentHint, CopyCode, Button, Details, and Tabs components so it doesn't interfere with our styling.
- Hide focus outline for AssessmentHint, CopyCode, Details, and Tabs components to match behavior of rest of site.
- Show tooltips on long press on mobile devices to better align with Material specs.
- Fixes to the CopyCode component:
- Resequence …

Fix sticky hover and focus styles

---

src/site/content/en/feed.njk

Fixes #2064
- This fixes the global update date to use the latest post's date, not the earliest's.

Fix the updated date

---

src/lib/components/LighthouseScoresAudits/_styles.scss
src/lib/components/LighthouseScoresMetrics/_styles.scss

Prevent audit cells to overflow, eg:
I use 360px as the smallest screen base, as our analytics show there's not really much traffic below that value.

Small visual fixes to /measure at 360px

---

src/site/content/en/fast/codelab-serve-modern-code/index.md

- Remove `<strong>` from code
- Add syntax highlighting to HTML snippets

fix: Remove Strong tags from code

---

src/lib/sw.js

- Force sw to claim clients. I think the change I landed in https://github.com/GoogleChrome/web.dev/pull/2074 may have broken something but I don't know caching well enough to explain it. For web.dev/subscribe we do a server-side redirect to https://services.google.com/fb/forms/web-dev-subscribe/. After #2074 went live, that page started showing up as offline for folks ¯\_(ツ)_/¯ but worked again after they refreshed.

Rev service worker version to force it to update.

---

src/site/content/en/blog/get-installed-related-apps/index.md

Changes the description of one of the suggested use cases. It is not currently possible for the native app to switch to the web app, but it is possible for web to switch to native.

Correct a technical error.

---

src/site/content/en/fast/codelab-serve-modern-code/index.md
src/site/content/en/fast/serve-modern-code-to-modern-browsers/index.md

Fixes #922 .
- Adds notes on default defer behavior for module scripts
- Removes redundant <strong> tags from code snippets

Adds note on module scripts default defer behavior

---

src/site/content/en/blog/maskable-icon/index.md
src/site/content/en/blog/periodic-background-sync/index.md
src/site/content/en/blog/sms-receiver-api-announcement/index.md
src/site/content/en/blog/web-share-target/index.md
src/site/content/en/blog/web-share/index.md
src/site/content/en/blog/workbox-share-targets/index.md

Makes the tags for fugu/capabilities consistent across the blog.

Synchronize tags in fugu posts.

---

package-lock.json
package.json
src/site/content/en/blog/index.njk

Heya! I'm looking to update eleventy to v0.10.0 and created this PR with the dependency update.
The update doesn't seem to break anything, but seems to set up some things for deprecation. Check out the [changelog](https://github.com/11ty/eleventy/releases/tag/v0.10.0) and if there's anything you want to update to work with v0.10.0 push a commit up to chore/update

chore: update dependencies from @11ty org

---

src/styles/components/_actions.scss

I noticed the share button wasn't working if you clicked on the span text inside of it. I think it's because it uses `e.target.href` to open the little share window.
- Disable pointer events on action button children.

Disable pointer events on action button children

---

package-lock.json
package.json
src/lib/actions.js

Fixes #2102.
- Rev `wicg-inert` to latest version (3.0.1) to ensure `<details>` children of an inert element aren't focusable.
- Add `inert` to `.w-footer` when SideNav is open.

Fix focus behavior for side nav

---

src/site/content/en/metrics/cls/index.md

This PR clarifies the difference between how CrUX and the Layout Instability API report CLS. The ambiguity was brought to my attention via this tweet: https://twitter.com/philwalton/status/1220798835754061824.

Clarify CrUX bucketing for CLS

---

src/site/content/en/blog/native-lazy-loading/index.md

There was a quite [noticable bug](https://github.com/aFarkas/lazysizes/blob/gh-pages/CHANGELOG.md#512) that was fixed in [5.1.2](https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js), which is the latest stable release so changing the example code to that.

Update lazysizes version to 5.1.2 (latest stable)

---

src/site/_includes/components/Hero.js

I noticed most blog posts shift a lot as they load their hero image. I believe giving them `width` and `height` fallback attributes is the approved way to define their intrinsic size ([thread](https://github.com/WICG/intrinsicsize-attribute/issues/16#issuecomment-503245998)) and seems to help mitigate a lot of the shifting.
Related [css-tricks post](https://css-tricks.com/what-if-we-got-aspect-ratio-sized-images-by-doing-almost-nothing/).
- Add `width` and `height` fallback attributes to hero image to prevent layout shift.

Add fallback size to hero so it doesn't shift.

---

src/site/_data/site.js

Fixes #2114.
We're now receiving a cert from Firebase Hosting for https://auth.web.dev, so we can use it for login.

flip prod auth domain

---

src/site/content/en/blog/nfc/index.md

- Changes title from "Interact with NFC devices on the web" to "Interact with NDV devices on Chrome for Android"
- Removes draft status so that the page is visible on the blog again

Clarify that NFC is only available on Chrome for Android

---

src/site/_includes/components/YouTube.js

- Hides the yt iframe during screenshot testing cuz it's flaky and keeps shifting the channel logo around a few pixels which breaks the tests. Returning `""` instead of a undefined return because eleventy will literally write "undefined" if we do that and it just looks ugly :P

Hide yt iframe during screenshot tests.

---

.github/workflows/continuous-integration-workflow.yml
.github/workflows/snapshot-firestore.yml

We could target e.g. /backups/YYYY-MM-DD, but it would be a more complex workflow (have to set an env var with `date "+%Y-%m-%d"`, then pass it to the gcloud command, ...).
This will work for now.

add Firestore backup workflow

---

.github/workflows/percy-workflow.yml

Fixes #2166
Better version of #2180
- Use GitHub Actions' [request paths syntax](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths) to limit when Percy runs. Should only run if .njk, .js, or .scss files are changed.

Only run Percy on certain file types.

---

src/site/_collections/recent-posts.js
src/site/_includes/components/PostCard.js
src/site/content/en/index.njk
src/styles/components/_grid.scss
src/styles/components/_post-card.scss
src/styles/tools/_breakpoints.scss

Fixes #2028 
On the homepage, when you resize to a smaller display, the recent posts cards wrap in a way that looks broken. This resolves the issue by changing the layout for the most recent card so it's in more of a featured position.
This is a short term fix, but really I'd like us to redesign the homepage at some point 👨‍🎨
Since a lot of work has been done on #1808, I think we should wait until that PR lands before merging this one. I can rebase against master after #1808 lands and clean things up in this PR. This PR is read for review though, so PTAL!
**Before**
**After**
- Changes the `recentPosts` collection so it ensures all posts have a thumbnail
- Adds a `featured` argument to the `PostCard` shortcode so it can apply a featured modifier …

Add a feature card class to 1st post on homepage.

---

.github/ISSUE_TEMPLATE/propose-new-content.md
.github/ISSUE_TEMPLATE/update-existing-content.md

- Splits the content issue template into two templates: one for proposing new content, another one for updating existing content

Update content issue templates

---

src/site/content/en/blog/notification-triggers/index.md

Notification Triggers is likely shipping in Chrome 80 beta next week, so I sanity checked the article. I found a few typos but nothing critical to the beta release.
FYI, @tomayac

Sanity check Notification Triggers article.

---

src/site/content/en/blog/fugu-status/index.md

Fixes #2171.
- Migrates the https://developers.google.com/web/updates/capabilities status page to a web.dev blog post

Capabilities status blog post

---

src/site/content/en/blog/fugu-status/index.md

- removes `draft: true` from fugu-status page

Make fugu-status live

---

package-lock.json
package.json
tools/percy/snapshots.js

Percy [recommends using scroll-to-bottomjs](https://docs.percy.io/docs/capturing-lazy-loading-images) to force `loading=lazy` images to trigger before doing a snapshot.
- Add scrolling to our snapshot script.
- Remove our sleep function as [PercyScript already provides one](https://docs.percy.io/docs/percyscript#section-waiting-for-elements).

Force percy to scroll page to load lazy images.

---

src/site/_data/site.js
src/site/_includes/codelab.njk
src/site/_includes/partials/banner.njk
src/site/_includes/partials/post.njk
src/site/_includes/path.njk
src/site/content/en/about/index.njk
src/site/content/en/authors/index.njk
src/site/content/en/blog/index.njk
src/site/content/en/learn/index.njk
src/site/content/en/measure/index.njk
src/site/content/en/tags/index.njk

Depends on #2205 
- Add `Banner` include to pages. Kind of a bummer to have to repeat it in so many places but `post.njk` needs it in a different spot from the rest of the pages so I didn't want to put it in `layout.njk`.
- Fixed a small bug with broken profile photos in codelabs.

Add MDN survey banner.

---

.eleventy.js
src/site/content/en/handbook/markup-code/index.md

MarkDown's default behavior of converting indented text to code blocks makes writing human-readable short codes very difficult. This PR turns off indented code blocks.

Disabled indented code blocks

---

src/styles/components/_details.scss

The chevron animation in the Details component is janky in Firefox. Since the details panel doesn't animate, animating the chevron doesn't seem essential, so this PR removes it.
- Remove Details component chevron animation.
- Remove $BORDER_COLOR variable from details stylesheet so it uses the global variable.
**Note:** Percy is grumping because it's not seeing a lazy-loaded image on the Learn page, but this PR causes no visual changes to the page on load; it just removes the chevron animation in the Details component.

Remove Details animation

---

src/lib/utils/router.js

Fixes #1868.
This was surprisingly simple.
To be fair, back/forward probably shouldn't be async operations, but this lets us share code between loading _new_ pages and navigating back to old ones.

disable scroll restoration for async loader

---

server.js
src/lib/bootstrap.js

Fixes #2024 
Also attempts to prevent more major failures in future by actively not including the Service Worker on unsupported domains.
We need the `server.js` change in this for two reasons:
* the literal 301 redirect for Google/search
* some poor user might have installed the Service Worker on "appengine-test.web.dev", and unless we nuke it, they'll never get an update (but the client-side change will hopefully help prevent things like this in future).

don't include SW on bad hostnames, redirect from appengine-test

---

src/site/content/en/blog/fugu-status/index.md
src/site/content/en/blog/notification-triggers/index.md

- Removes `draft: true` from Notification Triggers article 
- Adds Notification Triggers article to fugu-status
- Adds Web Serial codelab to fugu-status
cc: @tomayac

Remove `draft` from Notification Triggers article

---

src/site/content/en/blog/fugu-status/index.md
src/site/content/en/blog/nfc/index.md

This PR simply adds "Web NFC" to the new "New capabilities status" page and updates the Web NFC article to link back to it.

Add "Web NFC" to "New capabilities status" page

---

build.js
package-lock.json
package.json

Follow-on from #2246.
Generates Workbox logs in dev, removes in prod. Updates comment to explain how it works.

Terser rollup comment and dev/production

---

src/lib/utils/router.js

cc @philipwalton 
This actually isn't ideal and I played with not using scroll restoration, and instead doing something more like the polyfills for this feature do—basically when the browser does a popstate, two things happen:
1. `popstate`
2. (later, not sure how far) `scroll` (to restore position)
So you can basically retain the scroll position in the first event, immediately revert that position on the scroll, then once your async loading code is done, set the position as it was intended by `scroll`.
But the behavior seems pretty inconsistent.

clear scroll restoration before unload

---

src/site/content/en/metrics/cls/index.md
src/site/content/en/metrics/fcp/index.md
src/site/content/en/metrics/fid/index.md
src/site/content/en/metrics/lcp/index.md
src/site/content/en/metrics/tbt/index.md
src/site/content/en/metrics/tti/index.md

Clarifies the changes made in https://github.com/GoogleChrome/web.dev/pull/2250 to indicate that the 75th percentile recommendation refers specifically to mobile users.

Clarify that the p75 threshold is for mobile users

---

src/site/_includes/layout.njk

This PR adds missing meta theme-color element as suggested in Audits "Progressive Web App" section.
The value is the same as the one found in the web manifest.

Add missing meta theme-color

---

src/lib/components/Actions/index.js

This PR adds `rel="noreferrer"` to twitter share button as suggested in Audits "Best Practises".
`rel="noopener"` prevents the new page from being able to access the `window.opener` property and ensures it runs in a separate process.
`rel="noreferrer"` has the same effect but also prevents the `Referer` header from being sent to the new page.

Add rel="noreferrer" to twitter share button

---

src/site/_filters/html-date-string.js

Removes noisy warning about missing date strings.
The warning doesn't help me fix any underlying issues, doesn't provide context, so I am removing it.

remove noisy warning

---

src/site/content/en/blog/native-lazy-loading/index.md

- Updates browser support information regarding native image `loading` attribute
- Also firefox bug in issue tracker is now fixed https://bugzilla.mozilla.org/show_bug.cgi?id=1542784

native lazy loading support stats

---

src/site/content/en/blog/shape-detection/index.md

Barcode detection finally launches in Chrome 82. This PR updates the article accordingly.

[Shape Detection article] Add launch information for barcode detection

---

.remarkrc.js
src/site/content/en/blog/vr-comes-to-the-web-pt-ii/index.md
src/site/content/en/blog/web-ar/index.md
tools/linting/bad-urls.js
tools/linting/no-wiki-mdn-urls.js

This PR adds a linter that checks for links to "wiki.developer.mozilla.org" and warn to change to "developer.mozilla.org". 
It also updates some articles that are not compliant with this rule.
Fixes #2142

Add linter for wiki MDN links

---

.github/pull_request_template.md

Should help avoid the problem that occurred in PR #2250
- Mentions `DO NOT MERGE` label
- Removes the old comment about linking to content proposal issue (I think most of contributors know that they should do this and on the rare occasion that someone doesn't do it, I will spot it)

Mention `DO NOT MERGE` label in PR template

---

src/lib/components/CopyCode/index.js

This PR adds a missing `aria-label` to the CopyCode button as suggested by Audits "Accessiblity" section.

Add aria-label for CopyCode button

---

src/site/_collections/paginated-posts-by-author.js

I was testing with a fake article and getting very strange errors about duplicate permalinks. Turns out that when you use an invalid author ID, the pagination code tries to generate a permalink like "/en/" (with no suffix), so it fails without a good reason.
This explodes and explains why it's broken.

explode when using an invalid author

---

src/lib/sw.js
src/site/_includes/components/Meta.js
src/site/_includes/layout.njk
src/site/_utils/build-partial.js

* We were escaping titles, so pages with spaces loaded as partials were having space show up as %20
* Use the path's title as a fallback to article title (matches Meta)
* Default to a blank string if there's no title (we were stringifying "undefined")

fixes title generation issues re: Service Worker and partials

---

src/site/_includes/components/Meta.js

Fixes #1035 #2204
By adding a `canonical` field to the head of a file will add a `rel=canonical` to the head of the HTML.
@devnook @samthor PTAL, it's a small feature

feat(canonical): add support for canonical tags on pages, fixes #1035, fixes #2204

---

src/styles/components/_buttons.scss

The existing `.w-button` states had two issues:
- Hover and focus states were sticky on touch devices.
- The focus state wasn't conformant with [WCAG 2.1 SC 1.4.11](https://www.w3.org/TR/WCAG21/#non-text-contrast) (contrast for visual indicators of focus state was below 3:1).
- Using `@hover()` mixin, only show hover and existing focus state on devices that support hover.
- Using `focus-visible`, add contrast conformant focus ring* that appears only on keyboard navigation.
*Note: I would have preferred the focus ring to have rounded corners, but `box-shadow` and both pseudos are already in use.

Add accessible focus ring to w-button

---

src/site/content/en/blog/module-workers/index.md

This updates the Module Workers article with a section on Shared Workers, which are being updated to support modules in Chrome 82.
**Target live date:** before 03/25

Update Module Workers article with Shared Workers section

---

src/site/content/en/metrics/cls/index.md
src/site/content/en/metrics/fcp/index.md
src/site/content/en/metrics/fid/index.md
src/site/content/en/metrics/lcp/index.md

Expands on the update in https://github.com/GoogleChrome/web.dev/pull/2271 to suggest segmentation across both mobile and desktop devices and measuring the 75th percentile of both.

Add segmention rec for mobile and desktop

---

src/site/content/en/_redirects.yaml

Fixes #2337 
- Adds redirect from `/pwa/` to `/progressive-web-apps/`
We already redirect from `/pwa`, this just ensures that whether you include the trailing slash, we redirect you to the right place.

Add redirect for /pwa/ to PWA content

---

src/styles/generic/_lists.scss

- Make unordered list bullets inherit the color of surrounding text.
Rationale:
Currently, unordered list item bullets are always gray. When used in asides, that breaks visual cohesion. Also, because of the style used for default hyperlinks (underline only on hover), it makes it less immediately obvious that unordered lists in asides aren't hyperlinks, especially when they're proximal to a list of hyperlinks in the main body text (e.g., at the end of Lighthouse audit posts).

Make ul bullet color match text color

---

src/lib/bootstrap.js
src/lib/loader.js
src/lib/sw.js

Fixes #2311 and #1940.
I find the setup of the SW a bit fiddly, but I think the flows here make sense.
No SW => register and install, it claims clients, we "upgrade" to being intercepted by the SW. Partials are fetched. Can install as PWA almost immediately and work offline#.
Existing SW => force a refresh of partial(s), try to upgrade, if we're claimed by the SW (because of an architecture revision), do a reload ("abandon ship").

cache partials for PWA readyness

---

src/site/content/en/blog/wakelock/index.md

- The Origin Trial feedback included making manual and automatic releasing clearer. This PR addresses this.

[Wake Lock article] Make releasing options clearer

---

src/site/_includes/devsite/devsite-footer.njk
src/site/_includes/partials/footer.njk

Instead of unconditionally loading the footer image for "Google Developers" below that users usually don't get to see, this PR loads it lazily thanks to `loading=lazy` as described in https://web.dev/native-lazy-loading/
This will hopefully save one HTTP request on first load.

Lazy load Google Developers footer image

---

build.js

@mfriesenhahn can you try this on your Windows machine? And either way, can you upload a log of what the `npm run build` command spits out?
Attempts to solve #2331.

use explicit path.join rather than passing slash to fs.readFile

---

src/site/_includes/devsite/devsite-footer.njk
src/site/_includes/partials/footer.njk

Fixes #https://github.com/GoogleChrome/web.dev/issues/2364
- Adds dimensions on footer lazyloaded image as suggested by chrome `[Intervention]`

Set dimensions on footer lazyloaded image

---

src/lib/components/Search/index.js

This PR fixes some accessibility issues in the search widget discovered in the Audits accessibility section:
- Search input role needs to be ["searchbox"](https://www.w3.org/TR/wai-aria-1.1/#searchbox) instead of "search" to be compliant
- The search input wrapper aria-owns values was invalid because the `id` didn't exist in the page when search was not triggered. This is now fixed.
This change allows web.dev to reach the Accessibility score of 100.

Fix search widget accessibility issues

---

package-lock.json
package.json
src/lib/components/Search/index.js

This reverts commit 6586f7fd8b4f5f77ffc29762092e7c98efd601bc.
- Undo changes in #2348. It looks like those changes were causing index-algolia.js to break so the site wasn't deploying anymore. You can see an example of the build output here: https://github.com/GoogleChrome/web.dev/runs/514705638?check_suite_focus=true

Revert "upgrade to Algolia SDK 4+ (#2348)"

---

src/lib/components/LighthouseScoresMeta/index.js

Fixes #1224
Seems like downloading HTML pages on Chrome for Android is an issue with chromium => https://bugs.chromium.org/p/chromium/issues/detail?id=1041209 . So for now we will remove the button until there's a proper fix in Chrome.

fix(measure): disable report downloads, fixes #1224

---

src/site/content/en/blog/periodic-background-sync/index.md

This updates the existing [periodic background sync guidance](https://web.dev/periodic-background-sync/) to remove a few stray references to the origin trial (which has ended) and the fact that DevTools debugging is only available in Chrome 81 or later.
I also added a new section linking to another sample web app.

Post-OT updates to the PBS article

---

src/site/content/en/blog/how-to-distribute-signed-http-exchanges/index.md
src/site/content/en/blog/how-to-set-up-signed-http-exchanges/index.md
src/site/content/en/blog/native-file-system/index.md
src/site/content/en/blog/next-gen-css-2019/index.md
src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/index.md
src/site/content/en/handbook/content-checklist/index.md
src/site/content/en/handbook/inclusion-and-accessibility/index.md
src/site/content/en/handbook/markup-sample-app/index.md

Similarly to https://github.com/GoogleChrome/web.dev/pull/2340, by running a custom version of [remark-lint-no-dead-urls](https://github.com/davidtheclark/remark-lint-no-dead-urls), I was able to find dead internal URLs in web.dev. This PR updates some of them to the correct ones.

Fix internal dead URLs

---

.eleventy.js
src/site/_includes/components/Label.js
src/site/content/en/blog/module-workers/index.md
src/site/content/en/handbook/web-dev-components/index.md
src/styles/components/_all.scss
src/styles/components/_label.scss

This PR adds a new "Label" web.dev component that authors can use when they want to show a filename associated with a code snippet:
- new `{% Label %}` web.dev component
- updates the module-workers article to use it
- adds it to the handbook web.dev components page
Live preview: 
- https://deploy-preview-2387--web-dev-staging.netlify.com/module-workers/
- https://deploy-preview-2387--web-dev-staging.netlify.com/handbook/web-dev-components/#labels
Fixes #2058
old vs. new

Add "Label" web.dev component

---

src/lib/utils/router.js

- I noticed Firefox was logging a warning because when we navigate to a page without a hash in the url we still try to querySelector for one.

Fix warning in Firefox related to querying null

---

src/site/content/en/blog/image-support-for-async-clipboard/index.md

- Removes a superfluous try...catch block.
- Uses err for error names instead of e.

[Async Clipboard article] Remove superfluous try...catch block

---

src/lib/components/Codelab/_styles.scss
src/lib/components/Codelab/index.js

This PR hides Glitch for codelabs on mobile devices as it's not usable.
Live preview: https://deploy-preview-2389--web-dev-staging.netlify.com/codelab-remove-unused-code/
Fixes #2344

hide Glitch on codelabs on mobile

---

src/site/content/en/blog/a11y-tips-for-web-dev/index.md
src/site/content/en/blog/ar-hit-test/index.md
src/site/content/en/blog/perception-toolkit/index.md
src/site/content/en/blog/vr-comes-to-the-web/index.md
src/site/content/en/handbook/contributor-profile/index.md
src/site/content/en/lighthouse-accessibility/audio-caption/index.md
src/site/content/en/lighthouse-accessibility/duplicate-id/index.md
src/site/content/en/reliable/workbox/index.md

By running a custom version of [remark-lint-no-dead-urls](https://github.com/davidtheclark/remark-lint-no-dead-urls), I was able to find dead external URLs in web.dev. This PR updates all of them to the correct ones or removes them when it doesn't exist or is not relevant anymore.

Fix external dead URLs

---

src/lib/loader.js

Updates use of `content` var, since otherwise we're doing a `querySelector` multiple times.
Also clarifies how `ready` is used.

simplify var

---

src/lib/sw.js

This works around the issue raised [over in Workbox](https://github.com/GoogleChrome/workbox/issues/2402).
This isn't specifically tracked but I noticed it while working on JS issues. Images that we aggressively precache (anything in /images/*) weren't be served while offline, because the runtime handler was winning and claiming nothing was found.
As per the other bug:
- images live under /images/ and include both core site images as well as profile pictures etc
- we only want to precache the things that appear on the home page
- but we want to runtime cache any extended images that the user happens to load.

reorder caching so images are cached after 1st load

---

src/lib/utils/router.js

If the routing code failed before we called `ready()` to signify that the URL should change, we weren't setting the new URL correctly (instead just taking the old one).
I may force-submit this as this is relatively dangerous not to have out, it could prevent navigation.

fix router not setting correct URL on failure

---

src/lib/components/LighthouseGauge/test.js
src/lib/loader.js
src/lib/sw.js
src/lib/test/index.js
src/lib/urls-test.js
src/lib/urls.js
src/lib/urls_test.js

Fixes #2422
Loads to pages like "/foo?bar" (i.e., with no trailing slash on "/foo" but including a search param) resulted in redirects forever. This was a problem in both the SW and foreground pages.
This also fixes a couple of other issues:
* adds a test for normalizing
* fixes a likely `null` in the modal assessment cleanup code

fix SW redirect and normalizing URLs

---

src/site/content/en/metrics/cls/index.md
src/site/content/en/metrics/custom-metrics/index.md
src/site/content/en/metrics/fcp/index.md
src/site/content/en/metrics/fid/index.md
src/site/content/en/metrics/lcp/index.md

Fixes #2078
This PR adds a try/catch block around every code example that uses `PerformanceObserver` with the `type` option to avoid errors due to [this Safari bug](https://bugs.webkit.org/show_bug.cgi?id=209216).
Note: it feels a bit excessive to add the comment and bug link to each code example, but I did so because I was concerned that, without it, developers might think they need to use a try/catch *any* time they ever use `PerformanceObserver`, which isn't true.
An alternative way would be to define a helper function that wraps the try/catch and then use that helper function in each example, but that's also awkward to define for each metric.
If anyone has any thoughts on how to do this better, please let me know.

Add try/catch blocks for better cross-browser support

---

src/site/content/en/blog/native-lazy-loading/index.md

- Includes notes on `<iframe loading="lazy">` and the `auto` attribute being non-standard
Context: https://mobile.twitter.com/zcorpan/status/1242431629953548291
CC @zcorpan

adds note on iframe and auto value not being in spec

---

src/site/content/en/blog/nfc/index.md

The OT URL was missing somehow.

Set origin trial URL for Web NFC

---

build.js
src/lib/components/Codelab/_styles.scss
src/lib/components/Codelab/index.js
src/site/_includes/codelab.njk
src/styles/components/_header.scss
src/styles/generic/_page.scss
src/styles/pages/_all.scss
src/styles/pages/_codelab.scss
tools/percy/snapshots.js

This updates @beaufortfrancois' work, but tries to add/remove the listener as the element appears and is removed from the page.
It also (somewhat awkwardly) adds a warning notice when the screen is small. (This will be infinitely better when we switch to Shadow DOM).

update web-codelab and include notice on mobile

---

compile-css.js
package-lock.json
package.json

Remove explicit use of mkdirp in favor of built-in Node API.
FWIW a whole bunch of our immediate dependencies transitively depend on it still. It appears a bunch at the 2nd level.

remove mkdirp

---

src/site/content/en/blog/web-share-target/index.md

- Web Share Target demo link led to a Web Share demo, now leads to an actual Web Share Target demo

Link actual Web Share Target demo

---

.github/workflows/continuous-integration-workflow.yml
.github/workflows/percy-workflow.yml

- Add cache action to speed up our build times ([see cache Action explainer](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows))
- Change percy task to only run on pull_requests. It seems duplicative to run it when we merge into master as well.

Add node_modules caching to speed up Actions.

---

src/lib/components/Tabs/index.js

- During the last refactor of the Tabs web component, we removed the click handler and only had a focus handler to streamline the code. Turns out you need the click handler for iOS Safari.

Make tabs selectable on mobile

---

src/site/_includes/components/PostCard.js
src/site/content/en/blog/preload-optional-fonts/index.md

- Add missing `listitem` role to `PostCard`. We need this because the `PostCard` appears inside of a grid which has `role=list`.
- Add missing `alt` text for hero image on one of our posts. We should enforce alt as part of our (upcoming) yaml linting.

Get us a 100 accessibility score on the homepage.

---

src/site/content/en/blog/web-share-target/index.md

Reverts GoogleChrome/web.dev#2431
Let's keep the web share demo where it was and fix the demo if there's an issue.

Revert "Link actual Web Share Target demo"

---

.huskyrc
package-lock.json
package.json
tools/update-updated/index.js

Related to https://github.com/GoogleChrome/web.dev/issues/1959
- Adds a precommit script that will rev the `updated` field on modified posts. If a post does not have an `updated` field it will log a warning to the console but it won't block the commit.
I'm separately working on a linter that will run as a GH Action when someone does a PR. That linter will also flag the `updated` field if it hasn't been updated. That way the reviewer can decide if it's worth updating it or not (e.g. maybe deciding not to update it for small typo fixes).

Auto-update updated field on commits.

---

src/lib/components/AssessmentQuestion/index.js

- Currently, when a user submits an incorrect response to a self-assessment question, focus remains on the **Check** button even though it becomes disabled. To improve UX for keyboard users, this redirects focus to the currently active tab

Redirect focus on incorrect question submit

---

src/styles/components/_buttons.scss

- Icon buttons use a box shadow for the focus ring, but an outline was also showing. This removes the outline.

Fix dup focus rings on icon buttons

---

src/site/content/en/blog/samesite-cookie-recipes/index.md

Adds a link to MDN's cross-browser compatibility table at the top of the guide.

Add cross-browser support section to SameSite recipes

---

src/site/_drafts/_template-case-study/index.md
src/site/_drafts/_template-post/index.md
src/site/content/en/handbook/markup-media/index.md

- See https://github.com/GoogleChrome/web.dev/pull/2139 for context
- Add notice that posts without a hero will not appear on the homepage.

Add hero image notice.

---

src/site/_data/site.js
src/site/content/en/handbook/web-dev-components/index.md

- Disable the glitch embed when percy is running against the components page.
I think at some point we should probably rename the `site.env` variable since it's specific to eleventy at this point but I didn't want to do that in this PR for fear of breaking something unseen.

Clean up percy.

---

src/site/content/en/blog/covid19/index.md

A/B testing & personalization products are getting escalations from customers that web.dev is recommending a complete/outright disabling of all A/B testing & personalization immediately. This PR updates the guidance to do more justice to the nuance of the situation and explain that it's up to each business to decide whether A/B testing & personalization should be prioritized over page load time, or vice versa.

Update A/B testing & personalization guidance

---

src/site/content/en/blog/content-indexing-api/index.md

- Updates the "Launch" field to reflect that Content Indexing is launching in Chrome 83.
R: @rayankans to confirm that we're still on for a M83 launch.
CC: @jpmedley

Update the Launch field for Content Indexing

---

src/site/_includes/components/PostCard.js

- If an author forgets to put alt text on their hero image, then the link for the post card image will not have a name (and our a11y Lighthouse score will go down). But if someone is using a screen reader they likely don't get much from this link anyway since it's duplicative of the link used on the article title. So let's hide this link from screen readers and reduce the number of tab stops.

Hide post card image from screen readers.

---

src/site/content/en/blog/how-to-set-up-signed-http-exchanges/index.md

Adds testing instructions to the "How to set up signed exchanges" document, so publishers can verify the setup is correct.

Add SXG testing instructions

---

src/site/content/en/blog/badging-api/index.md

- fixes the invalid call of `setAppBadge` and `clearAppBadge` - they are available within `Navigator`, as the article itself informs.

Correct window to navigator in supporting section

---

src/site/content/en/blog/how-to-set-up-signed-http-exchanges/index.md

Fixes #2083 
I tried installing SXG and its nginx plugin with reading this document, and noticed some URLs are wrong to install [libsxg](https://github.com/google/libsxg/releases) from debian package.
- Fixes 404 urls for `libsxg` debian package
- Add `-y` option for consistency

Fix SXG debian package urls

---

package.json
src/styles/components/_all.scss
tools/percy/.percy.conf.yml

I think #2384 may have inadvertently broken the layout of the PostCard on tablets. The first card should have a 'featured' class that makes it lay out with the image on the left and the text on the right on tablets.
It looks like the cause of the bug is because we changed the ordering of our CSS. `_post-card.scss` used to come after `_grid.scss` and would override the grid. But when it was renamed to `_base-card.scss` the ordering swapped.
As a short term fix I moved the grid to the top of the file. But, as discussed with Michael, I'd love for us to take a crack at refactoring the cards so they're smaller and more composable and less dependent on overrides. There's also a lot of grid/typography/vertical rhythm stuff I'd like to improve in our CSS. Maybe if there's time we can dedicate …

Add percy test for tablets. Fix PostCards on tablet.

---

src/site/_includes/components/BaseCard.js

Related to #2554. If an article doesn't have a subhead it shouldn't render the subhead section. Otherwise it will render a link with no text inside of it which negatively affects our lighthouse a11y score. 
- Adds a `renderSubhead` function to the BaseCard which is a noop if there is no subhead.

Only render subhead if text exists.

---

src/styles/settings/_type.scss
src/styles/tools/_mixins.scss

Random tidbit I came across while reading [A Modern CSS Reset](https://hankchizljaw.com/wrote/a-modern-css-reset/).
https://marco.org/2012/11/15/text-rendering-optimize-legibility
- Changes our CSS to use `text-rendering: optimizeSpeed` instead of `optimizeLegibility`.

optimize text for speed versus legibility.

---

src/lib/actions.js
src/lib/fb.js
src/lib/store.js
src/lib/utils/storage.js

Wraps access to `window.localStorage`. This works around Firefox throwing a `SecurityException` in its private mode when you access this object.

wrap localStorage to deal with Firefox issues

---

server.js
src/lib/loader.js
src/lib/sw.js
src/site/content/en/_redirects.yaml

Fixes #2488 and #2529.
This (hopefully...) simplifies our SW a bit by treating 404's as unrecoverable errors that always go to the network. This occurs in the Service Worker as well as in the SPA routing (so a 404 will "break" the SPA). We just don't know if there's really a redirect backing whatever page 404'ed otherwise.
I've also added a comment to the redirects YAML to make it clear that trailing slashes there are unnecessary.

make 404s always go to network

---

tools/percy/snapshots.js

- It seems like /learn/ on mobile pretty consistently has flaky image loading issues. Seeing if increasing the time that percy waits before doing a snapshot helps any.

See if cranking up percy snapshot wait time helps with flakiness.

---

tools/percy/snapshots.js

- Use trailing slash on percy urls so we don't have to bother with a redirect.

Don't make percy go through redirects.

---

server.js
src/misc/nuke-sw.js

Adds a quick boolean that we can use to nuke the SW if necessary.

add service-worker kill switch

---

.github/workflows/percy-workflow.yml

We hit our free Percy limit of 5000 screenshots this month so I upgraded us to the paid plan. We made two changes recently that I think contributed to this overage:
- We were running Percy every time something got merged into master, even if we were just merging in markdown files of text. This also means we were running it at least twice for every PR (once during the PR review and once when it merged).
- I added an additional size to our [.percy.config.yml](https://github.com/GoogleChrome/web.dev/blob/6572b7c0bb5a2f8c6102ebec47747205caf23bb1/tools/percy/.percy.conf.yml#L3) file so we could take screenshots of tablets. So every PR generates at least three screenshots per synchronization.
- Only run percy against pull requests. Don't bother running it …

Only run percy against PRs.

---

src/lib/components/Search/index.js

Fixes #2346 
- remove `a` tag tab order inside search result box

search tab index bug

---

package-lock.json
package.json
tools/percy/snapshots.js

In my ongoing saga to make percy not flaky, I have stumbled across the networkidle option for puppeteer. Giving it a shot 🤞
- Tell percy to wait for the network to be idle before snapshotting.

Make percy wait for network idle.

---

build.js
src/build/virtual-json.js
src/lib/bootstrap.js
src/lib/components/Codelab/index.js
src/lib/fb.js
src/lib/store.js

Extracted from #2410 which will get closed.
* Adds virtual imports to all our build bundles (since you can just _not_ import them if you don't need them in your code)
* Exports individual keys (so our JS bundles aren't all including the whole config each)
* Update some code to use these keys
* Adds comments to the build script
* Disallows all external imports—i.e., those which Rollup can't find—Rollup would normally allow mistypings or missing deps (for example, if you haven't run `npm install` in a while), now throw

build script cleanup + virtual imports

---

.github/workflows/required-checks-workflow.yml

- Adds a GitHub Action to catch the DO NOT MERGE label. Should be set as a required check for branch protection in repo settings.

Add a workflow to catch the DO NOT MERGE label.

---

.github/stale.yml

- Adds a config for [stalebot](https://github.com/probot/stale)
- Issues and PRs with no activity for 30 days will be marked stale.
- Issues with the `pinned` label are exempt. Also, did you know you can [pin an issue](https://help.github.com/en/github/managing-your-work-on-github/pinning-an-issue-to-your-repository)?

Add stale bot config.

---

src/site/content/en/blog/use-srcset-to-automatically-choose-the-right-image/index.md

- Fixed a small typo I noticed in the srcset blog post

fix: typo in srcset blog

---

.github/workflows/continuous-integration-workflow.yml
src/site/_transforms/responsive-images/index.js
test/site/_transforms/responsive-images/index.js

Fixes #2609
- Adds a check to the responsive images handler to make sure it ignores JSON files or files with no output path (aka files with `permalink: false` set).
- Changes the ci workflow so it doesn't run `npm ci` twice.
- Changes the ci workflow to separate out the Algolia step so it's easier to isolate what's causing the failure next time.
- Adds a test to verify that non html files are ignored by the responsive images transform.
- Rewords the description of the test that checks if outputPath is not set.

Fix broken algolia build.

---

.gcloudignore

- As I was fixing a recent bug related to our deploy I noticed there's a number of files we send up to app engine that should be ignored. This just ignores those extra files.

Ignore more files so we do not deploy them.

---

.github/stale.yml

- Don't exempt issues with an assignee. Content team doesn't want this.
- Exempt issues with `accepted` label. Eng can use this to mark an issue to keep it alive.

Add accepted label. Remove assignee exemption.

---

.eleventy.js
src/site/_collections/authors.js
src/site/_collections/paginated-authors.js
src/site/_collections/paginated-posts-by-author.js
src/site/_collections/paginated-posts-by-tag.js
src/site/_collections/paginated-tags.js
src/site/_collections/tags.js

I moved most of the logic for the `paginated-tags`, `paginated-authors`, `paginated-posts-by-tags`,  and `paginated-posts-by-authors` into these "parent" collections (`authors` and `tags`). Since they had somewhat redundant logic/behavior I figured it would be good to apply all of that in one place.
Two reasons why this may be useful is:
1) We can now use the `authors` and `tags` collections to generate RSS feeds for each author and tag.
2) When we move to 11ty 0.11.0 there's a chance we can use computed data in order to do the pagination for the tags/authors landing pages and the individual tags/authors pages local data rather than creating multiple collections with similar data.
So it requires adding two collections for now, but it simplifies refactoring code for the derivative …

refactor(collections): create collections for `tags` and `authors` that derivative collections reference

---

.github/workflows/percy-workflow.yml

Fixes an issue where percy was not recording new snapshots to PRs against master.
- Make percy run checks against master if certain file types were changed.

Make percy record new snapshots for master.

---

src/site/_filters/strip.js
src/site/_includes/components/Meta.js

Fixes #2627
Replaces double quote's in attributes of meta tags using the `strip` function's `additionallyForbidden` argument.

fix(meta): remove double quote from text in meta attributes, fixes #2627

---

src/site/content/en/blog/content-indexing-api/index.md

This addresses a change to the Content Indexing API that will go into effect after the Origin Trial period ends, along with guidance about compatibility during the Origin Trial.
CC: @rayankans to confirm the details.

Content Indexing update: launchUrl is now url

---

src/site/content/en/blog/contact-picker/index.md

The docs didn't specify the Contact Picker is only available on mobile devices. This PR makes it more clear that they're mobile only.

Add note that the Contact Picker is available on mobile only

---

src/site/content/en/fast/preload-critical-assets/index.md

Closing tags for the two figure elements are missing a slash.
Currently:
Fixed:

Fix closing figure tags

---

build.js
package-lock.json
package.json

R: @samthor 
CC: @robdodson @MichaelSolati 
In the course of looking into something else service worker-related, I found a few tweaks that can optimize a your service worker a bit more (or are just best practices).
- Bumping your Workbox version dependencies in `package.json` so that they all match.
- Adding in a `dontCacheBustURLsMatching` config to your precache manifest generation, so that precaching requests for your versioned JavaScript URLs can be fulfilled from the HTTP cache.
- Changing your service worker's Rollup bundling to use [`@surma/rollup-plugin-off-main-thread`](https://github.com/surma/rollup-plugin-off-main-thread), which allows you to code split your service worker and then pull in everything you need at runtime via an AMD-style loader. This means that every time the, …

Workbox service worker tweaks

---

.github/ISSUE_TEMPLATE/propose-new-content.md

- Removes the `?fbzx` query param from the new content template, it's not required.

Remove the `fbzx` query param from the new content form

---

src/site/content/en/handbook/web-dev-components/index.md

- Use correct times symbol '×' instead of 'x'

[Handbook] Use correct times symbol '×' instead of 'x'

---

src/styles/components/_mastheads.scss

Fixes #2483 
- Clean up the learning path mastheads so they look better on mobile. Trying to be better about using relative units like `em` to (slowly) nudge us in the right direction for an eventual typography/writespace refactor.

Fix masthead on mobile.

---

src/site/content/en/handbook/handbook.11tydata.js
src/site/content/en/handbook/redirects/index.md

Fixes #2195
Changes:
* Adds instructions on how to do redirects.
* Adds a new `Content infrastructure` section to the Handbook.

Document redirects in the Handbook

---

src/site/content/en/handbook/markup-media/index.md

Fixes #2030 
- Adds image optimization guidelines
- Makes image sizing guidelines easier to scan
- Splits the content up into easy-to-scan sections
- Adds code samples to start of each section

Update image guidelines in the Handbook

---

src/lib/components/Codelab/_styles.scss
src/styles/pages/_all.scss
src/styles/pages/_codelab.scss

Fixes #2572. Probably.
This is to be fair a bit awkward as now it merges `web-codelab` styles in two places, buuut, I think it's the right answer for now. (at least until we have SD and rewrite a bunch of elements)

fix web-codelab fouc

---

src/site/content/en/lighthouse-performance/offscreen-images/index.md

- Add warning regarding native lazy loading not detected by lighthouse

Added warning re native lazy loading

---

.github/workflows/percy-workflow.yml

Some files like contributors.js get touched when an article gets published, and then percy runs every time someone pushes a change to that article during review. This limits the number of files percy cares about to just the subset that I think would actually affect the appearance of the site.

Ignore paths that were triggering percy.

---

src/site/content/en/blog/storage-for-the-web/index.md

- field `used` does not exist on resolved value, I belive it's a type and `usage` should be used

Fix mistake in the example

---

src/lib/fb.js
src/lib/utils/firebase-loader.js
test/unit/src/lib/utils/firebase-loader.js

I inadvertently introduced two issues to the Firebase code in #2767.
* We weren't returning the `firestore` object from its associated `Promise`
* We weren't setting `.async = false` on the dynamic scripts, so if e.g. Firebase's performance script loaded _before_ app, the load would fail.
(This didn't really show up in testing since cached files executed in element order.)

firebase loading fix

---

src/lib/components/Newsletter/index.js

Add `this.iframe.addEventListener('load', this.onIFrameLoad)` and/or check if `this.iframe.contentWindow.document.readyState === 'complete'` before removing scroll, setting height and modifying the `<a>` tags.

fix(web-newsletter): ensure iframe has loaded before modifying it

---

src/site/_includes/components/BaseCard.js

I noticed thumbnails on the /blog page were looking really pixelated. It turns out our use of `sizes` is working against us here. I think using `365px` was making it ignore the screen density, so it was selecting an image that was close to 365px which looked fuzzy on retina. Just removing sizes in this case and leaving the srcset that the cards provide fixes the issue. Now it selects the closest retina image.
- Remove `sizes=""` on card elements.
Compare the word "iframe" in the images below:
**Before**:
**After**:

Remove use of sizes in cards.

---

src/site/_includes/page.njk

- Fixes layout shift on the /vitals page because masthead image needed initial dimensions.

Add dimensions to masthead images.

---

src/lib/components/Actions/index.js
src/site/_data/site.js
src/site/content/en/_redirects.yaml

Fixes #2724
Add redirects from `/subscribe` to `/newletter`.

chore(redirect): send users from `/subscribe` to `/newsletter`, fixes #2724

---

src/lib/sw.js

Fixes #2807.
I think I was too aggressive last time I changed this stuff. I can't see a reason not to reintroduce this blind redirect, fundamentally because our server that generates redirects (which will be hit if e.g., /foo/ 404's) _also_ doesn't care (i.e., normalizes) all URLs to end with a slash, too.

redirect /foo => /foo/

---

src/lib/analytics.js
src/lib/bootstrap.js

- Changes places where we set custom dimensions to use strings instead of numbers. This makes the GA debug extension stop logging warnings on every event.

Set custom dimensions to strings.

---

src/site/content/en/blog/flexbox-gap/index.md

Fixes
- devtools image width extending beyond viewport on mobile
- removes dead link found on [twitter](https://twitter.com/tuhoojabotti/status/1258534267769901057?s=19) and [github](https://github.com/GoogleChrome/web.dev/commit/ed011f6897324c9c5f7f4984a2f24644b9186c28#commitcomment-39089105)

Flexbox gap patch

---

src/site/content/en/blog/native-file-system/index.md

Fixes #2828
- Fixed a simple typo in the `index.md` file in the blog for `native file system`
Here's the typo ->

Fixed the typo in the index.md for the blog native-file-system

---

src/site/content/en/index.njk

- Noticed the covid banner was knocking 10 points off our LH a11y score cuz the link and image didn't have accessible names. Since the image is decorative we can just hide it and rely on the link in the paragraph on the right.

Fix a11y score by hiding decorative banner image.

---

src/site/_data/postTags.js

Fixes #2785
Call `.toLowerCase()` on `tag.title` when generating a tag's description.

fix(postTags): set title in default description to lower case, fixes #2785

---

src/site/_includes/components/AuthorInfo.js
src/styles/components/_author.scss

- Adds the author's homepage to the social link list. 
- Switches authors markup to flex layout to avoid horizontal overflow.
- Before:
- After:

Add author homepage and switch to flex layout

---

src/site/content/en/blog/flexbox-gap/index.md

- With `flex gap` — With Flexbox `gap`
- `grid` cannot achieve the layout that `flex` — Grid cannot achieve the layout that Flexbox can
Also, there’s link to nowhere:
```md
[flexNG](#)
```
I’d fix it, but I’m not sure where to link. I know only LayoutNG, flexNG is new to me.

Clarify what’s code and what’s not

---

src/site/content/en/lighthouse-performance/user-timings/index.md

It previously linked to MDN.
- Fix broken link

Fix link to HTML5 Rocks

---

src/site/content/en/blog/image-support-for-async-clipboard/index.md

Fixes #2876
- The demo may fail due to a not yet implemented Feature Policy. Highlight this fact.

[Async Clipboard API article] Add prose why demo may fail

---

src/site/content/en/blog/optimize-cls/index.md

This (hopefully) fixes #2850 
- prefer WebM on all video elements in that article
- drop `codecs` parameter with invalid `h264` value altogether from `<source type>` attributes
- some style fixes (automatically done by editorconfig)

fix(optimize-cls): update code so that do not trigger warning in Firefox

---

.eleventy.js
.sasslintrc
src/lib/components/Tabs/_styles.scss
src/site/_collections/event-schedule.js
src/site/_data/event.js
src/site/_includes/components/EventTable.js
src/site/content/en/live/index.njk
src/styles/components/_author.scss
src/styles/pages/_live.scss

Shows sessions for web.dev/live.
Disables property-sort-order as it doesn't play nice with CSS Variables, see [issue](https://github.com/sasstools/sass-lint/issues/1224) (which has been going for ~2 years, has a PR, and seems to be being ignored).
Adds just a couple of sessions for now. We can fill them in.

webdev-live show sessions

---

src/lib/components/EventTime/_styles.scss
src/lib/components/EventTime/index.js
src/lib/pages/live.js
src/site/_collections/event-schedule.js
src/site/_data/event.js
src/site/_includes/components/EventTable.js
src/site/content/en/live/index.njk

Adds time component to web.dev/live. Supports start time (assumed in UTC) and optional duration in hours.
This displays in local timezone. Looks like this:
Matches mocks.

web.dev/live local time component

---

.github/workflows/lighthouse-ci-workflow.yml

fixes #2928 (Option 1 of 2)
- Migrates to use @lhci/cli@next directly to continue using the canary LHCI server.
- The alternative is move to temporaryPublicStorage until a separate LHCI server can be setup (see #2937)

chore: update LHCI integration to use @lhci/cli@next

---

.github/workflows/lighthouse-ci-workflow.yml

Sorry for the double PR today but just updated the LHCI server and noticed there weren't any datapoints from master in the past 2 months. Double checked the config and looks like the move to GitHub actions disabled running on master. It's best to run on master so that individual PRs *delta* can be surfaced in LHCI.
- Runs LHCI on master commits as well to establish a baseline

chore(ci): run lighthouse CI on master

---

src/site/_includes/partials/subscribe.njk
src/site/content/en/live/index.njk

Fixes #2903
Fixes #2901
I don't believe we use the `id="subscribe"` on `<web-subscribe>` directly for any reason, so I've repurposed it for the copy page.
There's still an issue; the subscribe element repositions itself because the event table and its tabs size is unknown until the JS loads. I'll create this issue when this PR is merged.

subscribe copy just for live page

---

src/site/_includes/partials/footer.njk
src/site/_includes/partials/text.njk
src/site/_includes/text.njk
src/site/content/en/community-guidelines/index.md
src/site/content/en/live/index.njk
src/styles/pages/_live.scss

Fixes #2931.
This page will be immediately live and just linked to from the shared footer. There's not a specific place for it in the web.dev/live design yet.
This also adds a generic "text" layout for this, as this content isn't a post or falls into any other category.

community guidelines page

---

src/styles/components/_topic.scss

Fixes #2470 
This was `display: flex` for some reason that I don't understand and doesn't seem to matter, so the extra `::before` element didn't work.

allow for ::before to push heading down

---

.github/workflows/lighthouse-ci-workflow.yml

- LHCI is running _way_ too often. Usually because a post will touch `contributors.j` and then the reviewer will accept a ton of changes, which runs LHCI many times. This throttles it to only run if important files were touched. The pattern is the same one we use for other actions.

Run lhci less often.

---

.github/CODEOWNERS

- Add @kaycebasques to codeowners for contributors and tags file.

Make kayce a codeowner for contributors and tags.

---

src/site/content/en/blog/more-variable-font-options-in-chromium-83/index.md

- Adds missing body argument to shortcode. This just makes the font and padding match other stuff in the body. I'm making some changes to the base banner class to be fixed position but banner--body will still be statically positioned. Wanted to add this argument so we don't break this article.

Add missing body argument to banner.

---

src/misc/manifest.webmanifest

This CL adds an app shortcut to the web app manifest so that users who installed web.dev PWA can use a shortcuts to "Measure".
See https://web.dev/app-shortcuts/ for what are app shortcuts.

Add "measure" app shortcut to web app manifest

---

src/site/content/en/live/index.njk
src/styles/pages/_live.scss

Fixes #2990 and ensures that every # on the page links to correctly and puts its heading below the header with a sane amount of padding.

ensure CSS padding at top for section

---

src/lib/components/ShareAction/index.js
src/site/content/en/live/index.njk

- Adds a `message` attribute to the share button so we can provide our own text. If no message is provided it will fallback to the original behavior of using the page title + author names.

Add message property to share button.

---

src/site/content/en/blog/variable-fonts/index.md

Fixes https://github.com/GoogleChrome/web.dev/issues/2862
- The table was missing the wrapper, causing overflow.

[Variable Fonts article] Add missing table wrapper

---

src/site/content/en/metrics/fcp/index.md

Link is broken on https://web.dev/fcp/: ctrl-f for `field metrics`. The link is: `https://web.dev/fcp/(/metrics/#in-the-field)`.
If it's easier to make the change yourself, that's good by me.

Fix link to field metrics in FCP

---

src/lib/sw.js

Possibly caused by lack of Headers() in Safari: https://developer.mozilla.org/en-US/docs/Web/API/Response/headers
Fixes #3009

Make Safari happy again

---

src/site/content/en/blog/get-installed-related-apps/index.md

- Add note that `getInstalledRelatedApps()` is currently broken on Android 
- Re-write some code as async/await

Add note that getInstalledRelatedApps is currently broken

---

src/site/content/en/lighthouse-performance/offscreen-images/index.md

- Removes the bug notice from the Lighthouse document on offscreen images audit now that it has been fixed.
Alternative: change the text to mention that this only applies to v5 and earlier.

fix: remove bug notice from lighthouse offscreen images

---

src/site/content/en/blog/samesite-cookie-recipes/index.md
src/site/content/en/blog/samesite-cookies-explained/index.md

Updates references to Chrome version 84 in line with https://blog.chromium.org/2020/05/resuming-samesite-cookie-changes-in-july.html

Updated SameSite rollout schedule

---

src/site/content/en/blog/commonjs-larger-bundles/index.md

It's more accurate to use ECMAScript modules since the standard continues to evolve.
Additionally, I added some actionable tips so folks can make sure they stay on the fast path ⚡️

Add actionable steps and rename ES2015 modules to ECMAScript modules

---

src/site/content/en/lighthouse-performance/time-to-first-byte/index.md

- Updated link to **Reduce server response times (TTFB)**  after the file was [renamed](https://github.com/GoogleChrome/lighthouse/commit/5162e5bbd989f8f1e915069dd3be0cf121adfd70#diff-7a82ec6e0314d8aebd8cf986bb7aaef5)

Fixed the URL to Reduce server response times (TTFB)

---

redirect-handler.js

Fixes #3079
The redirect handler was trying to match the url's pathname against the pathnames in the redirects.yaml. However, because we were using `req.url` it was including the query string in the match and not properly finding the redirect.
- Use `req.path` instead of `req.url`. `req.path` is the pathname and will not include query strings.
I'll do a follow up PR to add the query params back to the redirected string. But I'd like to first fix the 404s.

Fix 404ing redirect with query strings.

---

src/site/_data/event.js

Fixes #3040
- Update talk title from "Building for Modern Browsers and Progressively Enhancing Like It's 2003" to "Progressively Enhancing Like It's 2003".

Update talk title.

---

gulpfile.js
package.json

I think as part of the i18n work we started outputting html/json into language directories, but we didn't update the gulpfile to move their image assets to the right location. So we were outputting:
```
dist/
foo/
a.jpg
en/
foo/
index.html
index.json
```
This didn't break the site because our express server will look in the top dir, and then the en dir for assets. But we really want the images to live with their html files.
- Update the gulpfile so images in dist/ end up in the same directory as their html file.

Fix broken gulp image output.

---

src/site/content/en/payments/setting-up-a-payment-method/index.md

Fixes https://github.com/GoogleChrome/web.dev/issues/3101
- Fix wrong link in setting up a payment method : '_Empowering payment apps with Web Payments_'

Fix broken link in setting up a payment method

---

src/site/content/en/lighthouse-seo/robots-txt/index.md

Usage of the [Compare](https://web.dev/handbook/web-dev-components/#compare) component in https://web.dev/robots-txt seemed off. `"$"` was also not formatting correctly.

Fix usage of Compare components

---

src/lib/bootstrap.js

- I'm not sure if waiting for the load event is helping us. In fact it may be hurting us in LH if it counts against our TTI or FID. I think(?) it's safe to just go ahead and starting loading our additional scripts once bootstrap loads.

Skip waiting for load event to load app.js

---

src/site/content/en/lighthouse-performance/interactive/index.md

Looks like this was a typo back in the original commit (the thresholds haven't changed since then). "Fast" threshold is set [here in `interactive.js`](https://github.com/GoogleChrome/lighthouse/blob/a4535f32e16b862550aec5091243bf8dc6994135/lighthouse-core/audits/metrics/interactive.js#L50).
I also removed the HTTP Archive column because that seems like what newer LH documentation is doing (e.g. the [LCP docs](https://github.com/GoogleChrome/web.dev/blob/2a7caf37b7cc8de0fece7de63773b77cccf8d75b/src/site/content/en/lighthouse-performance/lighthouse-largest-contentful-paint/index.md#how-lighthouse-determines-your-lcp-score)) and it's kind of confusing :)

Fix Lighthouse TTI score threshold

---

src/site/content/en/progressive-web-apps/add-manifest/index.md

It seems the document has manifest.webmanifest everywhere but one reference to manifest.json.
- Update file name to what seems to be the new file name to be used.

Fix inconsistency in manifest file name

---

src/site/content/en/fast/defer-non-critical-css/index.md

Fixes https://github.com/GoogleChrome/web.dev/issues/3186
- Fix Broken link to command menu page

Fix broken link to command menu page

---

src/site/content/en/blog/why-coop-coep/index.md

Contrary to the current explanation, when an opener specifies a COOP of
`same-origin-allow-popups` and the opened resource specifies
`unsafe-none`, then the two documents *will* share the same browsing
context group.
This is supported by the explanation of `same-origin-allow-popups` which
precedes this section:
> A top-level document with `same-origin-allow-popups` retains
references to > any of its popups which either don't set COOP or which
opt out of isolation > by setting a COOP of `unsafe-none`.
It is also supported by the proposed specification text [1] which reads:
> To check if a response requires a browsing context group switch ,
> given a browsing context browsingContext , an origin responseOrigin
> and a cross-origin opener policy responseCOOP , run the followign
> steps:
>
> …

Correct description of COOP `unsafe-none`

---

src/site/content/en/blog/get-installed-related-apps/index.md

The bug affecting `getInstalledRelatedApps` has been fixed and deployed to all users. This PR removes the warning from the updates post.

Remove broken warning on getInstalledRelatedApps

---

.github/CODEOWNERS

Changes to the [`pwa-11tydata.js`](https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/progressive-web-apps/progressive-web-apps.11tydata.js) file requires approval from Rob or Sam (because it is a `js` file). 
If we're adding new content, it have to be reviewed and approved by Kayce. But it also needs approval from either Rob/Sam - because it touches a `.js` file. This extra approval feels unnecessary.
This PR adds @kaycebasques and me (the area/content owner) to the approval for the PWA `11tydata.js` file, so that either of us can approve any new content added to the PWA section.

Updates codeowners for PWA 11tydata.js to add petele

---

src/site/content/en/en.11tydata.js
src/site/content/en/learn/learn.11tydata.js

@kaycebasques - we talked about moving PWA higher up in the topic listing page, it fell off my plate and I am only finally getting around to it now.
- Reorders the Topics on the Home and Learn page to put our more critical content higher up. Vitals and PWA are now the top two items, followed by the other content.

Reorders topics on home & learn page

---

.github/CODEOWNERS

PR #3199 made me a code owner on the PWA `11ty.js` file. 
PR #3155 moves those files into a new location, and I lost my code ownership status. This gives me ownership over that file again.

Make petele codeowner of PWA

---

src/site/content/en/blog/web-otp/index.md

- Add a caveat that if sender's phone number is in the receiver's contact list, it won't work.
- Bump the available version number to 84.

Update Web OTP article

---

src/site/content/en/blog/granular-chunking-nextjs/index.md

- Mention `minsize` value and point to full config in granular chunking article
CC @spanicker

[Update] Mention `minsize` value and point to full config in granular chunking article

---

src/site/content/en/lighthouse-performance/performance-scoring/index.md

- Fix typo
- Add missing percentage value for "First CPU Idle" column in the Lighthouse 5 table

Fix typo and missing text

---

src/site/content/en/blog/web-otp/index.md

Per [spec](https://wicg.github.io/sms-one-time-codes/#parsing) the item after the '@' is the **host** part of the URL.
Origin includes scheme, and port as well which we don't want authors to include in the SMS as
there are automatically set to 'https' and 'null' by user agent to produce an origin given the host.

Update WebOTP blog to clarify that "host" should be used

---

src/site/content/en/blog/app-shortcuts/index.md

Corrected link over GitHub which is now 404 as part of the changes happened over branch name from master to main
- Error correction of a hyperlink towards GitHub
- 
-

Error correction

---

src/site/content/en/progressive-web-apps/app-like-pwas/index.md

As per the latest branch name changes from master to main. Some links seem to be 404 error, I'm fixing the same over this. :)
-  Fixing some 404 errors

Fixed some 404 error URLs, due to branch name changes

---

src/site/content/en/lighthouse-performance/performance-scoring/index.md

some updates.. primary goals:
* address that desktop scoring was introduced in v6
* explain that scores of 100 are not expected
also made changes:
* newer desmos for scorecurve (with p10)
* updated scorecalc link
* slow/moderate/fast -> poor/needsimprovement/good

performance-scoring: tweaks for LH v6

---

src/lib/components/BaseModalElement/index.js
src/lib/components/EventSchedule/index.js
src/lib/components/EventScheduleModal/_styles.scss
src/lib/components/EventScheduleModal/index.js
src/lib/pages/live.js
src/site/_data/event.js
src/site/_includes/components/EventTable.js
src/styles/pages/_live.scss

Creates a modal for schedule content. Positions this on the correct row. Works reasonably well on mobile even without CSS changes.
I've made changes based on feedback. You can now click whole row to select and I've addressed some accessibility feedback.
This is ready for review _but_ I've not imported everyone's abstracts. The original design calls for a single line inline with each session, but since most abstracts are at most one line _anyway_, I'm less inclined to show it there.
If you're happy I'll import everyone's abstract before submit.

schedule modal

---

src/site/_data/event.js
src/site/_includes/components/EventTable.js
src/site/content/en/live/index.njk

Fixes #3242
- Expands the event data to include flags for each day. Renames eventData to days and updates relevant shortcode.
- Bootstraps the page with event data, similar to what we do on /measure. This is so our client side js can poll and know when it needs to switch the video player.
- Adds an example of how we'd include different widgets based on the flags.

Add live page event data and bootstrap code.

---

src/site/_data/postTags.js
src/site/content/en/blog/app-shortcuts/index.md
src/site/content/en/blog/badging-api/index.md
src/site/content/en/blog/betty-crocker/index.md
src/site/content/en/blog/contact-picker/index.md
src/site/content/en/blog/content-indexing-api/index.md
src/site/content/en/blog/fugu-status/index.md
src/site/content/en/blog/get-installed-related-apps/index.md
src/site/content/en/blog/idle-detection/index.md
src/site/content/en/blog/image-support-for-async-clipboard/index.md
src/site/content/en/blog/maskable-icon/index.md
src/site/content/en/blog/native-file-system/index.md
src/site/content/en/blog/nfc/index.md
src/site/content/en/blog/notification-triggers/index.md
src/site/content/en/blog/periodic-background-sync/index.md
src/site/content/en/blog/shape-detection/index.md
src/site/content/en/blog/text-fragments/index.md
src/site/content/en/blog/wakelock/index.md
src/site/content/en/blog/web-otp/index.md
src/site/content/en/blog/web-share-target/index.md
src/site/content/en/blog/web-share/index.md
src/site/content/en/blog/websocketstream/index.md
src/site/content/en/blog/workbox-share-targets/index.md
src/site/content/en/progressive-web-apps/app-like-pwas/index.md

Fixes #2227 
- Changes all posts to use the `capabilities` tag 
- Removes `fugu` tag from all posts
- Adds description on capabilities tag page and include Project Fugu.
- Removes some misc tags that were no longer applicable.

Standardize on `capabilities` for tags

---

src/styles/components/_details.scss

Fixes #3239 (inline elements are displayed as block elements in mobile Safari)
- Remove flex layout from details widget. This fixes the Safari issue and doesn't change anything in other browsers.
**Before:**
**After:**

Remove flex layout from details widget

---

src/site/content/en/blog/color-scheme/index.md

- The value of `light only` was removed from the spec.

[color-scheme article] Remove `light only` references completely

---

src/site/content/en/blog/web-bundles/index.md

The "Web Packaging proposal" has a public home at https://github.com/WICG/webpackage.
Fixes #3271.

Replace a Google-internal link with a public one.

---

src/site/_includes/partials/subscribe.njk

Some people may bet having a weird experience when JavaScript is disabled and they try to sign up for the newsletter/subscribe. This will give them a friendly warning that the experience may not be as expected.

feat(subscribe): add warning when javascript is disabled

---

src/lib/components/EventSchedule/index.js
src/lib/components/EventStore/index.js
src/lib/components/EventTime/index.js
src/lib/components/Tabs/index.js
src/lib/pages/live.js
src/lib/store.js
src/lib/utils/time-offset.js
src/site/_data/event.js
src/site/_includes/components/EventTable.js
src/site/content/en/live/index.njk

Adds `<web-event-store>` and a few things to help manage the 'active day' of the event.
- you can pass e.g. "?_now=wdl-day2" to demo the event at a specific time
- the schedule is made available in unistore (with a boolean `.complete` as to whether the day is over)
- the active day is available in unistore—it prefers the upcoming day, but will retain the previous day until an hour before the next day (in case the user is still using the embed)
- I made it so deep-linking to a session ensures that tab is open when you load the page
- but otherwise it focuses the correct tab on load (this is _also_ done by the server, but maybe it's out of whack or we don't deploy properly)

web-event-store for time management

---

src/lib/components/EventStore/index.js
src/lib/components/LivestreamContainer/_styles.scss
src/lib/components/LivestreamContainer/index.js
src/lib/store.js

Fixes #3143, Fixes #3074
I tested the following scenarios:
The `isChatActive` code wasn't working because day 3 in the loop was setting `this._isChatActive` to false which then updated it in the store. So I changed some of the code in EventStore to make it always call setState and to make it a bit more stateless. Genuinely not trying to step on toes or anything 😅  I found it made it easier for me to reason through the code if it always called setState and if it left the decision of whether or not to render up to the components themselves. I don't think lit triggers a render if you set the same value over and over so I didn't need to add any guards to the elements. I watched the iframe src's in the elements panel and they stayed the same every tick.
- …

Make EventStore a bit more stateless. Get LiveStream working with unistore.

---

compile-css.js

This affects anyone where "node-sass" doesn't compile properly—i.e., if you're using latest Node.

silence require warning in compile-css

---

src/styles/pages/_live.scss

I noticed the carousel was causing the entire page to horizontally scroll on mobile because the parent had max-width: 512px. This limits that max-width to when the viewport is actually 512px.
- Add specific media query for 512px right column, otherwise set it to 100%

Don't let carousel parent break layout.

---

src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/index.md

- Add the `blog` tag to make this guide appear in the blog
- Update the date to today

List the CrUX Dash guide in the blog

---

src/lib/components/EventCarousel/index.js
src/lib/components/EventSchedule/index.js
src/lib/components/EventStore/index.js
src/lib/pages/live.js
src/lib/utils/time-offset.js
src/site/_data/event.js
src/site/_includes/components/EventTable.js
src/site/content/en/live/index.njk
src/styles/pages/_live.scss

Adds `<web-event-carousel>` to control whether the YouTube elements are clickable and have a thumbnail.
Shows enabled if there's a valid videoId and if the day is complete.

Control video tiles carousel

---

src/site/content/en/fast/serve-modern-code-to-modern-browsers/index.md

- Adds a section on using `bugfixes` property  with `@babel/preset-env`
CC @connorjclark @developit

Updates serve modern code to include bugfixes property

---

src/lib/components/EventMap/_styles.scss
src/lib/components/LivestreamContainer/_styles.scss
src/lib/components/LivestreamContainer/index.js
src/site/_data/event.js
src/site/content/en/live/index.njk
src/styles/components/_livestream-container.scss
src/styles/generic/_shared.scss
src/styles/pages/_live.scss

Fixes #3115, Fixes #3116
A bunch of CSS changes to make the pre event and during event pages look correct. We could land these now if we want. I still have some more changes for the during and post event pages but it might be good to break those apart. My hope is this will be the bigger of the two PRs because it contained a lot of cleanup.
- Adds a second carousel that displays only on mobile and hides the carousel in the right column.
- A lot of CSS :\
- Adds a share feedback button
- Adds the correct header for the during event phase.
- Adds a `.w-live-flow` class which can be used for consistent vertical rhythm.

Update styles for isPreEvent, isDuringEvent, and isPostEvent phases

---

src/site/_includes/partials/subscribe.njk
src/styles/components/_subscribe.scss
src/styles/generic/_forms.scss
src/styles/generic/_select.scss

Fixes #3372 
- Make our selects look fancy in all browsers 📸
- Add `.w-select--full-width` modifier class
- Updates subscribe form and /live/ sections to use the new styles
Here's what it looks like in Safari, Firefox, and Chrome:
Focus state just uses our site's default focus outline:
`.w-select--borderless` looks like this:
`.w-select--borderless` hover style:

Make select look all pretty and stuff.

---

src/site/content/en/blog/app-shortcuts/index.md

New release of PWABuilder supports app shortcuts. Let's update our article to mention it to help web developers who want to learn more about TWA.
Live preview at https://deploy-preview-3384--web-dev-staging.netlify.app/app-shortcuts/#trusted-web-activity-support
FYI @andreban @jungkees

Mention PWABuilder support for app shortcuts

---

build-sw.js

Adds a few conditions for different SW bundles rather than trying to enumerate through stuff, as we weren't bundling Workbox together.

fix SW bundling which wasn't working

---

src/lib/components/EventSchedule/index.js

Fixes #3336.
- Adds a wasModalOpen internal flag to EventSchedule to help it know when to reflect the current day in the tabs.

Don't switch tabs if the user is opening/closing the schedule modal

---

.github/workflows/continuous-integration-workflow.yml

- Disable the scheduled build while the live event is going on. Don't want to accidentally do any deploys while we're not looking :P

Disable scheduled deploy during live event.

---

src/site/content/en/blog/introducing-tooling-report/index.md

- Just fixing a typo in a link to a `CONTRIBUTING.md` file.

Fix typo on CONTRIBUTING.md name

---

.eleventy.js
build-sw.js
build.js
compile-css.js
server.js
src/build/hash.js
src/build/resource-path.js
src/lib/sw.js
src/site/_filters/strip-query-params-dev.js
src/site/_includes/layout.njk
test/integration/build-test.js

We're seeing odd caching problems in the Real World(™) whereby older HTML files are being served, which request hashed CSS/JS files that don't exist. This was mitigated by #3392 but this PR cleans up the behavior further.
- instead of generating "app-hashed.css" and serving it at all "app.css", "app-whatever.css", this PR now generates _only_ "app.css" and also catches "app-whatever.css".
- we include a cache-busting query param in our layout (e.g., "app.css?v=1234")
- this same exact URL, including cache-busting, is cached by our SW (avoiding #3363)
So if we see odd caching issues, "app.css" and "bootstrap.js" will _still be served_, because the server is ignoring the query string.
This will effect the "bigger refactor" in #3362 but that's fine.

use bootstrap.js/app.css again

---

.github/workflows/cleanup-versions-workflow.yml

This job failed, but I can't really work out why. It seems like the paths are a bit confused.
I'm just mirroring more what we do inside `package.json` now, where we always prefix with "./". ¯‍\‍_‍(‍ツ‍)‍_‍/‍¯

fix cleanup paths

---

src/site/content/en/blog/get-installed-related-apps/index.md

@petele I've used the `scheduled` tag so that we don't need to remember to push this at the end of next month.

Update getInstalledRelatedApps() for Windows support.

---

src/site/content/en/secure/cross-origin-resource-sharing/index.md

Added unit info for `Access-Control-Max-Age`

Add unit for Max-Age duration

---

src/site/content/en/blog/wakelock/index.md

- Remove full screen references. This is no longer needed since https://chromium-review.googlesource.com/c/chromium/src/+/2199677 is fixed. Thanks, @kenchris!

[Wake Lock article] Remove full screen references

---

src/site/content/en/blog/one-line-layouts/index.md

Link was broken as it was pointing inside the site. Added `https://` to have it point outwards.

[Bugfix] Fixes link on one line layouts article

---

src/site/content/en/blog/live-wrap-up/index.md

Fixes #3452
I want to discuss the destination of a broken link. Two patterns are possible:
1. https://web.dev/introducing-tooling-report
2. https://bundlers.tooling.report

update: tooling.report link

---

src/site/content/en/blog/hands-on-portals/index.md

This adds details of the [Portals origin trial](https://www.chromium.org/blink/origin-trials/portals) to the Portals article.
This is draft & "DO NOT MERGE" since the origin trial hasn't launched yet.
@uskay since you're the author of the original, can you take a look and let me know if you're ok with the changes?

Adding origin trial info & prettier reformat

---

src/site/content/sitemap.xml.njk

Fixes #3352
This way we can do away with the language, as it's not in the file slug.

fix(sitemap): use `canonicalUrl` for pages with a `url`, fixes #3352

---

src/site/_collections/authors.js
src/site/_data/authorsData.json

Currently we just log loudly that someone has no posts and no social information.
Instead we should throw. Or possibly not. But the warning is annoying and doesn't help anyone.

explode on missing author posts/social

---

src/site/content/en/fast/remove-unused-code/index.md

This PR adds a link to https://github.com/GoogleChromeLabs/webpack-libs-optimizations into “Remove unused code” audit docs, as it looks pretty relevant to the subject. But if you believe it’s not relevant/useful enough, feel free to close this.

Remove unused code: Mention GoogleChromeLabs/webpack-libs-optimizations

---

src/site/content/en/fast/chrome-ux-report/index.md

Updates https://web.dev/chrome-ux-report/ with links to the CrUX API guide and mentions CWV.

Add CrUX API to CrUX guide index

---

src/styles/generic/_lists.scss

Simple list in web.dev looks great, but once it's nested, it looks ugly.
The above image is current state with simple nested list. Notice there's unnecessary space before and after nested lists. These are because `ul` and `ol` tags have extra margin at the top and the bottom.
With this change, the nested lists look much better with minimized margin for top and bottom.
This change will make nested lists like [this](https://web.dev/chrome-ux-report-api/#what's-next) look better. (And I have a pull request to make it look better.)

Nested lists look ugly

---

src/site/content/en/lighthouse-performance/uses-responsive-images/index.md

- Not sure where this 25KiB came from but it was just bumped from 2KiB to 4KiB
noticed the typo in https://github.com/GoogleChrome/lighthouse/pull/11101/files

fix(lighthouse): correct use responsive images threshold

---

src/site/_data/authorsData.json

- Looks like there was a space added between the protocol and URL for `homepage` properties, this removes the space

Removes space in authorData.json homepage URLs

---

src/site/content/en/reliable/handling-navigation-requests/index.md

- Small typo in the word "Cache-Control"

Fix typo in "Cache-Control"

---

.github/workflows/continuous-integration-workflow.yml

During web.dev LIVE I disabled scheduled builds so we wouldn't accidentally deploy over the running site. This PR enables schedule builds again and sets them to run on Fridays (previously they did Mon-Thur). It seems like an easy mistake for an author to assume that a scheduled build would happen on Friday and since it's first thing in the morning I think there's less concern about deploying the site. I would still like to avoid deploying the site at the _end_ of Friday so folks don't have to stress about it going down over the weekend :)
- Enable schedule builds
- Run scheduled builds on Fridays

chore: Enable scheduled builds

---

.huskyrc
package.json
tools/update-updated/index.js

Fixes #3368
- Don't run `update-updated` as a pre-commit hook.
- Rename npm script from `precommit` to `updated`. If folks want to use the script they can still do `npm run updated`.

Disable updated hook.

---

src/site/content/en/blog/text-fragments/index.md

The origin trial for `ForceLoadAtTop` was extended to 85. https://groups.google.com/a/chromium.org/g/blink-dev/c/yG0JzbEUoX4/m/eFfQJwRzBAAJ

Extend origin trial.

---

src/site/content/en/blog/at-property/index.md

Fixes some typos in the @property post:
- Change `megenta` to `magenta`
- Add `rule` to give `@property` context
- Change `right` to `left` to describe image

Fix @property post typos

---

src/site/_data/paths/fast.json
src/site/_data/paths/metrics.json
src/site/_data/paths/vitals.json
src/site/content/en/learn/index.njk
src/site/content/en/learn/learn.11tydata.js

Given that /vitals, /metrics, and /fast are highly coupled, I think grouping them together makes it easier to locate content - for both the "performance" and "realize what the web can be" sections.
Before
After
cc @philipwalton

Create separate performance section on /learn, update captions

---

src/site/content/en/blog/notification-triggers/index.md

- Add info that the API is being put on hold.

[Notification Triggers article] Add "on-hold" info

---

src/site/content/en/blog/text-fragments/index.md

- The new link is https://github.com/GoogleChromeLabs/text-fragments-polyfill.

[Text Fragments article] Update polyfill link

---

src/site/_data/paths/progressive-web-apps.json
src/site/content/en/blog/badging-api/index.md
src/site/content/en/blog/multi-origin-pwas/index.md
src/site/content/en/blog/web-share-target/index.md

Replaces #3578 - essentially the same, except content is not physically moved, it's just added to the PWA landing page.
Updates to the PWA info architecture 
- Re-orders top line topics to move install closer to the top since it's a key component of PWAs
- Moves `badging`, `app shortcuts`, and `share target` into the PWA folder
- These were originally posted as blog posts, but have been moved into PWA area since they're only available to installed PWAs.
- Creates new advanced topics section where deeper dive content will go
- Moves PWA multi-origin from blog into advanced topics

Adds PWA content to PWA landing page

---

.github/CODEOWNERS

- Makes web-dev-content team the owners for src/images/authors. This will prevent the eng team from getting tagged in on content PRs.
- Switches to using full directory paths (content/ -> src/site/content)

Make content team the owners for author images.

---

src/site/content/en/blog/iframe-lazy-loading/index.md

- Fix a typo in the iframe-lazy-loading blog post

[docs] fix typo

---

src/site/content/en/blog/notification-triggers/index.md

- Re-add the link https://developers.chrome.com/origintrials/#/view_trial/6883752030435803137

[Notification Triggers article] Re-add OT link

---

src/site/content/en/blog/badging-api/index.md

- Updates App Badging API to include support for calling it from the service worker 
- Explicitly calls it App Badging (vs Badging) since the doc only covers app badging.
- Removes outdated origin trial info

Updates to App Badging API

---

src/site/content/en/blog/contact-picker/index.md

- More explicit about where the API is available (Chrome on Android) 
- More explicit about when `icon` and `addresses` landed
- Refined details around `getProperties()`

Updates to Contact Picker API article

---

src/site/content/en/blog/badging-api/index.md

- The link was missing. https://www.w3.org/TR/push-api/

[Badging API article] Add Push API link

---

src/site/content/en/angular/get-started-optimize-angular/index.md

"ng start" command is not available in Angular CLI.
"ng serve"  command is used to start Angular applications.
Reference: https://angular.io/cli
Fixes #3644

Correct cli command to start angular application

---

src/site/_includes/components/Instruction.js
src/site/content/en/fast/apply-instant-loading-with-prpl/index.md
src/site/content/en/fast/codelab-extract-and-inline-critical-css/index.md
src/site/content/en/fast/codelab-optimize-third-party-javascript/index.md
src/site/content/en/fast/identify-slow-third-party-javascript/index.md

Fixes #3609
- Change the instructions component to say "Click the Lighthouse panel" instead of the "Audits" panel. The name of the panel is inferred from the argument passed to the shortcode, i.e. {% devtools-**lighthouse** %}
- Updates existing articles to use devtools-lighthouse

Update instructions component to use Lighthouse.

---

.github/workflows/continuous-integration-workflow.yml

Moves the site to an hourly deploy cadence (Mon-Fri), instead of deploying every time we merge something into master. Also adds a 'Run Workflow' button so folks can manually deploy the site on-demand.
**Why do this?**
We've recently been seeing issues with App Engine failing our builds. The App Engine team is still debugging why this is happening, but one likely culprit is when we queue multiple builds to run at the same time. This is pretty easy to do if we merge two PRs close to one another. It's also wasteful to enqueue so many builds. This change will essentially bucket our builds, so if we merge 10 PRs in an hour, it'll only do 1 deploy. The addition of the manual trigger also means folks can deploy the site immediately if they need to.
- …

Add manual build trigger and updated scheduled build cron to be hourly.

---

src/site/content/en/blog/web-otp/index.md

A tiny typo fix. `recives` -> `receives` in Web TOP article.

A tiny typo fix.

---

src/site/content/en/blog/wakelock/index.md

- Re-add the link https://developers.chrome.com/origintrials/#/view_trial/902971725287784449

[Screen Wake Lock article] Re-add OT link

---

src/site/_collections/authors.js

Fixes #3318
When in `prod` mode the authors collection will check if the author has a profile picture. If they do not it'll log a warning in the console and swap in `no-photo@2x.jpg`.

fix(authors): add fallback images in `prod` if authors don't have them, fixes #3318

---

src/site/_collections/algolia-posts.js

This PR adds authors to algolia posts so that users who search for authors in web.dev can see posts they've published.
Once it's live, I'll add `authors` to the list of `searchableAttributes` in algolia admin interface.

Add authors to algolia posts

---

src/site/_includes/components/Hero.js

This PR make sure the hero image is not fetched on small screen devices. It is done by simply adding `loading=lazy` to the hero image element.
Without this fix, the hero image is always downloaded but never shown in the page on small screen devices.

Don't fetch hero image if small screens

---

src/site/content/en/blog/idle-detection/index.md

- The API now requires `IdleDetector.requestPermission()` rather than `Notificaiton.requestPermission()`.

[Idle Detection article] Reflect permission changes

---

.github/workflows/continuous-integration-workflow.yml

Fixes #3703 
- Index algolia _after_ a deploy succeeds

Don't index algolia if a build fails.

---

.github/workflows/lint-and-test-workflow.yml

Fixes #3705 
- Switch to pull_request_target so PRs from forks have proper permissions
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

Run linter and tests using pull_request_target

---

.github/workflows/percy-workflow.yml

- Removes the ignore for contributors.js because we don't use it anymore
- Tells percy to only snapshot if js files in src/ or shared/ are changed

Remove unused percy paths. Make others more specific.

---

.github/workflows/lint-and-test-workflow.yml

Fixes #3705 
- Rev to latest version of dorny/paths-filter which supports pull_request_target event.

Rev dorny/path-filter.

---

src/site/content/en/blog/keyboard-lock/index.md
src/site/content/en/blog/text-fragments/index.md

URLs with /features links to a list view and the identified item is supposed to expand and scroll into view. This is broken in the current iteration of Chrome Status.
@tomayac FYI

Always link to /feature instead of /features

---

src/site/content/en/lighthouse-performance/lighthouse-largest-contentful-paint/index.md

I think this is an inconsistency to the rest of the documentation. PageSpeedInsights and https://web.dev/lighthouse-largest-contentful-paint/ use 2.5-4 as moderate range.

Fix minimum bar for LCP

---

src/site/content/en/lighthouse-accessibility/bypass/index.md

Fixes #3606
- `<heading>` changed to `<header>` in lighthouse checks.

Issue #3606 : <heading> should be <header> in Lighthouse docs

---

src/site/content/en/blog/async-clipboard/index.md

Fixes #3724
- Fixes a syntax error in the snippet [here](https://web.dev/async-clipboard/#the-copy-event)

Fix Syntax and Reference errors in clipboard code snippet

---

src/site/content/en/blog/badging-api/index.md

Tiny change to note app badging is supported in Edge.

Add note about badging support in Edge 

---

src/site/content/en/blog/requestvideoframecallback-rvfc/index.md

- Improve the title. The current one wraps very unfortunately:

[requestVideoFrameCallback article] Improve title

---

src/site/_collections/authors.js
src/site/_collections/tags.js

Fixes #3532
The first time the collections get called is by 11ty when it passes the 11ty collection object into it. Every time we call it after, elsewhere, we are unable to pass in the 11ty collection object, which means that if we call it to process authors posts it'll think there are no authors posts and provide a twitter link instead of a link to the authors page.
By storing the result of the authors and tags, we can return the collection object with the posts and the correct links. (And we don't need to process it again)
Memoization FTW!(?)

refactor(collections): save processed 11ty collections, fixes #3532

---

.github/stale.yml

- Makes the stalebot leave a comment when it closes issues. This will make it easier to tally up how many items it closed each month.

Add stale close comment.

---

src/site/content/en/blog/hid-examples/index.md

This PR makes sure the HID examples post reflects new Origin Trial milestone (Chrome 86 instead of Chrome 85).

Updated Origin Trial date for HID examples post

---

src/build/minify-js.js
src/build/virtual-json.js
src/lib/actions.js
src/lib/app.js
src/lib/bootstrap.js
src/lib/components/AssessmentQuestion/index.js
src/lib/components/BaseElement/index.js
src/lib/components/Tabs/index.js
src/lib/urls.js
src/lib/utils/generate-salt.js
src/lib/utils/router.js
src/lib/utils/time-offset.js
src/lib/utils/underscore-import-polyfill.js
src/lib/utils/web-share.js
types/utils/global.d.ts
types/utils/navigator.d.ts
types/utils/npm-dependencies.d.ts

Fixes a bunch of small TSC typing issues.
We still have 78 errors, according to my local TSC. This is mostly in three categories:
* assuming a `Node` or `Element` can be used as a `HTMLElement` (just needs lots of casting), especially in component code
* we have untyped virtual imports for config
* no included types for SW code (the default DOM code doesn't seem to know about e.g., `ServiceWorkerGlobalScope`)

a bunch of misc tsc fixes

---

tools/cleanup-versions/index.js

Fixes #3759.
The action itself wasn't broken. I was just incorrectly recording the number of versions we successfully deleted to be _after_ we did a first deletion. So if there was fewer than 4 invalid versions, then this appeared if this was failing.

fix measuring what we delete

---

src/site/content/en/blog/fugu-status/index.md
src/site/content/en/blog/notification-triggers/index.md

- In the Fugu status list, move Notification Triggers from origin trial back to "behind a flag"
- More prominently state that Notification Triggers are currently on hold

Update Notification Triggers status

---

.github/workflows/alex-workflow.yml
.github/workflows/lint-and-test-workflow.yml

See this discussion: https://github.com/GoogleChrome/web.dev/issues/3705#issuecomment-675439002
Because we switched to the pull_request_target event, the files in our PRs were not being tested by our GH Actions. Instead, only the current contents of master were being tested. Alex was working around this because it uses a GH token to fetch the contents of the PR from the GitHub API.
- Move Alex into its own workflow so we can go back to using the pull_request event for our other linting and testing tasks.

Move alex to a dedicated workflow.

---

src/lib/components/CopyCode/_styles.scss
src/lib/components/CopyCode/index.js
src/site/_includes/partials/post.njk

Partial fix for #3783 
- Fixes the broken font on the copy code button.
- Hides the ToC for now as the `web-table-of-contents` seems to cause a bit of horizontal overflow on mobile.

Fix copy button, hide ToC for now.

---

package-lock.json
package.json
tools/percy/.percy.conf.yml
tools/percy/snapshots.js

TL;DR: This should fix intermittent missing assets: https://percy.io/web-dev/site/builds/6678051
When there is a `loading` attribute on an iframe, it causes request interception to hang in Puppeteer, which caused Percy's asset discovery process to timeout after 30 seconds (causing missing assets).
This PR updates the SDK to fix the asset discovery timeout (fixed upstream in Percy's SDKs). It also contains a few small updates to the `snapshots.js` script to make the tests run faster. When debugging, it made my feedback loop more manageable (2 mins --> 40 second test runs). With the small refactor to check for the `active` state (rather than a hard coded 5 second timeout), it shook out a small bug. It seems in tests the "about" page never gets the active state applied. It doesn't fail the …

test: Update `@percy/script` to avoid Percy SDK timeouts

---

src/styles/components/_label.scss

Fixes #3800
- Fix broken margin on `.w-label` element when it's next to a Glitch embed

Fixes #3800. Label should not overlap glitch embeds.

---

src/site/content/en/blog/coop-coep/index.md

* Add COOP Reporting API
* `blocked-url` => `blockedURL`

Update with COOP Reporting API

---

src/site/content/en/accessible/style-focus/index.md

- Fix incorrect URL link in https://web.dev/style-focus/#use-:focus-visible-to-selectively-show-a-focus-indicator

Fix URL link

---

src/site/content/en/react/route-prefetching-in-nextjs/index.md

Fixes #3818 and links broken due to changes in the URL scheme on nextjs.org.

Fix broken Glitch and nextjs.org links

---

src/lib/app.js

Related to #3836 
- Temporarily disable content indexing API. We should turn this back on when the underlying bug is fixed in the API itself.

Temporarily disable content indexing.

---

src/site/content/en/fast/native-lazy-loading/index.md

Anchors that link to "Distance-from-viewport threshold" section are broken after https://github.com/GoogleChrome/web.dev/pull/3513. This PR should fix them.

Fix broken anchor links on "Native image lazy-loading for the web" article

---

src/site/content/en/blog/storage-for-the-web/index.md

Add more accurate maximum storage info for Firefox based on the already cited article: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#Storage_limits

More accurate storage info for Firefox

---

.github/workflows/alex-workflow.yml

- alex-recommends wasn't using the latest version of alex, which was failing to detect singular uses of 'master' and 'slave'. Previously it would only flag these if they were used in the same phrase, i.e. "master and slave".

Get latest version of alex recommends

---

src/site/content/en/metrics/cls/index.md

I thought this was fixed a while ago, but @npm1 noticed today the `disconnect()` method was still being called. We need CLS to be observed for the entire page lifecycle, so we shouldn't ever disconnect the observer.

Fix a mistake in the CLS code sample

---

src/site/content/en/blog/multi-screen-window-placement/index.md

`onscreenschange` is the event handler.
`screenschange` is the event name.
https://annevankesteren.nl/2011/08/on-events

[Window Placement article] Correct terminology (event vs. event handler)

---

src/site/content/en/blog/iframe-lazy-loading/index.md

Add paragraph with bulk update solution for Wordpress users
next step: @kaycebasques to verify that we support this approach (pinged relevant people on 8/25)

Add WordPress guidance for iframes lazy-loading

---

src/lib/sw.js
sw-manifest.js

Fixes #3879
- Inline the sw manifest to avoid etags getting out of sync.

Inline sw manifest to avoid weirdness with etags.

---

src/site/content/en/blog/multi-screen-window-placement/index.md

Fixes a link to Chrome Status by changing a /features url to a /feature url.

Fix link in multi-screen article.

---

server.js

Fixes #3911 
- Add express handler that forces html to not be cached at all. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Directives for more info.
@jeffposnick mentioned that we might be able to get away with disabling etags in express.static() and relying on Last-Modified:
```
app.use(express.static('dist', {
etag: false,
lastModified: true,  // Just being explicit about the default.
}));
```
I'd like to land this no-store change as a quick fix to see if it unbreaks the site. Then we can see if using the `etag:false` approach works.

Force express to no-store our html.

---

src/site/content/en/blog/fetch-upload-streaming/index.md
src/site/content/en/blog/monitor-total-page-memory-usage/index.md
src/site/content/en/blog/nfc/index.md
src/site/content/en/blog/serial/index.md

As discussed in https://github.com/GoogleChrome/web.dev/pull/3860/#discussion_r487340601 and https://github.com/GoogleChrome/web.dev/pull/3860/#discussion_r488021594, the "experimental-web-platform-features flag" section should be moved before the origin trial section for all web.dev articles.
This PR addresses this.
Note that I intentionally didn't update the "updated" article tag as the content doesn't change, only the layout.

Move experimental-web-platform-features flag section

---

src/site/content/en/blog/storage-for-the-web/index.md

Quota heuristics are a complex area. Sorry for the confusion here! :cry: 
* Chrome uses up to 80% of total disk space for web storage. Source [here](https://source.chromium.org/chromium/chromium/src/+/master:storage/browser/quota/quota_features.cc?q=kExperimentalPoolSizeRatio).
* Out of this 80%, Chrome is willing to dedicate at most 75% to a single origin. Source [here](https://source.chromium.org/chromium/chromium/src/+/master:storage/browser/quota/quota_features.cc?q=kPerHostRatio). 75% * 80% = 60% total disk space / origin.

Fix Chrome's quota numbers.

---

src/site/content/en/metrics/index.njk
src/site/content/en/notifications/index.njk
src/site/content/en/payments/index.njk
src/site/content/en/progressive-web-apps/index.njk

As title described, I noticed that there are empty card/post on certain tags page (`/tags/*`). Including:
- https://web.dev/tags/metrics/
- https://web.dev/tags/notifications/
- https://web.dev/tags/payments/
- https://web.dev/tags/progressive-web-apps/
It looks like this:
I think it's because there are `tags` been defined which is exactly the same as `pathName`. And sort of created a self-referencing that resulted in the page been curated under itself.
Removing them should fix this.

Remove self-referencing tag from /tags/* page

---

src/styles/components/_images.scss

Web.dev's CSS uses `*{box-sizing:border-box}`. However, for `.w-screenshot` images/videos that supply a `width=".."` attribute, this means that images are rendered 10 pixels smaller than the markup's specified width. With this PR, the width attribute value for `.w-screenshot` images/videos is taken to be the _content_ width, so that images are not slightly scaled. This only affects `.w-screenshot` because it applies a border and padding.
You can see the blurry effect in the before & after images below:
Here's a live example image you can use to compare the deploy preview's sizing VS what's on stable:
https://web.dev/text-fragments/#mixing-element-and-text-fragments
https://deploy-preview-3943--web-dev-staging.netlify.app/text-fragments/#mixing-element-and-text-fragments

Respect screenshot image widths from markup

---

src/site/content/en/blog/detached-window-memory-leaks/index.md

Currently the table causes the whole page to scroll horizontally. I wasn't sure if it would be better to de-dent the table (thinking that might re-enable horizontal scrolling?), or just remove it entirely. I've just removed.it here if that's fine.

Detached Windows: fix table

---

src/site/content/en/blog/detached-window-memory-leaks/index.md

I had this lying around, decided to spruce it up enough that it's perhaps worth linking to in the article. I've intentionally _not_ embedding the Glitch here, because heap snapshots taken when iframed inside web.dev would be confusing.

(Detached Windows) Add step-by-step walkthrough

---

src/site/_filters/get-paths.js
src/site/_includes/codelab.njk
test/unit/src/site/_filters/getPaths.js

Fixes #3939.
Having said that, I wonder if we should just simplify the `getPaths` function: we only use it literally for one reason, to get the default path for "back" URLs.
(We use `postToPathsMap` for a bunch of things, but that's more on the _discovery_ angle, things we explicitly want to list in certain places.)

Fix undefined codelab paths

---

src/lib/urls.js
test/unit/src/lib/urls.js

Fixes #3969.
We were constructing a new URL from the pathname, which when it was "//foo", was treated as an origin. (This is an interesting bug and I wonder how often normalizing code doesn't look for this.)

remove extra slashes when normalizing URL

---

src/site/content/_redirects.yaml

Adds a vanity url redirect for web.dev/scale-on-web
- redirect web.dev/scale-on-web to web.dev/tags/scale-on-web

Add vanity url for scale on web case studies

---

src/styles/generic/_code.scss

This PR makes sure code blocks takes all available horizontal space on small(er) screens.
<p align="center">before vs. after</p>

Make code blocks larger on small screens

---

src/site/content/en/lighthouse-performance/lighthouse-largest-contentful-paint/index.md

LCP fast threshold was 2 even though the mid threshold starts at 2.5. This change makes the threshold consistently 2.5, which is how it's documented at web.dev/lcp.

Fix LCP fast threshold in LH doc

---

src/site/content/en/blog/detached-window-memory-leaks/index.md

This fix handles the case when nextSlide() is called before showNotes();
P.S. JFYI I don't participate in hacktoberfest :)

Add a guard in the example with a message passing

---

.github/workflows/tranaslation-status-workflow.yml
tools/update-translated/index.js

This PR changes the translation workflow Github Action to update the translation date in a separate json file instead of front matter of the translated post.

Update translated workflow

---

src/site/content/en/blog/file-system-access/index.md

- Add a link to TypeScript definitions for the FileSystem Access API to its blog post.

FileSystem Access: add TypeScript defs to "Helpful links"

---

src/site/content/en/reliable/app-shell-ux-with-service-workers/index.md

This PR updates a code example in the post https://web.dev/app-shell-ux-with-service-workers/ to use `handle` rather than `makeRequest`.
Based on https://github.com/GoogleChrome/workbox/pull/2123 `makeRequest` has been removed and `handle` is what should be used instead.
I followed https://philipwalton.com/articles/smaller-html-payloads-with-service-workers/ for an example of how `handle` should be used.

Update example from makeRequest() to handle()

---

src/site/content/en/blog/origin-trials/index.md

- Add info that breakage period [may be skipped](https://sites.google.com/a/chromium.org/dev/blink/launching-features#sites-canvas-main-content:~:text=If%20you%20wish%20to%20skip%20the,Ship%20imply%20approval%20of%20the%20request.).

[Origin Trial article] Add info that breakage period may be skipped

---

src/site/content/en/blog/logical-property-shorthands/index.md

Elad Shechter (@elad2412) suggested adding an additional example that appropriately covers a fallback, since the examples shown would not work completely. I agree, so I've updated the verbiage of the 1st fallback suggestion to call out it's incompleteness, and added a more complete solution that folks can use today. Hopefully it introduces only enough complexity that it can be leveraged and understood.

adds more elaborate example for fallbacks

---

src/site/content/en/blog/origin-trials/index.md

[Origin Trial article] Fix link in aside

---

src/site/_data/site.js
src/site/_includes/feed.njk
src/site/content/en/authors/feed.njk
src/site/content/en/tags/feed.njk

This PR make sure the `<updated>` feed date is the build date so that when an article is removed, RSS readers will fetch new information and will remove a previous cached article.
Fixes #3949

Change RSS updated field to build date

---

src/lib/components/Feedback/_styles.scss
src/styles/components/_actions.scss
src/styles/components/_article-header.scss
src/styles/components/_article-navigation.scss
src/styles/components/_footer.scss
src/styles/components/_header.scss
src/styles/components/_toc.scss
src/styles/generic/_main.scss

**Changes proposed in this pull request:**
When I wanted to print the detail page, there were many unrelated elements on the screen. I removed the elements that are not required for pdf or print.
**Removed elements for printing:**
- Feedback
- Action widget
- Header and footer
- Article navigation (return all articles)
- Toc button
**Also fixed this issue:**
Fixes #4037
**Preview:**
https://deploy-preview-4082--web-dev-staging.netlify.app/signed-exchanges/

Add print styles

---

src/site/content/en/blog/coop-coep/index.md

Reflect changes in Chrome 87
- `self.crossOriginIsolated` is now available
- Shared Array Buffers is available in Android Chrome
- `document.domain` is now immutable
- `performance.measureMemory()` is now an origin trial

Update COOP/COEP article

---

src/site/content/en/blog/async-clipboard/index.md

- Fixes the attributes that had an unfortunate line break.
- Add explanation about permissions policy.
CC: @dway123

[Async Clipboard article] Fix iframe permissions policy attributes, add explanation

---

src/site/content/en/blog/min-max-clamp/index.md

Added two sentences with two links total noting the risk with `clamp()` and `vw` for WCAG 1.4.4.

Note on WCAG risk for fluid type

---

src/site/content/en/blog/logical-property-shorthands/index.md

Replace margin-inline with margin, because context is about physical property
- 
- 
-

margin-inline isn't a potential physical cruft

---

src/site/_data/paths/reliable.json

Adds a link to the [The Cache API: A Quick Guide](https://web.dev/cache-api-quick-guide) from https://web.dev/reliable

Link to Cache API guide from web.dev/reliable

---

src/site/content/en/metrics/cls/index.md

- add a link from the CLS doc to https://developers.google.com/doubleclick-gpt/guides/minimize-layout-shift

cls: add link to ad-specific mitigation guidance

---

src/site/content/en/blog/file-system-access/index.md

Corrected mispelling of "showFileOpenPicker / showFileSavePicker" which should be "showOpenFilePicker / showSaveFilePicker" in the Polyfilling section.
- 
- 
-

[File System Access article] showFileOpenPicker -> showOpenFilePicker

---

src/site/content/en/blog/web-otp/index.md

Change `three` to `four` in the explanation about User Consent API constraint.

Trivial update to Web OTP

---

src/site/content/en/blog/link-prefetch/index.md

It's considered bad practice to navigate to `index.html`. Usually servers make it the default resource for a 'directory'. However, this is just convention, there's nothing that requires `/foo/` and `/foo/index.html` to be the same content.
If you prefetch `/foo/index.html` then navigate to `/foo/`, it will be a cache miss.
I've changes these references to `/articles/` to avoid this confusion.

Remove references to index.html

---

redirect-handler.js
server.js

This reverts #4087.
Fixes #4156.
Turns out our `_redirects.yaml` contains an entry which redirects "/fast/..." to "/...". We still have the top-level "/fast/" page, which was being redirected.
I actually can't remember why y'all wanted to prefer redirects. If we have a file on disk then it should probably win—it's easier for us to remove files, but a catch-all redirect feels more dangerous...
Anyway, I'm going to submit this since our major landing pages are currently broken.

Revert "prefer redirect"

---

src/lib/components/SideNav/index.js
src/site/_includes/layout.njk
src/site/_transforms/responsive-images/index.js

This CL make sure `/images/lockup.svg` is loaded only once from the CDN on web.dev website.
Currently it is downloaded twice, once from the web.dev domain **and** another time from the CDN.

Use CDN for side nav logo

---

src/site/content/en/blog/wake-lock/index.md

[Screen Wake Lock article] Type is optional

---

src/site/content/en/blog/async-clipboard/index.md

- Prune unnecessary iframe `allow` values.

[Async Clipboard article] Prune unnecessary iframe `allow` values

---

src/site/content/en/media/media-accessibility/index.md

Typo fix in 2nd paragraph last line of page: https://web.dev/media-accessibility/
`fo` -> `of`

fix typo in media accessibility page

---

src/styles/generic/_code.scss

- darker green
- slightly darker red
<details>
<summary>After <-> Before Screenshot Comparison</summary>
</details>

Code snippets pass contrast accessibility scores

---

src/site/content/en/blog/gamepad/index.md

This PR is simply about adding missing devices tag to the gamepad article

Add devices tag to gamepad article

---

src/site/content/en/fast/browser-level-image-lazy-loading/index.md

This PR make sure the demo points to the one that uses lazysizes library, not the native one.
Fixes #https://github.com/GoogleChrome/web.dev/issues/3944

Link to lazysizes library

---

src/site/content/en/blog/async-clipboard/index.md

Noticed a bad link at https://web.dev/async-clipboard/#related-links

Incorrect MDN link for Clipboard API

---

src/site/content/en/blog/speed-tooling-evolutions-cds-2019/index.md

A very small thing but one of the quote marks here is wrong (single quote rather than double quote).
URL: https://web.dev/speed-tooling-evolutions-cds-2019/#field-data-(crux)-thresholds-adjusted-in-pagespeed-insights

Fix incorrect quote mark

---

src/site/_includes/layout.njk

This PR makes sure `app.css` file is preloaded before Material Icons font (43KB font blocking any layout) to improve rendering performance due to [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=788757).
**TLDR;**
Time to start render: 1.1s faster
Web Vitals: 4.6 -> 3.5 
Time to interactive: 40 -> 18
**Without app.css preload**
**With app.css preload**
Full details https://webpagetest.org/video/compare.php?tests=201113_DiW6_b1a4559458aefb7524df621a3e91064e%2C201113_Di8C_9b8ea21c0df163a2f4642f48feba819f&thumbSize=100&ival=100&end=visual

Preload app.css

---

compile-css.js
src/site/_includes/components/Glitch.js
src/site/content/en/handbook/web-dev-components/index.md

This PR makes sure "clipboard" and "vr" unrecognized features are not set by default in iframes. For info, the complete list of
feature names allowed is available at https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/web_tests/webexposed/feature-policy-features-expected.txt and https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/feature_policy/feature_policy_features.json5.

Remove "clipboard" and "vr" from default iframes allow

---

.github/workflows/cleanup-versions-workflow.yml
.github/workflows/continuous-integration-workflow.yml
.github/workflows/snapshot-firestore-workflow.yml

Fixes #4233.
We don't use the offending bits directly. I'm upgrading to the latest suggested guide for `setup-gcloud` which I think will fix us. [See guidance](https://github.com/google-github-actions/setup-gcloud/tree/master/setup-gcloud).

updated gcloud dep

---

src/site/content/en/blog/async-clipboard/index.md

- Glitch doesn't pass on modified `allow` attribute values to nested iframes, so embedding the iframe directly.
@dway123 FYI.

[Async Clipboard article] Directly embed demo iframes

---

src/site/content/en/metrics/cls/index.md

Fixes #3835
There's generally confusion around whether or not scrolling is incorporated in CLS calculations. While the spec is clear, this article doesn't mention that scrolling is not excluded input.
- Adding a 'caution' aside to web.dev/cls on scrolling input not being given a 500 ms buffer

Clarifying scrolling as non-excluded input

---

src/site/content/en/blog/camera-pan-tilt-zoom/index.md

This PR is about making it clear that Android used to support zoom before, but still no pan and tilt.

Change wording around Android zoom support.

---

src/styles/fonts/_material-icons.scss

Following https://web.dev/preload-optional-fonts/ recommandations, marking Material Icons font as `font-display:optional` should improve greatly the CLS that has jumped recently with https://github.com/GoogleChrome/web.dev/pull/4218
Source: https://webpagetest.org/result/201119_DiJN_70db15a47be0291dfa7149a3beb4ad6c/
FIX: https://github.com/GoogleChrome/web.dev/issues/4263

Mark font-display:optional for Material Icons font

---

src/styles/components/_header.scss

This PR is part of the many PRs (to be expected) to fix CLS regression raised at https://github.com/GoogleChrome/web.dev/issues/4263
This one is specifically about the hamburger button that once resolved causes a tiny layout shift.

Fix layout shift in hamburger button

---

src/styles/generic/_tables.scss

- Adds visual scroll hint for wide tables ([demo](https://deploy-preview-4258--web-dev-staging.netlify.app/handbook/web-dev-components/#tables:~:text=Tables%20scroll%20when%20their%20width%20is%20larger%20than%20that%20of%20the%20content%20column%3A)):

[CSS] Add table scroll hint shadow

---

src/site/content/en/blog/bfcache/index.md

Just spotted a minor issue in the article on bfcache in the section on the restoration from bfcache

Use correct event in the article on bfcache

---

src/site/content/en/blog/bfcache/index.md

This jumped out while reading the article. The prose already explains the value is either `true` or `false`, so I think we can just write the code as one usually would without losing clarity.

Remove redundant `=== true`

---

.github/workflows/cleanup-versions-workflow.yml
.github/workflows/continuous-integration-workflow.yml
.github/workflows/snapshot-firestore-workflow.yml

This tries to fix #4298. We cannot test unless we submit as there's no PR-triggered tasks that deploy to Gcloud.

fix missing 'v'

---

src/site/content/en/blog/shape-detection/index.md

This PR makes sure macOS and Chrome OS support are mentioned for barcode detection.

Add macOS and Chrome OS support for barcode detection

---

src/site/content/en/blog/serial/index.md

This PR updates the serial article to document changes to the events fired when a serial port is connected or disconnected that are implemented in Chrome 89.
Spec: https://github.com/WICG/serial/commit/32dfe36cf081dd26f41681159a11863f5167bb91
Live preview: https://deploy-preview-4290--web-dev-staging.netlify.app/serial/#connection-disconnection

Use event.target for connect/disconnect serial events

---

src/site/content/en/blog/persistent-storage/index.md

What is "DOM Storage"? Does persist protect "Local Storage"?
This change could help clarify.
(I don't even know whether this is correct. I tried googling "DOM Storage", and some results make it look like it does include Local Storage, and other results make it look like it doesn't include Local Storage. If it doesn't, then reject this pull request, and instead add a note to say that Local Storage is not protected.)

question - What is "DOM Storage"?

---

src/site/content/en/blog/push-notifications-client-codelab/index.md
src/site/content/en/blog/push-notifications-overview/index.md
src/site/content/en/blog/push-notifications-server-codelab/index.md

I checked the article and did usability tests on the codelabs — nice work!
Made a few minor fixes in this PR.
I tested in Edge and Chrome on Windows 10 on a 'real' PC (and Windows 8 via BrowserStack). The codelabs worked as expected and I updated the compatibility information in the text.
* I noticed that [push-notifications-client-codelab-complete.glitch.me](https://push-notifications-client-codelab-complete.glitch.me/) is actually the server codelab, and [push-notifications-server-codelab-complete.glitch.me](https://push-notifications-server-codelab-complete.glitch.me/) has the heading **Push notifications client**. Am I missing something, or is this just a glitch?
* I added a note to one of the codelabs (using the text from the other) about allowing push notifications in the permission …

Push Notifications article and codelabs: minor fixes

---

src/site/_data/paths/devices.json
src/site/_includes/path.njk

This PR is about giving possibility to add a YouTube video to path landing pages and using this for web.dev/devices with YouTube video released at Chrome Dev Summit 2020.
Live preview: https://deploy-preview-4365--web-dev-staging.netlify.app/devices

Add YouTube video to paths landing pages

---

src/site/_data/paths/devices.json
src/site/_includes/path.njk

Following https://github.com/GoogleChrome/web.dev/pull/4366#issuecomment-742689784 suggestion, this PR moves youtube video under overview in path landing pages

Move youtube video under overview in path landing pages.

---

src/site/content/en/blog/extending-workbox/index.md

This PR modifies https://web.dev/extending-workbox/ by:
- Removing `draft: true` so that it shows up in the blog index.
- Embedding the accompanying CDS talk's video.
- Adding in a few extra links for context.

Workbox CDS article tweaks

---

src/site/content/en/blog/nfc/index.md

This PR removes a caution that is not necessary anymore as smart-poster records have been supported since Chrome 82/83 (May 2020)

Smart-poster records are supported since Chrome 82

---

src/site/content/en/lighthouse-best-practices/external-anchors-use-rel-noopener/index.md

- Update lighthouse audit info page with mention that noopener behavior is now the default in M88+.

Indicate that noopener behavior is now default

---

README.md

As I was looking into debugging eleventy, I've noticed command in the README was outdated. This PR fixes it.

Fix debugging npm command to debug eleventy

---

src/site/_transforms/responsive-images/index.js

This fixes an issue that is already live in production 😅
#4300 added automatic image dimensions to improve our CLS (yay!) but, if an author has already provided a width and height (or in many cases, just a width) then #4300 was overriding their dimensions and forcing some images to be quite large (because it was using their high res dimensions).
You can see an example on this page https://web.dev/workers-overview/ where the screenshot of Proxx is huge
After this patch is applied the screenshot looks like this:
- Only compute image size if the author has not specified a width or a height.

Don't compute image sizes if there's already a dimension.

---

src/styles/components/_images.scss

Fixes #4416
- added max-width for `.w-screenshot--filled` in order not to overflow
this styling depends on another css class `.w-screenshot` so it may not be a good solution to solve the issue.
Please give any advice if there are other ideas🙏

fix: image is cut off on mobile device when specifying .w-screenshot--filled

---

src/site/content/en/lighthouse-performance/third-party-facades/index.md

Fixes #4334.
Changes:
> - The audit was recently merged in LH, we can add a link to the [source code](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/third-party-facades.js)  as per https://github.com/GoogleChrome/web.dev/pull/4316#discussion_r532528310
> - We still need to add the facade additions process link (https://github.com/GoogleChrome/web.dev/pull/4316#discussion_r533717049)
> - Instead of having a specific section for a general iframes facade, call out generic iframe loaders in the paragraph above.

Update third-party facades audit doc

---

src/site/content/en/blog/trusted-types/index.md

Corrected syntax error caused by an unnecessary and ill-placed semi-colon
This code has an unnecessary and wrong semi-colon at the end of the line that defines the `createHTML` property on the object:
```javascript
if (window.trustedTypes && trustedTypes.createPolicy) { // Feature testing
trustedTypes.createPolicy('default', {
createHTML: (string, sink) => DOMPurify.sanitize(string, {RETURN_TRUSTED_TYPE: true});
});
}
```
My PR only removes that semi-colon.

Corrected syntax error in code example

---

src/site/content/en/fast/replace-gifs-with-videos/index.md

This prevents the common 'height not divisible by 2' error when working with GIFs of odd dimensions
Solution taken from https://stackoverflow.com/a/29582287
- Updates example FFMPEG commands to include a crop filter to make the commands more resilient when used with GIFs that may have odd (in a numerical sense) dimensions

Add crop filter to GIF -> video FFMPEG commands

---

src/site/content/en/blog/bfcache/index.md

- Note that Chrome 88+ will disavow opener for target=_blank hyperlinks
- 
-

Note that Chrome 88 will disavow opener for target=_blank links

---

src/site/content/en/fast/lazy-loading-images/index.md

Proposing the addition of vanilla-lazyload
- Added vanilla-lazyload to the list of scripts at the end of the article

Adding vanilla-lazyload to the scripts at the end of the page

---

src/site/content/en/blog/declarative-shadow-dom/index.md

This updates the Declarative Shadow DOM article to reflect changes to the API. Based on security feedback, fragment parsing APIs like `innerHTML` and `insertAdjactentHTML` no longer parses and applies declarative shadow roots, only `DOMParser` can be used to achieve this outside of standard HTML parsing, and only when a new includeShadowRoots option is provided.
/cc @mfreed7

[content update] Declarative Shadow DOM: Update to reflect innerHTML changes

---

src/site/content/en/fast/publish-modern-javascript/index.md

I've discussed this with the author of the tool. I'd actually intended to include Devolution in the original article.

Update publish-modern-javascript to add Devolution tool

---

src/site/content/en/blog/css-marker-pseudo-element/index.md

Minor edit to [Custom bullets with CSS ::marker](https://web.dev/css-marker-pseudo-element/) noting desktop and iOS Safari only support `color` and `font-*` (see https://bugs.webkit.org/show_bug.cgi?id=204163).

Update browser support info for ::marker

---

src/site/content/en/fast/use-lighthouse-for-performance-budgets/index.md

Fixing a tiny typo in the article [Use Lighthouse for Performance Budgets](https://web.dev/use-lighthouse-for-performance-budgets/):
- Changed "numer" to "number"

Fixed typo

---

src/site/content/en/metrics/fcp/index.md

Fixes #4408
- Correct the incorrect initialism from `FCP` to `LCP`
- Correct the incorrect, broken link from `/Fcp/` to `/lcp/`

Fix incorrect initialism and link on FCP page

---

src/site/content/en/blog/optimize-lcp/index.md

This wording now matches https://web.dev/lcp/
(IMO the existing wording could be misinterpreted to mean that it falls back to using the `<video>` element if the video placeholder is not specified.)
cc @philipwalton

Fix wording re: LCP calcuation for video elements

---

src/site/content/en/blog/fugu-status/index.md
src/site/content/en/blog/serial/index.md

This PR makes sure the article reflects the Serial API launching in Chrome 89.
Live preview:
- https://deploy-preview-4436--web-dev-staging.netlify.app/serial
- https://deploy-preview-4436--web-dev-staging.netlify.app/fugu-status
@reillyeon FYI

[Serial API article] Add launched info

---

src/site/content/en/blog/trust-tokens/index.md

- Update Trust Token blogpost to use the correct terminology.
- Specify redeemer should parse Redemption Record.
-

Trust Token V2 changes to blog post.

---

.github/stale.yml

Exempts the `bug` label from being marked as stale and closed by the stalebot.
We originally added the stalebot because content PRs were going stale and it should continue to serve that function. But we want to avoid legitimate bugs from being closed, especially when we're heads down working on a different project (like we recently were with developer.chrome.com).

Don't let bugs get closed as stale.

---

src/site/_includes/devsite/devsite-footer.njk
src/site/_includes/partials/footer.njk

- Remove no longer maintained Medium channel from footer.

Remove no longer maintained Medium channel from footer

---

src/site/content/en/blog/content-indexing-api/index.md
src/site/content/en/blog/fugu-status/index.md

This PR makes sure the "New capabilities status" page matches latest articles status:
- Move "Content Indexing API" from OT to Stable
- Move "Notification Triggers" from behind a flag to OT
- Order alphabetically capabilities in tables
- Remove Badging API outdated note
- Update "Content Indexing API" article to reflect shipped status
@petele @tomayac Can you review?
Live preview:
- https://deploy-preview-4503--web-dev-staging.netlify.app/fugu-status/
- https://deploy-preview-4503--web-dev-staging.netlify.app/content-indexing-api/

Update capabilities status

---

src/site/content/en/blog/user-agent-client-hints/index.md

Updates https://web.dev/user-agent-client-hints to cover the changes in [Intent to Remove: Rename User-Agent Client Hint ACCEPT-CH tokens](https://groups.google.com/a/chromium.org/g/blink-dev/c/t-S9nnos9qU/m/pUFJb00jBAAJ). This should not be merged until the intent is fully confirmed, but this is ready for review.
- Added a "gotcha" at the top to alert developers of the change
- Updated references to the previous `Accept-CH` format
- Simplified the table now the response / request values match
- Updated the reference for Feature Policy
- Remove the inline demo, as hints won't be delegated without a specific Feature Policy

Update Accept-CH format

---

src/site/content/en/metrics/lcp/index.md

Hey 👋 
When reading [web.dev/lcp/](https://web.dev/lcp/) I've noted the aside section pointing to WICG/largest-contentful-paint/issues/41.
My current understanding is that the issue has been closed for a few months and that the decision was made to keep considering removed elements for LCP. Hence the adjustment.
I believe to have signed the CLS accordingly.
I'm a  bit unsure whether an issue should still be created to link it in the commit? Please advise.

Correct metrics content for LCP to include removed elements

---

src/site/content/en/blog/coop-coep/index.md
src/site/content/en/blog/detached-window-memory-leaks/index.md
src/site/content/en/blog/monitor-total-page-memory-usage/index.md
src/site/content/en/blog/why-coop-coep/index.md

The new name is performance.measureUserAgentSpecificMemory.
This also updates the examples to the new result format.

Update performance.measureMemory after renaming

---

src/site/_includes/components/Instruction.js

As of DevTools (Chrome 83), the Audits panel is now the Lighthouse panel
- 'Audit tab' changed to 'Lighthouse tab'
- Instruction of selecting the right 'selection' checkbox is made more clear
- Button name updated to 'Generate report'

Update Audit tab to Lighthouse tab

---

src/lib/components/Search/index.js

- adds highlighting to the search 
- adds attributes to retrieve to the search (only request what's shown, makes the search a bit faster)
some questions that I need to check before it should be merged (but the main idea can already been reviewed)

feat(search): add highlighting

---

src/site/content/en/blog/how-to-use-local-https/index.md

- fixes link to in-page mkcert cheatsheet
- corrects the environment variable name in the Create React App script configuration example

Fix typos in how-to-use-local-https

---

src/site/content/en/media/video-and-source-tags/index.md

Changed 'butes' to 'bytes' under "Specify start and end times" heading
- 
- 
-

Updated a spelling mistake in index.md

---

src/site/content/en/progressive-web-apps/add-manifest/index.md

This PR adds standardized`description` ~, `categories`,~ and `screenshots` properties to the manifest article so that web developers interested in playing with the PWA install bottom sheet have some documentation.
Note that it currently requires `chrome://flags/#mobile-pwa-install-use-bottom-sheet` flag in Chrome Canary on Android.
Live preview: https://deploy-preview-4502--web-dev-staging.netlify.app/add-manifest/
@petele Can you review?

Add description and screenshots to manifest article

---

src/site/content/en/blog/web-share-target/index.md
src/site/content/en/blog/web-share/index.md

This updates the Web Share and Web Share Target blog posts to account for changes in Chrome 89, and to make the browser-support story more accurate in general.
R: @jpmedley @petele

Web share updates for M89

---

src/site/content/en/progressive-web-apps/add-manifest/index.md

This PR updates the "Add a web app manifest" article with new criteria for the `screenshots` web app manifest property.
@petele FYI

Add `screenshots` criteria

---

src/site/content/en/lighthouse-performance/critical-request-chains/index.md
src/site/content/en/lighthouse-performance/dom-size/index.md
src/site/content/en/lighthouse-performance/efficient-animated-content/index.md
src/site/content/en/lighthouse-performance/font-display/index.md
src/site/content/en/lighthouse-performance/offscreen-images/index.md
src/site/content/en/lighthouse-performance/redirects/index.md
src/site/content/en/lighthouse-performance/render-blocking-resources/index.md
src/site/content/en/lighthouse-performance/time-to-first-byte/index.md
src/site/content/en/lighthouse-performance/total-byte-weight/index.md
src/site/content/en/lighthouse-performance/unminified-css/index.md
src/site/content/en/lighthouse-performance/unminified-javascript/index.md
src/site/content/en/lighthouse-performance/unused-css-rules/index.md
src/site/content/en/lighthouse-performance/unused-javascript/index.md
src/site/content/en/lighthouse-performance/user-timings/index.md
src/site/content/en/lighthouse-performance/uses-long-cache-ttl/index.md
src/site/content/en/lighthouse-performance/uses-optimized-images/index.md
src/site/content/en/lighthouse-performance/uses-rel-preconnect/index.md
src/site/content/en/lighthouse-performance/uses-rel-preload/index.md
src/site/content/en/lighthouse-performance/uses-responsive-images/index.md
src/site/content/en/lighthouse-performance/uses-text-compression/index.md
src/site/content/en/lighthouse-performance/uses-webp-images/index.md

Continuation of #4093 
fixes #3674

Add Stack Pack guidance to Lighthouse docs

---

src/site/content/en/blog/webrtc-standard-announcement/index.md

see e.g. first item on
https://www.nvidia.com/en-us/geforce-now/faq/
I'll ask around if this needs more marketing related things from our end.

webrtc: fix gfn brand usage

---

src/site/_includes/components/Meta.js

I think this will be a temp fix as we don't use canonical urls in the Firebase hosting.

fix(canoical) use page data from source to generate canonical URLs, fixes #4504

---

src/site/content/en/progressive-web-apps/add-manifest/index.md

This PR is updating the `screenshots` requirement which is about aspect ration, not dimensions in the "add a web app manifest" article.

Update screenshots requirements

---

src/site/content/en/blog/appcache-removal/index.md

The end date of the [AppCache OT](https://developer.chrome.com/origintrials/#/view_trial/1776670052997660673) has been updated. It will now end with Chrome 93.

Update end date for AppCache origin trial

---

src/site/content/en/progressive-web-apps/add-manifest/index.md

According to internal stats, the `json` extension name is much more popular than the `webmanifest` one. This PR updates our documentation to promote `manifest.json` instead of `manifest.webmanifest`.

Promote json extension instead of webmanifest for manifest

---

src/site/content/en/angular/creating-pwa-with-angular-cli/index.md

I was following this guide to add PWA functionality to an Angular 11 app, but the Lighthouse tool was claiming I [still had no service worker](https://web.dev/service-worker/?utm_source=lighthouse&utm_medium=devtools) despite the fact that it was there. I also noticed that the service worker would take a long time to be installed.
Lo and behold, the default strategy can [take up to 30 seconds](https://stackoverflow.com/a/61152966/587091) to install the service worker. I don't know if you want this article to recommend `registerImmediately`, but at least the `registrationStrategy` property should be discussed.

Add a note about `registrationStrategy`

---

src/site/content/en/metrics/fcp/index.md

Fixes #4128
We decided several months ago that any Web Vitals metrics that aren't part of the set of Core Web Vitals should not suggest a threshold in their web.dev guidance. In some cases tools like Lighthouse or PSI may still give a score, but we're not going to be suggesting a threshold for field data in our web.dev metric guidance.

Remove the threshold recommendation for FCP

---

src/site/content/en/blog/how-to-use-local-https/index.md

This image is https://web.dev/how-to-use-local-https/ on mobile emulation. The caution is not visible. I've fixed it by adding body class.

Fix hidden caution on mobile

---

src/site/content/en/blog/love-your-cache/index.md

* 🔗 URL was doubled in the README markdown

Fix Netlify CDN reference link

---

src/site/content/en/blog/how-to-use-local-https/index.md
src/styles/components/_banner.scss
src/styles/generic/_lists.scss

Fixes #4597
- Improve the look of the Banner shortcode when it's used as a body banner.
- Improves the look of lists (reduces the space between the bullet and the list content).
cc @maudnals @kaycebasques if y'all are using the `Banner` shortcode, make sure to include the `'body'` argument, otherwise it gets hidden on mobile.

Improve body banner and list styles

---

.github/pull_request_template.md

@robdodson this updates the PR template to mention that people should fill out our content proposal form before submitting pull requests that create new content. It also mentions PR draft mode.
Fixes #3356

Update the PR template to mention the proposal form and draft mode

---

src/site/content/en/blog/fugu-status/index.md
src/site/content/en/blog/serial/index.md

This PR is about renaming the "Serial API" to "Web Serial API" in web.dev articles.
FYI @reillyeon

Rename Serial API to Web Serial API

---

src/site/content/en/fast/why-speed-matters/index.md

One of the articles linked (that I am the author of) is pointing to medium.com rather than the canonical page. 
This PR updates the URL so that it's pointing at the canonical source.

Updated link to canonical source

---

src/site/content/en/blog/async-clipboard/index.md

The Raw Clipboard API proposal is no longer being pursued for security reasons.
- 
- 
-

Remove link to Raw Clipboard design doc

---

src/lib/components/Search/index.js
src/lib/utils/escape-html.js

Fixes #4575
- Escape html entities (but allow `<strong>` tags) in search results. We allow strong tags because Algolia sends them back in the results to indicate which letters in the title match what the user was typing. The effect is really subtle and hard to see on the current site, but more noticeable on d.c.c.

Escape HTML titles/descriptions when displaying them as search results

---

src/site/content/en/fast/preload-critical-assets/index.md

According to https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#browser_compatibility preload is already supported by Firefox (since version 85)
- Remove information about Firefox not supporting preload

Make browser compatibility info up to date

---

src/site/content/en/blog/conversion-measurement/index.md

Fixes #4630
- Removed mentions of hexa encoding
- Updated conversiondestination definition
`DO NOT MERGE` yet: the article update should ideally happen shortly before comms go out to OT participants (should be some time next week).

Updated encoding and conversiondestination definition

---

src/site/_includes/components/Img.js

For images that are capped at 300px, don't create sizes up to 1,600px.
If the image is smaller than 200px, use the image width as the lower limit as to not scale up small images.

[Img component] Prevent markup bloat

---

src/site/content/en/blog/coop-coep/index.md

- Adds a link to [A guide to enable cross-origin isolation](https://web.dev/cross-origin-isolation-guide/).
- Embeds two video about COOP/COEP from web.dev live and CDS.

Add a link to COOP/COEP guide, embed two videos

---

src/lib/actions.js
src/lib/app.js
src/lib/components/LanguageSelect/index.js
src/lib/urls.js
src/lib/utils/language.js
src/site/_includes/partials/footer.njk

Fixes #4640
It removes also `getLanguageFromPath` and `getCanonicalPath` as we don't do language paths anymore.

Synchronize LanguageSelect element state with real language of the page

---

src/site/_includes/components/Video.js

- The `autoplay` attribute needs to go along with `playsinline` for iOS (see [blog post](https://webkit.org/blog/6784/new-video-policies-for-ios/#post-6784:~:text=%3Cvideo-,playsinline,-%3E))

[Video component] The `autoplay` attribute needs to go along with `playsinline` for iOS

---

src/site/content/sitemap.xml.njk

I noticed we had a few sitemap errors in search console because we were doing `<lastmod></lastmod>`
Because `lastmod` is optional, this just removes it if we don't have a confident date or updated date for a page. Search says that they generally ignore lastmod anyway but I figure it's good to not have sitemap errors.

Don't show lastmod if we don't have a date or updated.

---

src/site/content/en/progressive-web-apps/codelab-make-installable/index.md

This PR makes sure changes made in https://github.com/GoogleChrome/web.dev/pull/4622 are reflected in the associated codelab article.
Note that the codelab was also updated:
- I've asked Glitch support folks to restore it as it was [broken/empty previously](https://github.com/GoogleChrome/web.dev/issues/4632).
- A new service worker offline page logic was added to address [upcoming changes](https://developer.chrome.com/blog/improved-pwa-offline-detection/).
- Links have been fixed.
@petele Can you review/merge?

Minor updates to installable PWA codelab

---

.pullapprove.yml

Adds a `.pullapprove.yml` to the project so we can try out using [PullApprove](https://www.pullapprove.com/).
The file attempts to mostly mirror our existing CODEOWNERS file, but also adds an optional global group that should be able to approve content PRs but won't be notified about them.

Add pullapprove config file.

---

src/site/content/en/blog/user-agent-client-hints/index.md

See https://wicg.github.io/ua-client-hints/#user-agent-platform-architecture. All ARM-ish CPUs will report just "arm".
Fixes #4663
- Just fixing an incorrect value

Fixes #4663 - Use correct value for Sec-CH-UA-Arch example

---

redirects.yaml

Add a temporary redirect for a placeholder URL: https://web.dev/cors-rfc1918-guide
There will be two new articles:
* https://web.dev/cors-rfc1918 : The canonical article about CORS-RFC1918
* https://web.dev/cors-rfc1918-guide : A brief guidance on CORS-RFC1918 primarily as a destination for DevTools.
Until they emerge, we'll redirect traffic to https://web.dev/cors-rfc1918-guide to https://web.dev/cors-rfc1918-feedback.

Temporary redirect for CORS-RFC1918 guidance

---

src/site/_includes/components/Img.js

Fixes a small bug introduced in #4662. It was setting the max srcset to 800px, but really we want it to be 1600px (max width * max dpr).

Add max dpr multiplier

---

src/site/content/en/blog/color-scheme/index.md

**This PR**
_TL;DR; Changes https://drafts.csswg.org/css-color-adjust/#color-scheme-meta to https://html.spec.whatwg.org/multipage/semantics.html#meta-color-scheme_
Changes the URL for link of for more information about the `color-scheme` meta from a hash that no longer exists on the W3C draft page to a working link on the Whatwg spec.
**Why?**
The current URL https://drafts.csswg.org/css-color-adjust/#color-scheme-meta goes to the top of the document because there is no longer an element with the `color-scheme-meta` id in the page.
The only mention of the `color-scheme` meta tag in that draft does not have an `id` to link to it. The note reads:
> Note: [HTML] specifies a color-scheme meta tag which can be used to set the color-scheme on the root element as a non-CSS presentational hint. …

Changes color-scheme meta tag link URL from W3C draft to Whatwg

---

src/site/content/en/blog/hands-on-portals/index.md

Fixes #4671
- Remove all the Origin Trial information from the article. The experimental flag will be the only way to test out Portals until the next OT starts.
- Add guidance for the new flag: `chrome://flags/#enable-portals-cross-origin` for cross-origin navigations
- Test out existing code snippet and add any modification if needed (hooking the activate function call in the Portals element onload event in the very first code snippet)

Initial commit on removing the OT information and updating the article

---

src/site/content/en/blog/coop-coep/index.md
src/site/content/en/secure/cross-origin-isolation-guide/index.md

Improves cross-origin isolation related documents
- https://web.dev/coop-coep
- https://web.dev/cross-origin-isolation-guide
Here's list of changes:
- Add report only mode step in the guide to recursively apply COEP to iframes.
- Add explanation about `allow="cross-origin-isolated"` to enable SharedArrayBuffer etc within an iframe.
- Add instructions how to check iframe and popup window's status of cross-origin isolation on DevTools.

Improve cross-origin isolation related documents

---

src/site/content/en/authors/individual.njk
src/styles/pages/_author.scss

- Adds dimensions to images
- Improves the `sizes` for the author image.
A note about the `Img` shortcode. In this example the image is 128px on small screens and then 192 px on large screens. The `Img` shortcode has this line `minWidth: Math.min(MIN_WIDTH, widthAsNumber),` where MIN_WIDTH is 200. This means that the minWidth would be 192px even though the true minimum size this image is displayed at is 128px. I passed in an explicit minWidth option to fix this, but I'm curious if that line of code in the shortcode is correct. I'm not sure what a better alternative would be off the top of my head.

Improve CLS on Authors page regression

---

src/site/content/en/blog/streams/index.md

First of all: great article! This will surely help make ~2016~ **2021** the year of web streams! 😄
I did spot a couple of small inaccuracies, which this PR aims to fix:
* A "controller" is associated with a readable/writable stream, not with a reader/writer.
* The queuing strategy for a readable byte stream cannot have a `size(chunk)` function. ([Step 4.1 of the constructor](https://streams.spec.whatwg.org/commit-snapshots/4b5b3cdb0f22a791fc1a8e734296a32a94ad753a/#rs-constructor) forbids this. 🤓) The `highWaterMark` is *always* interpreted as a number of bytes, and the size of each chunk is *always* determined by its `byteLength`. (Interestingly, this also means that you cannot pass a `ByteLengthQueuingStrategy`, since that *does* have a `size(chunk)` method.)
* In one of the examples, …

[Streams article] Various fixes

---

src/site/content/en/blog/intersectionobserver-v2.md/index.md
src/site/content/en/blog/intersectionobserver-v2/index.md

- Migrate https://developers.google.com/web/updates/2019/02/intersectionobserver-v2 to `/intersectionobserver-v2/`.

Migrate IntersectionObserver v2 article

---

src/site/content/en/handbook/markup-media/index.md

I was working on a PR where I wanted to include captions with an image and had to do a little deducing to figure out how it works with the new image shortcodes. This should save our contributors some time.
Also, instructions with CSS classes for images (w-screenshot etc.) are gone from the handbook and I think we should bring them back. They still work and I find them very useful.
cc @kaycebasques

[Handbook update] Add instructions for inlcuding image captions

---

src/site/content/en/blog/serial/index.md

This PR updates an example in the serial article to make the design pattern for closing a serial port clearer as raised in https://github.com/WICG/serial/issues/126.

Update the close port example in the serial article

---

src/site/content/en/blog/codelab-address-form-best-practices/index.md
src/site/content/en/blog/fetch-upload-streaming/index.md
src/site/content/en/blog/link-prefetch/index.md
src/site/content/en/blog/min-max-clamp/index.md
src/site/content/en/blog/preconnect-and-dns-prefetch/index.md
src/site/content/en/fast/prioritize-resources/index.md
src/site/content/en/handbook/grammar/index.md
src/site/content/en/newsletter/archive/2020/03/index.njk
src/site/content/en/newsletter/archive/2020/06/index.njk
src/site/content/en/progressive-web-apps/define-install-strategy/index.md
src/site/content/en/reliable/broadcast-updates-guide/index.md
src/site/content/en/reliable/imperative-caching-guide/index.md
src/site/content/en/reliable/instant-navigation-experiences/index.md
src/site/content/en/reliable/two-way-communication-guide/index.md
tools/linting/no-dash-spaces.js
tools/linting/no-smart-quotes.js

We were matching single smart-quotes (‘’) but not doubles (“”).
This has actually fixed issues with inline samples already: e.g., the fix to "blog/link-prefetch/index.md".
This also fixes some issues with em/en dashes. We didn't hit these before as we considered all lines separately, but this would actually create space between content.

fix linter and remove all smart quote styles

---

src/site/content/en/blog/coop-coep/index.md

Removed many conditionals required before Chrome 89 from the COOP/COEP article
Also replaced the list of features available behind cross-origin isolation with a table.

Removed many conditionals required before Chrome 89 from the COOP/COEP article

---

src/site/content/en/reliable/codelab-service-workers/index.md

Removing one of the devtools instructions, because in this [codelab](https://web.dev/codelab-service-workers/) the instruction for devtools is duplicated and causes this text to be displayed twice: 
Press Control+Shift+J (or Command+Option+J on Mac) to open DevTools.
Press Control+Shift+J (or Command+Option+J on Mac) to open DevTools.

Sw codelab typo

---

src/site/content/en/lighthouse-best-practices/uses-http2/index.md

> Lighthouse gathers all resources from the same host as the page
and checks the HTTP protocol version of each resource.
me and @paulirish don't think that's right... after inspecting our we know we don't do this.

Update 'uses-http2' article to be more accurate

---

src/site/content/en/blog/preload-optional-fonts/index.md

The article title on https://web.dev/preload-optional-fonts/ had a typo, quick fix to address ☺️

Fix article title typo

---

src/site/content/en/metrics/cls/index.md
src/site/content/en/metrics/fid/index.md
src/site/content/en/metrics/lcp/index.md

This PR updates the threshold recommendations for each of the Core Web Vitals metrics to clarify that they are inclusive, favoring the better rating. This is now consistent with the [guidance published in Search Console's Core Web Vitals Report](https://support.google.com/webmasters/answer/9205520#:~:text=Status%20definitions).

Clarify that the Core Web Vitals thresholds are inclusive

---

src/site/content/en/lighthouse-pwa/offline-start-url/index.md
src/site/content/en/lighthouse-pwa/works-offline/index.md

Hello everyone, everything good?
According to this [Pull Request](https://github.com/GoogleChrome/lighthouse/pull/11806), in the lighthouse repository where @paulirish remove works-offline and offline-start-url audits, the current link is pointing to a broken page.
Therefore, I believe that it would be the best solution to remove the link, since the file no longer exists.
This fixes Issue #4873.

Removes a broken audit link

---

src/styles/components/_actions.scss

Fixes #4807
- Share and Subscribe action CTAs used in https://web.dev/handbook/web-dev-components/ seemed to be using assets from the images subfolder in `src`.
- Changed the relative path to image cdn assets path.

Change relative path to assets path for actions CTAs
