src/site/content/en/blog/agrofy/index.md
=> Add Agrofy case study

.eleventy.js, package-lock.json, package.json, src/site/_data/i18n/footer.yml, src/site/_filters/i18n.js, src/site/_includes/partials/footer.njk
This is based on the approach in dcc. I only translate 1 file (footer.njk) so that in case there are changes to the approach I don't have to update many files. The next translations will be added in consecutive PR.
=> Add i18n filter for templates

src/site/content/en/handbook/markup-media/index.md
Might also be nice to add a note and link to each of the uploader pages.
=> Added aside warning about different uploaders

src/site/content/en/fast/debugging-layout-shifts/index.md
Fixes https://github.com/GoogleChrome/web.dev/issues/4619
=> Add 'Debugging layout shifts' post

src/site/_includes/components/SignPosts.js
Fixes #4885
- Use the locale filter on path names in SignPost shortcodes
=> SignPosts should be translated

src/site/content/en/media/video-and-source-tags/index.md
- Adds missing e on the end of YouTub
=> Fixing typo

src/site/content/en/blog/yahoo-japan-news/index.md
=> Update aspect ratio details in Yahoo Japan case study

src/site/content/en/blog/strict-csp/index.md
- Remove empty bullet point in Strict CSP article (#4862)
=> Remove empty bullet point in Strict CSP article (#4862)

src/site/content/en/secure/cross-origin-isolation-guide/index.md
Update cross-origin isolation guide message
cc: @lutzvahl
=> Update cross-origin isolation guide message

src/site/content/en/blog/web-share/index.md
=> [Web Share article] Add StackOverflow tag

src/site/content/en/blog/coop-coep/index.md
Add one more reporting api service to /coop-coep article as it started to manage COOP/COEP reports.
=> Add one more reporting api service to COOP/COEP article

src/site/content/en/blog/vodafone/index.md
=> Add Vodafone case study

src/site/content/en/blog/devices-introduction/index.md, src/site/content/en/blog/granular-chunking-nextjs/index.md, src/site/content/en/blog/introducing-model-viewer/index.md, src/site/content/en/blog/introducing-tooling-report/index.md, src/site/content/en/blog/lighthouse-ci/index.md, src/site/content/en/blog/module-workers/index.md, src/site/content/en/blog/perception-toolkit/index.md, src/site/content/en/blog/periodic-background-sync/index.md, src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md, src/site/content/en/blog/progressively-enhance-your-pwa/index.md, src/site/content/en/blog/use-thumbor/index.md, src/site/content/en/blog/variable-fonts/index.md, src/site/content/en/blog/vr-comes-to-the-web/index.md, src/site/content/en/blog/web-on-android/index.md, src/site/content/en/blog/web-share/index.md
=> Fix typo in various pages

src/site/_data/i18n/paths/learn_web_vitals.yml, src/site/_data/paths/learn-web-vitals.json
Adds these articles:
- Debugging layout shifts
- Best practices for carousels
- Best practices for infinite scroll
=> Add articles to /learn-web-vitals

src/styles/components/_columns.scss
- Makes the column widget attempt to fit as many items as possible on a row
=> Fit up to three columns in the Columns component

src/site/content/en/blog/web-share/index.md, src/site/content/en/fast/signed-exchanges-webpackager/index.md
Original discussion here: https://github.com/GoogleChrome/web.dev/pull/4903
=> Update webpackager instructions

src/site/content/en/blog/building-a-settings-component/index.md
=> Post patch: Building a Settings component

src/site/content/en/lighthouse-performance/third-party-facades/index.md
Fixes https://github.com/GoogleChrome/web.dev/issues/4739
=> Fix inaccuracy in Lighthouse 3P facades article

src/site/content/en/blog/strict-csp/index.md
LH Release 7.3.0 has landed with the CSP XSS audit mentioned in the strict CSP article. These are some minor updates to the article to reflect what actually landed.
My editor enforced some minor whitespace changes, LMK if I should revert those changes.
=> Update strict CSP article Lighthouse section

src/site/content/en/blog/compat2021/index.md
=> [Compat2021 article] Linkify hashtag

src/site/content/en/blog/compat2021/index.md
- Fix link to `aspect-ratio` on MDN
=> Fix `aspect-ratio` link

src/site/content/en/blog/compat2021/index.md
Reported by @mathiasbynens:
https://github.com/GoogleChrome/web.dev/pull/4921#discussion_r599380127
=> Simplify language around flex image sizing bugs

src/site/content/en/blog/developer-satisfaction/index.md
- Minor corrections
- Add hashtag link
=> [DevSat article] Minor corrections

src/site/content/en/progressive-web-apps/offline-fallback-page/index.md
Fixes #4912
- Add comment about unused variable.
=> [Offline Fallback Page article] Add comment about unused variable

src/site/content/en/blog/compat2021/index.md
=> Changing terminology

src/site/content/en/blog/lowes/index.md
Edit the authors note on Lowe's case study
=> Edit the authors note on Lowe's case study

src/site/_data/authorsData.json
Adding Andy as an author in a separate PR so it can be merged, as all of the Learn CSS material which will be in draft PRs needs to link to include him as an author.
=> Add author andy bell

src/site/_includes/components/CompareCaption.js, src/site/_includes/components/Details.js
=> render compare caption with md

src/site/content/en/blog/read-files/index.md
- Add pointers to the new File System Access API throughout.
=> [Read Files article] Add pointers to the new File System Access API throughout

src/site/content/en/blog/app-shortcuts/index.md
This PR adds Chrome OS support to the app shortcuts article.
=> Added Chrome OS support for app shortcuts

src/site/content/en/blog/bfcache/index.md
=> Fix typo: unrequired comma

src/site/_data/authorsData.json
Adding me as an author as I'm making updates to some articles.
=> Adding ajara as author in web.dev

src/site/content/en/progressive-web-apps/add-manifest/index.md
This PR reflects Chromium changes in https://chromium-review.googlesource.com/c/chromium/src/+/2794482 and https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2794605.
=> Update PWA screenshots ratio requirements to be at most 2.3:1

src/site/content/en/fast/cookie-notice-best-practices/index.md
The GitHub-tracked one lacked a rendered ToC among other things! Minor change :)
=> Link to rendered WebPageTest documentation

src/site/content/en/blog/local-fonts/index.md
- Update to reflect API changes.
=> [Local Font article] Update to reflect API changes

src/site/content/en/blog/notification-triggers/index.md
- Update article now that the OT is over.
=> [Notification Triggers article] Update article now that the OT is over

redirects.yaml, src/site/_data/paths/learn-web-vitals.json, src/site/content/en/blog/debug-web-vitals-in-the-field/index.md, src/site/content/en/blog/debugging-web-vitals-in-the-field/index.md, src/site/content/en/fast/debug-layout-shifts/index.md
=> Add debugging web vitals in the field post

src/site/_data/i18n/common.yml, src/site/_includes/course.njk, src/site/_includes/icons/arrow-back.svg, src/site/_includes/icons/arrow-forward.svg, src/site/_includes/partials/course-pagination.njk, src/site/content/en/learn/css/borders/index.md, src/site/content/en/learn/css/shadows/index.md, src/styles/components/_all.scss, src/styles/components/_course-pagination.scss, src/styles/globals/gorko/_config.scss, src/styles/pages/_course.scss
Fixes #4582
- Adds next/prev links for the course footer.
=> Add next and prev buttons to courses

src/site/content/en/blog/app-shortcuts/index.md
This PR updates the milestone for App shortcuts support in Chrome OS.
=> Update Chrome OS milestone for app shortcuts

src/site/content/en/fast/why-speed-matters/index.md
fixed busines => business
- 
- 
-
=> Update index.md - misspelling

src/site/content/en/blog/evolving-cls/index.md
This fixes a few minor issues that were missed in #5031
=> Fix minor grammar issues

src/lib/components/AudioFab/index.js, src/lib/pages/course.js, src/site/_includes/course.njk, src/site/_includes/macros/audio-fab.njk, src/site/_includes/macros/audio-player.njk, src/site/content/en/learn/css/borders/index.md, src/site/content/en/learn/css/index.md, src/styles/components/_all.scss, src/styles/components/_audio-player.scss, src/styles/components/_buttons.scss, src/styles/components/_web-audio-fab.scss, src/styles/settings/_global.scss
Fixes #4581
Adds an audio player macro and an audio FAB macro. The audio FAB is a custom element which uses an intersection observer to show itself if the audio player is offscreen. Clicking the audio FAB will scroll the page back up to the audio player.
=> Add audio player for courses section

src/site/content/en/blog/evolving-cls/index.md
This PR fixes a small, clarity issue in the Evolving CLS post.
=> Clarify that higher is worse

src/site/content/en/lighthouse-seo/meta-description/index.md
- Use lowercase attribute value consistently.
=> [Meta Description article] Use lowercase attribute value

src/site/content/en/blog/bfcache/index.md
This PR updates a link that was incorrect as a result of a copy/paste error.
=> Fix incorrect link

src/site/content/en/blog/optimize-cls/index.md
=> fix(optimize-cls): add missing videos, fixes #5050

src/site/content/en/blog/floc/index.md
As discussed here: WICG/floc/issues/85.
Also updated here: GoogleChrome/developer.chrome.com/pull/615.
=> Updated information about exclusion/inclusion from FLoC calculation

src/site/content/en/learn/css/the-cascade/index.md
Fixes #4780 
See the linked issue for outstanding to do items on this lesson.
=> Adding lesson on the cascade

src/site/_data/authorsData.json, src/site/content/en/learn/css/selectors/index.md
Fixes: #4778 
Adding the Selectors lesson with codepens. See the linked issue for outstanding to dos.
=> Learn CSS Selectors

src/site/content/en/blog/carousel-best-practices/index.md
=> Add additional CLS info to carousel article

src/site/_data/authorsData.json
- Update profile photo for @petele and @b1tr0t
- Update profile details for @b1tr0t
=> Update profile photos for Penny & Pete

src/site/_data/authorsData.json
Fixes a typo I accidentally made in authorsData.json
=> Fix a typo 

src/site/content/en/learn/css/specificity/index.md
Fixes #4779 
Adding the Specificity lesson. There are a bunch of self-assessments in this which I'll add to the preflight issue as to do items.
=> Adds specificity lesson

src/site/content/en/blog/declarative-shadow-dom/index.md
- Updated the Declarative Shadow DOM article with official release milestones for Chrome and Edge, as per discussion with @mfreed7 & @jpmedley
=> Update Chrome + Edge release status for Declarative Shadow DOM

src/site/content/en/progressive-web-apps/install-criteria/index.md
- Remove note about changes to install criteria changes
See https://github.com/GoogleChrome/developer.chrome.com/pull/628 for additional details.
CC: @b1tr0t
=> remove install crit change from PWA docs

src/site/content/en/blog/2021-scroll-survey/index.md
=> New Post: 2021 Scroll Survey

src/lib/pages/home.js, src/site/_includes/homepage.njk, src/site/content/en/newsletter/index.njk
=> fix(subscribe): import subscribe element, fixes #5015

src/site/content/en/learn/css/inheritance/index.md
Fixes: #4781 
Adds the Inheritance lesson
=> Learn CSS Inheritance

src/site/content/en/learn/css/color/index.md
Fixes: #4782
Adds an initial draft of the color module.
=> Adds Learn CSS color module

README.md, src/site/content/en/blog/file-system-access/index.md, src/site/content/en/blog/more-variable-font-options-in-chromium-83/index.md, src/site/content/en/blog/zalando/index.md, src/site/content/en/fast/using-bundlesize-with-travis-ci/index.md, src/site/content/en/fast/using-lighthouse-bot-to-set-a-performance-budget/index.md
- Remove instances of "master"
@robdodson, please rename the `master` branch in https://github.com/GoogleChromeLabs/lighthouse-bot-starter before merging this. Thanks!
=> Remove instances of "master"

src/site/_includes/components/Author.js, src/site/_includes/components/AuthorCard.js, src/site/_includes/components/AuthorsDate.js, src/site/_includes/components/BaseCard.js
=> fix(card): improve quality by cropping them, fixes #4738

src/site/content/en/blog/coop-coep/index.md, src/site/content/en/secure/cross-origin-isolation-guide/index.md
This update adds information about upcoming changes around COEP: credentialless and COOP: same-origin-allow-popups.
=> Update cross-origin isolation related articles

src/site/content/en/tags/individual.njk, src/styles/pages/_tags.scss
=> Add RSS button

src/site/content/en/blog/building-split-text-animations/index.md
=> New post gui challenge split text

src/site/content/en/blog/floc/index.md
=> Added inclusion aside

package-lock.json, package.json, src/site/_includes/course.njk, src/site/_includes/partials/course-app-bar.njk, src/site/_includes/partials/course-audio.njk, src/site/content/en/learn/css/index.md, src/styles/components/_app-bar.scss, src/styles/components/_course-toc.scss, src/styles/globals/gorko/_config.scss, src/styles/pages/_course.scss, src/styles/tools/_mixins.scss
Fixes #5055 
- Adds the fluid type mixins from dcc so we can use them on the course heading and description
- Tidies up the course.scss and course.njk a bit to use more utility classes
=> Course headings

src/site/_data/authorsData.json, src/site/content/en/blog/datatransfer/index.md
Couple of corrections for the DataTransfer article, https://github.com/GoogleChrome/web.dev/pull/5126.
=> Data transfer corrections

src/site/content/en/blog/file-system-access/index.md
- Add info about `startIn`, `suggestedName`, and `id`.
=> [File System Access article] Add info about `startIn`, `suggestedName`, and `id`

src/site/_data/authorsData.json, src/site/content/en/blog/controlling-third-party-scripts/index.md
Fixes #5027 
Adds the third party tags article.
=> third party tags article

src/site/content/en/blog/building-a-settings-component/index.md, src/site/content/en/blog/building-a-sidenav-component/index.md, src/site/content/en/blog/building-a-tabs-component/index.md, src/site/content/en/blog/building-split-text-animations/index.md, src/site/content/en/blog/codelab-building-a-sidenav-component/index.md, src/site/content/en/blog/fast-playback-with-preload/index.md, src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/index.md, src/site/content/en/blog/next-gen-css-2019/index.md, src/site/content/en/blog/preload-responsive-images/index.md, src/site/content/en/blog/snap-after-layout/index.md, src/site/content/en/fast/codelab-optimize-third-party-javascript/index.md, src/site/content/en/fast/how-can-performance-improve-conversion/index.md, src/site/content/en/fast/what-should-you-measure-to-improve-performance/index.md, src/site/content/en/fast/your-first-performance-budget/index.md, src/site/content/en/handbook/audience/index.md
=> `s/Javascript/JavaScript`

src/site/content/en/learn/css/box-model/box-model.assess.yml, src/site/content/en/learn/css/box-model/index.md
=> Adds box model assessment

src/site/content/en/learn/css/selectors/complex-selectors.assess.yml, src/site/content/en/learn/css/selectors/index.md, src/site/content/en/learn/css/selectors/pseudo-selectors.assess.yml, src/site/content/en/learn/css/selectors/simple-selectors.assess.yml
=> Adds selector assessments

src/site/content/en/learn/css/the-cascade/conclusion.assess.yml, src/site/content/en/learn/css/the-cascade/index.md, src/site/content/en/learn/css/the-cascade/origin.assess.yml, src/site/content/en/learn/css/the-cascade/position.assess.yml
=> Adds cascade assessments

src/site/_data/authorsData.json, src/site/content/en/blog/mainline-mensware/index.md
- Add Mainline Mensware article.
=> Add Mainline Mensware article

src/site/_data/courses/css/toc.yml, src/site/content/en/learn/css/flexbox/index.md
Adds the flexbox lesson for the Learn CSS course
=> adding flexbox lesson

src/site/_data/courses/css/toc.yml, src/site/content/en/learn/css/logical-properties/index.md
Fixes #4786 
Adds the Learn CSS Logical Properties lesson.
=> adds learn css logical properties

.pullapprove.yml, src/site/content/en/learn/css/borders/index.md
- Adds una and adam as learn css reviewers
=> Add learn css reviewers

src/site/content/en/learn/css/specificity/index.md, src/site/content/en/learn/css/specificity/scoring-advanced.assess.yml, src/site/content/en/learn/css/specificity/scoring-beginner.assess.yml, src/site/content/en/learn/css/specificity/visualizing.assess.yml
3 new assessments 👍🏻 
https://deploy-preview-5155--web-dev-staging.netlify.app/learn/css/specificity/
=> Adds specificity assessments

src/styles/components/_course-toc.scss, src/styles/components/_details.scss, src/styles/components/_self-assessment-hint.scss, src/styles/pages/_live.scss
=> Remove proprietary -webkit-details-marker

src/site/content/en/blog/monitor-total-page-memory-usage/index.md
- Update the status of the API,
- Clarify the scope of the API.
=> Update the status of the Web memory API

redirects.yaml
=> Add vanity url for learncss

src/site/content/en/learn/css/color/color.assess.yml, src/site/content/en/learn/css/color/index.md
Adds 2 questions to section conclusion
https://deploy-preview-5166--web-dev-staging.netlify.app/learn/css/color/
also, fixes a few invalid hsl color examples provided in the text 👍🏻
=> Adds color assessment

src/site/content/en/blog/building-split-text-animations/index.md
=> Post patch: community contribution to split text post

src/site/content/en/blog/asyncify/index.md
Fixes #4817
- Add blog post about Asyncify.
=> Asyncify blog post

src/site/content/en/progressive-web-apps/using-a-pwa-in-your-android-app/index.md
- Removes Lighthouse 80
- Adds details on Chrome 86 crashes.
@b1tr0t PTAL
=> Updates section on the Quality Criteria

src/site/_data/courses/css/meta.yml, src/site/content/en/learn/css/css.11tydata.js
=> Add thumbnail for css course

src/site/_includes/macros/audio-player.njk, src/site/_includes/partials/toc-inner.njk, src/styles/components/_audio-player.scss, src/styles/components/_course-toc.scss
- Improve the look of the audio player for courses
- Fix issue where toc arrow was wrapping in Safari
=> Improve the look of the audio player and toc

.cloudbuild/deploy.yaml
Add missing prod env so firebase-config step generates CSP headings.
=> Add CLS reporting in prod

src/site/content/en/learn/css/flexbox/conclusion.assess.yml, src/site/content/en/learn/css/flexbox/flex.assess.yml, src/site/content/en/learn/css/flexbox/index.md
Adds 2 assessment sections, in the middle and end
https://deploy-preview-5183--web-dev-staging.netlify.app/learn/css/flexbox/
=> Adds flexbox assessments

src/site/content/en/learn/css/logical-properties/index.md, src/site/content/en/learn/css/logical-properties/logical-props.assess.yml
Assessment is at the end of the post 👍🏻
=> Adds logical properties assessment

src/site/content/en/learn/css/inheritance/conclusion.assess.yml, src/site/content/en/learn/css/inheritance/index.md
Adds 2 questions to section conclusion
https://deploy-preview-5156--web-dev-staging.netlify.app/learn/css/inheritance/
=> Adds inheritance assessments

src/site/content/en/learn/css/flexbox/index.md
I believe this to be a copy/paste error from it's similar explanation above it.
=> Learn CSS flexbox lesson patch

src/site/content/en/learn/css/sizing/index.md
Fixes: #4783 
Adds the initial draft of the sizing units lesson.
=> Adds Learn CSS Sizing

src/site/content/en/learn/css/box-model/index.md, src/site/content/en/learn/css/color/index.md, src/site/content/en/learn/css/flexbox/index.md, src/site/content/en/learn/css/logical-properties/index.md, src/site/content/en/learn/css/selectors/index.md, src/site/content/en/learn/css/specificity/index.md, src/site/content/en/learn/css/the-cascade/index.md
I've replaced out all the bitmap diagrams with SVG for merged modules of the CSS course. 
I've tidied up a couple of bits of formatting too, for good measure.
=> Learn css diagrams

src/site/content/en/blog/optimize-cls/index.md, src/site/content/en/blog/optimize-fid/index.md, src/site/content/en/blog/optimize-lcp/index.md, src/site/content/en/metrics/cls/index.md, src/site/content/en/metrics/fid/index.md, src/site/content/en/metrics/lcp/index.md, src/styles/globals/gorko/_config.scss
Fixes #5198
- Adds `width-full` to CWV svgs. Previously the site was using their width/height attributes, which are too small.
- Also adds utility classes for width-auto and height-auto as these may come in handy in the future.
=> Fix CWV images

src/styles/components/_course-toc.scss
- Fixes bug where course TOC isn't scrollable when it exceeds page length
- To reproduce: open Grid module on desktop and try to scroll
=> [learn-css] [courses] Table of Contents Scroll Bug

src/site/content/en/blog/referrer-best-practices/index.md
=> Updated browser overview table

src/site/content/en/blog/async-clipboard/index.md
=> [Aync Clipboard article] Fix borked link

src/site/content/en/metrics/lcp/index.md
=> Remove outdated information about LCP removed elements

src/site/content/en/learn/css/grid/grid.assess.yml, src/site/content/en/learn/css/grid/index.md
Fixes #4785 
Adds the grid lesson.
=> Add grid lesson

src/site/_data/courses/css/toc.yml, src/site/content/en/learn/css/pseudo-classes/index.md
Fixes: #4809 adds the pseudo-classes lesson.
=> Adds the pseudo-classes lesson

src/site/_data/authorsData.json
- Updated author data in json file
=> Update author data

src/site/content/en/learn/css/spacing/conclusion.assess.yml, src/site/content/en/learn/css/spacing/index.md, src/site/content/en/learn/css/spacing/margin-collapsing.assess.yml
2 pop quizes: 1 for margin collapse and 1 as a recap of the module 👍🏻
=> Adds spacing assessments

src/site/_data/courses/css/toc.yml, src/site/content/en/learn/css/shadows/index.md
Fixes #4840 adding the Shadows module.
=> Adds learn css shadows

src/site/_data/courses/css/toc.yml, src/site/content/en/learn/css/z-index/index.md
Fixes #4845 adds z-index and stacking context
=> Adds learn css z-index

src/site/_data/courses/css/toc.yml, src/site/content/en/learn/css/gradients/index.md
Fixes #4847 adds Learn CSS gradients
=> Adds learn css gradients

src/site/_data/site.js
=> add insights banner

src/site/content/en/learn/css/borders/index.md
- Fixes frontmatter issue for borders learn css module caused by #4834
=> [bugfix] Frontmatter RE:4834

src/site/_includes/components/Codepen.js
- Adds an editable query param to our codepen embeds.
=> Make codepens editable

src/site/content/en/learn/css/animations/index.md
Fixes: #4848 adds learn css: animations.
=> Adds Learn CSS Animation

src/site/content/en/blog/conversion-measurement/index.md, src/site/content/en/blog/using-conversion-measurement/index.md
Fixes #5245
- Added a banner to both articles
=> Edited both conversion measurement articles

src/site/content/en/learn/css/filters/index.md
Fixes #4849 Learn CSS: Filters
=> Adds Learn CSS Filters

src/site/content/en/learn/css/blend-modes/index.md
Fixes: #4850 Learn CSS: Blend modes
=> Adds learn css blend modes

src/site/content/en/learn/css/functions/index.md
Fixes: #4846 Adding Learn CSS Functions.
=> Adds learn css functions

src/site/content/en/learn/css/conclusion/index.md
Adds a conclusion for Learn CSS.
=> Learn CSS outro content

src/site/content/en/learn/css/borders/borders.assess.yml, src/site/content/en/learn/css/borders/index.md
=> Adds borders assessments

src/site/content/en/learn/css/layout/index.md, src/site/content/en/learn/css/layout/layout.assess.yml
3 question pop quiz at the end 👍🏻
=> Adds layout assessments

src/site/content/en/learn/css/z-index/index.md, src/site/content/en/learn/css/z-index/z-index.assess.yml
3 pop quiz questions for the module 👍🏻
=> Adds z-index assessments

src/site/content/en/learn/css/focus/focus.assess.yml, src/site/content/en/learn/css/focus/index.md
2 quiz questions about the focus module
=> Adds focus assessments

src/site/content/en/learn/css/shadows/index.md, src/site/content/en/learn/css/shadows/shadows.assess.yml
2 quiz questions for the shadows module. I tried to come up with more, but they were too abstract.
=> Adds shadows assessments

src/site/content/en/learn/css/sizing/index.md, src/site/content/en/learn/css/sizing/sizing.assess.yml
3 question pop quiz at the end
=> Adds sizing assessment

src/site/content/en/learn/css/pseudo-elements/index.md, src/site/content/en/learn/css/pseudo-elements/pseudo-elements.assess.yml
2 pop quiz questions at the end 👍🏻
=> Adds pseudo-element assessment

src/site/_data/authorsData.json, src/site/_data/courses/css/toc.yml, src/site/_includes/partials/author-stack.njk, src/site/content/en/learn/css/conclusion/index.md, src/site/content/en/learn/css/index.md, src/styles/globals/gorko/_config.scss, src/styles/utilities/_all.scss, src/styles/utilities/_list-separator.scss
Adds an author bubble stack partial which can be used at the end of posts or courses.
Fixes #5254 
- Updates Kayce and Jiwoong's author info
- Adds the conclusion to the end of the ToC for learn css
- Adds the author-stack partial
- Adds more utility classes 🎨
- Adds a little configurable list separator utility
=> Courses author bubble stack

src/site/content/en/blog/window-controls-overlay/index.md
=> [Window Controls Overlay article] Link to Edge’s docs

src/site/content/en/learn/css/filters/filters.assess.yml, src/site/content/en/learn/css/filters/index.md
A couple of questions at the end there 👍🏻 
also a typo header fix
=> Adds filters assessment

src/site/content/en/learn/css/blend-modes/blend-modes.assess.yml, src/site/content/en/learn/css/blend-modes/index.md
=> Adds blend mode assessments

src/site/_includes/partials/navigation-drawer-course.njk
- Hide course search (for now)
=> Remove search from courses

src/site/content/en/learn/css/box-model/index.md, src/site/content/en/learn/css/color/index.md, src/site/content/en/learn/css/flexbox/index.md, src/site/content/en/learn/css/grid/index.md, src/site/content/en/learn/css/inheritance/index.md, src/site/content/en/learn/css/layout/index.md, src/site/content/en/learn/css/selectors/index.md, src/site/content/en/learn/css/sizing/index.md, src/site/content/en/learn/css/specificity/index.md, src/site/content/en/learn/css/the-cascade/index.md
- Made adjustments to demo presentation to better fit space in modules
=> [learn-css] Demo visualization adjustments

src/site/content/en/learn/css/animations/animations.assess.yml, src/site/content/en/learn/css/animations/index.md
adds a few quiz questions about animations
=> Adds animations assessments

src/site/content/en/learn/css/gradients/gradients.assess.yml, src/site/content/en/learn/css/gradients/index.md
=> Adds gradient assessments

src/site/content/en/blog/coop-coep/index.md, src/site/content/en/secure/cross-origin-isolation-guide/index.md
This pull request updates the SharedArrayBuffer related articles.
cc: @lutzvahl
=> Update SAB related articles on restriction delay

redirects.yaml, src/site/_data/courses/css/meta.yml, src/site/_data/site.js, src/site/_includes/partials/course-cards.njk, src/site/content/en/learn/css/css.11tydata.js
- Soft launch learn css course
- Add redirect for learnCSS -> /learn/css. It looks like our redirects are case sensitive.
=> soft launch learn css

src/site/content/en/blog/url-protocol-handler/index.md
=> Add URL Protocol Handler article

src/site/content/en/blog/optimize-vitals-lighthouse/index.md
Fixes #5062
- Adds article (please feel free to adjust dates as needed)
=> Adds optimizing CWV with Lighthouse (fixes #5062)

src/site/content/en/blog/bluetooth/index.md
This PR adds the new manufacturer data filter(coming in Chrome 92) to the bluetooth article. See https://www.chromestatus.com/feature/5684530360877056
FYI @reillyeon
=> Add manufacturer data filter to bluetooth article

src/site/content/en/blog/excalidraw-and-fugu/index.md
=> Add Excalibur article

src/site/content/en/learn/css/box-model/index.md, src/site/content/en/learn/css/index.md
Some small fixes for the learn css course.
=> Some learn css fixes.

src/site/content/en/blog/building-a-media-scroller-component/index.md
=> [new post] GUI Challenges media scroller

src/lib/components/SnackbarContainer/_styles.scss
Fixes #5315 
- Bump that z-index!
=> Boost cookie banner z-index

src/styles/pages/_course.scss
Fixes #5328 
- Reduce negative margin on pre's in the course pages
=> Fix pre tag overflow on course pages.

src/site/content/en/learn/css/color/index.md
=> lch() link fix

src/site/content/en/blog/floc/index.md
Also removed **Summary** heading, which seems redundant.
=> Updated title

src/site/content/en/blog/text-fragments/index.md
=> [Text Fragments article] Add spec draft link

src/site/_data/authorsData.json, src/site/content/en/blog/fugu-status/index.md, src/site/content/en/blog/handwriting-recognition/index.md
=> Add Handwriting Recognition article

src/site/content/en/blog/drag-and-drop/index.md
fixed code snippet indentation for better readability
=> doc(drag-and-drop): fixed indentation

src/site/content/en/measure/index.njk, src/styles/components/_page-header.scss, src/styles/pages/_measure.scss
=> Remove CLS from the sign in element in /measure

src/site/_data/site.js, src/site/_includes/homepage.njk, src/site/content/en/index.md, src/site/content/es/index.md, src/site/content/pl/index.md
=> Add io banner.

src/site/_data/paths/secure.json, src/site/content/en/secure/security-headers/index.md
* Add maudn as an author to /security-headers article.
* Add it under /secure collection.
=> Add to /secure, add maudn as an author

src/site/_data/authorsData.json, src/site/content/en/blog/vitals-ga4/index.md
=> Add Measure Web Vitals with GA4 and BigQuery post

src/site/content/en/learn/css/layout/index.md
Just spotted this extra `<h1>` while doing a run-through!
=> Remove unnecessary h1

src/site/_data/authorsData.json, src/site/content/en/blog/vitals-business-impact/index.md
This is still a bit of a WIP, I wanted to PR it to get some opinions on the images given respective timezones. I need to go through it properly tomorrow.
@mihajlija @kaycebasques the columns thing doesn't look brilliant for the content with images and text. I could take the images and make them all centered in a same sized canvas which I think would help, but before I do that, do you have any better ideas?
I'll jump back on this first thing my morning so it is ready to go out later in the day.
=> Business impact article draft

src/site/content/en/blog/declarative-link-capturing/index.md
Fixes #4725
- Add the article.
=> Add Declarative Link Capturing article

src/site/content/en/blog/migrate-to-ua-ch/index.md
New article on UA-CH migration strategies
=> Migrate to User-Agent Client Hints blog post

src/site/content/en/blog/new-responsive/index.md
Fixes #5136
(Missing video until tomorrow)
=> [Post] The New Responsive

src/site/content/en/blog/new-responsive/index.md
=> fix date format on new responsive article

src/styles/components/_app-bar.scss
Fixes #5403
Boost app-bar z-index so it doesn't get covered by self assessment questions
=> bump app-bar z-index a bit

src/site/content/en/lighthouse-best-practices/uses-passive-event-listeners/index.md
Fixes #5331
Fix awkwardly worded lh audit title
=> Improve passive event listener audit title

src/site/_data/paths/learn-web-vitals.json, src/site/content/en/blog/vitals-business-impact/index.md
Add Business impact of CWV to /learn-web-vitals
=> Add new post to /learn-web-vitals

src/site/content/en/lighthouse-best-practices/image-aspect-ratio/index.md
Fixes https://github.com/GoogleChrome/lighthouse/issues/12499#issuecomment-843165567
- Updates the Lighthouse aspect ratio description to match the audit implementation
=> Update Lighthouse aspect ratio description

src/site/content/en/fast/lazy-loading-video/index.md
=> <video class="lazy" ... >

src/site/content/en/learn/css/sizing/index.md
Part of #5418
changing an incorrect percentage.
=> fix to sizing units

.github/ISSUE_TEMPLATE/propose-new-content.md, src/site/content/en/handbook/quick-start/index.md
Update handbook and issue template to use the newer content form.
=> Use new content form.

src/site/content/en/learn/css/the-cascade/index.md
- Fixes link to CSS Podcast for The Cascade article.
=> Fix link to CSS Podcast for The Cascade article.

src/site/content/en/lighthouse-best-practices/doctype/index.md
Add a link to Quirks Mode spec to show a list of quirks in both Quirks Mode and Limited Quirks Mode.
=> Add a link to Quirks Mode spec

src/site/content/en/learn/css/box-model/index.md, src/site/content/en/learn/css/flexbox/conclusion.assess.yml, src/site/content/en/learn/css/selectors/index.md
Fixing some raised issues:
Fixes: #5411 
Fixes: #5436 
Fixes: #5437
=> A few small fixes

src/site/_data/site.js
Replace I/O banner with WebDev Insights banner
=> Update banner to use WebDev Insights

src/site/content/en/angular/route-preloading-in-angular/index.md
=> fix(angular): fix broken videos, fixes #5442

src/site/content/en/blog/user-agent-client-hints/index.md
(Also update the example UA string)
Fixes #5450
- Updates the flag name
cc @rowan-m
=> Fixes #5450 - Update name of #reduce-user-agent flag

.github/workflows/firebase-hosting-cron.yml, version-check.js
=> dix(deploy): add args to `cancelWorkflowRun`

src/site/content/en/learn/css/sizing/index.md
=> Update explanation to match css example.

src/site/_includes/partials/topic.njk, src/site/content/en/handbook/author-profile/index.md, src/site/content/en/handbook/content-checklist/index.md, src/site/content/en/handbook/inclusion-and-accessibility/index.md, src/site/content/en/handbook/markup-media/index.md, src/site/content/en/handbook/quick-start/index.md
Fixes #5308 
- Fixes broken heading anchors on learning path pages (including the handbook)
- Updates the web.dev/handbook quickstart and inclusive writing sections and adds some additional linking between them.
=> Handbook updates

src/site/content/en/blog/new-responsive/index.md
- Add links to [`/prefers-color-scheme/`](https://web.dev/prefers-color-scheme/) and [`/color-scheme/`](https://web.dev/color-scheme/).
=> [The New Responsive article] Add links to `/prefers-color-scheme/` and `/color-scheme/`

src/site/content/en/handbook/web-dev-components/index.md
Combines the definition list examples with the list section. This is basically a copy/paste from dcc so they're consistent.
=> Definition list handbook

src/site/content/en/reliable/offline-ux-design-guidelines/index.md
=> [Offline UX Design Guidelines article] Remove capabilities tag

src/site/content/en/blog/display-override/index.md
=> [Display Override article] Add missing tag

src/site/content/en/blog/file-handling/index.md
=> [File Handling article] Add capabilities tag

src/site/content/en/lighthouse-performance/render-blocking-resources/index.md
Fixes #5491 
- Replace with actual Coverage Tab Link
=> Replace broken Link

src/site/content/en/blog/notification-triggers/index.md
=> [Notification triggers article] Remove tag

src/site/content/en/blog/declarative-link-capturing/index.md
=> [Declarative link capturing article] Add missing tag

src/site/content/en/blog/css-is-and-where/index.md
=> New Post - CSS `:is()` and `:where()`

src/site/content/en/blog/css-is-and-where/index.md
=> Fix minor typo

src/site/content/en/metrics/cls/index.md
Updates to the CLS definition in the main post.
@philipwalton @anniesullie I seems to me like the code snippet for calculating CLS is no longer correct, does anyone have a replacement or should we remove it for now?
=> Update CLS definition

.remarkrc.js, tools/linting/no-chrome-scheme.js
Fixes #5385
- Add `chrome://` scheme lint rule.
=> Add `chrome://` scheme lint rule

src/site/content/en/blog/cls-web-tooling/index.md
Fixes #5460 Evolving CLS in Web Tooling.
=> Adds evolving web tooling blog post

src/site/_data/paths/learn-web-vitals.json, src/site/content/en/blog/css-web-vitals/index.md
Fixes https://github.com/GoogleChrome/web.dev/issues/4835
=> CSS for CWV blog post

src/site/content/en/blog/pwa-url-handler/index.md
Fixes #4482 
- Add the article
=> Add PWA URL Handler article

src/site/content/en/authors/index.njk, src/site/content/en/authors/individual.njk, src/site/content/en/blog/index.njk, src/site/content/en/newsletter/index.njk, src/site/content/en/tags/index.njk, src/site/content/en/tags/individual.njk
Fixes #4504
Enable `addAllPagesToCollections` on some paginated pages so that `collections.all` picks up on them in `sitemap.xml.njk`.
=> fix(sitemap): add paginated pages to sitemap, fixes #4504

redirects.yaml
Fixes https://github.com/GoogleChrome/web.dev/issues/5496
Merge after https://github.com/GoogleChrome/developer.chrome.com/pull/848 has been merged.
- Add redirects.
=> Add d.c.c. redirects

src/site/content/en/blog/file-handling/index.md
Address @dway123's remarks (offline via email).
=> [File Handling article] Address @dway123's remarks

src/site/content/en/blog/compute-pressure/index.md
This is a placeholder PR for the Compute Pressure API, anticipated to be an origin trial in M92.
It's already received an out-of-band technical review.
The PR is not ready to merge until the origin trial process has started, at which point I will swap in the appropriate values.
=> Compute Pressure API OT

src/site/content/en/blog/pwa-url-handler/index.md
Fixes #5525. 
(Sorry, I looked at the author in the explainer and the crbug owner. Not mentioning @mandymsft was not on purpose.)
- 
- 
-
=> [URL Handling article] Acknowledge @mandymsft

src/site/content/en/blog/web-on-android/index.md
Fixes #5508 
- Adds security considerations for using WebView as an in-app browser.
=> Web on android update

src/site/content/en/fast/serve-responsive-images/index.md
=> fixing a typo

src/site/content/en/blog/web-otp/index.md
Just a tiny typo I spotted while referencing this doc yesterday.
=> fixing a little typo

src/site/_data/site.js
=> disable insights banner

src/site/content/en/blog/web-share-target/index.md
=> [Web Share Target article] Add feedback and hashtag

src/site/content/en/blog/web-share/index.md
=> [Web Share article] Add feedback and hashtag

src/site/content/en/blog/compute-pressure/index.md
- Needs to be 92 instead of 91 according to the [bug](https://crbug.com/1067627#c17).
CC: @jeffposnick
=> [Compute Pressure] Update OT milestone

src/site/content/en/blog/commonjs-larger-bundles/index.md
There's a mix of backticks and single quotes, this PR aims to use single quotes where this happens.
=> Use single quotes

src/site/content/en/blog/gamepad/index.md
This PR adds missing arrow to arrow function
=> Add missing arrow

src/site/content/en/blog/fugu-status/index.md
=> [Fugu Status article] Link new codelab

src/site/content/en/learn/css/selectors/index.md
=> change .my-element to my.class to match explanation

.github/stale.yml
See the discussion here: https://github.com/GoogleChrome/web.dev/issues/4487#issuecomment-856049433
=> Increase stalebot timeout to 90 days

src/site/content/en/blog/css-size-adjust/index.md
=> New Post: CSS `size-adjust`

src/site/content/en/blog/css-size-adjust/index.md
before the post goes live, would love to have the latest date so it's at the top 👍🏻
=> updating post date to publish date

src/site/content/en/blog/at-property/index.md
Reverts #4433 from #4260
- Revert PR made to add multiple declarations for `@property`
=> [bugfix] Revert 85f0811

src/site/content/en/blog/fast-playback-with-preload/index.md
This PR correctly annotates HTML snippets for better syntax highlighting
=> Correctly annotate html snippets

src/site/content/en/blog/building-a-color-scheme/index.md
=> New Post: Gui Challenges - Building color schemes

src/site/content/en/learn/css/box-model/index.md
=> Fixes size inaccuracy in box-model breakdown

src/site/content/en/learn/css/grid/index.md
Fixes #5490
I created the `align-items` and `justify-items` Codepen and updated the embed ID to point to the new demo 👍🏻
=> Add `align-items` and `justify-items` Codepen demo

.pullapprove.yml
- Adds support for `[PWA]`, `[Media]`, `[Identity]` tags and reviewers
=> Add more content areas to pullapprove

src/site/content/en/blog/module-workers/index.md
=> Add missed event type

src/site/content/en/blog/content-indexing-api/index.md
=> [Content Indexing API article] Fix links

src/site/content/en/mini-apps/mini-app-conclusion/index.md
=> [Mini App Conclusions] Fix link

redirects.yaml, src/site/_data/authorsData.json, src/site/content/en/blog/introducing-aurora/index.md
Fixes #5044
Reviewed here: https://docs.google.com/document/d/1chJSNnrZn3wRoNTaJa045FbIP9A-cY73QVlqceg6uvo/edit?usp=sharing&resourcekey=0-UJRoTSNwIy-EC9hTwaAJrg
=> Adds "Introducing Aurora" post

src/site/_data/authorsData.json, src/site/content/en/blog/conformance/index.md
Fixes #5044
Reviewed here: https://docs.google.com/document/d/1FNCJ75XN0J6lYqNWV5ETYbU1q78TQYsVTEfCUMc9Hlc/edit?usp=sharing&resourcekey=0-qkfGm-QebZ51mIP_KElQDg
=> Adds "Conformance for Frameworks" post

src/site/content/en/blog/blibli/index.md
=> Provide better hero image.

src/site/content/en/fast/font-best-practices/index.md
Clarify when variable fonts are larger
=> font-best-practices/index.md Clarify font terminology and variable font minutia 

src/site/content/en/blog/vitals-measurement-getting-started/index.md
Progress on #5627
[Title looks title-y](https://deploy-preview-5628--web-dev-staging.netlify.app/vitals-measurement-getting-started/):
[Links look link-y](https://deploy-preview-5628--web-dev-staging.netlify.app/learn-web-vitals/):
=> Remove newline from "Getting started with measuring Web Vitals" title

src/site/content/en/blog/blibli/index.md
=> Add tme so article pos shows it was last published

src/site/_data/authorsData.json
=> Fix a twitter handle.

src/site/content/en/blog/content-visibility/index.md
- Updates content-visibility post w/SPA note and experiment data
=> [Post Update] Content-visibility

src/site/_plugins/markdown.js
=> Add rel=noopener for external links in markdown

src/site/_data/i18n/footer.yml, src/site/_includes/partials/footer.njk
=> Add link to d.c.c in related content in footer.

src/lib/components/ScrollSpy/index.js, src/lib/components/TableOfContents/index.js, src/lib/pages/content.js, src/site/_includes/partials/toc-side.njk, src/styles/components/_course-toc.scss, src/styles/components/_toc.scss
=> Factor our ScrollSpy from Toc into separate component

.pullapprove.yml
=> Add draft PR as a separate condition to pullapprove

src/site/content/en/learn/css/animations/index.md
- animation-play-state: `pause` -> `paused`
=> fix(frontend-learn-css): typo of property's value

src/site/content/en/blog/storage-foundation/index.md
=> [Storage Foundation article] Fix links

src/site/_data/site.js
Remove insights banner as the campaign is over for now
=> remove banner

src/site/_includes/partials/item.njk, src/site/_includes/partials/post.njk
=> Remove whitespace from titles in the path topics list

src/site/content/en/learn/css/blend-modes/index.md
- `mix-blend` mode -> `mix-blend-mode`
- multiply and screen -> `multiply` and `screen`
=> fix(frontend-learn-css): format of properties' values

src/site/_transforms/purify-css.js
=> Remove unnecessary head ending

src/site/content/en/blog/conformance/index.md
Minor updates to Conformance blog post:
* Updates build time line
* Adds sentence about how conformance can be opted-out
* Fixes broken links
=> Updates Conformance blog post

src/site/content/en/learn/css/grid/grid.assess.yml
(am open to suggestions about the exact wording)
=> ✏️ Add rationale for grid quiz

src/site/content/en/learn/css/spacing/index.md
=> ✏️ [Learn CSS] Fix typo in Spacing module

src/site/content/en/learn/css/functions/index.md
=> LearnCSS: Functions syntax correct

src/lib/actions.js
=> Obfuscate error message

src/site/content/en/blog/new-pwa-training/index.md
- Added "New PWA Training" blog post
=> Add New PWA Training blog post

src/site/_data/site.js, src/site/content/en/handbook/banners/index.md
Add PWA summit banner and include instructions on how to add banners to the site.
=> Add pwa banner and instructions

src/site/content/en/blog/css-web-vitals/index.md
=> Update resource hints for Google Fonts

src/site/content/en/animations/animations-overview/index.md
- Changed animation to animate for correct grammar.
=> Change animation to animate

src/site/content/en/blog/cls-web-tooling/index.md
- Use YYYYMM format for CrUX BQ releases
=> Update CrUX BQ releases in CLS update

src/site/content/en/blog/debug-web-vitals-in-the-field/index.md
- fix `layoutShift` to `largestEntry`
- 
-
=> fix typo in "Debug Web Vitals in the field"

src/site/content/en/blog/file-handling/index.md
=> [File Handling article] Add OT link

src/site/content/en/blog/pwa-url-handler/index.md
Fixes https://github.com/GoogleChrome/web.dev/issues/5527
- Address @mandymsft's remarks.
=> [PWAs as URL handerls] Address @mandymsft's remarks

src/site/content/en/blog/file-system-access/index.md
- Clarify what this is _not_ about.
=> [File System Access API article] Add distinction clarification

src/site/content/en/blog/storage-foundation/index.md
- Use usual formatting and wording
=> [Storage Foundation article] Use usual formatting and wording

src/site/content/en/blog/url-protocol-handler/index.md
=> [URL Protocol Handling article] Add origin trial info

src/site/content/en/blog/url-protocol-handler/index.md
=> [URL Protocol Handler] Fix build

src/site/content/en/blog/media-session/index.md
This PR updates code samples to reflect recent changes in official samples. See https://github.com/GoogleChrome/samples/pull/730
=> Fix handling playbackState

src/site/content/en/blog/async-clipboard/index.md
=> [Async Clipboard article] Await blob

src/site/content/en/learn/css/borders/index.md
=> ✏️ [Learn CSS] Fix spacing in Border lesson

src/site/content/en/blog/aurora-resource-inlining/index.md
Capture the project Aurora initiatives around resource inlining.
cc @spanicker @housseindjirdeh @addyosmani @rachelandrew
=> Add a blog post about resource inlining

src/site/content/en/lighthouse-performance/speed-index/index.md
=> Clarify mobile speed index thresholds

src/site/content/en/blog/building-a-media-scroller-component/index.md
fixes #5560
ty @gauravsoni119!
=> GUI challenge - post patch with bug fixes

src/site/content/en/blog/webassembly-threads/index.md
=> Wasm threads blog post

src/site/content/en/blog/building-a-breadcrumbs-component/index.md
=> New Post: GUI Challenges - building breadcrumbs

src/styles/components/_numbered-header.scss, src/styles/globals/gorko/_config.scss, src/styles/tools/_functions.scss, src/styles/tools/_mixins.scss
We're getting a screen full of shouting from Sass at the moment, so I thought I'd just clean it all up :)
=> Sass deprecations

src/lib/components/AssessmentQuestion/_styles.scss, src/lib/components/BaseModalElement/_styles.scss, src/lib/components/LighthouseScoresAudits/_styles.scss, src/styles/tools/_mixins.scss
=> Fix the remaining sass warnings.

src/site/content/en/blog/aurora-resource-inlining/index.md
Add a video to show the effect of CSS inlining on CLS and LCP.
=> Add video after critical CSS inlining

src/site/content/en/blog/lcp-lazy-loading/index.md
=> Fix spacing in lazy-loading post

src/site/_filters/minify-js.js
Fixes #5802. I just forgot to call return so the async callback was getting triggered at random times 😅
=> Add missing return to make terser happy.

src/site/_includes/partials/author-stack.njk
Fixes #5818 
Small update since we changed the shape of author's global data.
=> Fix broken authors in learn css

src/site/content/en/blog/netzwelt/index.md
Fixes: #5034 
Adds the Case Study.
=> Add Netzwelt Case Study

src/site/content/en/blog/multi-screen-window-placement/index.md
Updated the article for the second OT.
Do not merge before the OT URL is up.
=> [Multi-Screen Window Placement API ] Update article for second OT

src/site/content/en/blog/building-a-breadcrumbs-component/index.md
- Replace 16px by 100%. https://twitter.com/tomayac/status/1207254730197614592?s=20
=> [Breadcrumbs article] Don’t hardcode font sizes (ever)

src/site/content/en/blog/webassembly-threads/index.md
=> Fix Rust syntax in Wasm threads blog post

src/site/content/en/metrics/cls/index.md
=> Fix URL link in CLS post

firebase-config.js
Disallow iframing web.dev (except self iframing). This adds the CSP header as well as the fallback X-Frame-Options header.
=> generate x-frame-options and csp equivalent

src/site/content/en/blog/compat2021-midyear/index.md
Fixes #5799
This is a blog post
=> [Add blog post] Compat2021 - midyear update

src/site/_includes/path.njk
Related issue with the detailed bug description – #5875
=> Fix TOC links for the learn pages

src/site/content/en/learn/css/the-cascade/index.md
=> fix "earn" => "learn" in link

src/site/_data/i18n/shows.yml, src/site/_data/showsData.json
Adds Designing in the Browser to shows page
=> Add DIB to shows

src/site/_data/paths/learn-web-vitals.json, src/site/content/en/blog/tag-best-practices/index.md
https://github.com/GoogleChrome/web.dev/issues/5718
=> Add tag best practices article

src/site/_includes/partials/footer.njk
Fixes #5888 
- Updated link that was 404ing
=> Updated Link in footer

src/site/content/en/blog/file-handling/index.md
Start fresh on what was #5531
-  Clarify permissions.
=> [File Handling article] Clarify permissions

src/site/content/en/blog/fetch-upload-streaming/index.md
Fixes #5869
This corrects the feature-detect in https://web.dev/fetch-upload-streaming/#feature-detection so it also works for Safari.
=> Update feature detect in streaming fetch article

src/site/content/en/fast/signed-exchanges/index.md
/cc @khempenius @antiphoton @Gregable
=> Add sxg-rs to the list of available tools

src/scss/_config.scss, src/scss/compositions/_auto-grid.scss, src/scss/compositions/_cluster.scss, src/scss/compositions/_repel.scss, src/scss/compositions/_sidebar.scss, src/scss/compositions/_switcher.scss, src/scss/next.scss, src/site/content/en/design-system/css-compositions.njk, src/site/content/en/design-system/temp-styleguide.njk
This is the compositional layouts for the new system that use the composition principles from CUBE CSS. 
The documentation has been added into the system, but the demos will not currently work until they are using the new CSS (next sprint). 
You can see them in action here: https://deploy-preview-5902--web-dev-staging.netlify.app/design-system/temp-styleguide#compositions
Here is a screencast showing it all working too: https://www.loom.com/share/cbfa3e23a8fc485193772ea0e742ed7a
=> CSS layout compositions

src/site/content/en/blog/file-system-access/index.md
=> [File System Access article] Document gotcha

src/site/content/en/blog/prefers-color-scheme/index.md, src/site/content/en/blog/user-preference-media-features-headers/index.md
=> Add User Preference Media Features Client Hints Headers article

src/site/content/en/blog/2021-scroll-survey-report/index.md
=> New Post: 2021 Scroll Survey Report

src/site/_collections/shows.js, src/site/_data/i18n/paths/authors.yml, src/site/_data/i18n/paths/shows.yml, src/site/_data/i18n/paths/tags.yml, src/site/_includes/authors-individual.njk, src/site/_includes/components/AuthorsDate.js, src/site/_includes/macros/show-card.njk, src/site/_includes/show.njk, src/site/_includes/shows-individual.njk, src/site/_includes/tags-individual.njk, src/styles/components/_author.scss
Fixes #5761
- Add links in individual show, tag, and author pages to view all of that certain area
- Add links in an individual video to see what show it belongs to
- Fix touch targets of authors
=> feat(virtual-collections): promote better discovery of virtual collections

src/site/content/en/blog/user-preference-media-features-headers/index.md
- Closes a code block that was left open.
=> [User Preference Client Hints article] Close code block

src/site/content/en/blog/local-fonts/index.md
- Remove outdated origin trial info.
=> [Local Fonts article] Remove OT info

src/site/content/en/blog/async-clipboard/index.md
- Document dealing with pasted files.
=> [Async Clipboard article] Document dealing with pasted files

src/site/content/en/blog/web-share-target/index.md
-updating to reflect that this is now supported in desktop platforms (Windows)
- adds mention to desktop platform
- 
-
=> Mention share target works on desktop

src/site/content/en/blog/window-controls-overlay/index.md
=> [Window Controls Overlay article] Update OT link

src/site/content/en/blog/coop-coep/index.md, src/site/content/en/blog/why-coop-coep/index.md, src/site/content/en/secure/cross-origin-isolation-guide/index.md, src/site/content/en/secure/security-headers/index.md
Small updates regarding JS Self Profiling API no longer depends on cross-origin isolation.
=> Small updates

src/site/content/en/blog/file-system-access/index.md
- Add browser support paragraph.
=> [File System Access article] Add browser support paragraph

src/site/content/en/blog/window-controls-overlay/index.md
=> [Window Controls Overlay article ] Correct OT date

src/site/content/en/learn/css/focus/index.md
=> LearnCSS: fixes broken link in focus article

src/site/content/en/blog/pwa-url-handler/index.md
See https://github.com/WICG/pwa-url-handler/issues/29#issuecomment-892261526
- Make same origin rules clearer.
=> [PWAs as URL handler article] Make same origin rules clearer

src/site/_filters/expand-authors.js, src/site/_includes/partials/course-app-bar.njk, src/site/_includes/partials/post.njk
Fixes #5924
- Add lang and i18n filter to the `expandAuthors` filter
=> fix(share): fix author titles in share component, fixes #5924

src/site/content/en/blog/vitals-tools-workflow/index.md
Fixes #5819 
Adding the Performance Tooling Workflow article.
=> Add the workflow article: publish 2021-08-09

src/site/_includes/partials/footer.njk
- Update twitter link
- Update chrome developers home link
- Update google developers site policies link
=> Update twitter and chrome developers link in footer.

src/site/_data/authorsData.json
=> Edited antoinebisch in authorsData.json

src/site/content/en/blog/building-a-switch-component/index.md
=> Blog gui challenges switch

src/site/content/en/learn/css/box-model/index.md
Fixes #5957
- use the web.dev codepen account
- removes postcss and babel from preprocessors
- adds new landscape layout
=> fixes #5957

src/site/content/en/blog/serial/index.md
Fixes #5974 
- Fixes the broken links in "Read from and write to a serial port".
=> Fix links in serial port article.

src/site/content/en/blog/how-to-set-up-signed-http-exchanges/index.md
Link to correct nginx-sxg-module repo, and add example nginx version constraint.
/cc @khempenius @kumagi
Addresses google/nginx-sxg-module#100.
=> Fix Debian install instructions

src/site/content/en/blog/building-a-switch-component/index.md
- adds a community submission entry to the gui challenge on switches
=> [GUI Challenges] community submission addition patch

src/site/content/en/blog/optimize-cls/index.md
=> Optimize CLS - dynamic content caption fix

src/site/content/en/learn/css/pseudo-elements/index.md
=> [learn css] pseudo-element correction patch

src/site/_data/paths/learn-web-vitals.json, src/site/content/en/learn-web-vitals/lab-and-field-data-differences/index.md
=> Add lab vs field data post

src/styles/components/_code-pattern.scss
=> Make codePattern demo and sample stackable

src/lib/pages/content.js, src/site/_includes/partials/post.njk
See https://github.com/GoogleChrome/web.dev/pull/5970/files#r688825126
=> Remove feedback widget from post.njk

src/site/content/en/blog/file-system-access/index.md
=> [File system access article] Use new compat widget

src/site/content/en/blog/trust-tokens/index.md
• Miscellaneous updates to wording and code samples.
• Added warning about TrustTokenV3 update.
Requires eng review/approval before merging.
@dvorak42 @davidvancleve fyi
=> Updated web.dev/trust-tokens

src/site/content/en/learn/css/grid/index.md
Change helps create a mental connection between the written example and the image below ([“Grid lines” section](https://web.dev/learn/css/grid/)).
Signed-off-by: Jens Oliver Meiert <jens@meiert.com>
=> docs: tweak copy to correspond with image (makes it a little bit easier)

src/site/content/en/blog/new-responsive/index.md, src/site/content/en/blog/urlpattern/index.md, src/site/content/en/blog/webrtc-standard-announcement/index.md, src/site/content/en/learn/css/logical-properties/index.md
Signed-off-by: Jens Oliver Meiert <jens@meiert.com>
=> docs: add missing periods

src/site/content/en/learn-web-vitals/lab-and-field-data-differences/index.md
I noticed the typo when I saw this tweet: https://twitter.com/googleanalytics/status/1430210483626209284
=> Fix typo in lab vs field post

src/site/content/en/blog/file-system-access/index.md
=> [File System Access] Fix gotchas aside

src/site/content/en/blog/idle-detection/index.md
=> [Idle Detection article] Update for launch

redirects.yaml
=> Add /si => /speed-index

src/site/content/en/blog/building-a-color-scheme/index.md
=> GUI Challenge Patch: adds work from @chris-kruining

src/site/content/en/blog/drag-and-drop/index.md
=> Clarify drag and drop article handleDrop

src/site/content/en/media/media-application-basics/index.md
Fixes #6056
@rkochman Please look this over.
=> Add windows version of command.

src/styles/components/_card-base.scss
Fixes #5961
- fix card layout for bp md by setting content to none
=> fix(card): fix card layout for bp md by setting content to none, fixes #5961

src/site/content/en/blog/2021-scroll-survey-report/index.md
=> Fixed link to Scroll Survey Report

src/site/content/en/blog/wake-lock/index.md
Mrunal did a great job implementing a previous iteration of the Screen Wake
Lock spec in Chromium. I've been maintaining both the spec and the
implementation for the past few years, so add a shameless plug for myself as
well.
=> [Screen Wake Lock article] Add myself to the acknowledgements aside.

src/site/content/en/blog/digging-into-the-privacy-sandbox/index.md
=> Fixed Attribution Reporting link

src/site/content/en/mini-apps/mini-app-project-structure-lifecycle-and-bundling/index.md
=> fixing typo in Project structure, lifecycle, and bundling blog

src/site/content/en/learn/css/inheritance/index.md
=> fixing url in learn css Inheritance podcast

src/site/content/en/fast/how-can-performance-improve-conversion/index.md
=> fixing url in How can performance improve conversion?

src/site/content/en/fast/identify-slow-third-party-javascript/index.md
=> fixing url in Identify slow third-party JavaScript blog

src/site/content/en/fast/using-bundlesize-with-travis-ci/index.md
=> fixing url in Using bundlesize with Travis CI blog

src/site/content/en/blog/optimize-vitals-lighthouse/index.md
=> fixing url in Optimizing Web Vitals using Lighthouse blog

src/site/content/en/blog/css-scroll-snap/index.md
=> fixing url in Well-controlled scrolling with CSS Scroll Snap blog

src/site/content/en/reliable/offline-cookbook/index.md
=> fixing url in The Offline Cookbook blog

src/site/content/en/blog/mediastreamtrack-insertable-media-processing/index.md
=> fixing typo in Insertable streams for MediaStreamTrack blog

src/site/content/en/blog/cls-web-tooling/index.md
=> fixing url in Evolving Cumulative Layout Shift in web tooling

src/site/content/en/mini-apps/mini-app-programming-way/index.md
=> fixing broken link in Programming the mini app way blog

src/site/content/en/payments/setting-up-a-payment-method/index.md
=> fixing broken link in Setting up a payment method blog

src/site/content/en/lighthouse-accessibility/use-landmarks/index.md
=> fixing url in HTML5 landmark elements are used to improve navigation blog

src/site/content/en/lighthouse-best-practices/errors-in-console/index.md
=> fixing url in Browser errors were logged to the console blog

src/site/content/en/progressive-web-apps/app-like-pwas/index.md
=> fixing url in Make your PWA feel more like an app blog

src/site/content/en/learn/css/filters/index.md
=> fixing url in learn css Filters podcast

src/site/content/en/payments/setting-up-a-payment-method/index.md
=> fixing url in Setting up a payment method blog

src/site/content/en/blog/codelab-sign-up-form-best-practices/index.md
=> fixing typo in Sign-up form best practices codelab

src/site/content/en/fast/remove-unused-code/index.md
=> fixing url in Remove unused code blog

src/site/content/en/fast/what-should-you-measure-to-improve-performance/index.md
=> fixing url in What should you measure to improve performance?

src/site/content/en/blog/generic-sensor/index.md
=> fixing url in Sensors for the web blog

src/site/content/en/blog/app-history-api/index.md
=> fixing url in Modern client-side routing: the App History API blog

src/site/content/en/mini-apps/mini-app-alternative-runtime-environments/index.md
=> [Mini Apps] Add VK mini apps

src/site/content/en/blog/serial/index.md
=> fixing url and removing en-us in Read from and write to a serial port blog

src/site/content/en/blog/granular-chunking-nextjs/index.md
=> fixing url in Improved Next.js and Gatsby page load performance with granular chunking blog

src/site/content/en/fast/optimize-css-background-images-with-media-queries/index.md
=> fixing url in Optimize CSS background images with media queries blog

src/site/content/en/blog/bundling-non-js-resources/index.md
=> Add post about new URL pattern

src/site/content/en/blog/app-history-api/index.md
=> App History API article - Typo fix

src/site/content/en/blog/pwa-url-handler/index.md
Fixes https://github.com/WICG/pwa-url-handler/issues/32#issuecomment-914657830
- Clarify this only works for the default browser.
=> [PWAs as URL Handlers article] Clarify this only works for the default browser

src/site/content/en/blog/urlpattern/index.md
R: @wanderview to okay the changes prior to merging.
=> Updates for URLPattern: shipping in M95

src/site/content/en/building-a-split-button-component/index.md
=> Blog post gui challenge split button

src/site/content/en/blog/ar-hit-test/index.md
https://codelabs.developers.google.com/codelabs/ar-with-webxr could not be found, so I replaced it with another code, maybe it is useful for your user.
- 
- 
-
=> fixing url in Positioning virtual objects in real-world views

src/site/content/en/fast/identify-slow-third-party-javascript/index.md
=> fixing url in Identify slow third-party JavaScript

src/site/content/en/blog/compress-images-avif/index.md
=> Fixing ImageMagick URL in Using AVIF to compress images on your site blog

src/site/content/en/blog/declarative-shadow-dom/index.md
=> fixing url in Declarative Shadow DOM blog

src/site/content/en/blog/appcache-removal/index.md
=> fixing url in Preparing for AppCache removal article

src/site/content/en/blog/virtualkeyboard/index.md
Fixes #5936
- Add the article.
=> Add VirtualKeyboard API article

src/styles/components/_buttons.scss, src/styles/components/_details.scss, src/styles/components/_self-assessment-hint.scss
=> Replace in css speak: none with speak: never

src/site/content/en/blog/next-gen-css-2019/index.md
=> fixing url in Next-generation web styling blog

src/site/content/en/blog/samesite-cookie-recipes/index.md
=> fixing url in SameSite cookie recipes blog

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/eventing-deepdive/index.md
=> Add eventing article

src/site/content/en/blog/user-agent-client-hints/index.md
Fixes #6197
- Updates content to account for UA-CH API Updates
- Fixes some links
- Fixes incorrect alt text for hero image
=> Fixes #6187 - Update UA-CH article content now that M93 is stable

src/site/content/en/blog/eventing-deepdive/index.md
=> Eventing Deep Dive: typo fix

src/site/content/en/blog/2021-scroll-survey-report/index.md
=> Temporarily removed Igalia link

src/site/content/en/blog/pwa-url-handler/index.md
=> [Progressive Web Apps as URL Handlers article] Add OT info

.github/actions/presubmit/action.yml, .github/actions/presubmit/index.js, .github/pull_request_template.md, .github/workflows/presubmit-workflow.yml, package-lock.json, package.json, src/site/content/en/handbook/pull-requests/index.md
Fixes #5793
- add new workflow that runs a prod build
- add action that checks if there is a presubmit label and removes it if there is
=> build(presubmit): create a presubmit step, fixes #5793

.github/workflows/lighthouse-ci-workflow.yml, .github/workflows/lint-and-test-workflow.yml, .github/workflows/percy-workflow.yml
- Update checkout action to v2
- Remove node setup, its not needed with checkout action
- Remove cache node_modules, it doesnt speed up builds in any noticeable way and can break updates to modules
=> refactor(workflows): simplify checkout and node setup

src/site/content/en/blog/swappie/index.md
=> Add Swappie case study

src/site/content/en/blog/get-installed-related-apps/index.md
-  Add spec link, update explainer link.
=> [getInstalledRelatedApps article] Add spec link, update explainer link

src/site/content/en/blog/eventing-deepdive/index.md
Fix heading levels and formatting
=> Update JS eventing post

src/site/content/en/blog/vitals-spa-faq/index.md
=> Add How SPA architectures affect Core Web Vitals post

src/site/content/en/handbook/adding-a-course/index.md
Adds additional instructions explaining how to create a course and which media assets are required.
=> Add more course set up instructions

src/styles/components/_code-pattern.scss, src/styles/pages/_code-patterns.scss
Fixes https://github.com/GoogleChrome/web.dev/issues/6237
=> Webkit fixes for patterns page

src/site/content/en/fast/signed-exchanges/index.md
/cc @khempenius @cpapazian @rgs1
=> Add Envoy SXG Filter to Tooling.

src/site/content/en/blog/app-history-api/index.md
=> remove ref to interface type in App History API post

src/site/content/en/learn/forms/accessibility/index.md
=> Learn Forms Accessibility

src/site/content/en/learn/forms/testing/index.md, src/site/content/en/learn/forms/testing/testing.assess.yml
=> Adds Learn Forms Testing

src/site/content/en/learn/forms/validation/index.md, src/site/content/en/learn/forms/validation/validation.assess.yml
Fixes #5840 adds the Validation module.
=> Learn Forms Validation module

src/site/content/en/blog/file-handling/index.md
=> [File handling article] Add icons

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/speculative-prerendering/index.md
Fixes #6178
To do:
cc @addyosmani
=> Add speculative prerendering post

src/site/content/en/blog/speculative-prerendering/index.md
This PR makes three minor changes:
1. Adds a cover image
2. Adjust author order 
3. Fixes MDN link linting issues
Let me know if this works? Cheers!
=> Speculative prerendering minor edits

src/site/content/en/blog/file-system-access/index.md, src/site/content/en/blog/storage-foundation/index.md
Clarify interoperability between the two APIs.
=> Storage Foundation: clarify interop

src/site/content/en/blog/speculative-prerendering/index.md
Make clear the API is proposed at the moment.
=> [Pre-rendering API article] Proposed API

src/site/content/en/blog/coop-coep/index.md
=> Small update to COOP/COEP

src/site/_data/courses/forms/toc.yml, src/site/_data/i18n/courses.yml, src/site/content/en/learn/forms/design-basics/design-basics.assess.yml, src/site/content/en/learn/forms/design-basics/index.md
=> Learn Forms design basics

src/site/content/en/handbook/web-dev-components/index.md
=> Add web-tabs to handbook

.eleventy.js, shared/locale.js, src/site/_data/i18n/post.yml, src/site/_filters/urls.js, src/site/_includes/components/LanguageList.js, src/site/_includes/components/Meta.js, src/site/_includes/partials/post.njk
=> Add translated-to widget to posts

.eleventy.js, src/lib/components/TableOfContents/index.js, src/site/_includes/partials/post.njk, src/styles/components/_toc.scss
=> improve toc discoverability

src/site/_includes/partials/post.njk
=> dont open toc automatically

src/site/content/en/blog/webtransport/index.md
=> [Web Transport article] Update DevTools bug

src/site/content/en/blog/user-agent-client-hints/index.md
Fixes #6314
- Update the article to use the new header name
-
-
=> Fixes #6314: s/Feature-Policy/Permissions-Policy/

src/site/content/zh/metrics/cls/index.md
- The origin bold syntax is not supported by markdown.
=> Fix the wrong bold syntax

src/site/content/en/blog/vitals-business-impact/index.md
updated with latest case studies
Submitted tracking issue https://github.com/googlechrome/web.dev/issues/6179
- added case study link to Vodafone
- added new case study Netzwelt
- added GEDI to last section of case study summaries
=> Update vitals-business-impact with latest case studies

src/site/content/en/blog/app-history-api/index.md
=> fix App History API example

src/site/_data/paths/learn-web-vitals.json, src/site/content/en/blog/embed-best-practices/index.md, web.dev.env
Fixes #6171
- A new blog entry for third-party embed best practices.
=> Embed best practices

src/site/_data/i18n/authors.yml
My bio needed updating as I'm no longer freelance :)
=> Fixing my bio

src/site/content/en/learn/forms/accessibility/index.md, src/site/content/en/learn/forms/attributes/index.md, src/site/content/en/learn/forms/auto/index.md, src/site/content/en/learn/forms/autofill/index.md, src/site/content/en/learn/forms/conclusion/index.md, src/site/content/en/learn/forms/cross-platform-testing/index.md, src/site/content/en/learn/forms/data/index.md, src/site/content/en/learn/forms/design-basics/index.md, src/site/content/en/learn/forms/form-fields/index.md, src/site/content/en/learn/forms/form/index.md, src/site/content/en/learn/forms/identity/index.md, src/site/content/en/learn/forms/internationalization/index.md, src/site/content/en/learn/forms/javascript/index.md, src/site/content/en/learn/forms/styling-form-controls/index.md, src/site/content/en/learn/forms/styling/index.md, src/site/content/en/learn/forms/testing/index.md, src/site/content/en/learn/forms/validation/index.md
- Tweaks for CodePen embeds
- Corrected some URLs
- Small typos
=> Learn forms: Tweaks for CodePen embeds, correct URLs

src/site/content/en/learn/design/intro/intro.assess.yml, src/site/content/en/learn/design/macro-layouts/index.md, src/site/content/en/learn/design/macro-layouts/macro-layouts.assess.yml, src/site/content/en/learn/design/media-queries/media-queries.assess.yml, src/site/content/en/learn/design/micro-layouts/index.md, src/site/content/en/learn/design/micro-layouts/micro-layouts.assess.yml
Two more, plus some fixes to the others.
=> Two more Learn Design modules

.eleventy.js, src/site/_includes/components/BrowserCompat.js, src/site/_utils/browserCompat.js
=> makes browserCompat a sync shortcode

src/lib/components/LearnFilter/index.js, src/scss/next.scss, src/scss/pages/_learn.scss, src/site/content/en/learn-next/index.njk, src/site/content/en/learn-next/learn-next.11tydata.js, src/site/content/en/learn/index.njk, test/unit/src/lib/components/LearnFilter/index.js
Fixes #6391
- Updates learn page to use new design system.
Issues
- SVGs may be wonky with their transparent backgrounds when in dark mode. Maybe we should set the images to have a white background no matter what?
- The SVG for the learn course does not scale well for the new card design. We probably need new assets there.
- I couldn't get the cards to align quite right, they seem off. @andy-piccalilli if you could take a look at them that would be awesome.
=> feat(learn): use new design system, fixes #6391

src/site/_data/i18n/courses.yml, src/site/content/en/learn/design/accessibility/index.md, src/site/content/en/learn/design/icons/index.md, src/site/content/en/learn/design/index.md, src/site/content/en/learn/design/interaction/index.md, src/site/content/en/learn/design/macro-layouts/index.md, src/site/content/en/learn/design/media-features/index.md, src/site/content/en/learn/design/picture-element/index.md, src/site/content/en/learn/design/responsive-images/index.md, src/site/content/en/learn/design/screen-configurations/index.md, src/site/content/en/learn/design/theming/index.md, src/site/content/en/learn/design/typography/index.md, src/site/content/en/learn/design/ui-patterns/index.md
Learn Design intro, also added "Coming soon" to the modules that are not launching.
=> Intro and coming soon text.

src/component-library/feature-card/feature-card.json, src/component-library/feature-card/feature-card.njk, src/scss/blocks/_feature-card.scss, src/scss/blocks/_hero.scss, src/scss/pages/_homepage.scss, src/scss/utilities/_wrapper.scss, src/site/_includes/homepage-next.njk
Fixes #6577
Also applies some typsetting tweaks discussed between @jimoong and I.
=> Design update snags

src/site/content/en/learn/design/internationalization/index.md, src/site/content/en/learn/design/intro/index.md
Fixed width: https://codepen.io/web-dot-dev/pen/RwZjwoQ
Liquid: https://codepen.io/web-dot-dev/pen/YzxEzpE
Adaptive: https://codepen.io/web-dot-dev/pen/oNeoNYw
Responsive: https://codepen.io/web-dot-dev/pen/JjyOjbE
rtl: https://codepen.io/web-dot-dev/pen/mdMqdOx
ltr: https://codepen.io/web-dot-dev/pen/gOxXOLK
=> LearnDesign: Update demos

src/site/content/en/lighthouse-performance/dom-size/index.md
Fixes https://github.com/GoogleChrome/lighthouse/issues/11746
=> update scoring criteria in lighthouse dom-size

src/site/content/en/learn/css/layout/index.md
=> Add a missing semicolon to CSS snippet

src/site/_includes/partials/theme-script.njk
=> fix(CSP): fix CSP from inline JS

src/site/content/en/metrics/tbt/index.md
Fixes #6623
The good TBT threshold is 200 ms
=> Make good TBT thresholds consistent

package-lock.json, package.json, src/site/_filters/minify-js.js
This is breaking our prod build.
I'm rev'ing terser too.
=> Fix minify build, args called in wrong order

src/scss/next.scss
Tweaks font size and auto-quotes selectors 
Fixes #6596
=> Blockquote adjustments

src/site/content/en/learn/forms/fields/index.md, src/site/content/en/learn/forms/internationalization/index.md, src/site/content/en/learn/forms/javascript/index.md, src/site/content/en/learn/forms/security-privacy/index.md, src/site/content/en/learn/forms/styling/index.md, src/site/content/en/learn/forms/testing/index.md, src/site/content/en/learn/forms/usability-testing/index.md
A few nits, mostly removing repetitive "in this module" text from descriptions as is displays in the home listing.
=> A few Learn Forms tweaks

src/site/content/en/learn/pwa/app-design/index.md, src/site/content/en/learn/pwa/architecture/index.md, src/site/content/en/learn/pwa/assets-and-data/index.md, src/site/content/en/learn/pwa/caching/index.md, src/site/content/en/learn/pwa/capabilities/index.md, src/site/content/en/learn/pwa/complexity/index.md, src/site/content/en/learn/pwa/conclusion/index.md, src/site/content/en/learn/pwa/detection/index.md, src/site/content/en/learn/pwa/enhancements/index.md, src/site/content/en/learn/pwa/experimental/index.md, src/site/content/en/learn/pwa/foundations/index.md, src/site/content/en/learn/pwa/getting-started/index.md, src/site/content/en/learn/pwa/index.md, src/site/content/en/learn/pwa/installation-prompt/index.md, src/site/content/en/learn/pwa/installation/index.md, src/site/content/en/learn/pwa/offline-data/index.md, src/site/content/en/learn/pwa/os-integration/index.md, src/site/content/en/learn/pwa/progressive-web-apps/index.md, src/site/content/en/learn/pwa/service-workers/index.md, src/site/content/en/learn/pwa/serving/index.md, src/site/content/en/learn/pwa/tools-and-debug/index.md, src/site/content/en/learn/pwa/update/index.md, src/site/content/en/learn/pwa/web-app-manifest/index.md, src/site/content/en/learn/pwa/windows/index.md, src/site/content/en/learn/pwa/workbox/index.md
Fixes: #6479 
Fixes: #6480 
Fixes: #6481 
First 3 Learn PWA, plus updating others to be "coming soon".
=> Learn PWA first three modules

src/site/content/en/home/index.md, src/site/content/en/measure-psi/index.njk, src/site/content/en/patterns/layout/aspect-ratio-image-card/index.md, src/site/content/en/patterns/layout/deconstructed-pancake/index.md, src/site/content/en/patterns/layout/index.md
=> fix copy nits for launch

src/site/content/en/learn/pwa/index.md
Quick fix to the description which was TODO.
=> fix learn pwa description.

src/lib/components/LighthouseViewer/index.js, src/scss/pages/_measure.scss, src/site/content/en/measure-psi/index.njk
Fixes CLS and dark theme on viewer
=> Measure page fixes

src/site/content/en/home/index.md, src/site/content/en/measure-psi/index.njk
=> Copy updates

src/site/_includes/about-next.njk
=> increase heading font

src/site/content/en/learn/design/intro/index.md, src/site/content/en/learn/design/media-queries/index.md, src/site/content/en/learn/design/micro-layouts/index.md
Moves CodePens to the web-dot-dev account.
=> Updates CodePens and links in Learn Design

src/site/content/en/blog/media-session/index.md
This PR adds the new YouTube video about the Media Session API.
=> Add YouTube video

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/smoothness/index.md
Fixes #6423 
Note: this post is not yet final. There are still a few tweaks that need to be made by @mmocny as well as assets to add. Also, this draft has not yet been reviewed by a tech writer. @malchata can you take a look tomorrow and make any comments or edits you think are necessary?
=> Add the initial smoothness metric draft

src/site/content/en/learn/design/macro-layouts/index.md, src/site/content/en/learn/design/media-queries/index.md
- Adds autoplaying videos on MQ module
=> [Learn Design] MQ Module Videos

src/site/content/en/blog/smoothness/index.md
- Some minor improvements and (link) additions.
=> [Towards an animation smoothness metric article] Some minor improvements and (link) additions

src/site/content/en/learn/pwa/conclusion/index.md, src/site/content/en/learn/pwa/index.md
Adding authors to the PWA course to match the other courses.
=> Adds author credit

src/site/content/en/blog/whats-new-pagespeed-insights/index.md
Fixes #6567 
Draft tech reviewed in Google docs by @mihajlija 
Fyi in case there are any additional changes we want to make @egsweeny. I'll aim to double check if there's any additional polish we want to make this evening.
=> Tooling updates post (PSI, /measure)

src/scss/_rollout.scss
=> fix search z-index

src/site/content/en/blog/fugu-status/index.md
- Remove stale list of APIs, replace with links to tracker.
=> [Fugu Status article] Remove stale list of APIs, replace with links to tracker

src/site/_data/site.js, src/site/_includes/partials/banner.njk, src/site/content/en/index.md
Reverts GoogleChrome/web.dev#6675
=> Revert "update"

src/site/content/en/blog/cds2021-updates/index.md
Fixes: #6667 
Here's the post, also let me know if I missed anything! 
I want to add the recap video before publishing, it goes live at 11am PT so I've left that as a todo.
cc @mihajlija
=> CDS links post

src/site/content/en/learn/design/media-queries/media-queries.assess.yml
Wrong answer was labeled as correct, this is a fix.
=> Fix design media queries test

src/site/content/en/blog/fugu-status/index.md
=> Fix typos in 'New capabilities status'.

src/site/_includes/partials/pagination-next.njk
=> fix(pagination): fix pagination bug that lets you go past the last page and that sends you to /blog/1 instead of /blog, fixes #6693

src/site/_includes/newsletter.njk, src/site/_includes/partials/newsletter.njk
- copy content of newsletter partial into newsletter layout
- delete newsletter partial
-
=> refactor(newsletter): simplify newsletter layout

src/site/_includes/components/Meta.js, src/site/_includes/partials/head.njk
=> Use the full url instead of fileSlug to find page.data

README.md
- I've added in one additional step to the README under the "Building the site" section which is not obvious to a lot of beginners. 
- I'm quite experienced with Git but I still ran all of the other commands without performing the above step. 
- I basically had to redo the steps again once I changed my current working directory.
Let me know I can make any improvements or if I've made any mistakes.
=> Added in a missing not so obvious step to the README

src/site/content/en/learn/pwa/foundations/index.md
https://web.dev/handbook/grammar/#lists
-
-
-
=> Correct formatting

src/site/content/en/learn/pwa/index.md
- Include myself as reviewer and provider of input for Learn PWA course
=> Include Sam Richard as providing input to Learn PWA

src/site/content/en/blog/introducing-aurora/index.md
This PR includes a mention of our new team members (Kara and Keen) to Aurora's introductory blog post.
=> Includes new team members to Aurora blog post

src/site/content/en/learn/pwa/getting-started/index.md
* Removes anthropomorphizing of the hypothetical note taking document.
* Fixes capitalization of PWA checklist. (This is not the actual name of the document at the end of the link.)
=> Minor Corrections

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml
- Adds Alexandra White to the authors YAML and JSON
=> Add alexandrawhite to authors

src/site/content/en/blog/file-handling/index.md
=> [File Handling article] Remove OT info

src/site/content/en/blog/image-component/index.md
=> Update index.md for italic text fixes

src/site/content/en/blog/embed-best-practices/index.md
- Included disclaimer on when to use suggested best practices  
=> Minor edit to Embed best practices

src/site/content/en/blog/window-controls-overlay/index.md
- Update article with new screenshots.
=> [Window Controls Overlay article] Update article with new screenshots

src/site/content/en/blog/bfcache/index.md
This PR updates the bfcache post to include new DevTools support. It also updates some outdated information to reflect current behavior.
=> Add DevTool support info to the bfcache post

src/site/content/en/learn/design/micro-layouts/index.md
Fixes #6765
- remove one backtick under "Combining queries" in https://web.dev/learn/design/micro-layouts/
=> remove extra ` backtick

src/component-library/compare/compare.njk, src/component-library/compare/variants/columns/columns.njk, src/scss/blocks/_compare.scss, src/scss/blocks/_prose.scss, src/site/_includes/components/Compare.js, src/site/_includes/components/CompareCaption.js
This sets the compare shortcodes to use the right markup 👍
=> Adjust the compare shortcodes and design system patterns

src/site/content/en/patterns/index.md
=> Fix spelling mistake in "optimize"

src/site/content/en/media/media-frameworks/index.md
- fixes a small typo tho -> to
=> fix(typo): fixing a small typo

src/site/content/en/blog/compat2021/index.md
Fixes #6797 by updating the screenshot and adding a caption to make it clear that it is a screengrab rather than live data, so may be out of date.
=> Updating screenshot

src/site/content/en/learn/css/backgrounds/index.md
- Add Learn CSS Backgrounds module
- Update Kevin's photo
- Update theme and height of Codepen components in Learn CSS Backgrounds module
Appended changes to  #6802 by @una
=> Add LearnCSS Background Module

src/site/content/en/learn/css/backgrounds/backgrounds.assess.yml, src/site/content/en/learn/css/backgrounds/index.md
- Add missing ':' prior to repeating background example in index.md file associated with Learn CSS Backgrounds module
- Fix space formatting of Think-and-check question associated with LearnCSSBackground module (enabling it to render as intended)
Changes to be appended to #6802
=> Update LearnCSS Background Module

src/site/content/en/blog/devices-introduction/index.md
@agektmr fyi: to double check that the WebAuthn codelab URL I used is the right one.
@beaufortfrancois fyi
=> Updated WebAuthn codelab link

src/site/_data/authorsData.json, src/site/_data/courses/css/toc.yml, src/site/_data/i18n/authors.yml, src/site/content/en/learn/css/backgrounds/backgrounds.assess.yml, src/site/content/en/learn/css/backgrounds/index.md, src/site/content/en/learn/css/conclusion/index.md
=> Add Learn CSS Backgrounds module

src/lib/actions.js, src/lib/components/LighthouseViewer/index.js, src/lib/components/UrlChooserContainer/index.js, src/site/content/en/measure/index.njk
This PR:
+ Adds AuditedOn and View Report fields back to /measure report
+ Fixes some inconsistency in LH error handling
=> Add link to LH Viewer

src/site/content/en/learn/design/internationalization/index.md
Change English to Japanese
- Changes 'English' to 'Japanese'
=> Fix typo in learn/design/internationalization

src/site/content/en/blog/svgcode/index.md
- Add the article.
**Merge this only _after_ the video has been released.**
Fixes https://github.com/GoogleChrome/web.dev/issues/6833.
=> Add SVGcode article

src/site/_data/i18n/footer.yml, src/site/_includes/partials/footer.njk, src/site/_includes/partials/site-footer.njk
Adds dcc to footer and changes the WebFu link to point directly.
cc @rachelandrew 
=> Update links in the footer

src/site/_includes/partials/header-course.njk
=> Replace logo with text for smaller viewports

src/site/_includes/partials/item.njk, src/site/_includes/partials/post.njk
Fixes #6474
- Set `linkify` to `false` for `md` filter used on titles.
-
-
=> fix(titles): urls in titles are not linkified, fixes #6474

src/component-library/stats/stats.json, src/scss/blocks/_prose.scss, src/scss/blocks/_stats.scss, src/scss/next.scss
=> Make w-stats extend the new stats component

src/component-library/tables/variants/misc-content-examples/misc-content-examples.json, src/component-library/tables/variants/misc-content-examples/misc-content-examples.njk, src/scss/blocks/_table-wrapper.scss, src/scss/next.scss, src/scss/pages/_design-system.scss, src/scss/utilities/_scrollbar.scss
Fixes #6872 
Fixes #4635
Fixes #6700
=> Table styles reverted to old style

src/scss/blocks/_site-footer.scss, src/scss/next.scss, src/scss/pages/_about.scss
=> Clean out :link selectors and remove from global CSS

src/site/content/en/handbook/word-list/index.md
- adding service workers to the work list so that is consistently used.
-
-
=> add service workers to work list

src/site/content/en/learn/css/typography/index.md, src/site/content/en/learn/css/typography/typography.assess.yml
=> LearnCSS: Text & Typography

src/site/_data/courses/css/toc.yml
- Add Typography to TOC for Learn Course
=> Add Typography to Learn CSS TOC

src/site/_data/authorsData.json
=> updating ajara's author photo

src/site/_includes/partials/offline.njk, src/site/content/en/offline.md, src/site/content/es/offline.md, src/site/content/ja/offline.md, src/site/content/ko/offline.md, src/site/content/pl/offline.md, src/site/content/pt/offline.md, src/site/content/ru/offline.md, src/site/content/zh/offline.md
=> Rollout the design system on offline pages

src/component-library/callout/callout.json, src/component-library/callout/callout.md, src/component-library/callout/callout.njk, src/scss/blocks/_callout.scss, src/scss/next.scss, src/site/_includes/components/CodelabsCallout.js
=> Add callout component

src/site/_data/i18n/authors.yml
- Add Maurizio Paradisi author for GEDI Case Study
=> Add Maurizio Paradisi author data for GEDI Case Study

src/site/_data/authorsData.json
- Add Maurizio Paradisi author image including Linkedin profile for GEDI Case Study
=> Add Maurizio Paradisi author image

src/site/content/en/blog/building-a-tabs-component/index.md
Appends new user submission to the Tabs post
=> GUI Challenges patch: adds community remix to Tabs

src/site/content/en/learn/design/internationalization/index.md
=> Fix factual error

src/site/content/en/blog/compute-pressure/index.md, src/site/content/en/blog/handwriting-recognition/index.md, src/site/content/en/blog/monitor-total-page-memory-usage/index.md, src/site/content/en/blog/storage-foundation/index.md, src/site/content/en/blog/window-controls-overlay/index.md
- Update some outdate origin trial data.
- Some `prettier` drive-by fixes.
=> Update some outdated origin trial data

src/site/content/en/lighthouse-performance/mainthread-work-breakdown/index.md
-change from "to to" to "to" in a sentence
-
-
=> typo correction

src/site/content/en/learn/pwa/app-design/index.md, src/site/content/en/learn/pwa/assets-and-data/index.md
Fixes #6482 adds the next two modules. 
@jpmedley I've assigned this to you for review, this was due to go out this week however I've only just got the reviews in from the team working on it. Let me know what you can do.
=> Learn PWA modules 4 and 5

src/styles/components/_youtube.scss
Fixes #6907
- Set `text-align: initial;` to `lite-youtube` element.
-
-
=> fix(youtube): fix youtube video alignment, fixes #6907

src/scss/blocks/_carousel.scss, src/scss/utilities/_scrollbar.scss, src/site/_includes/partials/course-cards-next.njk
=> Scrollbar & carousel styles update 

src/site/content/en/learn/forms/address/index.md
=> Wrong attribut used in Learn content

src/site/content/en/learn/pwa/caching/index.md, src/site/content/en/learn/pwa/service-workers/index.md
Fixes: #6484 
Fixes: #6485 
Two more modules for this course. Reviewer: @jpmedley 
@tropicadri @firtman can one of you check that the code highlighting is picking the correct lines in the Caching module. Thanks!
=> Adds two more Learn PWA modules

src/site/content/en/blog/file-handling/index.md
- More robust feature detection.
=> [File Handling article] More robust feature detection

src/site/content/en/blog/community-highlight-bramus/index.md
Remove character zero-width space (\u200b).
Fixes #6968
=> Fix the link to Bramus's twitter

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/ui-fund/index.md
Adds the day 6 article and Nicole as author.
=> Adds UI Fund article

src/site/content/en/blog/excalidraw-and-fugu/index.md
To understand the problem, look at this image.
=> Fix line breaks in I/O article.

src/scss/blocks/_prose.scss
=> Account for stacked headings in prose rules

src/scss/blocks/_fab.scss, src/scss/blocks/_prose.scss, src/scss/blocks/_table-wrapper.scss, src/scss/mixins/_button-base-styles.scss
Fixes #6930
Fixes #6931
Fixes #6933
=> Quick css fixes

src/site/content/en/progressive-web-apps/using-a-pwa-in-your-android-app/index.md
=> Add missing comma.

src/site/content/en/blog/handwriting-recognition/index.md
=> [Handwriting Recognition article] Add spec draft link

src/site/content/en/blog/fugu-status/index.md
- Re-add not shipping is OK.
CC: @beverloo
=> [Fugu Status article] Re-add not shipping is OK

src/site/content/en/blog/building-a-toast-component/index.md
=> New Post: GUI Challenges - Building a toast component

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/file-handling/index.md, src/site/content/en/blog/kapwing/index.md
Fixes #6805
-  Create Kapwing case study based on draft
Preview the case study: https://deploy-preview-6962--web-dev-staging.netlify.app/kapwing/
=> [Case study] Kapwing

src/site/content/en/blog/file-system-access/index.md
- Add note about parallel processing.
=> [File System Access article] Add note about parallel processing

src/lib/components/UrlChooser/index.js
Fixes #6813 
See that issue for full context.
- `http` -> `https`, hopefully not too earth-shattering 🙇
=> Update UrlChooser component to prefer https as default

src/site/content/en/blog/file-system-access/index.md
=> Tweak wording of await description

src/site/content/en/progressive-web-apps/add-manifest/index.md
Fixes #6990 
- fixed a very minor typo
=> Corrected the typo for issue #6990

src/site/content/en/blog/community-highlight-chen-hui-jing/index.md
Fixes: #6901 
Day 10 Designcember interview.
=> Community Highlight Chen Hui Jing

src/scss/blocks/_table-wrapper.scss, src/scss/compositions/_breakout.scss, src/scss/next.scss, src/scss/pages/_design-system.scss, src/site/_includes/design-system.njk, src/site/content/en/design-system/colors.njk, src/site/content/en/design-system/components.njk, src/site/content/en/design-system/css-compositions.njk, src/site/content/en/design-system/spacing.njk, src/site/content/en/design-system/typography.njk, src/site/content/en/design-system/welcome.md
A new composition to allow elements to break out of their parent's bounds
=> Breakout composition

src/site/content/en/learn/css/overflow/overflow.assess.yml
=> Learn CSS Overflow - Assessment patch

src/site/content/en/blog/building-a-toast-component/index.md
=> GUI Challenges - Toasts - add 2 remix's

src/site/content/en/learn/css/backgrounds/index.md
Fixes: #7000 by updating the link.
=> fixing a link

src/site/content/en/blog/designcember-calculator/index.md
=> Maintenance: fix broken links

src/site/content/en/blog/declarative-link-capturing/index.md, src/site/content/en/blog/handwriting-recognition/index.md, src/site/content/en/blog/pwa-url-handler/index.md, src/site/content/en/blog/storage-foundation/index.md, src/site/content/en/blog/user-preference-media-features-headers/index.md, src/site/content/en/blog/window-controls-overlay/index.md
=> Correct a repeated grammer mistake.

src/site/content/en/handbook/case-study-guidelines/index.md
- Updates case study guidance to add a requirement around case study deliverables.
=> Updates case study guidelines

src/site/content/en/blog/terra-dark-mode/index.md
- Improves code formatting for the JS snippet the Terra Dark Mode blogpost.
=> Improves code formatting for JS snippet

src/site/content/en/blog/state-of-css-2021/index.md
Updated after https://github.com/StateOfJS/StateOfCSS-homepage/issues/10.
=> Update CSS Grid screenshot for State of CSS 2021 post

src/site/content/en/blog/file-system-access/index.md
- Add `rename`, `move`, and `remove`.
=> [File System Access article] Add `rename`, `move`, and `remove`

src/site/content/en/blog/economic-times-cwv/index.md
- Fixes a typo in the description for the Economic Times case study.
=> Fixes a typo in the description for the economic times case study.

src/site/content/en/blog/handwriting-recognition/index.md
=> Update origin trial information.

src/site/content/en/learn/design/accessibility/index.md, src/site/content/en/learn/design/media-features/index.md, src/site/content/en/learn/design/screen-configurations/index.md, src/site/content/en/learn/design/ui-patterns/index.md
To merge Dec 23, makes the Learn Design content live.
=> [Designcember] removes placeholder true to make content live

src/site/content/en/blog/svgcode/index.md
Add a link to the app more prominently.
=> [SVGcode article] Add quick link

src/site/content/en/blog/designcember-calculator/index.md
- Adds the post.
- This was previously LGTM'ed in #7002.
=> Add Designcember Fugu post

src/site/content/en/blog/community-highlight-lynn-fisher/index.md
=> Adds Dec 30 post

src/site/_data/courses/design/toc.yml, src/site/content/en/learn/design/interaction/index.md, src/site/content/en/learn/design/interaction/interaction.assess.yml
Adds missing "Interaction" module to Learn Responsive Design
=> [Learn Design] Interaction module

src/site/content/en/learn/css/backgrounds/backgrounds.assess.yml, src/site/content/en/learn/design/intro/index.md, src/site/content/en/learn/design/intro/intro.assess.yml
Fixes: #6823 
Fixes: #7085 
Fixes: #7079
=> small fixes to Learn courses to merge after the code freeze

src/site/content/en/blog/coop-coep/index.md, src/site/content/en/secure/cross-origin-isolation-guide/index.md
Updates around `COEP: credentialless`
cc: @lutzvahl
=> Updates around `COEP: credentialless`

src/site/content/en/learn/pwa/assets-and-data/index.md
Changes proposed in this pull request: Fix spelling of "typicaly" to "typically"
When you're ready to submit your PR, don't forget to add the $-presubmit label.
=> fix: fix typo

src/site/content/en/blog/vitals-business-impact/index.md
Update list of RUM tools and minor text changes on supporting paragraph.
- Update list of 3P RUM providers (image and text)
- Minor text edits to supporting paragraph of RUM tools
Fixes #7121.
=> Update index.md of web.dev/vitals-business-impact

src/site/content/en/blog/pwas-on-oculus-2/index.md
=> [Oculus PWA article] Copy non-breaking spaces

src/site/content/en/blog/streams/index.md
=> [Streams article] Add `AbortSignal` info

src/site/content/en/blog/pwas-on-oculus-2/index.md
=> [Oculus article] Add photo credits

src/site/content/en/blog/hid/index.md
@beaufortfrancois 
After you knocked off, I noticed that your update forgot to change the year on the `updated` meta element. As long as I was here, I fixed the article on 'HID'.
=> Corrections to HID article

src/site/content/en/blog/building-a-toast-component/index.md
=> Fix broken link

src/site/content/en/blog/emscripten-embedding-js-snippets/index.md
=> Blog post: Embedding JavaScript snippets in C++

src/site/content/en/handbook/web-dev-components/index.md
Fixes #7171 
- Update broken links in handbook
=> Handbook link updates

src/site/content/en/blog/file-system-access/index.md
- Document drag drop loop issue.
=> [File System Access article] Document drag drop loop issue

src/site/content/en/lighthouse-performance/lighthouse-max-potential-fid/index.md
Just saw TBT mentioned in a Max FID article so here's a PR to correct it.
=> Update wrong mention of TBT in Max FID article

src/site/content/en/blog/building-a-theme-switch-component/index.md
=> New Post: GUI Challenges - Theme Switch

src/site/content/en/blog/variable-fonts/index.md
Fixes #7158
- Improve fallback pattern.
=> [Variable Fonts article] Improve fallback pattern

src/site/content/en/blog/optimize-vitals-lighthouse/index.md
- Adds paragraph + Lighthouse audit reference on not lazy-loading the LCP image (links to article)
- Adds paragraph + Lighthouse audit reference on deferring offscreen images
=> [Optimize CWV] Add note on lazy-loading and LCP

src/site/_includes/partials/head.njk
=> Add resource hint that preconnects to imgix

src/site/content/en/fast/cookie-notice-best-practices/index.md
- Fixed the typo in docs of cookie-notice-best-practices
=> Update index.md of cookie-notice-best-practices for typo error

src/site/content/en/blog/file-system-access/index.md
- Syntax issue.
- Reformatting.
=> [File System Access article] Fix syntax issue

src/scss/next.scss, src/site/_includes/components/Blockquote.js, src/site/content/en/handbook/web-dev-components/index.md
Local preview at this url: http://localhost:8080/handbook/web-dev-components/#block-quotes
=> Add pullquote option to blockquote component

src/site/content/en/blog/building-a-theme-switch-component/index.md
Adds community submitted remix's and versions to the end of the post 👍🏻
=> GUI Challenges - theme switch patch #1

src/site/content/en/fast/using-lighthouse-bot-to-set-a-performance-budget/index.md
- Replaced the existing command to have copy-to-clipboard functionality and keep all commands consistent across the entire document.
=> Update index.md for adding copy-to-clipboard functionality on a command

src/component-library/figure/variants/screenshot/screenshot.json, src/component-library/figure/variants/screenshot/screenshot.njk, src/scss/blocks/_figure.scss, src/site/content/en/blog/test-post/index.md
=> Add screenshot image

src/site/content/en/blog/window-controls-overlay/index.md
@tomayac This just [got its LGTMs](https://chromestatus.com/feature/5741247866077184#:~:text=96-,Prepare%20to%20ship,-Chrome%20for%20desktop) for shipping.
=> Update shipping version of Window Controls Overlay.

redirects.yaml, src/site/content/en/blog/browser-fs-access/index.md, src/site/content/en/blog/file-handling/index.md, src/site/content/en/lighthouse-pwa/installable-manifest/index.md, src/site/content/es/blog/file-handling/index.md, src/site/content/ko/blog/file-handling/index.md, src/site/content/pt/blog/browser-fs-access/index.md, src/site/content/zh/blog/file-handling/index.md
=> Update link to installable.

src/lib/components/Snackbar/index.js, src/lib/components/SnackbarContainer/index.js, src/scss/mixins/_button-base-styles.scss, src/scss/next.scss, src/scss/web-components/_web-snackbar.scss
FYI: I've forced the snackbar to show for PR reviews but it needs to be reverted before merging
Fixes: #6747
=> New snackbar styles

src/site/content/en/learn/css/backgrounds/backgrounds.assess.yml, src/site/content/en/learn/css/backgrounds/index.md
Fixes #7175 
I think our example conflated two things so I've made it clearly about order of the values.
=> fix example of position

src/site/content/en/blog/webassembly-feature-detection/index.md
=> Fixup: Add missing bundle command

src/site/content/en/blog/storage-foundation/index.md
=> [Storage Foundation article] Add abandoned message

src/site/content/en/blog/drag-and-drop/index.md
=> [Drag and Drop article] Fix formatting

src/site/content/en/blog/porting-gphoto2-to-the-web/index.md
=> Update date on part 2 USB blogpost

src/site/content/en/blog/web-platform-01-2022/index.md
=> add Web Platform January post
