GoogleChrome/web.dev

src/site/content/en/secure/cross-origin-isolation-guide/index.md

- The link of `Analyze the impact of cross-origin isolation` in https://web.dev/cross-origin-isolation-guide/ is 404 now because it's a typo with leading colon. Instead, it should use `#` to be an anchor.

Fix analysis anchor in cross origin isolation guide

---

src/site/content/en/blog/streams/index.md

Fix SyntaxError in example of "Piping a readable stream to a writable stream"
Fixes #4915

Fix SyntaxError in example of steams

---

src/site/content/en/secure/cross-origin-resource-sharing/index.md

Adds a link to the MDN information on preflighted requests to https://web.dev/cross-origin-resource-sharing/#preflight-requests-for-complex-http-calls
cc: @mihajlija @agektmr

adding link to MDN.

---

src/site/content/en/fast/lazy-loading-video/index.md

Originally discussed here: https://github.com/GoogleChrome/web.dev/pull/4859

Fix info on video lazy loading

---

src/site/content/en/blog/optimize-fid/index.md

Fixes #4930 
- Update "Use a web worker" link href to `#use-a-web-worker` to match anchor tag name.

Match link href with anchor name on "Optimize First Input Delay" page

---

src/site/content/en/handbook/content-checklist/index.md

- Update link to [GDDSG word list](https://developers.google.com/style/word-list)
Screenshot from https://web.dev/handbook/content-checklist/#insensitive-words:

Update link in content review checklists page

---

tools/linting/no-repeat-punctuation.js

This allows strikethrough (denoted by "~~").
We still trigger on "no-duplicate-headings-in-section", but a number of blog posts repeat headings. Can we turn this one off—or perhaps limit it to only top-level headings? @robdodson
"fixes" part of #4820.

allow strikethrough

---

src/site/_data/authorsData.json
src/site/content/en/blog/lowes/index.md

This adds the Lowe's site speed case study.
As the content was approved I have not made major changes other than to copy edit. I did break up the big paragraph under the impact heading as it was a bit of a wall of words.
The line at the top with the authors, I have left as is. I'm assuming we don't add each as an author being external?
cc: @mihajlija @garimamimani

Adding Lowe's case study

---

src/site/content/en/blog/variable-fonts/index.md

The author most probably accidentally missed the negation. If a website uses only a single font such as Roboto Regular, they would most likely not see any meaningful gain in font file size  if they switch to a variable font with many axes.
- Correct the performance gain explanation when using variable font against only a single style font

Correct the performance gain explanation

---

src/site/content/en/blog/media-session/index.md

This PR is about adding a screenshot featuring the now playing widget that is now completely supported by Chrome in macOS. See https://bugs.chromium.org/p/chromium/issues/detail?id=1112756

Add now playing widget screenshot to media session sample

---

src/site/content/en/blog/camera-pan-tilt-zoom/index.md

This PR is about updating the "Control camera pan, tilt, and zoom" blog post with a note on Chromium using the absolute UVC controls, not the relative ones. This will hopefully reduce developer confusion as seen in https://github.com/w3c/mediacapture-image/issues/263#issuecomment-804053608.

Warn developers about absolute/relative UVC controls

---

src/lib/components/BaseResponseElement/index.js
src/site/_drafts/_template-self-assessment/index.md
src/site/_includes/components/Assessment.js
src/site/_includes/course.njk
src/site/content/en/accessible/control-focus-with-tabindex/index.md
src/site/content/en/accessible/labels-and-text-alternatives/index.md
src/site/content/en/accessible/use-semantic-html/index.md
src/site/content/en/handbook/self-assessment-components/index.md
src/site/content/en/secure/same-origin-policy/index.md
types/site/_includes/components/Assessment/TargetAssessment.d.ts
types/site/_includes/components/Assessment/TargetAssessmentOption.d.ts
types/site/_includes/components/Assessment/TargetAssessmentQuestion.d.ts

Fixes #4973
- Changes `Assessment` widget so it no longer needs a `page` argument.
- Adds types for the `*.assess.yml` file
- Fixes a bug where multiple choice responses were attempting to bind to `null`.
- Adds the `content.js` entrypoint to `course.njk` so it can use our fancy self assessment web component

Fix broken Assessment shortcode

---

src/lib/actions.js

When opening the drawer the overflow should go on the body

set overflow hidden on body, not html

---

src/site/content/en/blog/generic-sensor/index.md

Fixes #4966
Release estimation for Gravity Sensor API is
chrome 91. [1]
[1] https://chromestatus.com/features/5384099747332096

Gravity sensor: Adding release estimation date

---

src/site/content/en/blog/media-session/index.md

This PR specifies the chrome version that supports properly now playing widget in the media session article.
Fixes https://github.com/GoogleChrome/web.dev/pull/4965#issuecomment-811106455

Specify Chrome version for now playing widget

---

src/site/content/en/blog/floc/index.md

- Consistently spell ad-tech with a dash. 
- Many small things (sorry, just random fixes really).
- Code improvements.
Not part of the PR since I don't have access to the source file:
For https://web-dev.imgix.net/image/80mq7dk16vVEg8BBhsVe42n6zn82/P3F4PUB0jrRcU0vC4XSM.png?w=1600:
`s/on the their/on their` and `s/adtech/ad-tech` throughout

[FLoC article] A lot of small suggestions and fixes

---

src/site/_includes/partials/analytics.njk

Anonymizes users IPs in analytics per [the API reference](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#anonymizeIp).

Anonymize IPs in google analytics.

---

src/site/_filters/navigation.js
src/site/_includes/partials/navigation-drawer-course.njk
src/styles/components/_course-toc.scss
src/styles/components/_drawer-course.scss

- Makes the courses show correct titles for pages in the navigation drawer
- Sets `overscroll-behavior: contain` on the drawer and toc so they don't accidentally scroll the page

Show live links in course and fix overscroll

---

src/site/content/en/progressive-web-apps/manifest-updates/index.md

Icons and name can from the manifest can no longer be updated for PWAs, on mobile or desktop. 
This PR updates the corresponding article to reflect that.

updates to manifest updates

---

src/site/content/en/blog/tabbed-application-mode/index.md

Fixes #5032
- Make the warning more explicit and link to `display_override`.

[Tabbed Application Mode article] Make the warning more explicit and link to display_override

---

.eleventy.js
package-lock.json
package.json
src/site/_plugins/markdown.js
src/site/content/en/handbook/web-dev-components/index.md
src/styles/generic/_lists.scss

Fixes #4929, fixes #1535
- Adds markdown-it-deflist 
- Tidies up markdown config and puts it into its own file, similar to what we do for d.c.c. I'm not sure why but once I did this I noticed it started uppercasing all of the w-heading-link slugs. That's actually the default behavior for `slugify` but on the live site they're always lowercased. So I passed an explicit argument for it to lowercase them 🤷‍♂️
- Adds styles for dt and dd that match d.c.c.

Add markdown definition list support.

---

src/site/_collections/authors.js
src/site/_collections/blog-posts-descending.js
src/site/_collections/tags.js
src/site/_data/i18n/common.yml
src/site/_includes/codelab.njk
src/site/_includes/components/AuthorsDate.js
src/site/_includes/components/BaseCard.js
src/site/_includes/partials/post.njk
src/site/_utils/sort-by-date.js
src/site/_utils/sort-by-updated.js
src/styles/components/_author.scss
types/eleventy/collection-item.d.ts

Fixes #2283
- Prefer sorting of posts in author and tag collections by their `updated` date rather than their posted date.
- Display the updated date on cards.
- Add the term "Updated" to `i18n.common`.

feat(updated): sort posts by updated and show updated date, fixes #2283

---

src/site/content/en/blog/why-coop-coep/index.md

Updates "Why you need "cross-origin isolated" for powerful features" to incorporate the story about timer resolution.

Incorporate timer story to why-coop-coep

---

src/site/content/en/developer-satisfaction/index.md

This PR moves the DevSat Dashboard to top-level content folder and removes the `draft` tag. The post will still not be anywhere in site's navigation, only accessible directly via the link.

Move DevSat post

---

src/site/content/en/blog/fugu-status/index.md
src/site/content/en/blog/goibibo/index.md
src/site/content/en/blog/payment-and-address-form-best-practices/index.md
src/site/content/en/blog/sign-in-form-best-practices/index.md
src/site/content/en/blog/sign-up-form-best-practices/index.md
src/site/content/en/blog/sms-otp-form/index.md
src/site/content/en/blog/web-otp/index.md

This PR updates the API name from "Web OTP" to "WebOTP" to be consistent with other APIs such as WebRTC, WebID and WebAuthn.

Rename Web OTP to WebOTP

---

src/lib/components/Search/_styles.scss
src/lib/components/Search/index.js
src/styles/components/_header-course.scss
src/styles/components/_header-default.scss
src/styles/components/_web-header.scss

Fixes #5043, fixes #5067, fixes #5071, fixes #4687 (maybe 😅)
In a previous PR I changed the header from being position: fixed to position: sticky. This caused the page to scroll because we call `scrollIntoView()` on search results. We do this because focus never leaves the search input, so when you use the arrow keys to go down it needs to scroll into view any results that have overflowed.
The fix is to make the header position: fixed only on the pages that actually use the search bar. For the courses header we can leave it position: sticky, which is nice because we don't need to ship a third style to add top margin to the courses app-bar.
I also set the text input to have a font-size of `1rem` to see if it fixes #4687. The font-size was already set to 16px so I don't know if this will …

Fix broken search.

---

src/site/content/en/lighthouse-performance/font-display/index.md

Add as="font" to avoid Chrome warning "<link rel=preload> must have a valid `as` value"
- 
- 
-

Added font preload content type

---

src/site/content/en/fast/browser-level-image-lazy-loading/index.md

Fixes #4273 
- add into the article the situation described by https://github.com/GoogleChrome/web.dev/issues/4273#issuecomment-817172962 when images without width/height may not lazy-load

Describe situation in which images without width/height are not lazy-loaded (#4273)

---

src/site/content/en/blog/cors-rfc1918-feedback/index.md

Updates the CORS-RFC1918 feedback article to point to updated news over on the developer.chrome.com blog. Also notifies readers that the specification's name has changed since the post was published.

Add pointer to Private Network Access update.

---

src/site/content/en/blog/web-otp-iframe/index.md

New article about WebOTP API to support receiving an SMS OTP from within an iframe.
cc: @yi-gu

New article: WebOTP iframe support

---

src/lib/components/LighthouseScoresAudits/index.js

... as otherwise the audit disappears and need to be run again if users hits back button.
Fixes #4946

Make lighthouse guides open in a new window

---

src/site/content/en/learn/css/box-model/index.md
src/site/content/en/learn/css/color/index.md
src/site/content/en/learn/css/flexbox/index.md
src/site/content/en/learn/css/inheritance/index.md
src/site/content/en/learn/css/logical-properties/index.md
src/site/content/en/learn/css/selectors/index.md
src/site/content/en/learn/css/specificity/index.md

- Untag course pages. These were appearing in the /tags/ section of the site but we don't want that. Instead we might add a banner to /tags/css promoting the course, but that'd be a separate PR.

Remove course tags.

---

src/site/content/en/vitals/index.md

This PR fixes an occurrence missed in https://github.com/GoogleChrome/web.dev/pull/4902.

Clarify that the thresholds are inclusive

---

package.json

Fixes #3605, unblocks #5008
`eleventy --watch` will run eleventy, which means if you have an npm script (like our dev script) where you want to 1st run eleventy, and then watch for changes, you can't really do it without running eleventy twice ([issue](https://github.com/11ty/eleventy/issues/1336)).
The solution is to write our own `chokidar` file watcher (which is what eleventy is using under the hood) to watch the `src/site` directory and re-run eleventy ourselves. Importantly, `chokidar` does **not** run your command when you first call the npm script.
- Replace `eleventy --watch` with our own chokidar watcher.

Run eleventy once before starting the server, then watch for changes.

---

src/site/content/en/blog/browser-fs-access/index.md

No issue created yet given the low complexity of the changes. But can create one if you want me to.
- The first link, <https://caniuse.com/#feat=file-system-access-api>, was broken, linking to an empty page basically
- The second link, <https://caniuse.com/?search=file%20system%20access%20api>, was linking to a search rather than the single feature (which might lead to different results in the future)
- Therefore exchange both links with the correct one, <https://caniuse.com/native-filesystem-api>
- (The URL is still derived from the previous name of the File System Access API, because https://github.com/Fyrd/caniuse/pull/5622#issuecomment-701910863)

Fix and harmonize links to caniuse for browser-fs-access

---

src/lib/components/ProgressBar/_styles.scss

- Changes the /measure progress bar to use transform instead of animating left, right which could be causing layout shift.

Fix progress bar cls

---

src/lib/components/CourseLinks/index.js
src/lib/pages/course.js
src/site/_includes/partials/navigation-drawer-course.njk
src/styles/components/_drawer-course.scss
src/styles/components/_web-navigation-drawer.scss

Fixes #5210
- Fixes an issue where the course links weren't scrolling if the viewport was shorter. I think this is a slight bug we accidentally introduced when we switched to the custom element as there was a `drawer-course__links` class which handled this previously (and does again now).
- Renames `DrawerCourse` -> `CourseLinks`. I did this because we have a `<web-navigation-drawer>` custom element as the parent and it was a bit confusing also seeing a `<web-drawer-course>` inside of it. This element only deals with tracking the visited state of the links so I think the naming may be ok.
- Fixes the visual states for active and completed links.

Fix drawer overscroll and add link states.

---

src/site/content/en/blog/bfcache/index.md

This PR updates the bfcache post to reflect that bfcache data is now in CrUX (it was added in Dec, 2020).

Update to reflect current bfcache in CrUX state

---

tools/percy/.percy.conf.yml

Percy often flakes on this test of the /live page because it has an autoplaying video inline. So this just sets videos to be visibility: hidden;

Fix flaky percy test

---

src/site/content/en/blog/mediastreamtrack-insertable-media-processing/index.md

R: @tomayac 
This adds some missing frontmatter used by https://github.com/GoogleChrome/web.dev/blob/36cfd75e305a614c7dee27c18eb8dc26549e1a51/src/site/_includes/content/origin-trial-register.njk#L1
Without it, the link at https://web.dev/webtransport/#register-for-ot is broken.

Add OT frontmatter

---

src/site/_includes/components/Meta.js
src/site/content/en/learn/css/css.11tydata.js

Fixes #5260, fixes #5255
- Exclude course content from collections. They'll no longer show up on authors or tags pages. If folks want they could remove the `eleventyExcludeFromCollections` property in their course to allow them to show up.

hide course tags and authors

---

src/site/_collections/authors.js
src/site/_collections/tags.js
src/site/content/en/learn/css/css.11tydata.js
types/eleventy/collection-item.d.ts

It looks like https://github.com/GoogleChrome/web.dev/commit/1f026fe0fe257883756a1cf31752b7972b0cbcde was a little too aggressive and was causing course titles to not appear in the course sidebar. It also means they would have probably been hard to add to our algolia index. So instead of excluding them from all collections I've added flags to specifically exclude content from the tags and authors collections.

Only exclude course content from authors and tags pages.

---

src/styles/pages/_course.scss

Fixes #5253 
@una @argyleink @andy-piccalilli can I get y'alls thoughts on these changes? I didn't bump the text down to 0.9rem because then it would be smaller than the body copy below it (which is 18px). But I can bump it down if you think it would look better.

Fix course description

---

src/site/_includes/partials/course-app-bar.njk
src/styles/components/_app-bar.scss

Fixes #5212 
Adds the site logo to the app bar

Add logo to courses

---

src/site/content/en/learn/css/box-model/index.md
src/site/content/en/learn/css/color/index.md
src/site/content/en/learn/css/flexbox/index.md
src/site/content/en/learn/css/gradients/index.md
src/site/content/en/learn/css/grid/index.md
src/site/content/en/learn/css/inheritance/index.md
src/site/content/en/learn/css/layout/index.md
src/site/content/en/learn/css/logical-properties/index.md
src/site/content/en/learn/css/pseudo-classes/index.md
src/site/content/en/learn/css/pseudo-elements/index.md
src/site/content/en/learn/css/selectors/index.md
src/site/content/en/learn/css/shadows/index.md
src/site/content/en/learn/css/sizing/index.md
src/site/content/en/learn/css/spacing/index.md
src/site/content/en/learn/css/specificity/index.md
src/site/content/en/learn/css/the-cascade/index.md
src/site/content/en/learn/css/z-index/index.md

Going over the already merged Learn CSS modules:
- adds missing descriptions
- removes duplicate headings
- adds the podcast episodes

Adds podcasts, descriptions, and tidies things up

---

src/site/_data/i18n/toc.yml
src/site/_includes/partials/toc-inner.njk
src/site/_includes/partials/toc-side.njk
src/styles/components/_course-toc.scss

Fixes #5268, Fixes 5214
- Adds a grayish background to the inner toc button
- Rewords toc label to "On this page"
- Hides the side toc if there are no headings

Add background color and fix toc without contents.

---

src/site/_includes/course.njk
src/styles/components/_app-bar.scss

Fixes #5213
- Adds a little inline script to watch a sentinel element and apply a `[data-stuck]` state to our app-bar so we can style it when it's doing its position: sticky thing.

add stuck state to course-app-bar

---

src/styles/components/_app-bar.scss
src/styles/components/_course-pagination.scss
src/styles/pages/_course.scss

Fixes #5295
- Drops the middle breadcrumb on smaller screens and adjusts breadcrumb font-size down to match mocks.
- Fixes the colors in course pagination to match the mocks.

Fix app bar squish and pagination colors.

---

src/site/content/es/es.11tydata.js

The translation banner uses outdated canonicalUrl property. Let's disable it until we find a good replacement for it.

Disable translation banner

---

src/site/_data/courses/css/meta.yml
src/site/_includes/partials/navigation-drawer-course.njk

Fixes #5306
Only show the 'NEW' badge if content was launched after the course's initial publish date.

Don't apply 'new' badge to course launch content.

---

src/site/content/en/blog/text-fragments/index.md

- Add info about programmatic link generation.
- Add info about  obtaining text fragment links for analytics. 
- Remove info about past origin trial.

[Text Fragment article] Add info about link generation and analytics, remove OT info

---

src/site/content/en/blog/async-clipboard/index.md

- Safari requires async work to be done differently.

[Async Clipboard article] Document Safari's special way

---

src/site/content/en/blog/web-otp/index.md

Incorporate cross-origin iframe support in the WebOTP canonical article.

Incorporate cross-origin iframe support in WebOTP

---

src/lib/components/NavigationDrawer/index.js

Fixes #5314 
- Remove touch handlers for swipe actions on the drawer. These were causing issue in Safari and it's not a very critical feature.

Disable drawer touch events

---

firebase-config.js

We have been experiencing minimal violations on [CSP frontend](https://csp.googleplex.com/#!/?query_mintimestamp=1619150400000&query_maxtimestamp=1620657600000&query_product=webdev&query_collectortable=EXTERNAL&query_deduplication=ACTIONABLE&f_domain=web.dev&f_version=&f_effectivedirective=script-src-elem,base-uri,script-src&f_policytype=STRICT_DYNAMIC&f_policywithunsafeeval=false).  I also did a site crawl using puppeteer looking for any CSP violations on chrome and found none. With these results, I think it is safe to enforce the CSP.
Follow up to https://github.com/GoogleChrome/web.dev/pull/5008

Enforce CSP

---

src/lib/components/Header/index.js
src/styles/components/_app-bar.scss
src/styles/components/_header-course.scss

Fixes #5320 
- Makes the course header sticky on mobile.
- Temporarily disables moving focus to the header when the drawer closes.

Make course header sticky. Partial fix for focus bug.

---

src/site/content/en/blog/webtransport/index.md

As per https://twitter.com/yoursunny/status/1391140496131694596, there are some recent updates to the WebTransport specification that have made it into Chrome, and need to be reflected in the WebTransport origin trial post.
R: @yutakahirano and @vasilvv to confirm that these changes look good and that there isn't anything else recently implemented that should also be updated.

WebTransport OT interface updates

---

src/site/_collections/authors.js
src/site/_collections/tags.js
types/site/_collections/authors.d.ts
types/site/_collections/tags.d.ts

In this PR I refactor the authors and the tags collections to be easier to read and to look more a like (considering they basically are the same sort of data, just organized by different ways).
But importantly both collections now support a `date` (created on) and an `updated` (updated on) field, which will be used in future indexing endeavors...

refactor(collections): clean up logic for authors and tags

---

src/site/content/en/blog/browser-flags/index.md

- Add the article.
A follow-up PR will rewrite all `chrome://` URLs to `about://`.

Add Browser Flags article

---

src/site/_includes/partials/course-pagination.njk

Fixes #5395
- Fixes incorrect increment value for next page in course pagination
Before (on page 1):
https://web.dev/learn/css/box-model/
After (on page 1):
https://deploy-preview-5398--web-dev-staging.netlify.app/learn/css/box-model/

Fix incorrect pagination value for next page

---

src/lib/components/CourseLinks/index.js
src/site/_data/site.js

Analytics are hard :P
I think this should make reading the course progress easier. I don't think we're supposed to use the `value` field. Otherwise it tries to average all of the values together and we don't get useful data.

Improve learn css course tracking.

---

src/site/content/en/learn/css/pseudo-classes/index.md

Instead of nested `<kbd>` elements, close the `<kbd>` element. The nested elements were breaking the layout. 
Fixes #5430

Fix bug in pseudo-classes markdown.

---

src/site/content/en/blog/deprecating-excalidraw-electron/index.md
src/site/content/en/blog/display-override/index.md
src/site/content/en/blog/excalidraw-and-fugu/index.md
src/site/content/en/blog/file-handling/index.md
src/site/content/en/blog/load-faster-like-proxx/index.md
src/site/content/en/blog/mainline-mensware/index.md
src/site/content/en/blog/maskable-icon/index.md
src/site/content/en/blog/tabbed-application-mode/index.md
src/site/content/en/blog/url-protocol-handler/index.md
src/site/content/en/blog/window-controls-overlay/index.md
src/site/content/en/progressive-web-apps/customize-install/index.md
src/site/content/en/progressive-web-apps/install-criteria/index.md
src/site/content/en/progressive-web-apps/offline-fallback-page/index.md
src/site/content/en/react/add-manifest-react/index.md

This is per the [word list](https://web.dev/handbook/word-list/).

Make capitalization of 'web app manifest' match the handbook.

---

src/site/content/en/learn/css/specificity/index.md

- Adjust the heading so selector names order corresponds to the section content (keeping class and pseudo-class together seems helpful to the reader)
- Mention provide a reference to atttribute selectors in the discussion of specificity points

Mention and add reference to attribute selectors

---

src/site/content/en/blog/migrate-to-ua-ch/index.md

- Update the code example for `navigator.userAgentData.brands`
- Use `Array.prototype.includes()` because `Array.prototype.contains()` doesn't exist.
- Replace `filter().length > 0` with `some()` for brevity.

Fix JavaScript code sample for userAgentData.brands

---

src/site/content/en/blog/declarative-shadow-dom/index.md

This is a small update to the Declarative Shadow DOM article that adds the recommended polyfill-compatible solution for preventing FOUC, courtesy of @mfreed7.

Declarative Shadow DOM: FOUC avoidance update

---

src/site/content/en/learn/css/selectors/index.md

learn/css/selectors page:
- typo fix: `<section`> to `<section>`
- add missing space after a comma

Typo fixes

---

src/site/content/en/blog/async-clipboard/index.md

The `copy` function should be an `async` since it uses the `await` keyword.

Make copy an async function

---

src/site/content/en/payments/android-payment-apps-delegation/index.md

Chrome 92 introduced the support of Android payment apps to WebLayer and an intent action "org.chromium.intent.action.UPDATE_PAYMENT_DETAILS" to make it possible to invoke the payment-details-update service in Chrome and other browsers (WebLayer, so far)[1]. The old example code was only able to do it on Chrome because the intent was limited to "org.chromium.components.payments.PaymentDetailsUpdateService" class which other browsers don't share.
Since WebLayer is an embedded browser. When the Android payment apps verify the calling browsers, they have to allowlist the specific embedders. So far, the only WebLayer embedder is the Google Quick Search Box app.
The example code will be updated with these two changes accordingly.
[1] https://groups.google.com/u/1/a/chromium.org/g/paymentrequest …

Add supports to WebLayer

---

src/site/content/en/blog/generic-sensor/index.md

Gravity Sensor API was released with chrome 91.
Fixes #5473

Gravity sensor: Remove release estimation date.

---

src/site/content/en/blog/keyboard-lock/index.md
src/site/content/en/blog/multi-screen-window-placement/index.md
src/site/content/en/blog/video-basics/index.md
src/site/content/en/blog/vr-comes-to-the-web-pt-ii/index.md
src/site/content/en/handbook/audience/index.md
src/site/content/en/handbook/content-checklist/index.md
src/site/content/en/learn/css/box-model/index.md
src/site/content/en/lighthouse-pwa/themed-omnibox/index.md

Fix typos by replacing `the the` with `the` (`s/\bthe the\b/the/g`).

replace "the the" with "the"

---

src/site/content/en/blog/debug-web-vitals-in-the-field/index.md

Fixes #5401, specifically the issue mentioned in https://github.com/GoogleChrome/web.dev/pull/5401#issuecomment-846276825

Update code examples to address edge cases

---

src/site/content/en/metrics/cls/index.md

The aside can be re-added once this is published: https://github.com/GoogleChrome/web.dev/pull/5498

Remove the tooling updates aside until published

---

src/site/content/en/metrics/cls/index.md
src/site/content/en/metrics/fcp/index.md
src/site/content/en/metrics/fid/index.md
src/site/content/en/metrics/lcp/index.md

This PR adds recomended thresholds to the FCP metric page. (cc: @brendankenny @rviscomi) 
Also (bonus!) I noticed the sizes were incorrect or not set on several of the visuals, so I updated those.

Add recommended thresholds for FCP

---

src/site/content/en/metrics/cls/index.md

Follows up on https://github.com/GoogleChrome/web.dev/pull/5502 to re-add the aside as soon as #5498 is published.

Re-add the CLS tooling updates aside

---

src/site/content/en/blog/evolving-cls/index.md
src/site/content/en/metrics/cls/index.md

This PR adds an update to the Evolving CLS post indicating that the updates to CLS are now available across Chrome's web tooling surfaces.

Update the Evolving CLS post with tooling status

---

src/site/content/en/blog/cls-web-tooling/index.md

We neglected to include a more nuanced note for the API. Fixing that now.

Correction for PSI

---

src/site/content/en/blog/browser-flags/index.md

- Add `about:blank` exception. Thanks, @naskooskov!

[Browser Flags article] Add `about:blank` exception

---

src/site/content/en/blog/pwa-url-handler/index.md

`s/Window/Windows`
Thanks, @beaufortfrancois!

[PWA as URL Handlers article] Fix typo

---

src/site/_data/i18n/paths/discoverable.yml
src/site/_includes/path.njk
src/styles/pages/_path.scss

Fixes #5486
- Change existing yaml to remove literal `\n` characters and instead use a yaml pipe to allow for newlines.
- Add a (somewhat gross) BEM class to the path overview. I think we're going to clean these pages up as part of Andy's work hopefully.

Fix \n appearing in path overview.

---

src/lib/components/LanguageSelect/index.js
src/site/_includes/partials/translation-disclaimer.njk
src/site/content/es/es.11tydata.js
src/site/content/es/vitals/index.md

Fixes #5443 
This PR attempts to show only languages that are available for the given page, and hide the rest. If only the English language is available, the switcher is not rendered.

A proposal to fix language confusion with LanguageSelect

---

src/site/content/en/blog/app-shortcuts/index.md

This change comes from an update in Chrome for Android.

The first 3 shortcuts are used on Android, not 4

---

src/site/content/en/blog/five-ways-airshift-improved-their-react-app/index.md

This PR adds missing `async` to the `Cost` function which uses `await`

Add missing async

---

src/site/content/en/learn/css/grid/index.md

- Fix typo in "Learn CSS" -> "Grid" Section

Typo in learn css grid section

---

src/site/content/en/lighthouse-performance/first-contentful-paint/index.md
src/site/content/en/lighthouse-performance/interactive/index.md
src/site/content/en/lighthouse-performance/lighthouse-largest-contentful-paint/index.md
src/site/content/en/lighthouse-performance/lighthouse-total-blocking-time/index.md
src/site/content/en/lighthouse-performance/performance-scoring/index.md
src/site/content/en/lighthouse-performance/speed-index/index.md

Lighthouse 8 was just [released](https://github.com/GoogleChrome/lighthouse/releases/tag/v8.0.0) and brought new score thresholds for `total-blocking-time` and `first-contentful-paint` and a re-weighting of the overall performance score.
I also noticed that the `speed-index` thresholds were incorrect and the screenshots were out of date (showing old metrics), so I updated those and a few random obsolete links.
This isn't the full revamp some of these articles need, but that can wait for the migration to d.c.c (or whatever we decide to do there).

update metric thresholds for Lighthouse 8

---

src/site/content/en/learn/css/flexbox/index.md

Change the unpacking of `flex: 1` with respect to `flex-shrink` to
`flex-shrink: 1` to be consistent with the specification and fix wording
of the sentence referring to the list detailing the unpacked values.
For further details please refer to:
- https://drafts.csswg.org/css-flexbox-1/#flex-common
- https://developer.mozilla.org/en-US/docs/Web/CSS/flex#syntax
Fixes #5537
- Changing the explanation of the `flex: 1` unpacking from `flex-shrink: 0` to `flex-shrink: 1`.
- Rewording the sentence explaining the unpacking of `flex: 1`.

docs(frontend): correct unpacking of `flex: 1` (#5537)

---

src/site/content/en/learn/css/functions/index.md

Fixes #5583
-  Fixes a typo: `ore` -> `or`

fix(frontend-learn-css): typo in functions chapter

---

.pullapprove.yml

- Don't tag in reviewers if a PR contains `WIP` in the title or is in draft mode.
- Auto-assign @jpmedley if the PR contains `[Fugu]` or `[Capabilities]` in the title, or if it uses the fugu or capabilities label.
- Auto-assign @mihajlija if the PR contains `[CWV]` or `[Vitals]` in the title, or if it uses the vitals label.
- Auto-assign @mihajlija if the PR contains `[Privacy]` or `[Security]` in the title, or if it uses the `privacy/security` label.
- Don't auto-assign reviews to the content team. This is to cut down on notification spam. Instead, we'll try to use a sheriff rotation to triage and assign reviewers.

Tune up pullapprove groups

---

src/site/content/en/blog/tabbed-application-mode/index.md

- Remove warning about `"tabbed"` being a no-op.

[Tabbed Application Mode] Remove warning about `"tabbed"` being a no-op

---

src/site/content/en/learn/css/functions/index.md

- Fixes a typo of the link to the Animation lesson: `/learn/css/animation` -> `/learn/css/animations `

fix(frontend-learn-css): link to the animate lesson

---

src/site/content/en/learn/css/the-cascade/index.md

"order of your in a CSS rule" is poor wording.  Change to "order inside a CSS rule" for more clarity
- 
- 
-

✏️ Fix typo in Cascade lesson

---

src/site/content/en/learn/css/pseudo-elements/index.md

In the [section about the ::marker pseudo-element within chapter 13 of the Learn CSS course](https://web.dev/learn/css/pseudo-elements/#::marker), the supported CSS properties neither include the `animation` nor the `transition` properties, which, by my understanding of the [specification](https://www.w3.org/TR/css-lists-3/#marker-properties) and the [linked MDN article](https://developer.mozilla.org/en-US/docs/Web/CSS/::marker#allowable_properties), they should.
Fixes #5668
- Extend the supported properties for `::marker` by mentioning the `animation` and `transition` properties as well.

docs(learn-css): extend supported properties for ::marker (#5668)

---

.eleventy.js
src/site/_filters/first-paragraph.js
src/site/_includes/feed.njk
src/site/content/en/authors/feed.njk
src/site/content/en/tags/feed.njk

Fixes #5676 and fixes #5663
- Add filter that extracts just the first paragraph of HTML content and apply it to the RSS feeds.

fix(feeds): trim RSS feed entries' content to just the first paragraph, fixes #5676 and fixes #5663

---

src/site/content/en/blog/prefers-color-scheme/index.md
src/site/content/en/progressive-web-apps/add-manifest/index.md

This PR adds upcoming "media" attribute support for `meta[name=theme-color]` to the "Add a web app manifest" article.
See https://groups.google.com/a/chromium.org/g/blink-dev
Live preview: https://deploy-preview-5620--web-dev-staging.netlify.app/add-manifest/#theme-color

Add media attribute support for meta[name=theme-color]

---

src/site/content/en/learn/css/flexbox/conclusion.assess.yml

When first reading the first question, I thought it may have been a trick question.  This commit adds clarification that the Flexbox is using the initial flex values in an `ltr` language

📝 Update Flexbox assessment

---

src/site/content/en/blog/coop-coep/index.md

Starting 92 Chrome desktop requires cross-origin isolation to use SharedArrayBuffer. This pull request adds a link to the more detailed info at developer.chrome.com.

Append caution about SAB change in Chrome 92 to COOP/COEP article

---

src/site/content/en/blog/payment-and-address-form-best-practices/index.md

- Remove double parentheses around link, they were linking to https://web.dev/payment-and-address-form-best-practices/%28https:/baymard.com/blog/address-line-2%29 instead of https://baymard.com/blog/address-line-2

Remove double parentheses in link  

---

src/site/content/en/lighthouse-performance/uses-webp-images/index.md

- Updates the modern image formats documentation to reflect the [latest changes in Lighthouse](https://github.com/GoogleChrome/lighthouse/pull/12682/files)

Update Lighthouse docs for modern image formats

---

src/site/content/en/blog/declarative-link-capturing/index.md

I noticed the DEMO link URL is wrong and `capture_links` values here are written with snake case. https://web.dev/declarative-link-capturing/
@tomayac Could you take a look at this?

Fix DEMO link and capture_links values

---

src/site/content/en/blog/conformance/index.md

- fix [custom plugin](https://nextjs.org/docs/tag/basic-features/eslint#eslint-plugin) and [shareable configuration](https://nextjs.org/docs/tag/basic-features/eslint#base-configuration) markdown links in the **Conformance in Next.js** section of the conformance blog post;

Fix markdown links in the conformance blog post

---

src/site/content/en/lighthouse-performance/render-blocking-resources/index.md

This PR clarifies that `media=all` in a stylesheet link tag does _not_ constitute "matching the user's device" and thus is still considered render-blocking. I believe this could be potentially confusing if not clarified.
I realize the wording might not be very smooth / matches the overall writing style. Feel free to edit with better wording.

Update documentation on render-blocking stylesheet

---

src/site/content/en/handbook/grammar/index.md

Add note re about:// instead of chrome:// to handbook.

---

src/site/content/en/blog/css-is-and-where/index.md

This fixes a small typo on [New CSS functional pseudo-class selectors :is() and :where()](https://web.dev/css-is-and-where/) page.
```
`:is()` takes the specificity of it's most specific selector.
```
»
```
`:is()` takes the specificity of its most specific selector.

fix typo in bullet list article

---

src/site/content/en/blog/css-is-and-where/index.md

Fixes small typo in docs
- `header` —> `heading` as name of h1, h2, etc. html elements

Correct element name to heading from header

---

src/site/_includes/path.njk

Changed heading text from 'What you'll learn' to 'Table of Contents'
Fixes #5670
- Changed heading text 
Current Behaviour - 
Proposed Behaviour -

Heading text changes

---

src/site/content/en/learn/css/borders/index.md

The attached CodePen (https://codepen.io/web-dot-dev/pen/poRraBp) uses `2px` instead of `1px`.

✏️ [Learn CSS] Fix typo in Border section

---

src/site/content/en/blog/web-share/index.md

This PR simply adds files support for Web Share in Safari 15 to the official "web share" article.

Add files support for Web Share in Safari 15

---

src/site/_includes/components/Hero.js

Fixes #5813
We should make this change on d.c.c. as well.
- Don't lazy load above the fold images as it hurts LCP

Don't lazy load hero images. Improves LCP

---

src/styles/components/_stats.scss

Fixes #5766 
- Reduces margin for `.w-stats` container from `margin: 32px -32px` to `margin: 24px -24px`
- Note: Instead of jumping directly from 32px to 24px, a media query could be introduced to update the margin for mobile viewports as this is when things start to overflow.

Decrease margin on .w-stats container to get rid of CLS in the CLS article

---

src/site/content/en/blog/compat2021/index.md

We've been slightly inconsistent here, but mostly written "Compat 2021" instead of "Compat2021", notably here:
https://wpt.fyi/compat2021
I noticed this while reviewing https://github.com/GoogleChrome/web.dev/pull/5870, let's be consistent from now on :)

Add a space where missing for "Compat 2021"

---

src/site/content/en/learn/index.njk

The detailed description of that bug was described at related issue #5879
By replacement the hardcoded values we can avoid to get the same issues in the future. Now all values are comes from translates. Bassically it's the same values that user see at titles, but transformed a bit to easily used as URL addresses next.
I think that such improvement can help to reduce the probability of the same human errors in the future.

Fix headline anchors navigation at "/learn" page by removing hardcoded values

---

src/site/content/en/learn/css/pseudo-elements/index.md

In the [section about the ::selection pseudo-element in chapter 13 of the "Learn CSS" course](https://web.dev/learn/css/pseudo-elements/#::selection) the supported properties contain `carret-color`, `cursor` and `outline`, which I could neither find in the [referenced MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection#allowable_properties), nor the [official specification](https://drafts.csswg.org/css-pseudo-4/#highlight-styling).
Fixes #5677
- Remove `carret-color`, `cursor` and `outline` from the list of supported CSS properties for the `::selection` pseudo-element

docs(learn-css): reduce allowed properties for ::selection (#5677)

---

src/site/content/en/blog/content-visibility/index.md

In my opinion a major pain point of most blog posts is they give info about how to combat drawbacks of nice features (such as `content-visibility: auto` and the scrollbar problem, which is fixed by `contain-intrinsic-size`) but without mentioning how you can implement this in larger scale. 
It is very rare that a dev has time to add (and maintain!) sizes of elements. So, as @slightlyoff has created blog-posts about the topic already, I figured mentioning those (as they contain code that is ready to be implemented) gives developers an easer time implementing `contain-intrinsic-size` and `content-visibility: auto`.
- Add a short sentence linking to @slightlyoff's blog posts about automatically setting `contain-intrinsic-size` by utilizing …

Mention @slightlyoff's blog posts for automating `contain-intrinsic-size`

---

src/site/content/en/blog/urlpattern/index.md

A single character seems to have been lost along the way.

Correct URL component encoding example in URLPattern article.

---

src/site/content/en/blog/browser-level-lazy-loading-for-cmss/index.md

This PR updates the content of https://web.dev/browser-level-lazy-loading-for-cmss/ to reflect the recent findings around potentially negative LCP impact of lazy-loading elements above the fold, see https://web.dev/lcp-lazy-loading/.
@rviscomi @addyosmani Would be great to get your review on these updates.

Update lazy-load CMS post with updated guidance around LCP

---

src/site/content/en/blog/building-a-breadcrumbs-component/index.md

- I think it should be `crumbs.forEach` instead of `crumb.forEach`.

Fix typo in code example

---

src/site/content/en/blog/aurora-resource-inlining/index.md

Related issue: https://github.com/GoogleChrome/web.dev/issues/5876
- Adding head and body tags in examples.

Adding head and body tags in examples.

---

src/lib/components/ThemeToggle/index.js
src/lib/components/base.js
src/scss/blocks/_theme-toggle.scss
src/scss/next.scss
src/site/_data/design/themes.js
src/site/_data/design/tokens.json
src/site/_includes/partials/head.njk
src/site/content/en/design-system/temp-styleguide.njk

This is the theme switcher that toggles dark/light mode, overriding the initial `prefers-color-scheme` setting that is honoured by default. The setting is stored in and loaded from local storage.
In `head.njk`, the little snippet of JavaScript applies the setting _before_ the CSS is loaded to prevent a flash of incorrect theme, when a user has a setting stored in local storage. 
In terms of UI on the toggle itself, I've just applied some really basic CSS so it doesn't look rubbish. We need to work out how the toggle will look, globally, so I'll tag in @jimoong for some thoughts on that. It's using `<button>` elements to toggle right now, but we could also lean into an `<input type="checkbox" role="switch" />` to support something more "toggle"-like. 
I added it to the `base.js` because we …

Theme switcher

---

src/site/content/en/blog/urlpattern/index.md

This addresses some developer feedback raised in https://github.com/WICG/urlpattern/issues/63 about how the `baseURL` property affects the constructed `URLPattern`.
CC: @wanderview

Clarifications about baseURLs when using URLPattern 

---

src/site/content/en/blog/vitals-tools-workflow/index.md

- Not rendering link. I presume because you can't use markdown in the middle of HTML table?
https://web.dev/vitals-tools-workflow/#:~:text=Allows%20slicing%20of%20data%20in%20meaningful%20ways%20which%20can%20be%20joined%20with%20other%20public%20datasets

Correct link markup in Web Vitals Tools article

---

src/site/_data/authorsData.json
src/site/_data/i18n/authors.yml
src/site/content/en/blog/css-scroll-snap/index.md

This PR migrates the scroll snap article: https://developers.google.com/web/updates/2018/07/css-scroll-snap
I've given it a light edit for web.dev style, updated the browser information, and future work section to make it up to date.
Once this is merged I'll redirect the original, and also update the large number of links to this piece over at MDN.

migrates the scroll snap article

---

.eleventy.js
src/lib/components/CourseLinks/index.js
src/site/_includes/components/includeRaw.js
src/site/_includes/course.njk
src/site/_includes/design-system.njk
src/site/_includes/macros/icon.njk
src/site/_includes/partials/course-app-bar.njk
src/site/_includes/partials/head.njk
src/site/_includes/partials/header-course.njk
src/site/_includes/partials/navigation-drawer-course.njk

This follows-up from @robdodson 's PR #5964 and adds an `includeRaw` helper.
Very confusingly, all the previous includes that go outside "src/site/_includes" seem to have needed "../../.." and yet somehow still end up in "src/site" as the base path. I can't explain it, but I think Nunjucks' include function must do something different or special here.
So I've simplified that here.

add includeRaw shortcode

---

src/site/_data/i18n/patterns.yml
src/site/_includes/pattern-set.njk

Some patterns might belong directly to the pattern suite (/patterns/PatternSuite/Pattern) instead of a PatternSet (/patterns/PatternSuite/PatternSet/Pattern). They are displayed under "other patterns" heading in the pattern suite page.

@devnook Add patterns that do not have a parent PatternSet to the pattern-set page

---

src/site/content/en/blog/content-visibility/index.md

This will (hopefully) fix a rendering issue leading to the `## Hiding content with `content-visibility: hidden` header being rendered wrong at https://web.dev/content-visibility/.

Update content-visibilty to fix typo

---

src/site/content/en/blog/gpu/index.md

The link to the Babylon.js Playground is not the right one in web.dev/gpu, it should be: https://playground.babylonjs.com/#XCNL7Y

Update Babylon.js playground link

---

src/site/content/en/blog/optimize-lcp/index.md

The indentation on the code block is causing our translation PRs to double wrap things in backticks.

Fix broken indentation that is messing up translation PRs

---

gulp-tasks/write-version.js

Forgot to update the write version to get the commit sha from git rather than the github env variable.

fix(write-version): use git to get commit sha

---

src/site/content/en/blog/gpu/index.md

This PR adds a caution about GPU adapter being null which may cause confusion. See https://github.com/mrdoob/three.js/pull/22482/files

Add caution about null GPU adapter

---

src/site/content/en/blog/conversion-measurement/index.md

… Conversion Measurement API blog
- 
- 
-

fixing url in A more private way to measure ad conversions, the Event Conversion Measurement API blog

---

src/site/content/en/blog/gpu-compute/index.md
src/site/content/en/blog/gpu/index.md

This PR simply moves the ["GPU compute" article from Web Fu](https://developers.google.com/web/updates/2019/08/get-started-with-gpu-compute-on-the-web) to web.dev now that we have web.dev/gpu.
I'll start a PR to redirect automatically WebFu article to web.dev as well.
FYI @Kangz
Live preview: https://deploy-preview-6113--web-dev-staging.netlify.app/gpu-compute/

Move GPU compute article from WebFu to web.dev

---

src/site/content/en/blog/deprecating-excalidraw-electron/index.md

Fixing Url in Deprecating Excalidraw Electron in favor of the web version blog

---

package.json
src/pattern-library/patterns/aside/aside.njk
src/site/_data/design/patterns.js

The output HTML was a touch ropey in the design system patterns (soon to be renamed components) which will affect copy and paste:
This mini PR leverages `prettier` and a little regex to remove blank lines to assist with that:

Leverage prettier and regex to improve output formatting

---

src/site/content/en/blog/webassembly-threads/index.md

The URL has changed as they needed external host to add COOP/COEP headers.
- 
- 
-

Change URL for FFMPEG demo

---

src/site/content/en/progressive-web-apps/add-manifest/index.md

This PR simply removes the flag for screenshots and description web app manifest fields that is not required anymore in Chrome Stable.

Remove flag for screenshots and description

---

src/site/content/en/blog/vr-comes-to-the-web-pt-ii/index.md

https://github.com/mdn/content/pull/8719#issue-728506061 - Facebook has stopped supporting the React 360 project since 2018 but it is still available to view and use.
- 
- 
-

fixing url in Virtual reality comes to the web, part II blog

---

src/site/content/en/mini-apps/mini-app-project-structure-lifecycle-and-bundling/index.md

Sorry, I forgot about it in https://github.com/GoogleChrome/web.dev/pull/6110.
- 
- 
-

fixing url in Project structure, lifecycle, and bundling

---

src/site/_filters/i18n.js
src/site/_includes/partials/navigation-drawer-course.njk

I found strange (probably intended?) behavior in Nunjucks, that it was falling back to the previous `{{ title }}` when the result of calling the i18n filter was `undefined`.
Anyway, the solution here is to actually barf on missing i18n strings. This was hitting us when a user tried to access a string like "i18n.courses.foo", when strings "i18n.courses.foo.bar" was actually defined (since the parent object existed, it just has no 'en' prop).

throw on missing i18n string

---

src/site/content/en/blog/bundling-non-js-resources/index.md

In response to my issue, Parcel has added a dedicated section in docs for this pattern, so changing the link to point right there.
- 
- 
-

Provide more specific link to Parcel docs

---

src/site/_data/countries.js

Fixes #6193.
- Use the correct locale (zh-TW) for the display name of Taiwan in Newsletter page.

fix(newsletter): use zh-TW for Taiwan, fixes #6193

---

src/site/content/en/blog/eventing-deepdive/index.md

Thanks for a great article.
I understand propagation/capture/bubble so much better now!
I just think two of the live demo links may be out of sync with their surrounding text though, see below:
- Fix live demo link for stopping propagation at `#A` in the bubbling phase
- Fix live demo link for `stopPropagation()` in the _target phase_ for `#C`

JavaScript Eventing Deep Dive: Fix 2 live demo links to match the text

---

src/site/content/en/blog/eventing-deepdive/index.md

- Origin of all events is `window`, not `document`. Thanks, @philipwalton!

[Eventing deep dive] Origin of all events is window, not document

---

src/site/content/content.11tydata.js

Fixes #3311
- Check all content for origin trial front matter and add origin trial tag if missing.
- 
-

feat(tags): automagically add `origin-trials` tag to posts, fixes #3311

---

src/scss/blocks/_prose.scss
src/site/_data/design/themes.js

To keep the rollout process simple, the media query-based dark mode will no longer work _but_ we can still toggle modes on and off for testing.

Remove the auto dark mode for now

---

src/site/_includes/course.njk
src/styles/generic/_code.scss

Previously you could not use markdown backticks in the titles or descriptions for course content. This already works for regular blog posts, but it didn't for courses.
This also adds an `.unstyled-code` class which can be used as an exception to disable most of our code styles.
Before:
After:

Let authors use markdown in course titles and descriptions.

---

.eleventy.js
src/component-library/aside/aside.json
src/lib/utils/is-design-system-context.js
src/scss/blocks/_prose.scss
src/scss/next.scss
src/site/_data/design/components.js
src/site/_includes/components/Aside.js
src/site/_includes/design-system.njk
src/site/content/en/design-system/css-methodology.md

I recorded a screencast of this admittedly, questionable approach: https://www.loom.com/share/a5f832e2f84948d4a81b7ee86c6d1b1e
If we go down this route, the main problem will be how do we handle nested shortcodes. For example, how do we handle a `{% Img %}` being passed into an `{% Aside %}`? The markdown is processed using [our filter](https://github.com/GoogleChrome/web.dev/blob/main/src/site/_filters/md.js).
Other than that and the frightening globals, this could have legs—especially as it is very temporary. 
Let me know ur thoughts and please, feel free to play around on this branch too! 
Example page that uses the new design system and an existing shortcode: https://github.com/GoogleChrome/web.dev/blob/prototype-shortcode-context/src/site/content/en/design-system/css-methodology.md

WIP: prototype rendering new design system components without disturbing older stuff

---

.cloudbuild/deploy.yaml

This matches what we've done for our Actions. Cloud Build's node is (sometimes) crashing without this.
Amusingly we request a huge instance yet Node still has a RAM limit here. Well, at least our CPU is faster for builds.

allow more ram during build (seeing sometimes failures)

---

src/site/content/en/blog/sign-in-form-best-practices/index.md

Using `autofocus` may reduce usability/accessibility, and it doesn't have all that much (potential) benefit: 
• https://www.a11yproject.com/checklist/#global-code
• https://brucelawson.co.uk/2009/the-accessibility-of-html-5-autofocus

Remove autofocus recommendation

---

.github/workflows/presubmit-workflow.yml
src/site/_collections/hooks/utils.js
src/site/_transforms/minify-html.js
src/site/_transforms/purify-css.js

- Change build command in presubmit to staging environment
- Update `purify-css` and `minify-html` to run on LHCI urls when in staging
-

test(presubmit): build a staging version of site to speed up HTML and CSS transforms

---

src/site/_data/site.js

- Adding a PWA banner with a link to the registration
My idea is to have this banner until Oct 7, when I'll change the banner to link to the livestream, so people can join, and I'll remove the banner by EOD oct 7th.

PWA summit, registration banner.

---

src/site/content/en/fast/lazy-loading-video/index.md

Both libraries work with video loading. vanilla-lazyload can be used to lazyload also images, background images and iframes.
- Adds vanilla-lazyload alongside lozad as both libraries can be used to lazyload videos, and vanilla-lazyload also works also with background images.

Added vanilla-lazyload alongside lozad

---

src/site/_includes/components/BrowserCompat.js

FIX https://github.com/GoogleChrome/web.dev/issues/6300

Handle array `support` in browser compat widget

---

src/site/content/en/learn/forms/design-basics/index.md

This fixes an issue where other PRs can't be merged because of this lint warning.
```
> web.dev@3.0.0 lint:md /Users/fbeaufort/Documents/GitHub/web.dev
> remark -q -f .
src/site/content/en/learn/forms/design-basics/index.md
169:1-169:95  warning  An MDN link contains a locale (/en-US). Please remove the locale from the link.  bad-urls  remark-lint
⚠ 1 warning
```

Remove locale from mdn link

---

src/site/content/en/blog/media-session/index.md

This PR makes sure the article is less centered on Chrome as Media Session is now supported in Safari as well.
An issue for the browser compatibility widget has already been filed at https://github.com/GoogleChrome/web.dev/issues/6300
Live preview: https://deploy-preview-6302--web-dev-staging.netlify.app/media-session/

Update Media Session article with WebKit support

---

src/site/content/en/fast/signed-exchanges/index.md

We've found that people much prefer the platform-specific tools over the
general-purpose tools, so we should make their search easier by directing them
towards those first, followed by the general purpose tools (Web Packager), and
then the libraries for building your own implementation.
Shortened the Web Packager section by removing an out-of-date alpha warning and
a production step that's duplicative of the "How to set up" article.
Cleaned up the tooling intro section a bit.
/cc @khempenius 
~~This is based on top of #6230. Ignore the first commit; I'll rebase once it's merged.~~

Move platform-specific SXG tooling to the top.

---

src/site/content/en/blog/bluetooth/index.md

Following https://twitter.com/quicksave2k/status/1443896996159492102 from https://github.com/WebBluetoothCG/web-bluetooth/issues/188#issuecomment-929915013, this PR adds a caution section about parallel GATT operations.

Add parallel GATT operations caution

---

src/site/content/en/fast/signed-exchanges/index.md

- Add "SXG" to "Libraries" section heading for parallelism with its siblings.
- s/SXG tool/SXG library/
/cc @khempenius

SXG wording tweaks

---

src/lib/components/ShareAction/_styles.scss

share-action hover style sets filter to 0.5 results with corrupted style
-
-
-

fix(share-action): corrupted hover style

---

src/site/content/en/blog/google-search-sw/index.md

This updates the https://web.dev/google-search-sw/ post to reflect the current status of the Google Search service worker.
Text has been reviewed out-of-band by @b1tr0t

Update to Search SW post

---

src/site/content/en/progressive-web-apps/install-criteria/index.md

Apparently the install docs for FF are a 404 now. I couldn't find a language agnostic one so I went for `en-US`.

fix dead PWA install link for FF

---

.eleventy.js
package-lock.json
package.json
src/lib/patterns.js
src/site/_filters/minify-js.js
src/site/_filters/site-render.js
src/site/_includes/pattern-set.njk
types/site/_data/patterns.d.ts

This improves on e.g., the `md` filter, because it'll run Nunjucks code too.
Used for Patterns cc @una 
Fixes #6603
Demo, although I took this change out:

add `siteRender` filter to render as close to site as possible

---

src/site/content/en/patterns/layout/aspect-ratio-image-card/demo.md
src/site/content/en/patterns/layout/aspect-ratio-image-card/index.md
src/site/content/en/patterns/layout/clamping-card/demo.md
src/site/content/en/patterns/layout/clamping-card/index.md
src/site/content/en/patterns/layout/container-query-card/demo.md
src/site/content/en/patterns/layout/container-query-card/index.md
src/site/content/en/patterns/layout/deconstructed-pancake/demo.md
src/site/content/en/patterns/layout/deconstructed-pancake/index.md
src/site/content/en/patterns/layout/holy-grail/demo.md
src/site/content/en/patterns/layout/holy-grail/index.md
src/site/content/en/patterns/layout/index.md
src/site/content/en/patterns/layout/line-up/demo.md
src/site/content/en/patterns/layout/line-up/index.md
src/site/content/en/patterns/layout/pancake-stack/demo.md
src/site/content/en/patterns/layout/pancake-stack/index.md
src/site/content/en/patterns/layout/repeat-auto-minmax/demo.md
src/site/content/en/patterns/layout/repeat-auto-minmax/index.md
src/site/content/en/patterns/layout/sidebar-says/demo.md
src/site/content/en/patterns/layout/sidebar-says/index.md
src/site/content/en/patterns/layout/super-centered/demo.md
src/site/content/en/patterns/layout/super-centered/index.md
src/site/content/en/patterns/layout/twelve-span-grid/demo.md
src/site/content/en/patterns/layout/twelve-span-grid/index.md
src/site/content/en/patterns/web-vitals-patterns/carousels/index.md
src/site/content/en/patterns/web-vitals-patterns/fonts/index.md
src/site/content/en/patterns/web-vitals-patterns/infinite-scroll/index.md
src/site/content/en/patterns/web-vitals-patterns/notices-pattern-set/index.md
src/site/content/en/patterns/web-vitals-patterns/video/index.md

Copyedits for the patterns, I also made the changes in Una's draft PR #6617 as that was ending up in a tangle of merge conflicts.
@una I had one query, I don't really understand what you are saying here in the aspect ratio example:
> "To maintain a 16 x 9 aspect ratio without this property, you'd need to use a [`padding-top` hack](https://css-tricks.com/aspect-ratio-boxes/) and give it a padding of `56.25%` to set a top-to-width ratio. We will soon have a property for this to avoid the hack and the need to calculate the percentage. You can make a square with `1 / 1` ratio, a 2 to 1 ratio with `2 / 1`, and really just anything you need for this image to scale with a set size ratio."
This makes it sound like you can't do a 1/1 aspect ratio, which you can, with the `aspect-ratio` property …

Pattterns copy edit, remove draft status

---

src/site/content/en/blog/url-protocol-handler/index.md

- Add launch info
- Remove origin trial info

[URL Protocol Handling] Add launch info, remove origin trial info

---

src/scss/_rollout.scss

Sticky tape on assesment button

---

src/site/content/en/blog/responsiveness/index.md

Add initial responsiveness metric draft

---

src/site/_filters/github-link.js

- The old branch name is still surfaced in the `Improve article` links at the bottom of each article.

["Improve article" link] `main` is the new `master`

---

src/lib/components/UrlChooser/_styles.scss
src/lib/components/UrlChooser/index.js

Fixes #6680
- wrap url in p tag and set p's text-overflow to ellipses
-
-

fix(UrlChooser): fix url overflow, fixes #6680

---

src/site/content/en/learn/css/transitions/index.md

Fixes issue where dev tools image in "transition-timing-function" section was too large
- Update dev-tools image to a wider image

LearnCSS: Transitions -> update devtools image

---

src/site/content/en/learn/design/intro/index.md

Becuase images less than 800 pixels wide are being blown up (and look pixellated), I've created new versions of those images that have space on either side to avoid this scaling issue.

Swap out narrow images

---

src/site/content/en/blog/fugu-status/index.md

- We can now use ID links since the tracker now supports them.

[Fugu Status article ] Use ID links

---

src/site/content/en/blog/lighthouse-user-flows/index.md

[Lighthouse user flows](https://web.dev/lighthouse-user-flows/#capturing-a-warm-load)
the `testUrl` was set to https://pptr.dev/ in code but the preceding paragraph and the screenshot points to https://web.dev/performance-scoring/
- change `testUrl` value in the "Capturing a warm load" section to https://web.dev/performance-scoring/

lighthouse-user-flows: fix URL in the warm-load example

---

src/site/content/en/blog/responsiveness/index.md

Mentioned layout shift metrics instead of responsive metrics
-
-
-

Spotted a typo in the feedback section

---

src/lib/components/Subscribe/index.js
src/site/_includes/homepage-next.njk
src/site/_includes/partials/subscribe-next.njk
src/site/_includes/partials/subscribe.njk
src/styles/components/_subscribe.scss

Fixes #6663
- Finds elements across `subscribe.njk` and `subscribe-next.njk` to attach onto and update.
- Attaches `pages/home.js` to home page
-

fix(Subscribe): find correct elements in subscribe form, fixes #6663

---

src/scss/blocks/_fab.scss
src/site/_includes/partials/subscribe-action-next.njk

Fixes #6676
- Creates new subscribe fab for new design system
- Fixes FAB label so it's shown in viewports medium and higher
-

feat(subscribe): create subscribe FAB using new design system, fixes #6676

---

src/site/content/en/lighthouse-performance/uses-webp-images/index.md

As of version 93, Firefox supports displaying still AVIF images. AVIF sequences are not supported.
- Added Firefox as a browser supporting AVIF

Add Firefox to the list of browsers supporting AVIF

---

src/lib/psi-service.js

Fixes #6694
To match the old /measure which simulated a mobile-device-load, the PSI API needs an explicit `strategy=MOBILE` or it defaults to desktop.

simulate a mobile device in /measure tool

---

src/site/content/en/blog/gpu/index.md

This PR updates the OT timeline for WebGPU now that it has been extended: https://developer.chrome.com/origintrials/#/view_trial/118219490218475521
FYI @kangz

Update OT timeline

---

src/site/content/en/blog/declarative-link-capturing/index.md

- Add OT not launching warning.

[Declarative Link Capturing] Add OT not launching warning

---

src/site/content/en/blog/whats-new-pagespeed-insights/index.md

This removes an extraneous `)`:
> ![image](https://user-images.githubusercontent.com/134745/141169564-d58e64ce-083c-4f0d-aea7-e84b6dda5921.png)

Remove extraneous closing parenthesis

---

src/site/content/en/handbook/quick-start/index.md
src/site/content/en/patterns/example-set/full-html-demo/index.md

Found a typo while reading through the quick start section. `fromtmatter` -> `frontmatter`.

fix(typo): s/fromtmatter/frontmatter

---

src/site/content/en/blog/bfcache/index.md

This PR updates the DevTools section of the bfcache post to indicate that developers no longer have to enable the experiment to test the feature (it's now on by default).

Remove the instruction to enable the bfcache experiment

---

src/styles/generic/_links.scss

Fixes #5671
- remove outline on `<a>` on active
-
-

fix(anchor): remove outline on `<a>` on active, fixes #5671

---

src/site/content/en/blog/asyncify/index.md
src/site/content/en/blog/building-a-switch-component/index.md
src/site/content/en/blog/compress-images-avif/index.md
src/site/content/en/blog/introducing-model-viewer/index.md
src/site/content/en/blog/lighthouse-ci/index.md
src/site/content/en/blog/lighthouse-whats-new-6.0/index.md
src/site/content/en/blog/logical-property-shorthands/index.md
src/site/content/en/blog/speculative-prerendering/index.md
src/site/content/en/fast/codelab-extract-and-inline-critical-css/index.md
src/site/content/en/fast/incorporate-performance-budgets-into-your-build-tools/index.md
src/site/content/en/fast/using-bundlesize-with-travis-ci/index.md
src/site/content/en/fast/using-lighthouse-bot-to-set-a-performance-budget/index.md
src/site/content/en/handbook/quick-start/index.md
src/site/content/en/handbook/writing-blog-posts/index.md
src/site/content/en/lighthouse-seo/http-status-code/index.md
src/styles/generic/_code.scss

GitHub should be written with a capital H. `Github` -> `GitHub`.

fix(typo): fix GitHub casing

---

src/site/content/en/blog/ps-on-the-web/index.md

This adds a section to the Photoshop on the Web case study detailing their service worker usage.
The text has been reviewed by the relevant folks at Adobe.

Update to Photoshop case study

---

src/lib/components/LighthouseViewer/_styles.scss

Fixes #6820
- CSS changes
-
-
Here's what I'm aiming for
and this is what i was able to produce
vs what it is now

fix(measure): make styling more like previous measure page, fixes #6820

---

src/component-library/button/button.json
src/lib/components/Snackbar/_styles.scss
src/lib/components/Snackbar/index.js
src/scss/mixins/_button-base-styles.scss
src/styles/components/_buttons.scss
src/styles/tools/_mixins.scss

Fixes #6705
- Add clear button class.
- Add clear button class/attribute to snackbar buttons.
Before:
After:
This'll obviously need some love and attention if/when we remove the component level styling and the old SCSS.

fix(Snackbar): use new button classes for snackbar, fixes #6705

---

src/site/content/en/blog/serial/index.md

This PR adds explicitly the user gesture requirement to the Serial API to help developers that may not understand the error message.
Context: https://stackoverflow.com/questions/70007274/how-to-use-the-chrome-web-serial-api/70017650#70017650

Add user gesture requirement

---

src/site/content/en/blog/declarative-link-capturing/index.md

[Declarative Link Capturing article] Remove OT info

---

src/site/content/en/lighthouse-accessibility/heading-order/index.md

For context, I'm maintaining [a guide](https://www.notion.so/mui-org/Technical-documentation-7e55b517ac2e489a9ddb6d0f6dd765de) with all the learnings we had at MUI to write great documentation. I have linked this section, but I don't feel great about people that would make this mistake and be categories as "less experienced".

Remove value judgement from the recommendation

---

src/site/content/en/blog/gpu/index.md

This PR simply adds a link to the [WebGPU Best Practices](https://toji.github.io/webgpu-best-practices/) resource by @toji
FYI @Kangz

Add WebGPU Best Practices resource

---

src/site/content/en/blog/coop-coep/index.md

Based on @maudnals 's suggestion, removed many Reporting API related content and defer to [the new Reporting API dedicated article](https://web.dev/reporting-api/).

Defer Reporting API content to the new article

---

src/site/content/en/learn/forms/form-fields/index.md

Fixes [#6896](https://github.com/GoogleChrome/web.dev/issues/6896)
Change in this PR includes : 
- updation of  Checkbox wrong attribute from `selected` to `checked` in  [form-fields/#type](https://web.dev/learn/forms/form-fields/#type) page.

[Web.dev Doc] : Checkbox attribute changed from selected to checked

---

src/site/content/en/blog/responsiveness/index.md

This PR updates the responsiveness post to indicate that some of the issues previously affecting the metric candidates have been fixed in Chrome 98.
It also address one small issue with the code example that I noticed while testing the metrics on Chrome 98.

Update bug info and code example for the responsiveness post

---

src/lib/components/Carousel/index.js
src/lib/pages/home.js
src/lib/pages/learn.js
src/site/_includes/partials/course-cards-next.njk

- Update course cards partial to use carousel
- Carousel tracks active card when tabbing and using arrow keys.
- Carousel scrolls when using forward/back buttons.

refactor(course-cards-next): use carousel

---

src/scss/mixins/_card-base-styles.scss

adding word-break to fix the title overflow from the cards
Fixes #6836
Before fix:
After fix:
Update the css to wrap the heading inside the card incase of test overflow.

Update _card-base-styles.scss for card header overflow

---

src/component-library/hero/hero.njk
src/site/_includes/homepage-next.njk

Fixes #6895
- Remove `loading="lazy"` from all images in `.hero` elements
-
-

fix(hero): remove `loading="lazy"` from all images in `.hero` elements, fixes #6895

---

algolia.js
src/site/_filters/algolia-item.js
src/site/_includes/base.njk
src/site/_includes/blog.njk
src/site/_includes/index-page.njk
src/site/_includes/item-page.njk
src/site/_includes/path.njk
types/eleventy/collection-item.d.ts
types/utils/algolia.d.ts

Fixes #4027
- Limit search to just title, description and content. (Things like the URL could have been false positives with the inclusion of "web")
- Add custom ranking sort on new `priority` field.
- Default pages to algolia priority of `1`.
- Set paginated pages algolia priority to `0.9`.
- Set path pages algolia priority to `1.1`.
- Set path pages to use `eleventyComputed` instead of `renderData` for title and what not. (When using `renderData` posts don't have a title, and therefore fail to be indexed by algolia)

fix(algolia): add landing pages and prioritize them, fixes #4027

---

src/site/content/en/learn/css/backgrounds/index.md

-  Hotfix: Add missing 'worse' compare box treatment to two compare blocks in CSS Backgrounds module
**Before**
**After**

Hotfix: Add missing 'worse' compare box treatment to two compare blocks in CSS Backgrounds module

---

src/site/content/en/blog/notification-triggers/index.md

- Explain that we no longer pursue this API.

[Notification Triggers article] Add no longer pursued warning

---

src/lib/components/BaseResponseElement/index.js

Fixes #6463
- Add method to scroll to selected, correct, option
-
-

fix(BaseResponseElement): scroll to selected option when option is correct, fixes #6463

---

shared/locale.js
src/lib/utils/language.js
src/site/_includes/components/LanguageList.js

This PR fixes:
- Wrong Russian language name translation (first letter is incorrect now). I am a native speaker and it misleads me) You can check it in [Google Translate](https://translate.google.com/?hl=ru&sl=en&tl=ru&text=Russian%20language&op=translate)
- Removed duplicate language names lists

Fix Russian language translation

---

src/site/content/en/blog/user-agent-client-hints/index.md

As we are going to deprecate the existing client hint `Sec-CH-UA-Full-Version`, using `Sec-CH-UA-Full-Version-List` instead. For details please check https://github.com/WICG/ua-client-hints/issues/196
Fixes https://github.com/WICG/ua-client-hints/issues/196
- Add new client hint `Sec-CH-UA-Full-Version-List` description 
- Update example using `Sec-CH-UA-Full-Version-List` instead of `Sec-CH-UA-Full-Version`

Update examples with Sec-CH-UA-Full-Version-List

---

src/site/content/en/blog/window-controls-overlay/index.md

- New `getTitlebarAreaRect()` method (https://github.com/WICG/window-controls-overlay/pull/46).

[Window Controls Overlay] New `getTitlebarAreaRect()` method

---

src/site/content/en/blog/window-controls-overlay/index.md

- Rename to `titlebarAreaRect`.

[Window Controls Overlay article] Rename to `titlebarAreaRect`

---

src/site/content/en/blog/speculative-prerendering/index.md

This PR updates a link that seems to be incorrect and should be linked to the Github explainer.

Fix incorrect link

---

src/site/content/en/blog/content-visibility/index.md

This PR adds:
* A warning about the performance penalties of forced layout, and a tip for how to find and remove them via devtools.
* A new paragraph describing the benefits of contain-intrinsic-size: auto.

Add warning about forced layouts, info about auto

---

src/site/_includes/path.njk

Fixes #7032
- Display subtopics in toc
-
-

fix(path): add subtopics to toc, fixes #7032

---

src/site/_data/i18n/instruction.yml
src/site/_includes/components/Instruction.js

Fixes #6982 
Add an optional `locale` param in the `Instruction` shortcode. Can use that like below in any article, especially translated one.
```js
{% Instruction 'devtools-network', 'li', locale %}
```
Preferably able to access to `@this {EleventyPage}` object like the `components/Aside.js`, then we can eliminate this additional `locale` param. However, I couldn't get that work.

[i18n] Localize string in `Instruction.js`

---

src/scss/blocks/_carousel.scss
src/site/_data/design/themes.js

It takes up way too much space and results in half-cards being rendered.

Prevent carousel buttons showing on small viewports

---

src/site/content/en/blog/declarative-link-capturing/index.md
src/site/content/en/blog/launch-handler/index.md

Fixes https://github.com/GoogleChrome/web.dev/issues/6866
- Add the article

Add launch handler article

---

src/site/content/en/blog/launch-handler/index.md

There are [a few ways](https://yaml-multiline.info/) to do multi-line strings in YAML; the use of `|` as a prefix will add in newlines to match the newlines in the YAML, while using `>` will translate the newlines into spaces. In the case of this post, the spaces approach is more appropriate:
Before:
After:

Remove newlines in subhead from launch handler post

---

src/site/content/en/blog/building-a-toast-component/index.md

Fixed the link by removing the two zero width spaces ([\u200B](https://www.fileformat.info/info/unicode/char/200b/index.htm)) in the URL.
Before this change the `<output>` in the articles [markup paragraph](https://web.dev/building-a-toast-component/#markup) pointed to a 404 page.
- fix broken link in [building-a-toast-component article](https://web.dev/building-a-toast-component)

fix(building-a-toast-component): Fix broken link

---

src/scss/blocks/_prose.scss
src/scss/next.scss

Fixes #7044
- Only apply `li` styles to the `ol` or `ul` that they are inside of.
Before:
You're seeing `<ul>` lists embedded inside of a `<li>` inside of a `<ol>`, and it looks like an embedded `<ol>`, which isn't right...
After:

fix(lists): fix order and styling of embedded lists, fixes #7044

---

src/site/content/en/blog/economic-times-cwv/index.md

- Removes incorrect hero and thumbnail images for the Economic Times case study.

Removes hero and thumbnail images for the economic times case study.

---

src/styles/components/_code-pattern.scss

Fix bug of content overflow in all the code components within [web.dev/patterns](url)
Fixes #7088 , #7063,
- Fix content overflow in contents that uses code-pattern component.
- Add `overflow: scroll` property to .code-pattern__content class

fix: content overflow of code-pattern.scss component

---

src/site/content/en/blog/how-we-built-designcember/index.md

- Update images
- Update video
- Update some text
Missing: updating the last image to a higher res version (ran into uploader permissions issues)

Designcember post: update videos and images, some text

---

src/site/content/en/blog/declarative-link-capturing/index.md

- Add information for migrating from Declarative Link Handling to Launch Handler API
- Introduces new Link Capturing user-enabled feature in Chrome

Add DLC to Launch Handler migration info

---

src/site/content/en/blog/how-we-built-designcember/index.md

Fixes: #6783 
Post for Dec 28.

Building Designcember post

---

src/site/content/en/learn/design/intro/index.md
src/site/content/en/learn/design/media-queries/media-queries.assess.yml

Fixes #7105
- Fix meta viewport code samples to use the correct attribute: "content"
- https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag#viewport_basics
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attributes

Fix meta viewport tag content

---

src/site/content/en/blog/declarative-shadow-dom/index.md

The prior Declarative Shadow DOM polyfill code does not work for nested custom elements. When an outer `template[shadowroot]` gets converted to a `shadowRoot`, any nested DSDs are no longer accessible on the `document`. Instead, we have to search any `shadowRoot`s we attach in order to find any nested DSDs.
Alternately, we might be able to process them in reverse order, in order to implicitly handle more deeply nested nodes before the nodes they're nested within, but that seems more fragile & magical.
See https://glitch.com/edit/#!/experienced-mint-wednesday for an example that requires this change.
Fixes #7107

Add nested shadowRoot support to DSD pollyfill

---

.github/stale.yml

- The stalebot is a useful tool for identifying what issues have gone stale, but the tech writers team has decided that it is not a prudent tool for issues with the "content" label, as some content-related issues have an arc over a long period of time, and may be mistakenly marked "stale" when they are actively in development (but their respective issues have not been touched for a while).

Exempts the content label from being processed by stalebot.

---

src/site/content/en/blog/window-controls-overlay/index.md

- Remove OT info
- Add launch info

[Window Controls Overlay article] Remove OT info, add launch info

---

src/site/content/en/blog/hid/index.md

This PR adds a udev example rule for WebHID so that Linux users can access HID devices with Chromium.
See https://github.com/WICG/webhid/issues/87
@nondebug FYI

Add udev example rule for WebHID

---

package-lock.json
package.json
src/lib/analytics.js

This PR updates the version of the [web-vitals](https://github.com/GoogleChrome/web-vitals/) library used on web.dev. It also adds two additional metrics (FCP and TTFB) that we can use to help debug performance issues.
I have a few additional performance improvement PRs that I plan to submit shortly, but I'd like to get this PR merged first so we can compare the before and after results.

Update the web-vitals library and metrics

---

firebase.incl.json
src/site/_data/site.js

After a recent perf audit of web.dev, I noticed that HTML pages were not being cached on the CDN. For example, if you run:
```sh
curl -svo /dev/null https://web.dev/
```
The response headers always show a miss, no matter how many times you request the page from the same machine:
```
< x-cache: MISS
< x-cache-hits: 0
```
I reached out to the Firebase team to see if they could give me data on our cache hit rate, and this is what I found (broken down by content type):
This chart shows that the cache hit rate for subresources (JS, CSS, images, font) is actually pretty good, but the hit rate for documents is terrible. And this confirms my local testing. HTML pages are basically never being cached, despite the use of the [Surrogate-Control](https://developer.fastly.com/reference/http/http-header …

Update CDN cache config

---

src/lib/components/Assessment/_styles.scss

add flex-direction to web-assessment__content  class
Fixes #7184
- add `flex-direction: column` to `web-assessment__content` class

add flex-direction to web-assessment__content

---

src/site/content/en/blog/gamepad/index.md

[Gamepad article] Remove `GamepadList` refs

---

src/site/_includes/post-old.njk

- Delete `post-old.njk` layout, not used anymore
-
-

refactor(post): remove `post-old.njk` layout

---

src/lib/components/Carousel/index.js

Fixes #6609 fixes #6776
- add click listener to carousel instead of click on carousel children
- also break for a tags
-

fix(carousel): add click listener to carousel instead of click on carousel children, also break for a tags, fixes #6609 fixes #6776

---

package-lock.json
package.json
src/site/_data/site.js

This PR updates the web-vitals JS library to address an issue fixed in https://github.com/GoogleChrome/web-vitals/issues/201.
This change should have no effect on the functionality of the site, but it'll address an issue with the accuracy of the TTFB data we're reporting to Google Analytics.

Update web-vitals to 2.1.4

---

src/site/content/en/blog/webtransport/index.md

This contains updates to https://web.dev/webtransport/
The WebTransport API has left origin trial and is now shipping by default in Chromium 97+.

WebTransport OT => shipping updates

---

src/site/content/en/blog/porting-libusb-to-webusb/index.md

1) Looks like more platforms migrated away from libusb since I wrote this, so "some" is more accurate than "many".
2) When talking about "some platforms", "Chromium" clarification is unnecessary.
Follow-up to #7151 
-
-
-

Little reword to the "fun fact" in USB article

---

src/site/content/en/blog/devices-introduction/index.md
src/site/content/en/blog/hid/index.md

This PR mentions the handy [HID Explorer web app](https://nondebug.github.io/webhid-explorer/) in https://web.dev/devices-introduction and https://web.dev/hid

Mention HID Explorer tool

---

.eleventy.js
src/component-library/callout/callout.njk
src/scss/blocks/_callout.scss
src/site/_filters/find-by-url.js
src/site/_includes/components/CodelabsCallout.js
src/site/content/en/lighthouse-seo/http-status-code/index.md
test/unit/src/site/_filters/find-by-url.js
test/unit/src/site/_filters/index.js
test/unit/src/site/_includes/components/CodelabsCallout.js
test/unit/src/site/_includes/components/index.js

- Remove old HTML.
- Fix layout of links to message so they're side by side like old design.
- Add some typings to functions for code quality.
- Add tests.

refactor(CodelabsCallout): remove old callout HTML and fix layout

---

src/scss/_rollout.scss
src/scss/blocks/_stack-nav.scss

Fixes #6915
- set colors and backgrounds with `get-utility-value` and new design system colors.
-
-
[See here for demo](https://threadit.app/thread/rz4odvh5ear9238mcx83/message/p5eg7kl9fcml85ohuxlg8hl6?utm_medium=referral-link)

fix(search): fix dark mode for search, fixes #6915

---

src/lib/components/AssessmentQuestion/_styles.scss

Fixes #7219
- Set flex to `1` so on mobile it takes up space
-
-
[See here for demo](https://threadit.app/thread/tnlgi4mjsnjb07mj2bzp/message/r4tphgib90dl0d2990ht8lwq?utm_medium=referral-link)

fix(assessment): display full question in mobile, fixes #7219

---

src/site/content/en/learn/design/ui-patterns/index.md

- Fix typo in the related article link
Original link leads to https://web.dev/learn/design/ui-patterns/css-scroll-snap/
Actual expected target is https://web.dev/css-scroll-snap/

Fix internal page link to be root-relative

---

src/site/content/en/blog/file-handling/index.md

[File Handling article] Remove launch info

---

src/site/content/en/blog/nfc/index.md

This PR adds a new section that explains how to make an NFC tag permanently read-only with the NDEFReader `makeReadOnly()` method.
FYI @zolkis @kenchris @reillyeon

Add "Make NFC tags read-only" section to Web NFC article

---

src/site/content/en/blog/better-responsiveness-metric/index.md

`minDuration` should have been `durationThreshold` (as per spec and local testing)

Replace typo in JS snippet for responsiveness post

---

src/site/content/en/payments/how-payment-request-api-works/index.md

Requires user activation before calling `show()`.

Append a note that Payment Request `show()` requires a user activation.

---

.eleventy.js
src/site/_includes/partials/item.njk

Related to #7225
Fixes only titles, links fixed in #7283
- Add `i18n` to urls used to display paths' items' links

fix(i18n): display i18n titles of courses in paths

---

src/site/content/es/secure/cross-origin-isolation-guide/index.md
src/site/content/ja/secure/cross-origin-isolation-guide/index.md
src/site/content/ko/secure/cross-origin-isolation-guide/index.md
src/site/content/pt/secure/cross-origin-isolation-guide/index.md
src/site/content/ru/secure/cross-origin-isolation-guide/index.md
src/site/content/zh/secure/cross-origin-isolation-guide/index.md

This patch removes "JS Self-Profiling API" from outdated translations in cross-origin isolation guide article

Remove JS Self Profiling from translations in cross-origin isolation guide article

---

src/site/_data/paths/secure.json
src/site/content/en/blog/reporting-api/index.md
src/site/content/en/blog/strict-csp/index.md
src/site/content/en/secure/network-error-logging/index.md

Context:
_This PR is a prerequisite to retiring [this obsolete webFundamentals Reporting API article](https://developers.google.com/web/updates/2018/09/reportingapi). 
Most of the content in that webFundamentals article is obsolete. So we want to redirect it to the [new Reporting API article](https://web.dev/reportingapi). 
But before we can do that, we need to make Network Error Logging content, that's supported in the old Reporting API but not in the new one, available somewhere.
This is what this PR is about._
- Add new article _Network Error Logging_; its content is extracted from https://developers.google.com/web/updates/2018/09/reportingapi 
- Reference this _Network Error Logging_ article where relevant.
@agektmr Would you please drop your …

Added Network Error Logging article (migrated from web fundamentals)

---

src/site/_data/authorsData.json
src/site/_data/i18n/authors.yml
src/site/_data/paths/secure.json
src/site/_filters/find-by-url.js
src/site/content/en/secure/enable-https/index.md

Migrating the article from https://developers.google.com/web/fundamentals/security/encrypt-in-transit/enable-https

Migrate enable-https article

---

src/lib/components/Assessment/_styles.scss

Fixes #7262
- set overflow to auto when web-assessment is open
-
-
https://threadit.app/thread/to9fc3kmn1kb36rd6aap/message/vi5rb2u9183l10pvsdagt9dq?utm_medium=referral-link

fix(assessment): allow overflow on mobile, fixes #7262

---

src/site/content/en/handbook/inclusion-and-accessibility/index.md
src/site/content/en/handbook/markup-media/index.md
src/site/content/en/handbook/quality/index.md

It is imperative that our guidance for content creators is both technically accurate and inclusive. With that, I've made some updates to accessibility guidance. There will be more updates in the future, but this is a good place to start.
- Updates to the handbook's accessibility guidance
- Clarify inclusion vs. accessibility needs
- Add GDDSG references
- Update guidance for alt text
- Add guidance on preferred words (and words to avoid)
- Add plain language guidance, which replaces grade level readability
- Our work should match the guidelines
- "Keep it simple" to "Keep it concise" -- the jump link still says "simple" to avoid breaking references. This can be updated at a future date.
- Update example code for `<figure>` element which was …

[A11y] Handbook updates for accessibility

---

src/site/content/en/handbook/word-list/index.md

- Move words to avoid to a separate section, instead of using the crossed-out style
- Add "spec" to words to avoid, as noted in https://github.com/GoogleChrome/developer.chrome.com/pull/2069

Update Handbook word list

---

src/site/content/ja/secure/same-site-same-origin/index.md

- Fix Japanese translation of "schemeful samesite" (based on https://developers-jp.googleblog.com/2020/12/chrome-same-site.html)
cc/ @agektmr

Fix "schemeful same-site" translation in Japanese

---

src/site/content/en/fast/content-delivery-networks/index.md

- Goal behind the performance of CDN's is minimizing latency and maximizing cache hit ratios. I think this needs to be changed as the current statement is contradicting the goal.

Update "Content delivery networks (CDNs)" post for contradicting statements

---

src/site/content/es/blog/off-main-thread/index.md

- Fix `Use web workers to run JavaScript off the browser's main thread` Spanish translation, the current sentence means `Use web workers to run JavaScript FROM the browser's main thread`
`presubmit`

Fix off-main-thread Spanish translation

---

src/site/content/en/blog/webcodecs/index.md

This PR fixes some nits in the WebCodecs article:
- Prettier JS formatting
- Use `const` instead of `let` when appropriate in JS snippets
- Use camelCase instead of snake_case for variable names and functions in JS snippets 
- Remove extra declarations in JS snippets
- Replace `wicg` with `w3c` in links
- Fix not existing links
- And other nits/typos.

Fix nits in WebCodecs article

---

src/scss/blocks/_toggle-switch.scss

- Make sure the entire toggle switch has a type `pointer` cursor, currently only the `input` has it, which looks bad.

Type `pointer` cursor for the entire toggle switch

---

src/site/content/en/fast/priority-hints/index.md

Fixes #7326
This PR updates the info regarding the origin trial to recommend specifying the `Origin-Trial` HTTP header rather than in a `<meta>` HTML element using `http-equiv`.

Updates the priority hints post re: origin trial info.

---

src/site/content/en/fast/reduce-javascript-payloads-with-tree-shaking/index.md

This migrates [the tree-shaking guide from WebFundamentals](https://developers.google.com/web/fundamentals/performance/optimizing-javascript/tree-shaking) to web.dev. It has also been updated to reflect the current web.dev style guide, and some outdated info has been removed altogether. However, updates were not comprehensive enough to warrant changing the update date in the front matter, so this shouldn't appear as a "new" article.
[This PR](https://github.com/google/WebFundamentals/pull/9500) adds a redirect on WebFundamentals to migrated guide.

Migrates the tree shaking guide from WebFundamentals.

---

src/site/content/en/blog/hid/index.md

This PR adds a new section that explains how to revoke access to an HID device with the new HIDDevice `forget()` method.
FYI @nondebug

Add HIDDevice.forget()

---

src/site/content/en/learn/design/internationalization/index.md

in https://web.dev/learn/design/internationalization/#identify-a-linked-document's-language there's a paragraph saying
> You can also use the `hreflang` attribute on the `link` element. This goes in the `head` of your document:
but the following code uses `lang`. this patch fixes it.
-
-
-

[Learn Responsive Design] change `lang` to `hreflang` in the Internationalization article

---

src/site/content/en/lighthouse-best-practices/external-anchors-use-rel-noopener/index.md

Lighthouse no longer checks for links with `target="_blank"` having the `rel="noopener"` attribute since `rel="noopener"` is implied already in all current evergreen browsers.
(maybe the content on this page needs further updates to note that?)

fix: remove dead link

---

src/site/content/en/learn/css/the-cascade/index.md

Calc is already being used in clamp. Make clamp easier to read.
Fixes #6854

refactor: clamp expressions can take math functions

---

src/site/content/en/accessible/control-focus-with-tabindex/index.md

Fixes #7269 
The focus ring was barely visible in dark mode. As it is important to be able to see which item has focused I've made a very obvious ring. I moved the demos to CodePen so they could be part of the web.dev account and therefore editable by anyone on the team.

making the tabbed item visible

---

src/site/content/en/fast/priority-hints/index.md

This PR makes the fix that #6764 would have if stablebot had not marked the PR stale and the branch wasn't deleted. It fixes a small typo in the priority hints code where an inline `rel` attribute value wasn't written as a string when it needed to be.

Fixes issue from closed PR #6764

---

src/site/_data/i18n/paths/lighthouse_accessibility.yml
src/site/_data/paths/lighthouse-accessibility.json

Lighthouse report will be changing the link here:
from https://developers.google.com/web/fundamentals/accessibility to https://web.dev/lighthouse-accessibility/
Adding link to /accessible to give developers a starting point on a11y. Hopefully all the content under that group of pages is equivalent to the old link (I did not verify. I would have liked to linked to it aswell in /lighthouse-accesibility, but I could not work eleventy).

add link to /accessibile from /lighthouse-accessibility

---

src/site/content/en/blog/trusted-types/index.md

Carrying this change over from https://github.com/GoogleChrome/web.dev/pull/6582, which we couldn't merge, as it seems important.
CC: @koto @agektmr

Use document, not window event listener for securitypolicyviolation

---

src/site/content/en/blog/fetch-metadata/index.md

- Firefox supports fetch metadata as of Firefox 90, update the fetch metadata article to note this.

Update fetch metadata article to state that Firefox supports FM

---

src/site/content/en/blog/constructable-stylesheets/index.md

Moving the post from https://developers.google.com/web/updates/2019/02/constructable-stylesheets to this site.

Moving the constructable stylesheets post to web.dev

---

run-algolia.js

This is useful for determining why `npm run algolia` fails. Without it, there's just a generic `The promise rejected with the reason "#<Object>".` logged.

Log the exception when Algolia fails to run

---

src/scss/pages/_course.scss

Fixes #7345
This layout shift appeared to only be happening intermittently, but setting a max-width on the sidebar should prevent it in the future.

Fix layout shift by setting a max width on sidebar

---

src/lib/components/ResponseThinkAndCheck/_styles.scss

Fixes #7424
Changed from `color: $PRIMARY_TEXT_COLOR;` to `color: var(--color-mid-text);`
- enhanced the contrast ratio from `1.06` to `10.14`.
- it's working well in both Dark and Light themes.

Fix: changed the color from $PRIMARY_TEXT_COLOR  to var(--color-mid-text) to enhance the contrast in the Dark theme

---

src/site/content/en/lighthouse-performance/uses-rel-preconnect/index.md

Fixes #7445 
- Add double quotes to all occurrences of `<link rel=preconnect>`

Add double quotes to rel=preconnect occurrences

---

src/site/content/en/blog/responsiveness/index.md

- Updates the language in the aside at the top of the [responsiveness metric feedback post](https://web.dev/responsiveness/) with more specific information.
cc: @anniesullie @powdercloud for thoughts/guidance on language.

Updates the language in the aside in the responiveness metric doc.

---

src/site/content/en/blog/responsiveness/index.md

As the title suggests, this is a small update to add a link to the CrUX landing page in the aside at the top of the responsiveness metric call for feedback.
cc: @philipwalton

Adds the link to the CrUX documentation to the responsiveness metric feedback page.

---

src/site/content/en/animations/animations-guide/index.md

Fixes #5946
It's not clear that the original images were ever checked in to GitHub—I can't find it in old commits—and reproducing the images with the current Firefox's DevTools is not feasible, as the interface has changed since the article was originally written.
I'm in favor of just removing the broken images, as the text itself, including the link to the authoritative MDN documentation, should be sufficiently useful.

Remove missing images from CSS Animations guide

---

src/site/content/en/accessible/accessible-tap-targets/index.md

Instead of promoting use of `pointer`, which will only catch cases where the browser/OS deems the touchscreen to be the *primary* input (thus leaving out touch-enabled laptops, where mouse/trackpad is still considered the *primary*), use `any-pointer` instead.
This also pads out the throwaway line about testing for width, which came a bit out of nowhere at the end there, and gives it some context.

Tweak media queries section for accessible tap targets

---

src/site/_includes/item-page.njk

- The page at https://web.dev/tags/case-study/ shows a misplaced \ at the top.

Remove the backslash from the landing page header.

---

src/site/_data/authorsData.json
src/site/_data/i18n/authors.yml

#7503 introduced `patrickhlauke` as an author, but there was no corresponding metadata, which broke our build.
I copied info from @patrickhlauke's GitHub profile to bootstrap things and unbreak us; Patrick, feel free to tweak that info in a follow-up PR if you would prefer to be represented differently.
(We will follow-up separately about improving the processes that allowed this breakage to occur.)

Adds missing authors data

---

src/site/content/en/learn/design/theming/index.md

Fixes #7509
There are some non-printable characters in the old URL, which ends up escaped as `%E2%80%8B%E2%80%8B` when applied to the `<a>` tag.

Fix unprintable characters in URL

---

src/site/content/en/blog/speculative-prerendering/index.md

- Suggestion to make the OT limitation explicitly written for prerender2 that it is **only for Android**
- Suggestion to update the writing of the OT period to be available until M100 (source: https://developer.chrome.com/origintrials/#/view_trial/1325184190353768449)
Fixes #7506 
cc/ @addyosmani

Updating OT limitations

---

src/site/content/en/learn/css/sizing/index.md

Fixes: #7276 
The issue was that the example imported a stylesheet setting `box-sizing` to `border-box`. I've set that back to `content-box` but also updated the test to explain that it is only 150px if the default of content-box is used.

clarifying percentage example

---

package-lock.json
package.json

Fixes #7235, fixes #7339, fixes #7513
This updates our 11ty dependency from v0.12.1 to v1.0.1-canary.3. A few other related 11ty dependencies have their versions bumped as well.
I am not thrilled about updating to a canary release, but we've [waited a few weeks for v1.0.1](https://twitter.com/eleven_ty/status/1501709420715200516) so far, and it has important performance improvements for our build. More importantly, the current 11ty version leads to incorrect exit status when our build fails, causing our presubmit tests to not correctly flag critical build issues. (See #7513.)
For those reasons, I think it's worth just biting the bullet and updating now, and we can update again once v1.0.1 is released.
I added https://github.com/11ty/eleventy-upgrade-help to the build to see if anything …

Update to 11ty 1.0.1-canary.3

---

src/site/_includes/learn-page.njk

This was the root cause of the issue in #7523, as the HTML minifier we switched to was not as forgiving about mis-matched tags as the previous one we were using.

Close the <h3> on the /learn/ page properly

---

src/site/content/en/blog/storage-foundation/index.md

Fixes #7533
This swaps out a `/` for a `-`, preventing a 404.

Replace incorrect character in an href

---

src/site/_data/i18n/tags.yml
src/site/content/en/blog/web-platform-01-2022/index.md
src/site/content/en/blog/web-platform-02-2022/index.md

Fixes #7344 
Adds a tag for the new to the web platform series, this fixes the issue requesting this but I also want to be able to link to the series from a talk.

Adding new to the web platform tag

---

src/site/content/en/blog/gpu/index.md

A request to extend WebGPU origin trial has been made:  https://groups.google.com/a/chromium.org/g/blink-dev/c/GD0shbDnFuM
I will merge this PR when/if the request gets approved.
FYI @kangz

Extend WebGPU Origin Trial

---

README.md

If someone needs to run a production build locally, chances are the `node` process will run out of memory. This includes specific instructions in the `README` for increasing `node`'s heap size.
(The underlying reasons of _why_ this is necessary are still a bit hazy—it's got something to do with how much 11ty state needs to remain in the heap during our build.)

Instructions about node heap size for local prod builds

---

src/site/content/en/blog/critical-rendering-path-adding-interactivity-with-javascript/index.md
src/site/content/en/blog/critical-rendering-path-analyzing-crp/index.md
src/site/content/en/blog/critical-rendering-path-constructing-the-object-model/index.md
src/site/content/en/blog/critical-rendering-path/index.md
src/site/content/en/blog/performance-audit-tools/index.md

https://developers.google.com/web/fundamentals/performance/audit/tools
https://web.dev/performance-audit-tools
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/adding-interactivity-with-javascript
https://web.dev/critical-rendering-path-adding-interactivity-with-javascript
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/analyzing-crp
https://web.dev/critical-rendering-path-analyzing-crp
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/constructing-the-object-model
https://web.dev/critical-rendering-path-constructing-the-object-model
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/measure-crp …

Content migration batch 9

---

package.json
src/site/content/en/blog/web-platform-02-2022/index.md
src/site/content/en/blog/web-platform-03-2022/index.md

The new to the web platform in March post. To do:

Web platform march 2022

---

package-lock.json

This resolves an issue we're having with our production deployment following https://github.com/GoogleChrome/web.dev/pull/7614, in which `npm ci` is failing with the following error:
```
Step #0 - "Install dependencies": npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
Step #0 - "Install dependencies": npm ERR! 
Step #0 - "Install dependencies": npm ERR! Invalid: lock file's @mdn/browser-compat-data@4.1.10 does not satisfy @mdn/browser-compat-data@4.1.14
```

Update to package-lock.json for @mdn/browser-compat-data

---

src/site/content/en/secure/fixing-the-japanese-keyword-hack/index.md

The current URL `/secure/how-do-I-know-if-my-site-was-hacked/` 301 redirects to `/how-do-I-know-if-my-site-was-hacked/` which 404's due to the uppercase I

fix link on "how to check if your site is hacked"

---

src/site/content/en/blog/hid/index.md

This PR adds the new `"exclusionFilters"` option to `navigator.hid.requestDevice()` in the WebHID blog post. See https://chromestatus.com/feature/5194022623641600

Add exclusionFilters to WebHID blog post

---

src/site/content/en/blog/defining-core-web-vitals-thresholds/index.md

Minor fix to the [Defining the Core Web Vitals metrics thresholds](https://web.dev/defining-core-web-vitals-thresholds) article. The first `.table-wrapper` div is missing its closing tag causing the remaining article to not display properly - missing margins, making it difficult to read the article.
Checked the translations and it seems this is only an issue in the English version.
<details><summary>Before fix</summary>
</details>
<details><summary>After fix</summary>
</details>

Fix table markup in Defining CWV metrics article

---

src/site/content/en/blog/strict-csp/index.md

This fixes #7640; specifically, the complaints about https://web.dev/strict-csp/
That page has invalid HTML due to nesting `{% Details %}` components. This is related to the issue we had with `{% Aside %}` components, which was addressed in #7648, but we can't perform the same fix—I can't get the Markdown escaping happy.
Ideally, we'd have a fix for `{% Details %}` within https://github.com/GoogleChrome/webdev-infra, but in the meantime, we can address the issue in https://web.dev/strict-csp/ via simplifying the page structure.

Markdown cleanup for Strict CSP post

---

src/site/_includes/components/CodelabsCallout.js
test/unit/src/site/_includes/components/CodelabsCallout.js

Fixes #7466
I'm working under the assumption that it's better to show English-language codelabs (and the accompanying English-language description) instead of showing nothing on a localized page where there's no language-specific codelab available.
If you disagree, then instead of falling back to checking for `en`, we can just return `''` if there's no language-specific codelab.
This ends up [looking like](https://deploy-preview-7470--web-dev-staging.netlify.app/i18n/ja/http-cache/):

Use 'en' codelabs on translated pages

---

src/site/_includes/components/Aside.js
src/site/content/en/blog/test-post/index.md

This PR does three things:
1. Fixes #7640, by ensuring that the string returned by the `{% Aside %}` component won't interact with the parent's Markdown parsing, e.g.  by including multiple newlines, which could cause a `</li>` tag to be potentially added to the middle of the returned string. The approach used here [mimics what's done](https://github.com/GoogleChrome/web.dev/blob/main/src/site/_includes/components/Label.js) in the `{% Label %}` component.
2. Adds a test case to `/test-post/` to trigger this issue. I can confirm that the test results in incorrect HTML prior to this PR, and correct HTML with this PR.
3. Removes unused code that was leftover from before our design system migration.

Fix for the Aside component

---

src/scss/next.scss
src/scss/web-components/_web-subscribe.scss
src/styles/generic/_input.scss

Fixes #7638
Our current HTML minifier removes the `type="text"` attribute from `<input>` elements, since that's the implicit value. (I don't see any [option](https://docs.rs/minify-html/latest/minify_html/struct.Cfg.html) to disable this removal.)
Our current CSS uses the presence of `type="text"` to style certain form fields, including the newsletter signup field. When those fields are unstyled, they can look jarring, especially in Dark Mode.
This PR attempts to address this by finding all the places we have explicit styling for `input[type='text']`, and adds `input:not([type])` as an additional selector to apply the same styling.
I could have also removed the `type="text"` attributes from the original HTML (since they're going to be removed during minification anyway), to keep the …

Treat missing type attribute as type=text in CSS

---

src/site/content/en/blog/declarative-link-capturing/index.md

The Launch Handler API has changed slightly, so the Declarative Link Capturing page which has a section on migration to Launch Handler needs to be updated.

Update DLC article with new launch handler API manifest changes

---

src/site/content/en/blog/building-a-dialog-component/index.md

- updates variable name inside dialog delete mutation observer callback `dialog` -> `removedNode`.

Fix typo in Building a dialog component post

---

src/site/content/en/blog/compress-images-avif/index.md

There was a missing closing HTML element that was messing up the formatting.

fix broken markup on AVIF article

---

src/site/_data/courses/pwa/toc.yml

This moves the list of capabilities to the end so that we can later replace it with something more robust at a higher level without disrupting the numbering of the parts.
@rachelandrew I marked this p0 because it blocks PRs or remaining parts in Learn PWA

Change order of Learn PWA modules.

---

src/site/_includes/components/Aside.js

Fixes #7710
Following #7648, the logic for parsing the content inside an `{% Aside %}` changed. Markdown is parsed, but there's an extra level of escaping done by default that would prevent HTML inside of `{% Aside %}` from being rendered.
It seems like it's common enough for folks to use HTML inside of `{% Aside %}` (@rachelandrew fixed a similar issue in #7680), so I think we need to enable it here rather than trying to clean up each instance.

Allow HTML in Aside components

---

src/site/content/en/blog/commonjs-larger-bundles/index.md

you talk about esm but you aren't truly using esm, b/c esm is strict about the path
this only works cuz you are using a bundler...
also extensionless file lookups makes a lot of unnecessary stats lookup on the HDD
made a benchmark on a module that included 5000 empty dummy files with and without `.js` extension and the result was that it took like like 0.5 - 1.5s longer to find all those small modules.

use extension

---

src/site/content/en/handbook/markup-media/index.md

This updated recommendation for image dimensions in the handbook matches what I've observed the best practice to be when uploading images to the CDN.
The current wording was a source of confusions for @malchata in https://github.com/GoogleChrome/developer.chrome.com/pull/2611#discussion_r852238823
@devnook, it would be great if you could confirm that this update describes what is in fact the best practice.

Info about image CDN and dimensions in handbook

---

src/site/content/en/blog/serial/index.md

This PR adds a new section that explains how to revoke access to a Serial port with the new SerialPort forget() method.
FYI @reillyeon

Add SerialPort forget() method

---

src/site/_data/i18n/tags.yml
src/site/content/en/blog/aurora-resource-inlining/index.md
src/site/content/en/blog/conformance/index.md
src/site/content/en/blog/image-component/index.md
src/site/content/en/blog/introducing-aurora/index.md
src/site/content/en/blog/script-component/index.md

There currently isn't a way to easily find content about the
Aurora project. The Insights Team suggested adding a tag to
web.dev to make our content more discoverable / searchable.

Add tag for "Aurora project" blog posts

---

src/site/content/en/handbook/quick-start/index.md

Quick start instructions still suggest adding tags to tagsData.json, which seems to have been replaced by tags.yml in the i18n folder.

Update quick start instructions for adding a tag

---

src/site/content/en/blog/stale-while-revalidate/index.md

Before the change, there is one way to misunderstand the sentence, for example:
```
Cache-Control: max-age=100, stale-while-revalidate=200
```
can be understood as "if the cache age is **covered by** 200, then it can be served from cache. If the cache age is **not covered** by 200, e.g. if it's 250-second-old, then it cannot be served from cache". That's a wrong understanding because the cache is good for 300 seconds.
(Sorry I saw instruction of "don't forget to add the `$-presubmit` label" but I don't know what that means.)

minor improvements to stale-while-revalidate blog

---

src/site/content/en/metrics/cls/index.md
src/site/content/en/metrics/fcp/index.md
src/site/content/en/metrics/fid/index.md
src/site/content/en/metrics/lcp/index.md

This PR is a slight reformatting of the existing threshold diagrams in the metrics docs, that I think were a regression in redesign (just a guess, not sure when).
The main thing this changes is the `width` and `height` attributes so they're not too small on desktop views.
Ideally our CSS would default to full width (or have an option to do so), but I didn't see anything in the existing CSS, so this was a quick fix.

Fix broken metric threshold diagrams

---

src/site/_data/site.js
src/site/_includes/partials/analytics.njk

This PR updates the analytics implementation to capture the user's color scheme preference (i.e. light vs. dark mode) as a custom dimension.
I originally wanted to include other user preferences here as well, but given that the site's analytics initialization code runs in the HTML templates, I didn't want to add too much bloat if we didn't have specific plans to use that information (please let me know if we do).

Add analytics for user color scheme preference

---

src/site/content/en/blog/web-components/index.md

Completed entire description field, instead of cutting it off at 'foll'
Seen in Safari & Chrome
Check it out for yourself: https://web.dev/web-components/

Fixing cut-off description

---

src/site/content/en/blog/virtualkeyboard/index.md

Fixes #7829 by changing the name of the event to match the specification.

geometrychanged  => geometrychange for Virtual Keyboard API

---

src/site/content/en/fast/signed-exchanges-webpackager/index.md

- Updating instructions to include Google CA specific details.

Add Google ACME cert renewal specific directions.

---

src/site/content/en/blog/virtualkeyboard/index.md

`const { x, y, width, height } = event.target;`  is incorrect. 
moving to `const { x, y, width, height } = event.target.boundingRect;` 
And switched order of paragraphs so allow referencing to the right one.

Fix virtualKeyboard geometrychange example

---

src/site/content/en/blog/usb/index.md

As raised in https://bugs.chromium.org/p/chromium/issues/detail?id=1322413, the article implied developers could jump straight from the notification to calling getDevices(). This is not the case.
FYI @reillyeon

Don't imply getDevices after notification click

---

src/site/content/en/blog/optimize-lcp/index.md

This PR updates the [Optimize LCP](https://web.dev/optimize-lcp/) post with new content to go along with an upcoming I/O talk.
This post could be published at any time, but on Thursday morning I plan to submit an update that will add an embed of the I/O session video.

Update Optimize LCP post with new recommendations

---

src/site/_data/paths/metrics.json
src/site/content/en/blog/better-responsiveness-metric/index.md
src/site/content/en/blog/optimizing-content-efficiency-javascript-startup-optimization/index.md
src/site/content/en/blog/responsiveness/index.md
src/site/content/en/blog/vitals-field-measurement-best-practices/index.md
src/site/content/en/blog/vitals-spa-faq/index.md
src/site/content/en/metrics/fid/index.md
src/site/content/en/metrics/tbt/index.md
src/site/content/en/metrics/tti/index.md
src/site/content/en/metrics/user-centric-performance-metrics/index.md

Since the new [INP metric](https://web.dev/inp/) has landed, the current docs should be updated to reflect the inclusion of that metric as a web vital. This pull request updates and tweaks language in necessary docs to mention INP where needed. This PR does _not_ update any articles about runtime/page responsiveness that were framed around a certain time period (e.g., https://web.dev/vitals-tools-2020/).

Adds INP mentions to relevant docs.

---

src/site/_includes/components/CodePattern.js

I'd noticed that the patterns page started to slow down and lag as more and more demo's are added. I added loading lazy to the pattern demo iframes and the issue is pacified. This PR contains that addition for y'all to review 👍🏻

Adds `loading=lazy` to pattern iframe embeds

---

src/site/content/en/fast/signed-exchanges/index.md

Simplify the aside text by linking to the explanation on the new landing page,
and add a comparison to the cross-site prefetching space, per the promise on
that page. Also clarify a few other sentences while I'm here.
/cc @malchata @sidlall

Changes per new cross-origin prefetch page.

---

src/site/content/en/blog/state-of-css-2022/index.md

- Fixes an example in [new media query width syntax](https://web.dev/state-of-css-2022/#was-in-min-width-or-max-width).
I think the example is wrong, can you check if I'm right?

Fix `@media min-width` example

---

src/site/content/en/blog/variable-fonts/index.md

Fixes #7774
- update the future syntax for specifying variable fonts in the `src()` descriptor

Update variable fonts src format syntax

---

src/site/content/en/blog/optimize-lcp/index.md

When I look at this page in production, I see rendering issues that weren't visible when staging the content locally. It looks like there were some HTML markup errors, but the browser corrected them when rendering the page. *However,* it looks like whatever HTML minification logic we're using in product was breaking on these issues and then not properly closing tags, leading to this in production.
Anyway, this PR should fix the issues with this page, but it'd be great if we could preview these types of things locally or on staging and be confident that the final version won't change.

Fix markup errors in the Optimize LCP post

---

src/site/content/en/blog/preload-scanner/index.md

- Fixes a problem where SVG images are too small in the [preload scanner article](https://web.dev/preload-scanner/).

Fixes image sizes in preload scanner article.

---

src/site/content/en/blog/preload-scanner/index.md

- Fixes a typo in the browser preload scanner article that inverted the intended meaning of a sentence.

Fixes a typo in the browser preload scanner article.

---

src/site/content/en/progressive-web-apps/manifest-updates/index.md

The link here is wrong: https://web.dev/manifest-updates/#cr-desktop-test
Updated with new link.

Update to new chrome internal apps link

---

src/site/content/en/secure/same-origin-policy/index.md
src/site/content/en/secure/same-origin-policy/self-assessment.assess.yml

There was errors in same-origin policy explanation in https://web.dev/same-origin-policy as described in #7584. This pull request fixes them.

Fix the issue #7584 in same-origin policy article

---

src/lib/components/UrlChooser/index.js

Fixes #7957
This adds support for navigating to URLs like http://web.dev/measure/?url=https%3A%2F%2Fexample.com which will prefill the `value` of the `<input>` field used to determine the URL that's being measured.
It also updates the current page's URL to add in the corresponding `url=...` query parameter when a report is started.

Support url=... query parameter in /measure/

---

src/site/content/en/learn/pwa/capabilities/index.md

Fix Markdown link in /learn/pwa article

---

src/site/content/en/blog/new-responsive/index.md

Fixes issue #7996 where HTML is malformatted due to missing closing tags
- Addition of missing closing tags for two `<figcaption>` elements

Adding closing <figcaption> tags

---

src/site/content/en/blog/push-notifications-web-push-protocol/index.md

There are some issues with https://web.dev/push-notifications-web-push-protocol/ following the migration to web.dev, due to the way the Markdown fenced code blocks were translated over.
Fenced blocks marked as `text` don't get their `>` and `<` characters automatically escaped, for one thing. There is also some extra indentation in some JavaScript blocks.

Clean up fenced code blocks in Web Push article

---

src/site/content/en/blog/indexeddb/index.md

We're redirecting most of the PWA learning material from d.g.c. into /learn/pwa, however this article about IndexedDB is content we don't have. Migrated as is, I've not updated.
Original: https://developers.google.com/web/ilt/pwa/working-with-indexeddb

migrating IndexedDB article from d.g.c

---

src/site/content/en/web-dev-basics-one/js-libraries-vs-frameworks/index.md

Fixes #7840 
Another of the pieces of content we are hosting for the ETT course.
Preview: https://deploy-preview-7975--web-dev-staging.netlify.app/js-libraries-vs-frameworks/

libraries vs frameworks article

---

src/site/_includes/components/BrowserCompat.js

Fixes #7447 
- Introduce a `ReleaseStatement` to lookup `status` info for a given browser release version within compatAria, compatVersion, compatProperty functions.
- Perform a `status` check to determine if the browser release is "current" or not when deciding whether to display the version number or "x" in the compat* functions.
Notes:
The BrowserCompat.js component before my proposed changes was mainly relying on [`SimpleSupportStatement`](https://github.com/mdn/browser-compat-data/blob/312dabab943fe43f7caf7466224d844fa8c4aace/types.d.ts#L134) which provided `version_added`, `version_removed` etc. But this statement type did not include the fields we needed to check the browser version status, as this information was stored in …

Update the BrowserCompat component to filter against stable browsers

---

src/site/content/en/blog/serial/index.md

- Add https://webserial.io to the list of WebSerial Demos

Add https://webserial.io

---

src/lib/actions.js

Fixes #7749
This seems to behave reasonably, as far as I can tell, in Safari and Chrome (which now natively support `inert`) as well as in Firefox (where the `wicg-inert` polyfill will still get used).
My guess is that there's a difference between native `inert` and the polyfill with regards to the children of a parent element that has `inert` set on it—but that's just a guess. In any case, removing `inert` from the parent `web-header` when the navigation drawer is open looks like it makes the navigation drawer interactive again.

Don't set inert on web-header when nav drawer opens

---

src/site/content/en/progressive-web-apps/what-are-pwas/index.md

I did a review to look for things that are obviously out of date, and corrected a few writing things along the way. There are a few things to note.
* I tried to steer away from language that implies we control how users feel ("features that users will love"). I was able to rewrite all such statements except one at the end. That it is now the only such statement in this article, I think, makes it more effective.
* The new editor is enforcing usage more strictly than I have in the past (at least around certain common colloquial usages). The [distinction between 'like' and 'as'](https://www.grammarly.com/blog/like-vs-as/?gclid=CjwKCAjwkYGVBhArEiwA4sZLuIVOYG0uzbQuRVZv-JlRVW7YqaVGmANnCNfVKsnIzSaT-qeOhfJcWRoC0hEQAvD_BwE&gclsrc=aw.ds) is now enforced.
* I also replaced 'leverage' with 'use'. The …

Review PWA intro.

---

src/site/_includes/pattern-set.njk

- Patterns page now says "On this page" instead of "Layout patterns"
It's confusing going to a patterns page that isnt about layout and seeing the ToC titled "Layout patterns" when really it's the same component as a blog post has which reads "On this page". This normalizes the text and disambiguates pattern detail pages table of contents.
side note / feature request:
if the pattern page has no sub categories, this ToC component shouldn't be present on the page because it's pointless to show "Table of contents > All". thoughts?

Fixes patterns landing page table of contents copy to match blog posts

---

src/site/_includes/homepage-next.njk

Fixes #8121 by only considering case studies with the language code of `en` for inclusion on the homepage.

Only feature English-language case studies on homepage

---

src/site/content/en/blog/howbrowserswork/index.md

- Remove duplicate hard-coded table of contents (no longer works and web.dev already offers an automated version)
- Remove mention of self-hosted translations (those seem to no longer be available after migration to web.dev)
- Relocate mention of Korean and Turkish translations under the "Translations" heading at the end of the page
- Remove unnecessary `span` inside of `figcaption` elements (no styles assigned to them)
- Remove orphan closing `</a>` tag in a table cell, causing layout issues for the remainder of the page
- Remove Aside directive around complex details under "Browsers' error tolerance" (it doesn't allow for multiple paragraphs and lists, making content difficult to read)
- Adjust markup indentation
-
-
-
When …

Remove outdated information and delete orphan closing tag

---

src/scss/blocks/_browser-compat.scss
src/site/_data/i18n/browser_compat.yml
src/site/_includes/components/BrowserCompat.js
src/site/content/en/handbook/web-dev-components/index.md

Fixes #7936 and fixes #7798
This adds logic to the existing `BrowserCompat` shortcode to do two things:
- If a feature is currently marked as being available behind a flag, show a flag icon, not a version number for the browser:
- If a feature is deprecated, show the trash icon, not a version number for the browser:

BrowserCompat UI for deprecated and flagged features

---

src/site/content/en/blog/critical-rendering-path-render-blocking-css/index.md

Current link on the page https://web.dev/critical-rendering-path-render-blocking-css/ 
leads to https://web.dev/critical-rendering-path-render-blocking-css/render-tree-construction, 
which is semantically incorrect as well as incorrect (maybe stale) link.
- Just fixing a broken link referencing to an article on Render-tree Construction

Fixed broken link referencing to Render-tree Construction page

---

src/site/content/en/blog/file-system-access/index.md

- Clarify `removeEntry()` and `move()` are still behind a flag.

[File System Access API] Add behind a flag info

---

src/site/content/en/blog/customelements/index.md

Previously entitled "Getting started with Web Audio API", which is a different article at web.dev/webaudio-intro
Fixes #8240

Correcting /customelements title to describe the article correctly

---

package-lock.json
package.json

As discussed with @rachelandrew, this is a major semver bump but from what I can tell, the breaking changes are related to TypeScript definitions that we are not dependent on. Things look okay when tested locally.
Still, we're breaking this up into a separate PR to accompany #8251 to keep it simpler if we need to roll things back.

Update @mdn/browser-compat-data to v5.x

---

src/site/content/en/blog/webrtc-basics/index.md
src/site/content/en/blog/webrtc-infrastructure/index.md

and throws an exception in chrome:
```
Uncaught DOMException: Failed to construct 'RTCPeerConnection': 'stuns' is not one of
the supported URL schemes 'stun', 'turn' or 'turns'.
```

webrtc: dont use "stuns:" which is not implemented in any browser

---

src/site/content/en/lighthouse-seo/font-size/index.md

In the image above the changed paragraph it says:
> Strive to have >60% of page text >= 12px
I think that is the same as what the text ends up saying after the this commit (?) "Lighthouse flags pages on which 40% or more of the text has a font size smaller
than 12&nbsp;px."
Maybe it would be better to change the explanation to explain this the other way around like "Unless your page have 60% or more text with text size bigger than 12px"?
I think I'm leaning towards it being more intuitive the way that the text ended up in this commit though :)
/ Trond froding
PS: Thanks a lot for all amazing content on web.dev!

Fix small text threshold explanation

---

src/site/content/en/blog/transformstream/index.md

Add `TransformStream` short blog post.
Fixes https://github.com/GoogleChrome/web.dev/issues/8250.

Add `TransformStream` short blog post

---

src/site/content/en/blog/building-a-dialog-component/index.md

- The author mentions using `overflow: auto` so the scrollbar only shows up when needed, but in the code example `overflow-y: scroll` is used.

Building a dialog component: Swap out overflow-y: scroll with auto

---

src/site/content/en/fast/serve-images-with-correct-dimensions/index.md

The distinction between relative/absolute sizing in this section seems redundant as the solution seems the same (as is the link for each one, which goes to the same article on responsive images). Makes for confusing reading and I can't see any disadvantage to consolidating these sections into one.
-
-
-

Remove distinction between relative/absolute sizing

---

src/site/_data/authorsData.json
src/site/_data/i18n/authors.yml
src/site/content/en/blog/bfcache/index.md

- Adds a section on measuring bfcache hit ratio
Also includes some other misc changes
- Removed unnecessary `=== true` code section as follow on from #4272
- Adds case study from Smashing Magazine (full disclosure - I wrote this one).

Update bfcache article with section on measuring cache ratio hit

---

src/site/content/en/handbook/word-list/index.md

- Updates the web.dev handbook's word list to include a section on terminology, starting with clarification on terms such as "Core Web Vitals", "Web Vitals" and "metrics".

Adds a terminology section to the word list section of the handbook.

---

src/site/_includes/components/BrowserCompat.js

Fixes #8333 by using a ✅ icon when there's a feature whose `version_added` field is set to `true` (as opposed to being set to an actual version number).
CC: @jpmedley

Use checkmark icon in BrowserCompat when version_added is true

---

src/site/content/en/blog/floc/index.md

- Adds note to FLoC blog post that confirms the trial ended in 2021 and developers can find an alternative proposal in Topics.
https://deploy-preview-8299--web-dev-staging.netlify.app/floc/
Addresses #8278

Update old FLoC blog post

---

src/site/content/en/blog/script-component/index.md

Noticed a small typo here https://web.dev/script-component/#third-party-scripts-in-a-next.js-blog:~:text=As%20seen%20in%20the%20video%2C%20First%20Contentful%20Paint%20(FCP)%20occurs%20at%200.4%20seconds%20on%20the%20page%20without%20the%20Script%20component%20and%200.9%20seconds%20with%20the%20Script%20component.
- Fixes text to show the Script component improves performance instead of regressing it 😁
Unless I'm misunderstanding this?

Fix typo in Next.js Script article

---

src/site/_includes/partials/post-next.njk
src/site/_includes/partials/site-header.njk

Fixes #8320 
- Our Hamburger menu button on mobile doesn't have an accessible name - added an aria-labelledby to point to tool tip (which is hidden by default), similar to other code.
- Our Article tags are in a `role="list"` but there are no list items within that list (as it's a `div` instead of `ul`, and there are no `li` items). I changed it to a `<nav>` instead (which has an implicit `navigation` role as changing the `div` to `ul` causes an indentation (requiring CSS changes), it would require wrapping the links in `<li>`s (possibly requiring further CSS changes), and other "lists" like language links do are not in `role="lists"` anyway. Plus `<nav>` is actually more accurate.

Some small Accessibility tweaks to score 100 in Lighthouse

---

src/site/content/en/fast/serve-images-webp/index.md

Fixes #3314
- Outlines how to use the HTTP `Accept` header to automatically rewrite requests for WebP images based on its contents.

Adds guidance on serving WebP images using the HTTP `Accept` header

---

src/site/_includes/spaces.njk
src/site/content/en/spaces/_example_ended/index.md

This addresses some feedback from @una ahead of the Spaces landing page launch.
All metadata is now pulled in from our standard `authors.yaml` source, instead of using Twitter metadata.
Each `space.hosts` entry in the YAML metadata for a Space can now just be set to a `authors.yaml` id. Additionally, an optional `primary_host` property can be set to an `authors.yaml` id, in order to trigger the "HOST" display tag.
I'm not sure if this follows 100% of the best practices, but hopefully it's enough to get us launched. There might be some cleanup of the templating that's needed post-launch.
Here are screenshots from the locally staged version:

Use authors data for Spaces hosts

---

src/site/content/en/blog/backdrop-filter/index.md
src/site/content/es/blog/backdrop-filter/index.md

- Replaced the word `backdrop-image` with `backdrop-filter` on the content of this https://web.dev/backdrop-filter article

fix `backdrop-image` typo

---

src/site/content/en/metrics/inp/index.md

- @mmocny clarified in #8391 post-merge that spacebar-initiated scrolling does not observe the scrolling behavior _itself_, but rather keyboard events triggered by pressing the spacebar.
cc: @mmocny

Clarifies scrolling language per @mmocny.

---

src/site/content/en/blog/godaddy/index.md

The figcaption cites "Google Data Studio" as the source of the data. The "CWV Tech Report" is hosted on Data Studio and would be a more appropriate way to credit the source.
This PR suggests changing the citation to the dashboard's shortlink: cwvtech.report.

Update GoDaddy citation of CWV Tech Report

---

src/site/content/en/blog/webaudio-intro/index.md

- Missing space in "Applying a simple filter effect to a sound" title line prevented correct formatting and inclusion of heading in TOC navigation.  Space added.

Fixes markdown formatting issue on /webaudio-intro

---

src/scss/pages/_spaces.scss

Adjust the spacing of the avatars:
1. Shrink the avatars overlap tp 30% so that the hosts faces are better visible.
2. Expand the overlap to 50% for 5 or 6 hosts to prevent current overflow:

Adjust avatar offset for bigger number of hosts

---

src/site/content/en/blog/hid/index.md

This PR updates the WebHID article by linking to the brand new https://www.chromium.org/developers/how-tos/file-web-hid-bugs/  page.
FY @nondebug

Link to "How to file WebHID bugs"

---

src/site/content/en/blog/eventsource-basics/index.md

Fixes #8346
- js -> javascript for markdown blocks
- closes php code in example, to fix markdown
https://deploy-preview-8413--web-dev-staging.netlify.app/eventsource-basics/#server-examples

Fix markdown block for php

---

src/site/content/en/metrics/ttfb/index.md

Adds TTFB guideline thresholds as [recently announced in the CrUX API addition of this metric](https://groups.google.com/a/chromium.org/g/chrome-ux-report-announce/c/v-h5gKkUEE0), as requested from the webperf community on Slack.
@philipwalton @malchata @rviscomi any thoughts on whether I've overdone it with the aside as well as the text at the top? It's a bit of repetition but trying to stress the reduced emphasis that should be placed on these thresholds.

Add TTFB guideline thresholds

---

src/site/content/en/blog/rendering-on-the-web/index.md

- Fix reversed post date and update date of the post "Rendering on the Web"
A small note, I noticed the last update date is ["2019-11-26"](https://web.archive.org/web/20220404211354/https://developers.google.com/web/updates/2019/02/rendering-on-the-web#:~:text=Last%20updated-,2019%2D11%2D26,-UTC.) on the Wayback Machine, but I'm not sure if that's unrelated, so I didn't change it here.

Fix date of post "Rendering on the Web"

---

src/site/_includes/macros/post-card.njk

In the post detail template `post-next.njk`, the subhead is treated as markdown. This PR implements that behavior in the blogpost card template as well, which is used in the blog overview.

Treat subhead as markdown in post overview

---

src/lib/components/NavigationDrawer/index.js
src/lib/components/Search/index.js

Fixes #8131
It would be great to get your take on this approach, @devnook, as I feel like I'm addressing these in an ad hoc fashion, and don't really understand how, e.g., the whole actions/state model for controlling how elements on the page behave when specific actions are being performed.
That being said, I'm basically re-adding the same logic around setting `inert` that was removed #8105, except:
- only when the search UI interface is open **and**
- only on the `<web-navigation-drawer>` element, not `<web-header>` (since the search element is a child of `<web-header>`)

Make web-navigation-drawer inert when search UI is open

---

src/site/content/en/blog/file-system-access/index.md

- Add `readwrite` mode for `showDirectoryPicker()`.

[File System Access article] Add `readwrite` mode for `showDirectoryPicker()`

---

package-lock.json
package.json
src/site/_includes/components/CodePattern.js
src/site/content/en/patterns/components/split-buttons/assets/body.html

Because Prism outputs preformatted code, it will often contain blank lines, eg if the source contains blank lines. Unfortunately the markdown parser sees that as "the HTML has ended, process as markdown".
This results in lots of malformed HTML that may appear fine in dev, but may appear differently once the minifier has chewed through it. On the live site, this resulted in articles that appeared to abruptly end (although in truth the HTML was just reparented somewhere it wasn't visible).
To avoid this, 'blank lines' (which in markdown-speak can include whitespace) are replaced with an empty span, followed by any whitespace.
The span is not an empty line in markdown-speak, so it continues to defer to HTML source.
A more robust solution would be to insert this kind of markup _after_ …

Prevent prism generating blank lines

---

src/site/_includes/components/CodePattern.js

The previous regex didn't correctly handle more than two newlines in a row. This now matches each blank line separately.

Improve regex in markdown hack

---

src/site/content/en/blog/css-border-animations/index.md

Fixes: https://github.com/GoogleChrome/web.dev/issues/8417
This PR adds the `css-border-animations` blogpost, as proposed in https://github.com/GoogleChrome/web.dev/issues/8417
Changes when compared to the draft:
- Updated publication date
- Moved demos to the `web-dot-dev` CodePen account
- Rewrote section on stretching the backgrounds
- Added a hero image
I see in the calendar that the “New to the Web Platform” post is also scheduled for the set date. Feel free to move this post further down the schedule.

Add css-border-animations blogpost

---

src/site/content/en/blog/css-border-animations/index.md

The text included some non-visible characters, breaking the link.

Fix link in `css-border-animations` article

---

src/site/content/en/blog/media-recording-audio/index.md

I believe the purpose was to highlight part of the code but it was being presented as code causing confusion by looking like types

docs(content): remove html tag in code examples

---

src/site/content/en/blog/css-individual-transform-properties/index.md

The Image service does not seem to handle `rgb(r g b a)` in SVGs when converting to another format. The boxes become black. This behavior is exposes in the `css-individual-transform-properties` post:
This PR updates the image to a version that uses `rgba(r,g,b,a,)`, which is supported.
For reference, my findings:
- ❌ RGB(R G B / A): https://web-dev.imgix.net/image/AeNB0cHNDkYPUYzDuv8gInYA9rY2/IzfmyutXOJG8DQLTxka7.svg?w=1200
- ✅ HEX: https://web-dev.imgix.net/image/AeNB0cHNDkYPUYzDuv8gInYA9rY2/NO3X4blU7sVayJx7EX25.svg?w=1200
- ✅ RGB(R G B): https://web-dev.imgix.net/image/AeNB0cHNDkYPUYzDuv8gInYA9rY2/OiZitY9ly3Gc3dsw3fGj.svg?w=1200
- ✅ RGBA(R,G,B,A): https://web-dev.imgix.net/image/AeNB0cHNDkYPUYzDuv8gInYA9rY2/4KSYYba8wDbfZsycAV23.svg?w=1200

Fix social image

---

src/site/content/en/blog/new-patterns-july-2022/index.md

A pattern isn't embedding, it was missed by me when I updated the others to their newer `patternId`'s. This updates that pattern as well.

Fixes pattern embed path

---

src/lib/components/NavigationDrawer/index.js
src/scss/blocks/_site-header.scss

This PR takes a different approach to solving #8134, thereby fixing the unpleasant side-effect as described in #8462. 
Because the whole `web-navigation-drawer` was made `inert` in #8134, the search box –which is a child of `web-navigation-drawer` on some pages– would no longer work.
Instead of making the entire `web-navigation-drawer` `inert`, this PR sets its `pointer-events` to `none`. This solves #8134 and fixes #8462 as well.

Do not make web-navigation-drawer inert. Fixes #8462

---

src/site/content/en/fast/serve-images-with-correct-dimensions/index.md

- The image dimensions guide deals largely with image file size, but there is a good place in the document to call out information on CLS-related issues, as well as evaluating whether an `<img>` element is a better choice over CSS background images due to browser preload scanner optimizations.

Adds CLS and browser preload scanner guidance to the image dimensions guide.

---

src/site/content/en/metrics/lcp/index.md

- Updates the LCP candidate information by specifying that full-viewport images are no longer considered for LCP [since Chrome 88](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/speed/metrics_changelog/2020_11_lcp.md).

Adds full viewport image guidance for LCP.

---

src/site/content/en/metrics/lcp/index.md

Hello! This change removes (what I believe to be) an outdated 'caution' aside on `/lcp` regarding tabs loaded in the background, as the web-vitals library [ignores paint metrics for tabs loaded in the background](https://github.com/GoogleChrome/web-vitals/commit/783a28ac8c77442a80038e94a1e1297e2084d7a2). This is reflected in the library's README.
The aside on `/lcp` was initially added in [August of 2019](95c072f480), and the web-vitals commit linked above landed in March of 2020, so I'm guessing the web.dev update probably just fell off the radar.

Clarify LCP 'caution' aside regarding tabs loaded in background

---

src/site/content/en/blog/optimize-lcp/index.md

- Include `fetchpriority="high"` when preloading images.
- Change lazy-loading text "deprioritized" to "delay" to more accurately reflect what this does.
- Move lazy loading warning to be beside lazy loading text.
- Explain why images are not fetched with a high priority even if discovered early.

Update Optimize LCP post with more fetchpriority guidance

---

src/site/_includes/homepage-next.njk
src/site/_includes/partials/course-cards-next.njk
src/site/_includes/path.njk
src/site/content/en/react/route-prefetching-in-nextjs/index.md
src/site/content/es/react/route-prefetching-in-nextjs/index.md

- Changes the sites use of `importance="high"` to `fetchpriority="high"` for banner images and the like, since this was renamed and Chrome no longer supports `importance`
- Update one doc (and it's translation) for similar reasons.

Update importance="high" to fetchpriority="high"

---

.github/workflows/percy-workflow.yml

See if this fixes Percy since it started failing 
- Increase memory size for node for Percy CI.

Increase Memory for Percy to prevent CI failures

---

src/site/content/en/blog/iframe-lazy-loading/index.md

The document said there was three possible values for the attribute “loading”, when only two `exist`

There are two values for attribute “loading”, not three

---

src/scss/web-components/_web-copy-code.scss

Fixes #8507. This adds `position: relative` to the `web-copy-code` button as currently the UI element is positioned absolutely and by this jumps to the next relative element which is the wrapping `article` element.

Make web-copy-code position relative

---

.github/pull_request_template.md

Remove instruction to run presubmit

---

src/site/content/en/metrics/cls/index.md
src/site/content/en/metrics/fcp/index.md
src/site/content/en/metrics/fid/index.md
src/site/content/en/metrics/inp/index.md
src/site/content/en/metrics/lcp/index.md
src/site/content/en/vitals/index.md
src/site/content/es/metrics/cls/index.md
src/site/content/es/metrics/fcp/index.md
src/site/content/es/metrics/fid/index.md
src/site/content/es/metrics/lcp/index.md
src/site/content/ja/metrics/cls/index.md
src/site/content/ja/metrics/fcp/index.md
src/site/content/ja/metrics/fid/index.md
src/site/content/ja/metrics/lcp/index.md
src/site/content/ko/metrics/cls/index.md
src/site/content/ko/metrics/fcp/index.md
src/site/content/ko/metrics/fid/index.md
src/site/content/ko/metrics/lcp/index.md
src/site/content/pt/metrics/cls/index.md
src/site/content/pt/metrics/fcp/index.md
src/site/content/pt/metrics/fid/index.md
src/site/content/pt/metrics/lcp/index.md
src/site/content/ru/metrics/cls/index.md
src/site/content/ru/metrics/fcp/index.md
src/site/content/ru/metrics/fid/index.md
src/site/content/ru/metrics/lcp/index.md
src/site/content/zh/metrics/cls/index.md
src/site/content/zh/metrics/fcp/index.md
src/site/content/zh/metrics/fid/index.md
src/site/content/zh/metrics/lcp/index.md

Fixes #8547
- Add note that iframes count to CWV docs
- Remove "CLS has changed" warning as over a year old now.
- Update `master` to `main` as web-vitals.js has moved.

CWV iframes info

---

src/site/content/en/fast/reduce-webfont-size/index.md

- Ilya's [web font optimization guide](https://web.dev/reduce-webfont-size/) had several bits of guidance that are no longer necessary now that Internet Explorer 11 is end of life. The entire guide has been updated to avoid recommending EOT and TTF fonts, and only recommends WOFF usage for legacy browser support.
- Adds general guidance around LCP and CLS.

Updates web font optimization guide with updated advice and Core Web Vitals guidance.

---

src/lib/utils/language.js
src/site/_filters/urls.js
src/site/_includes/components/LanguageList.js

Fixes #7430 
- Sort the `langhrefs` array with structure ['es', '/i18n/es/some-page', ...] by languages that are within the Latin script group.
- Sort the `langhrefs` array once more to ensure the latin script languages are sorted alphabetically.
- Non-latin script languages will keep their relative ordering
- Add `scriptGroups` object representing language script groups.
Page: https://web.dev/splash-screen/
**Before:**
Available in: [Español](https://web.dev/i18n/es/splash-screen/), [한국어](https://web.dev/i18n/ko/splash-screen/), [Português](https://web.dev/i18n/pt/splash-screen/), [中文](https://web.dev/i18n/zh/splash-screen/), [English](https://web.dev/i18n/en/splash-screen/)
**After:**
Available in: …

Sort language list to have Latin script languages appear first and alphabetically sorted, while maintaining relative ordering

---

src/site/_filters/slugify.js
src/site/_plugins/markdown.js

Follow on from #8263 - looks like I missed question marks from filter breaking some links
- Add question marks to slugs filter so https://web.dev/cls/#what-is-a-good-cls-score works again, rather than requiring [https://web.dev/cls/#what-is-a-good-cls-score?](https://web.dev/cls/#what-is-a-good-cls-score?) which also doesn't play nice with GitHub markdown auto conversion (I had to linkify it properly myself) - another reason to fix this!

Strip question marks from slugs

---

src/site/content/en/accessible/style-focus/index.md

* updated info about button focus in Firefox on macOS
* rm block about `:focus-visible` is experimental
1. Seems like focus works correctly in `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0`
2. It have nice browsers support by https://caniuse.com/?search=focus-visible info

docs(style-focus): button focus macos firefox

---

src/site/_filters/slugify.js
src/site/_plugins/markdown.js

Another addition to #8263 and #8549 (the gift that keeps on giving!) that I discovered is needed after writing an article with HTTP/2 in a heading.
- Removes `/` from slugs

Slugify slash

---

src/site/content/en/blog/optimizing-content-efficiency-loading-third-party-javascript/index.md
src/site/content/en/blog/performance-http2/index.md
src/site/content/en/blog/rendering-on-the-web/index.md
src/site/content/en/fast/apply-instant-loading-with-prpl/index.md
src/site/content/en/fast/efficiently-load-third-party-javascript/index.md

- Minor tweaks where we push HTTP/2 push (pardon the pun), but shouldn't since it's going away.

Remove HTTP/2 Server Push recommendations

---

src/site/content/es/learn/css/sizing/index.md

Fixes #8420 
- Replace `movimiento rápido del ojo` with `rem`

Fixed rem units translation

---

src/site/content/en/learn/design/responsive-images/images.assess.yml

The correct word to use in this context is "complement," not "compliment."
- Fixing the spelling of two words
-
-

Fix spelling mistakes

---

src/site/_includes/partials/site-footer.njk

Web Fundamentals is gone, removing the link from the footer.

remove webfu from footer

---

src/site/content/es/metrics/lcp/index.md

- Replaced the word "pain" to "paint" in the spanish version of https://web.dev/i18n/es/lcp/ article.

Fix spanish translation typo

---

src/site/content/en/blog/prefers-reduced-motion/index.md
src/site/content/es/blog/prefers-reduced-motion/index.md
src/site/content/ko/blog/prefers-reduced-motion/index.md
src/site/content/pt/blog/prefers-reduced-motion/index.md

Resolves #8569. This removes the language hints for the code blocks as they are not supported with `{% aside %}`.

Do not use block syntax in `{% aside %}` in `prefers-reduced-motion` article

---

src/site/content/en/learn/pwa/installation-prompt/index.md

The glitch was pointing to the original code not to the copy owned by web.dev team and it had an error. So I fixed the web.dev copy and now I'm fixing the link to the glitch to point to the correct one.

Fixing glitch in a glitch

---

firebase.incl.json
package-lock.json
package.json
src/site/_data/site.js

This PR continues the work done in https://github.com/GoogleChrome/web.dev/pull/8517 and updates the [webdev-infra](https://github.com/GoogleChrome/webdev-infra) package, so `fetchpriority` works with the image shortcode.

Update webdev-infra to enable fetchpriority use

---

src/site/content/en/fast/reduce-javascript-payloads-with-code-splitting/index.md

Related to #7518 
- Minor content fix for correctness. The previous code example ran `someFunction` immediately instead of inside the promise callback.

Fix typo in code splitting code sample

---

src/site/content/en/metrics/inp/index.md

- Now that the `web-vitals` JS library is out of beta, we can remove mentions of it in articles.

Removes mention of the web-vitals next tag in the INP documentation.

---

src/site/_includes/partials/course-cards-next.njk

@philipwalton as discussed this removes `fetchpriority="high"` from learn cards.
- [Home page](https://web.dev/) - they are way down the page so shouldn't be high.
- [Learn page](https://web.dev/learn/) - They aren't LCP elements on desktop (only mobile) so only getting it right half the time.
Turns out didn't need `loading="auto"` as not using the `{% img %}` template so don't default to lazy loading.

Remove fetchpriority from course cards

---

src/site/content/en/blog/milliseconds-make-millions/index.md

Fixes 404'd URL referenced in https://web.dev/milliseconds-make-millions/
- removed old article url: https://www2.deloitte.com/ie/en/pages/consulting/articles/milliseconds-make-millions.html
- replaced with: https://www2.deloitte.com/content/dam/Deloitte/ie/Documents/Consulting/Milliseconds_Make_Millions_report.pdf

Updated blog url for Milliseconds Make Millions

---

src/site/content/en/fast/remove-unused-code/index.md

- Updates the [remove unused code post](https://web.dev/remove-unused-code/) intro with a note about how unused code can affect certain Core Web Vitals and other metrics.

Adds core web vitals guidance to the remove unused code guide.

---

src/site/content/en/blog/bfcache/index.md

Fixes links at https://web.dev/bfcache/#measuring-your-bfcache-hit-ratio:~:text=The%20Chrome%20team%20is%20working%20on%20a
Brackets are the wrong way around!

Fix bfcache link

---

src/site/content/en/blog/is-it-modal/index.md

I think it’s a good idea to always say “the three *major* browser engines” because there are other, smaller browser engines.

Make text more exact

---

src/site/_includes/partials/post-next.njk

Resolves #8574. This PR stops adding the slugified title as an id to the `h1` of our posts. As the headline is not linkable from the UI (other headlines show a # you can use to copy a deep link) this should not affect anyone.

Do not add an id to h1 in posts

---

src/scss/next.scss

Long strings (like URLs) wrapped in `code` elements used in paragraphs can cause overflow issues. This PR allows them to break. Fixes #8262.
**Before**
**After**

Break words in `p code` elements

---

src/site/content/en/blog/is-it-modal/index.md

On https://web.dev/is-it-modal/ one of the embedded demos uses `requestFullscreen()` to open the page in fullscreen.
However, the shortcode doesn't have the `fullscreen` feature policy by default, so the demo doesn't work as expected. https://github.com/GoogleChrome/webdev-infra/blob/ac4056a326e0cb3f501fcb72c71de91a9b8ffd70/shortcodes/Codepen.js#L40-L48
This adds `fullscreen` directive to the iframe using shortcode property.
Fixes #8651
-
-
-

add `allow="fullscreen"` attribute to the `:modal` demo

---

src/scss/next.scss
src/site/content/en/metrics/inp/index.md

The [INP article](https://web.dev/inp/) overflows on mobile (I'm on an iPhone but think it's the same on Android based on desktop emulation).
- Add a CSS to allow the long code to wrap in `li code` similar to `p code` added in #8565 by @matthiasrohmer 
Note: I changed it from `word-break: break-all;` to `overflow-wrap: break-word;` to only break the word if it needs to.

Fix code overflow issue on INP article

---

src/site/content/en/blog/file-system-access/index.md

Fixes an issue in the file system access blog post that results in the exiting the loop of entries early.
https://web.dev/file-system-access/#opening-a-directory-and-enumerating-its-contents

Fixed: loop dropping out at first non file entry

---

src/site/content/en/blog/lcp-lazy-loading/index.md
src/site/content/en/blog/vitals-field-measurement-best-practices/index.md
src/site/content/en/metrics/cls/index.md
src/site/content/en/metrics/fcp/index.md
src/site/content/en/metrics/fid/index.md
src/site/content/en/metrics/lcp/index.md
src/site/content/en/metrics/ttfb/index.md
src/site/content/en/vitals/index.md

This PR updates all references to `getXXX()` function names from `web-vitals` v2 to `onXXX()` names per `web-vitals` v3 changes. It also updates documentation links since those have been moved and the links were broken.

Update web-vitals code per v3 changes

---

redirects.yaml
src/lib/analytics.js
src/site/_data/paths/learn-core-web-vitals.json
src/site/content/en/blog/debug-performance-in-the-field/index.md
src/site/content/en/blog/debug-web-vitals-in-the-field/index.md
src/site/content/en/blog/vitals-ga4/index.md
src/site/content/en/blog/vitals-spa-faq/index.md
src/site/content/en/blog/vitals-tools/index.md
src/site/content/en/learn-core-web-vitals/crux-and-rum-differences/index.md
src/site/content/en/learn-core-web-vitals/lab-and-field-data-differences/index.md

This PR updates the [Debug Web Vitals in the field]() post to reference the new [attribution build](https://github.com/GoogleChrome/web-vitals#attribution-build) in `web-vitals` v3 and adds debug guidance for INP.
However, since the post now includes INP, to avoid any confusion (consistent with other recent changes we've made) this PR also updates the title and URL of the post from "Debug Web Vitals..." to "Debug performance...".
Note: to make it easier to review the diff I've kept the original file location (if I rename the file and make changes, GitHub does not render the diff properly, so it's impossible to review). Once these changes have been approved I'll update the file location and merge.

Document new web-vitals attribution features

---

src/scss/next.scss

Fixes #8632 
New wrapping:
- Change from `word-break: break-all;` to `overflow-wrap: break-word`

Fix code block wrapping for headers

---

src/site/content/en/patterns/layout/container-query-card/index.md

The shorthand `container` property requires the `container-name` to be specified. As it's missing in the container query it uses `inline-size` as the name of the container and the default value of `normal` for the `container-type`.
The article could be slightly expanded to point out that the `@container` rule can also take the name of a container.
The same fix is required in the linked codepen at the bottom https://codepen.io/una/pen/xxLPwBX

Fix invalid/broken container query syntax

---

src/site/content/en/reliable/two-way-communication-guide/index.md

- Added `self` in sample code in service worker

Add missing `self` in the Service worker two-way-communication guide

---

src/site/content/en/blog/new-responsive/index.md
src/site/content/en/learn/css/flexbox/index.md
src/site/content/en/learn/css/grid/index.md
src/site/content/en/learn/design/micro-layouts/index.md

Linking grid, flexbox, user adaptive emulation, and container queries content to relevant DevTools docs.
Fixes [GoogleChrome/developer.chrome.com/#3271](https://github.com/GoogleChrome/developer.chrome.com/issues/3271), fixes [GoogleChrome/developer.chrome.com/#3264](https://github.com/GoogleChrome/developer.chrome.com/issues/3264), fixes [GoogleChrome/developer.chrome.com/#3263](https://github.com/GoogleChrome/developer.chrome.com/issues/3263), fixes [GoogleChrome/developer.chrome.com/#3202](https://github.com/GoogleChrome/developer.chrome.com/issues/3202).

Added links to relevant DevTools docs

---

src/site/content/en/blog/creative-list-styling/index.md

Addresses #8697. (Codepen demos will also need to be updated.)
- Add line detailing use of `start` attribute in order for list markers to count down correctly across all browsers when using `::before`.

Adding note about `start` attribute

---

src/site/content/en/blog/optimize-lcp/index.md

This PR removes an aside that we discovered today has some incorrect information. After testing this in several cases, I can confirm that webfont swap does not trigger a new LCP entry, even if it makes the node larger after the font is applied.

Remove incorrect aside in Optimize LCP

---

src/site/content/en/blog/monitor-total-page-memory-usage/index.md

- fixes/updates the demo (broken since the API was renamed in Jan 2021)
- small content updates to remove the majority of the references to the original Origin Trial, flags, etc, since the API has been shipping since m89
- demo code changes to hopefully make failure cases clearer. `performance.measureUserAgentSpecificMemory` doesn't exist when not cross-origin isolated, making it easy to confuse with the API being unsupported altogether (the report I got was that all the demo code was broken when copy/pasted into the DevTools console on some non-isolated test page)

fix performance.measureUserAgentSpecificMemory demo and update article

---

src/site/content/en/metrics/ttfb/index.md

- Fixes TTFB label on mobile view which is incorrectly labels Interaction to Next Paint
Prod:
This branch:

Fix TTFB gaphic on mobile

---

src/site/content/en/blog/optimize-lcp/index.md

Fixes typo: "know as" --> "known as"

Fix typo in optimize LCP

---

src/site/content/en/learn/accessibility/images/index.md

- minor grammar
- typo on brackets around an attribute (not an element)

Learn a11y: Grammar and typo on SVG in image section

---

src/site/content/en/learn/accessibility/index.md

https://web.dev/learn/accessibility/
> Digital accessibility, commonly abbreviated a11y, is about designing and building websites and web apps so that disabled people can interact with in a meaningful and equivalent way.
“so” was apparently part of an abandoned turn of phrase, but was kept there.

Learn a11y: Fix typo in first paragraph

---

src/site/content/en/blog/critical-rendering-path-constructing-the-object-model/index.md

- Changed Chrome DevTools Timeline to Chrome DevTools Performance panel
- Fix Chrome Devtools broken links returning 404
- Fix DOM and CSSOM construction images mismatch

change timeline to performance, fix image mismatch

---

src/site/content/en/learn/accessibility/images/index.md
src/site/content/en/learn/accessibility/motion/index.md
src/site/content/en/learn/accessibility/motion/motion.assess.yml
src/site/content/en/learn/accessibility/why/index.md

- Remove duplicate NYT article (per https://github.com/GoogleChrome/web.dev/pull/8767) and #8777
- Fix #8780 
- Fix #8771
- Plus add subheaders to break up code samples
- [Preview](https://deploy-preview-8783--web-dev-staging.netlify.app/learn/accessibility/images/#decorative-images)
- Fix #8764 
- The language used was previously for general intent. Now, the specific Windows and Android examples and noted.
- [Preview](https://deploy-preview-8783--web-dev-staging.netlify.app/learn/accessibility/why/#what-is-the-individual-impact), under "Seizure and vestibular disorders"
- Fix #8763 
- Integrated more information about the settings of different UIs and the option for a toggle in-UI
- [Preview](https://deploy-preview-8783--web-dev-staging.netlify.app/l …

Learn A11y Cleanup

---

src/site/content/en/blog/reporting-api/index.md

Fix #8624
https://deploy-preview-8786--web-dev-staging.netlify.app/reporting-api/#reports

Line breaks / space in reporting api blog post

---

src/site/content/en/learn/html/semantic-html/index.md

changes `role=header` to `role="heading"`
closes #8789

Semantic HTML code snippet typo fix

---

src/site/content/en/blog/speed-layers/index.md
src/site/content/en/blog/speed-rendering/index.md

Fixes #8722 
- remove references to `jankfree.com` in https://web.dev/speed-rendering/ and in https://web.dev/speed-layers/

Remove references to jankfree.com

---

src/site/content/en/fast/font-best-practices/index.md

- Restructures headings to allow the topics to show in the index at the side of the page
- Makes it clear inlining font-face will not cause earlier load unless all CSS is also inlined (this was raised on WebPerf slack and was original intent of this PR but then I did a load of other edits while in here)
- Adds comment on inlining CSS being a more advanced technique.
- Tones down anti-preload advice. It's still the best way to avoid font loading issues IMHO. We use it on web.dev for example!
- Expands section on font sub-setting
- Notes we're ready to move to a WOFF2 only world
- Adds comment on `font-display: block` as many (myself included!) hate the jarring shifts caused by `font-display: swap`, even if they help with LCP/CLS
- Adds short not on …

Misc edits to font best practices document

---

src/site/content/en/learn/html/document-structure/index.md

should be two or three letters, not two
Fixes #8752

Learn HTML: value of the lang attribute

---

src/site/content/en/learn/html/document-structure/index.md

Proposed changes:
- Correct `mask-icon` description according to [Apple’s docs](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html)
- Add `apple-touch-icon` example and description

Correct mask-icon description, add apple-touch-icon one

---

src/site/content/en/blog/carousel-best-practices/index.md

- Fixes tiny typo in "carousel best practices" blog post

Fix grammar typo in carousel best practices blog

---

src/site/content/en/accessible/semantics-and-screen-readers/index.md

No known associated issue number. Grammatical fix.
Removed improper use of apostrophe from HTML tags in content. The 's' was added to these tags to indicate multiples of said tag, not possessiveness.

Remove apostrophe from HTML tags

---

src/site/content/en/fast/image-cdns/index.md

The document specifies that _"[Thumbor](https://github.com/thumbor/thumbor) is the only self-managed image CDN available today."_
https://github.com/GoogleChrome/web.dev/blob/8ee8b7fcf6f37fab3f6a0fe345f720a6bc8f2629/src/site/content/en/fast/image-cdns/index.md?plain=1#L80
Looks like there are a few other alternatives out there, so saying it's the only one available today is false.
P.S. 
1. I am not affiliated with any of these projects, just stumbled upon them while doing my own research
2. I am not suggesting to accept my edit "as is", just wanted to bring the attention to the fact there are other projects out there, this PR needs revising :-)

Mention alternatives to Thumbor

---

src/site/_transforms/purify-css.js

Fixes https://github.com/GoogleChrome/web.dev/issues/8844. The CSS should already be available when 11ty starts so it can be read from the filesystem as soon as the module is available and then be reused, as only the purge result changes per page, but the input stays the same.
Improves build time quite a bit, hence squeezed it in. Test run for /en/ only, ELEVENTY_ENV=prod:
Before: Copied 31 files / Wrote 2315 files in 189.66 seconds (81.9ms each, v1.0.1)
After: Copied 31 files / Wrote 2315 files in 159.26 seconds (68.8ms each, v1.0.1)

Read CSS only once in purge-css transform instead of for every page

---

src/site/content/en/metrics/cls/index.md
src/site/content/en/metrics/fcp/index.md
src/site/content/en/metrics/fid/index.md
src/site/content/en/metrics/inp/index.md
src/site/content/en/metrics/lcp/index.md
src/site/content/en/metrics/ttfb/index.md
src/site/content/es/metrics/cls/index.md
src/site/content/es/metrics/fcp/index.md
src/site/content/es/metrics/fid/index.md
src/site/content/es/metrics/lcp/index.md
src/site/content/ja/metrics/cls/index.md
src/site/content/ja/metrics/fcp/index.md
src/site/content/ja/metrics/fid/index.md
src/site/content/ja/metrics/lcp/index.md
src/site/content/ko/metrics/cls/index.md
src/site/content/ko/metrics/fcp/index.md
src/site/content/ko/metrics/fid/index.md
src/site/content/ko/metrics/lcp/index.md
src/site/content/pt/metrics/cls/index.md
src/site/content/pt/metrics/fcp/index.md
src/site/content/pt/metrics/fid/index.md
src/site/content/pt/metrics/lcp/index.md
src/site/content/ru/metrics/cls/index.md
src/site/content/ru/metrics/fcp/index.md
src/site/content/ru/metrics/fid/index.md
src/site/content/ru/metrics/lcp/index.md
src/site/content/zh/metrics/cls/index.md
src/site/content/zh/metrics/fcp/index.md
src/site/content/zh/metrics/lcp/index.md
src/site/content/zh/metrics/ttfb/index.md

- Adds Browser Compat Data to the metric pages where available to show browser support
- Add PSI link I noticed was missing from some of the Lab Tools sections.
@philipwalton would be good to get your eyes on this to make sure I've pick the best APIs. Decided to put under the "Measure XXX in JavaScript" section.

Add Browser Compat data to metrics where available

---

src/site/content/en/blog/avoid-large-complex-layouts-and-layout-thrashing/index.md

- Removes a single letter at the end of the document which seems to be a typo.

Remove single letter at the end

---

src/site/content/en/fast/browser-level-image-lazy-loading/index.md

It appears [this information is incorrect](https://web.dev/browser-level-image-lazy-loading/#how-does-the-loading-attribute-work-with-images-that-are-in-the-viewport-but-not-immediately-visible-for-example-behind-a-carousel,-or-hidden-by-css-for-certain-screen-sizes)
Demo: https://resource-loading-examples.glitch.me/lazy-loading.html
- Correct lazy loading guidance to note hidden images may not be loaded when hidden by CSS.

Correct hidden lazy-loading information

---

src/site/content/en/learn/accessibility/assitive-technology/index.md
src/site/content/en/learn/accessibility/automated-test/index.md
src/site/content/en/learn/accessibility/design-test/index.md
src/site/content/en/learn/accessibility/forms/index.md
src/site/content/en/learn/accessibility/javascript/index.md
src/site/content/en/learn/accessibility/manual-test/index.md
src/site/content/en/learn/accessibility/patterns/index.md
src/site/content/en/learn/accessibility/user-test/index.md

Add coming soon language to Learn a11y content not yet published. It's still possible for users to get to those pages, so we should indicate why the page is blank.
Pages which will be updated this week do not have this addition.
For example https://deploy-preview-8929--web-dev-staging.netlify.app/learn/accessibility/forms/

Add coming soon to placeholder content

---

src/site/content/en/blog/optimize-cls/index.md

- Remove Emojis from article headings. They're fun, but lead to weird URLs. And the Lighthouse links don't work because of them (which was the original small thing I came to fix, but as ever couldn't hold myself back from doing other changes while in here!).
- Update `aspect/ratio` info following @jakearchibald 's [recent post on this](https://jakearchibald.com/2022/img-aspect-ratio/).
- Add info on `<source>` support for art direction which has been added since this article was published.
- Add width and height to videos (should really practice what we preach!), though they all use 16/9 so have correct space reserved anyway.
- Remove references to Lighthouse 6 and Chrome 84 as those really are quite old by now. Think it's safe to just say Lighthouse …

Update Optimize CLS article

---

src/site/content/en/blog/critical-rendering-path/index.md

Fixes #8805
Original content retrieved [here](https://web.archive.org/web/20220326164156/https://developers.google.com/web/fundamentals/performance/critical-rendering-path/).

Added missing course link/intro to Critical Rendering Path page

---

src/site/content/en/blog/badging-api/index.md

[Badging API] Actually show spec link

---

src/site/content/en/blog/web-platform-10-2022/index.md

- Fixed a broken link by removing extra parenthesis
- Linked Chrome 108 and Viewport changes links to blog articles on Chrome dev blog
@rachelandrew

Fix: Broken Links

---

package-lock.json
package.json

- Prerender2 is coming, and web-vitals 3.0.4 contains some small bug fixes for that so let's upgrade to it.

Upgrade web-vitals to 3.0.4

---

src/site/content/en/blog/website-navigation/index.md

Two of the links had Notion URLs instead of what I think are the intended destinations.
-
-
-

Fix Additional Resources links

---

src/site/content/en/blog/prefers-color-scheme/index.md

- `MediaQueryList.addListener()` is now deprecated. 
- Replaced with `MediaQueryList.addEventListener('change', () => {})`.
- See: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener
- _Note: But some older browsers only support `addListener()` right?_
Link to article: https://web.dev/prefers-color-scheme/#reacting-on-dark-mode-changes

Update MediaQueryList.addListener() code sample

---

src/site/content/en/blog/trust-tokens/index.md

Pending further updates to this article, and content restructuring.
(Not sure if 'The developer.chrome.com article [Private State Tokens](...)' is quite right, but the page title looks a bit odd on its own.)

Added aside for API rename

---

src/site/_data/paths/fast.json

- Adds [Optimize long tasks](https://web.dev/optimize-long-tasks/link) to [Fast -> Optimize Your Javascript](https://web.dev/fast/#optimize-your-javascript)
- Adds [Best practices for tags and tag managers](https://web.dev/tag-best-practices/) link to [Fast -> Optimize your third-party resources](https://web.dev/fast/#optimize-your-third-party-resources)
- Adds [Best practices for fonts](https://web.dev/font-best-practices/) to [Fast -> Optimize WebFonts](https://web.dev/fast/#optimize-webfonts)

Add three articles to /fast/ page

---

src/site/content/en/lighthouse-performance/render-blocking-resources/index.md

critical resources are now displayed with Blue and not green. Please also update the images used in article that displays the old green color for critical resources.

Updated Critical resource color to blue from green as used in the latest chrome updates

---

src/site/content/en/blog/bfcache/index.md

Fixes #9044
- Clarifies that unload handler can still allow bfcache on mobile, but that's still not a reason to use it

Add note on unload handlers on mobile to bfcache article

---

src/site/content/en/blog/components-howto-checkbox/index.md

- Fixed broken links pointing to the old page at Web Fundamentals in the "HowTo: checkbox" article.

fix: update broken links in HowTo: checkbox

---

src/site/content/en/blog/speedy-css-tip-animated-gradient-text/index.md

This is to match the font-size in other code blocks in the article.

Change font-size in code example for consistency

---

src/site/content/en/learn/forms/styling-form-controls/index.md

This PR adds some missing nuance to the custom styling of checkboxes and radios, alludes to the fact that radios and checkboxes are more styleable now than they used to be, and adds more reference materials that I've written (and the already linked to resources mentioned) but were not directly referenced via this article

provide additional info re: styling checkboxes/radios

---

src/site/content/en/blog/pagevisibility-intro/index.md

- fix code snippet in doc "Using the Page Visibility API": do not use `&lt;`, use the symbol directly

fix: do not use html markup for symbol in code snippet

---

src/site/content/en/blog/web-components-io-2019/index.md

- Fixed a broken link to `<model-viewer>` that currently spans into multiple paragraphs due to missing backticks:

fix: add backticks to fix broken model-viewer link

---

src/site/content/en/blog/webtransport/index.md

Fixes wrong documentation
Refer to the incomingBidirectionalStreams and its unidirectional counterpart instead of the older method, that is not present in current specs and implementation.

Fix part, which do not match the current spec

---

src/site/content/en/blog/components-howto-checkbox/index.md
src/site/content/en/blog/components-howto-tabs/index.md
src/site/content/en/blog/components-howto-tooltip/index.md

- Fixed indentation of code examples that are currently broken in several places,
- Removed some trailing whitespaces, extra newlines, and an extra backtick,
- Changed `window.customElements.define` to `customElements.define`.

fix: fix code indentation in HowTo: components

---

src/site/content/en/blog/website-navigation/index.md

I was reading the latest article on [building the main navigation for a website](https://web.dev/website-navigation/) and found this bit of code confusing the way it was written since it suggests that `isOpen` is true when `aria-expanded="false"` (but `aria-expanded="false"` means the menu `isClosed`). Imo, it makes more sense to check `isOpen` directly but negate the condition when updating the `aria-expanded` attribute.
(Note: I'm not sure how to update the associated CodePens, or if that's even necessary since the code is functionally the same.)

Clarify code for checking if the navigation menu is currently open

---

src/site/content/ko/fast/defer-non-critical-css/index.md

- [defer-non-critical-css](https://web.dev/i18n/ko/defer-non-critical-css/#%EC%B8%A1%EC%A0%95) page has broken image because `{` was missing in front of img tag (only ko)
- <img width="753" alt="image" src="https://user-images.githubusercontent.com/33471826/195772913-0ac4aeed-3a95-4a45-8e84-f02efe3319a8.png">
- fix alt text

'defer-non-critical-css' with broken image in ko

---

src/site/content/en/blog/bfcache/index.md

Closes #9044 
Clarifies the mobile browser behavior related to `unload` listeners. This PR builds on the changes in #9052.

Clarify browser behavior in bfcache post

---

src/site/content/en/identity/passkey-form-autofill/index.md

Removes "prerequisite" section because:
- passkeys are now available on Android devices
- the compatibility widget is misleading as it only tells it supports WebAuthn, not the Conditional UI.
-
-
-

Remove "prerequisite" section

---

src/site/content/en/learn/html/headings-and-sections/index.md

Replacing the term 'offshore dev' with 'new team member' reads better and is less location-biased.
Fixes #9159 
- Replace 'an offshore dev' with 'a new team member'

Remove biased wording

---

src/site/content/en/measure/index.njk

Fixes #9129
- Add conversion tracking on measure on the 'Try Pagespeed Insights' button

fix: conversion tracking missing on button

---

src/site/content/en/identity/passkey-registration/index.md

No issue related.
- Remove invisible characters in a code example
- Use single quotes instead of double quotes for consistency in a code example
- Use `true` for a boolean value instead of a string `"true"`

Fix typos in passkey-registration

---

src/site/content/en/learn/html/navigation/index.md

The image was supposed to be of the current page, not MLW
-
-
-

Learn HTML: navigation: correct image

---

src/site/content/en/learn/html/headings-and-sections/index.md

per https://front-end.social/@lex/109488659217731866, the placement of the codepen was indeed confusing.
-
-
-

moved codepen example

---

src/site/content/en/learn/html/links/index.md

there's a code assigning a string to `a.href` in https://web.dev/learn/html/links/#links-and-javascript ; however the string misses an opening quote.
- fix code in example

fix code in /learn/html/links

---

src/site/content/en/learn/html/document-structure/index.md

Fixes #9221
-change <script href> attribute to <script src>

Learn HTML: change <script> href attribute to src

---

src/site/content/en/learn/html/attributes/index.md

there is a style block that is supposed to be interactive and enable styling itself. If this is not allowed, https://codepen.io/estelle/pen/LYroGqK can be included as a codepen

Style element is supposed to be interactive

---

src/site/content/en/blog/media-recording-audio/index.md

This PR promotes `AudioWorklet` instead of `ScriptProcessor` in the "Access the raw data from the microphone" section from "Recording Audio from the User" blog posts.
Live preview: https://deploy-preview-9175--web-dev-staging.netlify.app/media-recording-audio/#access-the-raw-data-from-the-microphone

Use AudioWorklet instead of ScriptProcessor

---

src/site/content/en/blog/custom-elements-v1/index.md

- Fixed incorrect indentation of HTML, CSS and JS snippets in "Custom Elements v1" article.
Note: I also found broken indentation and small issues in other imported articles, see my PRs:
- https://github.com/GoogleChrome/web.dev/pull/9150
- https://github.com/GoogleChrome/web.dev/pull/9165

Fix broken indentation in Custom Elements v1 article

---

src/site/content/en/blog/customelements/index.md
src/site/content/en/blog/shadowdom-201/index.md
src/site/content/en/blog/shadowdom-301/index.md
src/site/content/en/blog/shadowdom/index.md
src/site/content/en/blog/webcomponents-template/index.md

- Fixed a bunch of broken `html5rocks` links and `#` cross references in old articles about Web Components specs,
- Improved code indentation (that apparently was messed up, especially in case of CSS), added missing backticks,
- Removed a few links that are clearly outdated, e.g. Google Plus. Replaced some other links, changed to `https:`,
- Added a missing warning to an old article about Custom Elements (inspired by those in Shadow DOM articles),
- Removed a few closing `</pre>` tags - most likely leftovers from the old website that wasn't using markdown.

Fix broken links and indentation in old WC articles

---

src/site/content/en/blog/components-howto-tabs/index.md

- Added missing parts of code to [HowTo: Tabs](https://web.dev/components-howto-tabs/) based on the [source on GitHub](https://github.com/GoogleChromeLabs/howto-components/blob/master/elements/howto-tabs/howto-tabs.js),
- Fixed one copy-paste leftover, added missing `_`, backticks and `<kbd>` tags,
- Updated the arrow functions style to align with the current Prettier defaults.

Fix missing code in HowTo: Tabs article

---

src/site/content/en/blog/howbrowserswork/index.md

There are some places in the text that reference figure numbers, but the captions don't show them.
Fixes #9245
- Add numbers to the captions of figures

Add number to figure captions

---

src/site/content/en/blog/constructable-stylesheets/index.md

Noticed this had the wrong BCD link - it likes to CSS support (which ALL browsers support).
Also removed the version number info as no longer relevant (especially with the correct BCD data).

Update Compat widget on Contructable Style Sheets Doc

---

src/site/content/en/learn/css/index.md

Fixes #9255
- Link to Learn HTML web.dev course instead of MDN's Intro to HTML

Link to web.dev HTML course instead of MDN

---

src/site/content/en/blog/optimize-inp/index.md

- Received internal feedback from an engineer that `IntersectionObserver` callbacks don't delay rendering, as they are not in the critical rendering path for the renderer. This pull request removes any mention of `IntersectionObserver` for accuracy (but preserves `ResizeObserver` mentions because those callbacks _are_ in the critical rendering path).

Removes mention of `IntersectionObserver` callbacks in the Optimize INP guide.

---

src/lib/analytics.js

After looking at some of the initial data coming into GA4, I noticed I missed updating this name from `pageview` to `page_view`.

Fix incorrect page view event name

---

src/site/content/en/blog/css-marker-pseudo-element/index.md

Fixes #9283
- hand written iframes (arent using the mixins) have been manually given lazy loading

Lazy load the iframes in the CSS marker blog post

---

src/site/content/en/learn/html/attributes/index.md

The css selectors should have a level 4 header, not 2. Also, IIRC, it has to do with IDs, not global attributes.

Learn HTML: attributes: Moved a small section

---

src/site/_includes/partials/picked-case-study.njk

- Currently the LCP image on web.dev home page is the second image, as the video doesn't count. The second image is lazy loaded, affecting our LCP :-( This PR fixes that.

Stop the web.dev homepage LCP image being lazy loaded

---

src/site/content/en/blog/workers-basics/index.md

It appears that in the batch H5R migration done in #8036, the title for the WebSocket article was mistakingly used for the WebWorker article as well. This PR restores the title from the original H5R post.
- Fix the incorrect title in the following article: https://web.dev/workers-basics/

Fix incorrect title for WebWorker article

---

src/lib/components/CourseLinks/index.js

Fixes #9277
- Remove gtag calls as currently not working and turns out they are not actually used!
- I've left the percentage calculation in there, just in case we want to surface it in the front end in future.

Remove course analytics gtags

---

src/site/_data/i18n/paths/fast.yml
src/site/_data/paths/fast.json
src/site/content/en/blog/off-main-thread/index.md
src/site/content/en/blog/preconnect-and-dns-prefetch/index.md
src/site/content/en/fast/extract-critical-css/index.md
src/site/content/en/fast/rail/index.md
src/site/content/en/progressive-web-apps/pwa-checklist/index.md

As discussed in #9336, the RAIL guidance is pre-Core Web Vitals and that should be our preference performance guidance over RAIL.
- Updates the [Fast](https://web.dev/fast/) page to remove RAIL and adds CWV section instead (plus another couple of references I noticed were missing). [Preview](https://deploy-preview-9352--web-dev-staging.netlify.app/fast/)
- Adds a note at the top of the [RAIL](https://web.dev/rail/) page about CWV (but keeps the page as linked a lot externally). [Preview](https://deploy-preview-9352--web-dev-staging.netlify.app/rail/)
- Updates most RAIL references to CWV links

Rail -> Core Web Vitals updates

---

src/site/content/en/secure/build-a-support-team/index.md

- Update "Google Webmaster Central" to our new name "Google Search Central", and the link to our homepage
- Fix the link to the the malware subforum
- "Top Contributors" are now called "Product Experts". Also fixed the link to the about page for them

Fix links and product names

---

src/site/_includes/homepage-next.njk
src/site/_includes/partials/picked-case-study.njk

The new home page redesign seems to have lost a couple of recent fetchpriority changes. This restores them.
Also the first featured card has a hardcoded background image (not an issue now as it's showing a video instead of an image but will be an issue if we revert to an image in future).

Fix fetchpriority on new home page

---

src/site/content/en/metrics/inp/index.md

The INP table of contents looks quite different to the others:
This changes it to be more in line:
- Change "good" to just good, to be consistent.
- Remove caveat about how it's hard to quantify - it is for all metrics but we don't feel the need to explain the rational for them in this doc (though the CWVs are documented in [Defining the Core Web Vitals metrics thresholds](https://web.dev/defining-core-web-vitals-thresholds/) and we should add to that if INP becomes one).
- Indent some headers to match other Web Vitals TOCs.

Slight tweaks to bring INP doc more in line with the other Web Vitals

---

src/site/_data/courses/accessibility/toc.yml
src/site/content/en/blog/learn-accessibility-available/index.md
src/site/content/en/learn/accessibility/conclusion/index.md
src/site/content/en/learn/accessibility/forms/forms.assess.yml
src/site/content/en/learn/accessibility/forms/index.md
src/site/content/en/learn/accessibility/index.md
src/site/content/en/learn/accessibility/test-assistive-technology/at.assess.yml
src/site/content/en/learn/accessibility/test-assistive-technology/index.md
src/site/content/en/learn/accessibility/test-automated/automated.assess.yml
src/site/content/en/learn/accessibility/test-automated/index.md
src/site/content/en/learn/accessibility/test-manual/index.md
src/site/content/en/learn/accessibility/test-manual/manual.assess.yml

Five modules + the final blog post have been copyedited: 
- https://deploy-preview-9287--web-dev-staging.netlify.app/learn/accessibility/forms/
- https://deploy-preview-9287--web-dev-staging.netlify.app/learn/accessibility/test-automated/
- https://deploy-preview-9287--web-dev-staging.netlify.app/learn/accessibility/test-manual/
- https://deploy-preview-9287--web-dev-staging.netlify.app/learn/accessibility/test-assistive-technology/
- https://deploy-preview-9287--web-dev-staging.netlify.app/learn/accessibility/conclusion/
- [blog post](https://deploy-preview-9287--web-dev-staging.netlify.app/learn-accessibility-available/)
Fixes: #8157, #8158, #8159, #9300, #8153 
There's also an announcement blog post. The date should match whatever the modules dates. Copyedit completed. Proposed for …

Final Learn Accessibility modules

---

src/site/content/en/blog/top-cwv-2023/index.md
src/site/content/en/index.md

- Make the 2023 CWV recommendations the featured post on the Performance section of the home page
- This drops Long Tasks post and makes Optimizing INP the second featured post. Open to swapping those if people wish? 
- Makes a small tweak to the discoverability of inline styles text after more thoughts from yesterday's conversations.

Further tweaks to CWV 2023 recommendations

---

src/site/content/en/blog/learn-accessibility-available/index.md
src/site/content/en/learn/accessibility/more-html/document.assess.yml
src/site/content/en/learn/accessibility/more-html/index.md

The announcement blog post makes it seems like the course is over rather than being fully available. This language update should clarify.
https://deploy-preview-9395--web-dev-staging.netlify.app/learn-accessibility-available/
Also addresses #9299. The assessment is corrected and more clarifying content has been added for this issue.
- https://deploy-preview-9395--web-dev-staging.netlify.app/learn/accessibility/more-html/

Learn a11y headline and corrections.

---

src/site/content/en/payments/android-payment-apps-developers-guide/index.md
src/site/content/en/payments/empowering-payment-apps-with-web-payments/index.md
src/site/content/en/payments/handling-optional-payment-information/index.md
src/site/content/en/payments/orchestrating-payment-transactions/index.md
src/site/content/en/payments/registering-a-web-based-payment-app/index.md
src/site/content/en/payments/setting-up-a-payment-method/index.md
src/site/content/en/payments/web-based-payment-apps-overview/index.md

- Remove mentions of `PaymentInstruments`
- Revert mentions of shipping address support
- Update video scripts
- chore
cc: @rsolomakhin

Update payment articles

---

src/site/content/en/fast/use-lighthouse-for-performance-budgets/index.md

When reading the article and clicking on the link to LightWallet, my first reaction was that the link was incorrectly marked up.
In its current state, it links to the article the reader is reading. This was not what I was expecting. After reading the article, I realized that LightWallet is the name used to define and test against a predefined performance budget with the Lighthouse CLI.
The update here attempts to clarify this upfront and removes the link to avoid confusion.

chore(content): clarify meaning of LightWallet

---

src/site/content/en/patterns/media/microphone-process/assets/body.html
src/site/content/en/patterns/media/microphone-process/assets/processor.js
src/site/content/en/patterns/media/microphone-process/assets/script.js
src/site/content/en/patterns/media/microphone-process/assets/style.css
src/site/content/en/patterns/media/microphone-process/demo.njk
src/site/content/en/patterns/media/microphone-process/index.md
src/site/content/en/patterns/media/microphone-process/processor.js

This PR is ready for review.
Live previews: 
- https://deploy-preview-9198--web-dev-staging.netlify.app/patterns/media/microphone-process/
- https://deploy-preview-9198--web-dev-staging.netlify.app/patterns/media/

Add microphone process pattern

---

src/lib/app.js

Fixes #9388
- Adds a bit of JavaScript to display `autoplay` on videos (and ensures `control` attribute is also set) when `prefers-reduced-motion` is enabled.
Note: `autoplay` is discouraged, and should only be used for short clips without considerable motion (if even then).

Disable autoplay when using prefers reduced motion

---

src/site/content/en/blog/webaudio-intro/index.md

The article mentioned a broken link to BufferLoader as well as not being clear about this class being a non-api feature but custom implementation.
- WebAudio API documentation

Update WebAudio documentation

---

src/site/content/en/fast/image-cdns/index.md

JPEG XR is not supported by Edge anymore, so I have changed the example to a more common scenario.

Remove mention of JPEG XR

---

src/site/content/en/blog/gpu-compute/index.md

With WebGPU now enabled on Android with https://chromium-review.googlesource.com/c/chromium/src/+/3914870, this PR updates the article accordingly.
FYI @kangz

Remove desktop only support

---

src/site/content/en/learn/images/automating/index.md
src/site/content/en/learn/images/cms/index.md
src/site/content/en/learn/images/webp/index.md

4a74bc1 Restores the sections of “Site generators, frameworks, and CMSes” that went missing.
19875a2 Adds correct syntax highlighting to several snippets in “Automating compression and encoding”
54ab806 Quick kludge to ensure sufficient contrast on the transparent PNG we snagged from https://developers.google.com/speed/webp/docs/compression
+ @AaronForinton @rachelandrew

Learn images

---

src/site/content/en/blog/optimize-lcp/index.md

The Optimize LCP page has a section about reducing TTFB and it links to the TTFB metric page. Now that we have a dedicated Optimize TTFB page, this PR updates the LCP guide to point to the TTFB guide.

Link directly to Optimize TTFB

---

src/site/content/en/learn/images/jpeg/index.md

I know the intention is to convey this step isn't hard, but using words like "just" or "simply" can end up having the uninteded effect of making the reader feel like they should know more.
-
-
-

Remove the word "simply"

---

src/site/content/en/secure/same-site-same-origin/index.md

- Replace 'schemelses' with 'schemeless'

Fix mispelled word in same-site / same-origin article

---

package-lock.json
package.json
src/lib/actions.js
src/lib/components/CourseSearchResults/index.js
src/lib/components/Search/index.js
src/lib/components/SearchResults/index.js
src/lib/components/SelectGroup/_styles.scss
src/lib/components/SelectGroup/index.js
src/lib/components/Tabs/index.js
src/styles/components/_buttons.scss
src/styles/components/_details.scss
src/styles/components/_self-assessment-hint.scss
src/styles/components/_tooltips.scss
src/styles/generic/_shared.scss

web.dev has "needs improvement" INP for both the home page and the origin as a whole
@philipwalton identified the cookie consent banner and navigation drawer as two sources of INP from [web-vitals.js element attribution data](https://github.com/GoogleChrome/web-vitals#send-attribution-data), and noticed that both the `focus-visible` and `wicg-inert` polyfills were major parts of the task blocking the main thread on interactions with those components. This PR focuses on the navigation drawer first because its performance appears worse than the consent banner and (in theory) it will be interacted with much more often than the consent banner.
@tunetheweb and I failed to coordinate, so this overlaps with #9408
This polyfill runs whether or not the browser had built-in support for …

Improve navigation drawer performance, remove/update old polyfills

---

src/site/content/en/blog/web-platform-11-2022/index.md

Correct link is https://web.dev/viewport-units/

Fix link to Viewport Units article

---

.github/dependabot.yml
package-lock.json
package.json

Follow-up to https://github.com/GoogleChrome/developer.chrome.com/pull/5237. Configures dependabot to have PRs to update @mdn/browser-compat-data and 11ty and webdev-infra.

Setup dependabot

---

src/site/_includes/components/SignPosts.js

This annoys me on [LCP page](https://web.dev/lcp/) for example:
This PR adds some spaces:
It looks like there was some stuff to set this via CSS here:
https://github.com/GoogleChrome/web.dev/blob/2a0c52d47645b519de8909da46d9baba906e2c06/src/styles/pages/_post.scss#L47-L50
But doesn't look like this is pulled in anymore (I don't really know how our scss builds to be honest) but even then, semantically, I think it should be spaces (for screen readers and the like to read it properly), so went with the simple fix.

Add space to SignPosts lists

---

src/site/_includes/partials/head.njk

The origin trial token added in #9532 was the test site one, not the production one 🤦‍♂️
This PR fixes that.

Use the correct origin trial token

---

src/site/content/en/blog/vitals-spa-faq/index.md
src/site/content/en/learn-core-web-vitals/crux-and-rum-differences/index.md

Fixes #9510
- Adds like to Soft Navs post to [How SPA architectures affect Core Web Vitals](https://web.dev/vitals-spa-faq/) post
- Similar for [Why is CrUX data different from my RUM data?](https://web.dev/crux-and-rum-differences/) post (added two references here).

Add links to soft navs experiment to SPA CWV guide and CrUX v RUM post

---

src/site/content/en/blog/web-bundles/index.md

Chrome team is no longer pursuing Navigation-to-Web-Bundles feature. The experimental implementation was removed from Chrome M112. https://bugs.chromium.org/p/chromium/issues/detail?id=994700

Add a warning to web-bundles article

---

src/scss/web-components/_web-navigation-drawer.scss

Right now, if the user tabs thru the navigation using a keyboard, the sidebar stays hidden. For 20 clicks. This forces the navigation to be visible when the focus is that sidebar.

Make navigation visible when focus is in it

---

src/scss/next.scss
src/site/_includes/base.njk
src/site/_includes/core.njk

Related to https://github.com/GoogleChrome/web.dev/issues/9589 and https://github.com/GoogleChrome/web.dev/issues/9551.
This disables the ribbon on the right hand side for now to internally test out some variants first.

Disable DevRel ribbon in current form

---

src/site/content/en/learn/html/attributes/index.md

Fixes #9332
- Fixed a typo, by adding a missing quotation mark on the learn HTML contenteditable section.
- This is the current code containing the typo:
`const editor = document.getElementById("myElement");
if(editor.contentEditable) {
editor.setAttribute("contenteditable", "false); **here is the typo**
} else {
editor.setAttribute("contenteditable", "");
}`
- Below is the link to the section.
[(https://web.dev/learn/html/attributes/#contenteditable)]

fixing minor typo 

---

src/site/_data/paths/identity.json

Fixes #9244
- Fixed reference links on [the Identity url path](https://web.dev/identity/)

Fix broken reference links in Identity

---

src/site/content/en/fast/navigation-and-resource-timing/index.md

Fixes #9557
- The [Navigation and Resource Timing API article](https://web.dev/navigation-and-resource-timing/) has an incorrect code example for the `PerformanceObserver` API re: use of the `buffered` flag.

Fixes incorrect `PerformanceObserver` code in nav/resource timing article.

---

src/site/content/en/learn/html/forms/index.md

- Image gallery wraps on a mobile viewport
Before/after

Add flex-wrap to images for the Learn HTML: Forms

---

src/scss/pages/_collection.scss

Fixes #8855 
- fixed the size of the check icon on collections TOCs so that the size remains consistent

stlye: fixed icon size table of contents

---

src/site/content/en/learn/images/descriptive/index.md

- 1. The DPR should be calculated as the division of a device's actual screen resolution by its CSS viewport pixels and not 
the other way around. i.e DPR = Actual screen resolution/Viewport's CSS pixels.
- 2. Minor typo - Replacing a period(.) with a comma(,)

Content and typo fix suggestions for Learn Images

---

src/site/content/en/fast/performance-budgets-101/index.md

Fixed a broken link performance scores link
Old link: hhttps://developer.chrome.com/docs/lighthouse/performance/performance-scoring/#perf-scoring
Fix  link: https://developer.chrome.com/docs/lighthouse/performance/performance-scoring/#perf-scoring
Fixes #9678
Link performance scores need to update
Current link: hhttps://developer.chrome.com/docs/lighthouse/performance/performance-scoring/#perf-scoring
Needs to update to: https://developer.chrome.com/docs/lighthouse/performance/performance-scoring/#perf-scoring

Fix broken link

---

src/component-library/spinner/spinner.json
src/component-library/spinner/spinner.md
src/component-library/spinner/spinner.njk
src/lib/components/Subscribe/index.js
src/scss/blocks/_spinner.scss
src/scss/next.scss
src/scss/web-components/_web-subscribe.scss
src/site/_includes/about-next.njk
src/site/_includes/homepage-next.njk
src/site/_includes/partials/subscribe.njk
src/site/content/en/newsletter/index.njk
types/utils/global.d.ts

Fixes #9528
- Loads reCAPTCHA .js script when the newsletter form element comes into view (detected via a single use IntersectionObserver)
- Shows a tiny loading animation while the reCAPTCHA script is being fetched/executed
- Tested and working on various browsers
Loading animation placeholder:
Recorded using a throttled connection.

feat: load recaptcha when newsletter form is in view

---

src/site/content/en/learn/images/cms/index.md

* update intro indicating API has improved over time
* update quality section to `wp_editor_set_quality` which controls quality for all mime types (also raise quality to 70 as 65 is quite low and likely to show degrdation - the default is 82 for JPEG and 86 for WebP currently)
* add a section explaining how to output WebP images using the `image_editor_output_format` filter
* move section explaing how uploads are handled above filter descriptions

Improve learn images CMS/WordPress section

---

src/site/content/en/learn/css/functions/index.md

- add missing space between `for` and `X`

chore(typo): Add missing space

---

src/site/content/en/web-dev-basics-one/fetch-api-error-handling/index.md

Added a missing 'not'!
Fixes #9714

Add important missing word to Fetch API error handling

---

src/site/content/en/blog/media-session/index.md

The code example is about the camera being toggled, yet the code snippet incorrectly listens for the `togglemicrophone` action. That should be `togglecamera` instead.

Media Session API: Fix code example

---

src/site/_includes/partials/head.njk

This PR adds Private Aggregation API (PAA) testing.
* Related DCC PR: https://github.com/GoogleChrome/developer.chrome.com/pull/5304
* Related Shared Storage Demo (SSD) PR: https://github.com/GoogleChromeLabs/shared-storage-demo/pull/17
---
[Private Aggregation API](https://developer.chrome.com/docs/privacy-sandbox/private-aggregation/) allows users to report cross-site data in [Shared Storage](https://developer.chrome.com/en/docs/privacy-sandbox/shared-storage/).  
This test adds a Private Aggregation API call that reports randomly generated key/value pairs.  The reports are not collected.  
The PAA test script is injected as a third-party script.  The 3p script contains its own 3p origin trial token.
---
To test, visit the staging link (TBD), then open up …

Add Private Aggregation API testing

---

src/site/content/en/fast/priority-hints/index.md

Updates the [Priority Hints](https://web.dev/priority-hints/) article to:
- Adds Browser Compat data (at the top and also in the Browser Compat section)
- Adds note that these are now part of HTML and Fetch standard even if still marked as experimental on MDN (@pmeenan will this stay that way until another browser implements this, or should this now be removed from MDN?)

Update priority hints browser compat info

---

src/site/content/en/blog/preload-responsive-images/index.md
src/site/content/en/learn/design/responsive-images/index.md

Fixes #8228 
Fixes #6150
Updates [Preload Responsive Images](https://web.dev/preload-responsive-images/) article to:
- Add Browser compat widget
- Add note about not including `href` to avoid downloading incorrect image on some browsers
- Add a note about lack of `type` support
Updates [Learn->Design->Responsive Images](https://web.dev/learn/design/responsive-images/) article to:
- Clarify `loading`
- Add note on `fetchpriority`
- Rewrite preloading section
- Add mroe context to `decoding` section

Update responsive images guidance

---

src/site/content/en/learn/html/dialog/dialog.assess.yml

Just a small mistake in the quiz section - ::backdrop is considered a pseudo-element rather than a pseudo-class.

replace pseudo-class with pseudo-element

---

src/site/content/en/blog/rendering-on-the-web/index.md

- replace `renderToNodeStream` with `renderToPipeableStream` and add new document link
- fix the broken link for `Streaming server rendering`

Update `Rendering on the Web` article

---

src/site/content/en/learn/pwa/installation/index.md

This PR fixes a dead link by using the same link as the one in the _Resources_ section.

Fix dead link to PWA installation pattern

---

src/site/content/en/blog/optimize-cls/index.md

Firefox supports `width` and `height` attributes of [&lt;source&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source) element inside a `<picture>` since version 108, so the article was changed accordingly.
Supporting notes: [Release 108](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/108)

Add support of `width` & `height` in `<source>` on firefox

---

src/site/content/en/blog/min-max-clamp/index.md

The video showing usage of max() was below the paragraph explaining how min() could be used and vice versa, which was confusing. The figcaptions of these videos also both mentioned clamp() while that function was no longer used in those examples, so I've changed those to refer to respectively min() and max() to better indicate the video contents.
- Swap location of videos
- Update figcaption text for both
Fixes #7734

Swap video's and update figcaption

---

src/site/content/en/progressive-web-apps/codelab-make-installable/index.md

Fixes #7146.
- Add aside to tell the reader to use a standalone tab.

Make it installable codelab: Add aside to tell the reader to use a standalone tab

---

redirects.yaml

A redirect to web-otp article is not happening.
This pull request fixes it.

Fix a redirect for WebOTP

---

src/site/content/en/learn/pwa/web-app-manifest/index.md

- Highlight that the workaround to make icons work in Safari is no longer needed

Add a note for Icons in Safari

---

src/site/content/en/progressive-web-apps/install-criteria/index.md

Fixes issue #9742 (or partial fix)
- The presence of a fetch handler is no longer a requirement. There might be some other changes too about required fields which can be determined through some other means. I'll loop someone more familiar with the whole set of changes.

Chrome 103+

---

src/site/content/en/blog/optimize-lcp/index.md

- The LCP breakdown code can sometimes be slightly off the LCP time due to rounding errors
- Also add warning about prerendered pages.

Correct LCP breakdown code and add warning on prerendered pages

---

src/site/content/en/blog/text-fragments/index.md

- Rename `textStart`→`start` and `textEnd`→`end` (see https://github.com/WICG/scroll-to-text-fragment/pull/218).

[Text fragments article] Rename `textStart`→`start` and `textEnd`→`end`

---

src/lib/components/NavigationDrawer/index.js

Fixes #9639, fixes  #9792 
For #9639, the navigation drawer on the mobile view needs two clicks on the outside of the drawer container to close itself. It should close when clicking just once, which is the same behaviour as when clicking on the close button.
For #9792, the local navigation of the learning courses reopens each time when click the 'Close' icon.
It happens because the focus event is still on the drawer element so it cannot be completely closed. 
Thus, the change proposed in this pull request is removing the focus event from the navigation drawer after clicking the close button or clicking outside the drawer container, using `HTMLElement.blur()`.

fix: the navigation drawer cannot be closed

---

src/site/content/en/blog/source-maps/index.md

Minor improvement to example in source-maps article

---

src/site/content/en/blog/import-maps-in-all-modern-browsers/index.md

The snippets in this article don't work together because the URL for `lodash` used points to a file that's not a module and contains no exports. Simply replacing `lodash` with `lodash-es` causes the example to work, but `lodash`'s main file transitively imports over 600 internal modules - which seems like a bad example to set. Even importing `lodash-es/map.js` directly still transitively imports over 100 modules. To both fix the example and avoid loading an unnecessarily large dependency tree for such a simple example, I've replaced `lodash` with `browser-fs-access`, which is a module and has no transitive imports.
Fixes #9856
- Replace use of `lodash` in the `/import-maps-in-all-modern-browsers/` article with `browser-fs-access`.
Edit: `d3-array` …

`/import-maps-in-all-modern-browsers/`: Fix examples by replacing `lodash` with `d3-array`.

---

src/site/content/en/blog/better-responsiveness-metric/index.md

The [responsiveness](https://web.dev/better-responsiveness-metric/) post mentions long tasks but links to MDN docs. This change updates the link to point to our more relevant long tasks guide.

Update responsiveness post to link to long tasks guide

---

src/site/content/en/blog/source-maps/index.md

- Fix link to https://developer.chrome.com/en/articles/x-google-ignore-list/

fix link to x_google_ignoreList blog

---

src/site/content/en/blog/web-platform-03-2023/index.md

Currently it shows no browser supports the new color feature.
- fix link to bcd for `color-mix()` function

web-platform-mar-2023: fix link to browsercompat color-mix

---

src/site/content/en/learn/accessibility/structure/index.md

Update learn accessibility footnote on `<section>` requiring a name attribute

---

src/site/content/en/blog/optimize-long-tasks/index.md

> The scheduler API currently offers the postTask() function which, at the time of writing, is available in Chromium browsers and Firefox behind a flag.
This is too ambiguous. People may assume that postTask is behind flag in *both* Chromium and Firefox.

Improve wording

---

src/site/_includes/partials/site-header.njk

Fixes #9874 
- prevented mobile menu button tooltip from cropping
- fixed typo in menu-button-tooltip name

9874-mobile-menu-tooltip-cropped

---

src/site/content/ko/metrics/cls/index.md

- fix wrongfully swapped links in Korean CLS doc translation

fix wrongfully swapped links in Korean CLS doc translation

---

src/site/content/en/learn/html/document-structure/index.md

Update description as in provided source https://developer.mozilla.org/en-US/docs/Glossary/UTF-8 where says `Each character is represented by one to four bytes.`

Update UTF-8 description

---

src/scss/blocks/_post-credits.scss
src/scss/next.scss
src/site/_data/i18n/post.yml
src/site/_includes/partials/post-credits.njk
src/site/_includes/partials/post.njk
src/site/content/en/blog/web-platform-01-2023/index.md
src/site/content/en/handbook/yaml-front-matter/index.md

Fixes #9817 
- Added credits section at the end of the posts
- Added support for defining editors
- Added support for adding image credit with name and link

9817 implement credits design for articles

---

redirects.yaml
src/site/content/en/blog/better-youtube-web-part1/index.md
src/site/content/en/blog/optimize-lcp/index.md
src/site/content/en/blog/preconnect-and-dns-prefetch/index.md
src/site/content/en/blog/top-cwv-2023/index.md
src/site/content/en/blog/web-platform-04-2022/index.md
src/site/content/en/fast/browser-level-image-lazy-loading/index.md
src/site/content/en/fast/fetch-priority/index.md
src/site/content/en/fast/image-cdns/index.md
src/site/content/en/fast/lazy-loading-video/index.md
src/site/content/en/learn/design/responsive-images/index.md
src/site/content/en/learn/images/performance-issues/index.md
src/site/content/en/newsletter/archive/2022/05/index.njk
src/site/content/en/react/route-prefetching-in-nextjs/index.md
src/site/content/es/react/route-prefetching-in-nextjs/index.md

As part of standardization the Priority Hints spec was moved into the HTML and Fetch specs and no longer exists as a separate specification (the [old specification was archived](https://github.com/WICG/priority-hints)). Additionally the HTML attribution was renamed from `priority` to `fetchpriority` (though the fetch attribute remains `priority` since the "fetch" part is redundant).
To reduce confusion, we have recently taken the decision to refer to this feature as "Fetch Priority" going forward (note the API is Fetch Priority and the attribute is `fetchpriority` for HTML and `priority` for Fetch).
- Rename Priority Hints article to Fetch Priority since this is the main reference point for this feature.
- Update the main article slug from …

Rename Priority Hints to Fetch Priority

---

redirects.yaml

@ThomasTheDane recorded his I/O talk and used the link "web.dev/wordpress-on-wasm" on the slide. Set up forwarding on web.dev such that this link goes to "https://web.dev/wordpress-playground/".

Add redirect

---

src/site/content/en/blog/emscripting-a-c-library/index.md

- The original somehow breaks the site: https://web.dev/emscripting-a-c-library/. This PR fixes this: https://deploy-preview-9941--web-dev-staging.netlify.app/emscripting-a-c-library/.

Reformat Emscripten article

---

src/site/content/en/identity/passkey-form-autofill/index.md
src/site/content/en/identity/passkey-registration/index.md

Update passkeys articles to explain the caveats of the difference between user verification being `preferred` and `required`.

Passkeys update

---

src/site/_includes/content/metrics/metrics-changelog.njk
src/site/content/en/metrics/inp/index.md

The Chrome Speed Metrics team recently added an INP changelog so let's add it to the INP doc
- Add INP changelog to /inp/ doc
- Add link for feedback
- Remove newlines from changelog template as they make searching for this text harder

Add INP change log

---

src/site/content/en/progressive-web-apps/add-manifest/index.md

**Describe the bug**
The Browser support widget in the [Add a web app manifest](https://web.dev/add-manifest/) article says that Chrome and Edge do no support Web manifest.
**To Reproduce**
1. Go to the [Add a web app manifest](https://web.dev/add-manifest/) article.
2. Scroll down to Browser support section.
3. Check that Chrome and Edge do not support Web Manifest.
**Expected behavior**
[can-i-use](https://caniuse.com/?search=web%20app%20manifest) says that Chrome and Edge do support web manifest, so it should be displayed in the article as well.
**Screenshots**
It seems that the [@mdn/browser-compat-data](https://github.com/mdn/browser-compat-data) package no longer supplies a dedicated `"html.manifest"` data source key.
Since `"html.manifest"` does not exist, I suggest that we use …

Fix manifest browser support data source key

---

src/site/content/en/progressive-web-apps/install-criteria/index.md
src/site/content/es/progressive-web-apps/install-criteria/index.md
src/site/content/ja/progressive-web-apps/install-criteria/index.md
src/site/content/ko/progressive-web-apps/install-criteria/index.md
src/site/content/pt/progressive-web-apps/install-criteria/index.md
src/site/content/ru/progressive-web-apps/install-criteria/index.md
src/site/content/zh/progressive-web-apps/install-criteria/index.md

Related to [#9651](https://github.com/GoogleChrome/web.dev/issues?q=is%3Aissue+is%3Aopen+criteria).  
- Remove outdated link to Samsung Internet docs. I have found [this](https://developer.samsung.com/automation/progressive-web-app.html) section about PWA as the most relevant substitution for the deleted link, but it is a user guide and does not have any mention about install criteria.
- Remove outdated link to UC Browser docs. The deleted link led to the inactive [plus.ucweb.com](plus.ucweb.com). It seems  that UC Browser no longer have an active website with the docs.

Remove outdated install criteria links

---

src/lib/analytics.js

Currently Google Tag Manager (which loads Google Analytics) is loading before the cookie state has been got. This means we always assume cookies are set to no
- Check cookie acceptance as part of analytics initialisation
- Fire an event when analytics is configured, so we can delay GA4 initialisation until this event is sent

Check cookies before loading gtm

---

src/site/_data/paths/learn-core-web-vitals.json

Just noticed that the Core Web Vitals label apears on this article twice:
This is because the page is listed twice on the https://web.dev/learn-core-web-vitals/ page
- Remove one of references

Fix CrUX-RUM label

---

src/site/content/en/learn/css/inheritance/index.md

Fixes #9976
- fix highlighted lines of css code examples in css inheritance lesson

fix highlighting in code examples (#9976)

---

src/site/_collections/authors.js
src/site/_data/i18n/authors.yml
src/site/_filters/expand-authors.js
src/site/_includes/partials/paged.njk

This annoys me:
```
Eleventy is building, please wait…
Date passed to prettyDate filter was undefined or null.
Date passed to prettyDate filter was undefined or null.
Date passed to prettyDate filter was undefined or null.
Date passed to prettyDate filter was undefined or null.
Date passed to prettyDate filter was undefined or null.
Date passed to prettyDate filter was undefined or null.
Date passed to prettyDate filter was undefined or null.
Author 'matmarquis'pages
Author 'matmarquis'pages
Author 'matmarquis'pages
Author 'matmarquis'pages
Author 'matmarquis'pages
Author 'matmarquis'pages
Author 'matmarquis'pages
Author 'matmarquis'pages
Author 'matmarquis'pages
Author 'matmarquis'pages
Author 'matmarquis'pages
Author 'matmarquis'pages
Author 'matmarquis'pages
Author 'matmarquis'pages …
```

Fix build warnings

---

src/site/_includes/components/Meta.js

Noticed this:
This is because the meta data includes imgix params:
https://web-dev.imgix.net/image/jL3OLOhcWUQDnR4XjewLBx4e3PC3/1AtWWHLH0bovMgv44FBU.svg?auto=format&fit=max&w=1200&fm=auto does not work
https://web-dev.imgix.net/image/jL3OLOhcWUQDnR4XjewLBx4e3PC3/1AtWWHLH0bovMgv44FBU.svg works
Looks like there is some logic to strip params from SVGs except if they are explicitly provided. So let's stop providing them for SVGs

Fix social thumbnails for SVG images

---

src/site/_includes/partials/head.njk

We are currently running an origin trial added in #9532 to test documentation rules to prefetch next navigations for performance reasons. We have collected data over the last few months and now want to do a full prerender, instead of just a prefetch, and collect more data on that.
We're also set the `eagerness` to `moderate` to allow it to happen on `hover` as well as `mousedown`. 
We have #9559 open to remind us to remove this origin trail after the experiment finishes (or the feature reaches stable - [currently scheduled for Chrome 115](https://chromestatus.com/feature/5112150536749056)).
Note: I opened a similar PR for d.c.c. here: https://github.com/GoogleChrome/developer.chrome.com/pull/6329

Updated prerender experiment to use prerender instead of prefetch

---

src/lib/actions.js
src/lib/analytics.js

Noticed this bug in the build:
```
> rollup -c
./src/lib/app.js, src/lib/pages/about.js, src/lib/pages/content.js, src/lib/pages/course.js, src/lib/pages/default.js, src/lib/pages/design-system.js, src/lib/pages/explore.js, src/lib/pages/home.js, src/lib/pages/learn.js, src/lib/pages/measure.js, src/lib/pages/newsletter.js → dist/js...
(!) Circular dependency
src/lib/actions.js -> src/lib/analytics.js -> src/lib/actions.js
created dist/js in 447ms
```
We don't actually need to set the config at this step so moving this back to analytics.js

Fix circular dependency in build

---

src/site/content/en/blog/bfcache/index.md

As raised by @aarontgrogg the current wording is confusing:
> Trying to get a better grasp of bfcache, but really confused when reading this page/section:
https://web.dev/bfcache/#avoid-windowopener-references
I get that I should try not to use `window.open()` or `target="_blank"`.
But if I must use one of them, is it saying I should or shouldn't use `rel="noopener"` ?
"Should" seems to make more sense, in order to sever the tie between pages, but just wanting to verify...
- Improve wording to make it clearer

Clarify confusing wording on bfcache article about noopener

---

src/site/content/en/blog/web-platform-05-2023/index.md

It’s hosted on DCC, not web.dev

Fix link to scroll-driven animations article

---

src/site/content/en/learn/pwa/assets-and-data/index.md
src/site/content/en/learn/pwa/index.md
src/site/content/en/learn/pwa/installation/index.md

We had updated the documentation pages in /pwa but we were missing the /learn/pwa bits, this PR takes care of it.

updating learn pwa to remove sw as a requirement for installability

---

src/site/content/en/blog/avif-updates-2023/index.md

- Markdown syntax was used in a `<figcaption>` in the [2023 AVIF updates post](https://web.dev/avif-updates-2023/), which does not get transformed into a link. Changed it over to an `<a>` element to fix it.

Fixes broken link in `<figcaption>` in AVIF updates post.

---

src/site/content/en/blog/strict-csp/index.md

The strict CSP article is out of date as strict CSP is supported in all modern browser engines these days. 
- Added browser compatibility widget for strict CSP
- Updated text to call out that strict CSP is now supported in all major browser engines
- Made the 'browser fallback' section optional and tweaked text to reflect this
What page(s) need to be updated?
- https://web.dev/strict-csp
- I'm not sure if/how translations are handled
Why is this update needed?
- Information is out of date
What's the deadline?
- No deadline
cc: @maudnals

Update browser support for strict CSP

---

src/site/content/en/webassembly/compiling-mkbitmap-to-webassembly/index.md

Fixes a small double backtick I noticed in the mkbitmap article.

Fix typo in mkbitmap to WebAssembly article

---

src/site/content/en/fast/fetch-priority/index.md

@pmeenan and I recently discovered that Favicons are no longer treated separately in terms of prioritisation so removing it from the table.

Remove favicon from Fetch Priority article

---

src/site/content/en/learn/html/links/index.md

`links` is a JS _property_ of the `document` object

Learn HTML, typo

---

src/site/content/en/blog/optimize-ttfb/index.md

I meant LCP here, but rereading it I think better to use TTFB rather than call out LCP in this one case, when the whole article is about improving TTFB for LCP.

Fix typo in Optimize TTFB article

---

src/site/_transforms/minify-html.js

Fixes #10218
- Stop over-stripping HTML tags. Yes technically the browser will fill them in again but it's just confusing!

Stop over minifying HTML

---

src/site/content/en/blog/get-installed-related-apps/index.md

[getInstalledRelatedApps] Linkify `assetlinks.json`

---

src/site/_data/authorsData.json

The new author https://web.dev/authors/mitchgalavan/ has a wrong Twitter URL. This pull request fixes it.

Fix a wrong author info in authorsData.json

---

src/site/_includes/homepage.njk
src/site/_includes/item-page.njk
src/site/_includes/partials/post.njk
src/site/content/en/newsletter/index.njk

This brings back the newsletter form after having been disabled in https://github.com/GoogleChrome/web.dev/pull/10120.

Re-enable newsletter sign-up form

---

src/lib/analytics.js
types/utils/global.d.ts

- Add no restored reasons API analytics as noticed we have a lot less bfcache usage on desktop than mobile and would like to understand why
- Also found a small bug when `attribution.eventEntry` is not set so included that fix too.
Equivalent change to d.c.c. is: https://github.com/GoogleChrome/developer.chrome.com/pull/7074

Add bfcache not restored reasons api

---

src/site/_includes/partials/head.njk

This expands the scope slightly, but also we're contemplating a change which would make this unnecessary -- but while developer.chrome.com is using this syntax, it's more difficult to tell at a glance how common other uses are.

Speculation rules: match any hash fragment.

---

src/site/content/en/blog/optimize-long-tasks/index.md

- Now that the [`scheduler.yield` origin trial post](https://developer.chrome.com/blog/introducing-scheduler-yield-origin-trial/) is public on d.c.c., this pull request adds an aside to the [Optimize long tasks guide](https://web.dev/optimize-long-tasks/) mentioning both the d.c.c. post and links out to the origin trial.

Adds `scheduler.yield` callout in the Optimize Long Tasks guide.

---

src/site/_data/authorsData.json
src/site/_data/i18n/authors.yml
src/site/content/en/blog/terra-prefetching-case-study/index.md

- Terra reached out to one of our Web Ecosystems Consultants and arranged to have this case study publish. This pull request adds that finished case study.

Adds Terra prefetching case study.

---

src/site/content/en/blog/ta-test-coverage/index.md

Test Automation post 5

---

src/site/content/en/blog/ta-code-coverage/index.md

- Fix wrong url and typo. It has to be "code coverage" because this article is about code coverage. In the article, we have a section specifically explain code coverage != test coverage.
- Fix low contrast table view in dark mode. The previous hardcoded value only work in light mode. Update it to use existing variable.
- Fix list image padding issue. Previously, the list item in "There are five branches in the code example:" format incorrectly due to the inline image. 
- Fix branch coverage code highlight. Previously not highlighted at all.

[ta] Fix Test Automation #5

---

src/site/content/en/blog/css-subgrid/index.md

Remaining tasks before submission:

New Post - CSS subgrid

---

src/site/_data/authorsData.json
src/site/_data/i18n/authors.yml
src/site/content/en/blog/loading-ads-page-speed/index.md

- Adds effective ads loading post.

Adds effective ads loading post.

---

src/site/_includes/feed.njk
src/site/content/en/authors/feed.njk
src/site/content/en/shows/feed.njk
src/site/content/en/tags/feed.njk

- Fixes broken RSS feed for feedly. as reported by several users.
It looks like they don't accept `type="text/html"` anymore. The [spec](https://www.ietf.org/rfc/rfc4287.html#section-3.1.1) specifies we should be using `"html"` anyway. Doesn't look like we changed anything here, so maybe something changed at Feedly's end?
FYI, this was originally changed too `text/html` in #5873 but with no explanation why. D.C.C still uses `"html"`
[Prod](https://web.dev/feed.xml) (and recent other staging URLs) has this on Feedly:
This [branch's preview](https://deploy-preview-10424--web-dev-staging.netlify.app/feed.xml) has this on Feedly:

Fix broken RSS feeds
