content/reliable/service-workers-cache-storage/index.md

It's likely I will need to play with image appearance a good bit, but starting somewhere.

Re-doing service workies section

---

content/accessible/control-focus-with-tabindex/index.md
content/accessible/guides.yaml
content/accessible/headings-and-landmarks/index.md
content/accessible/keyboard-access/index.md
content/accessible/labels-and-text-alternatives/index.md
content/accessible/semantics-and-screen-readers/index.md
content/accessible/style-focus/index.md
content/accessible/use-semantic-html/index.md
content/accessible/what-is-accessibility/index.md
content/secure/guides.yaml

Sweep of accessibility content (8 guides total)

Accessibility content review

---

content/_project.yaml
content/about.html
content/index.html
content/learn.html
content/measure.html
templates/devsite.html

These should come from devsite now.
Not ready for merge yet. I need to test devsite's CL against this PR.

Remove our hardcoded twitter card paths

---

content/accessible/headings-and-landmarks/index.md

Added a little live example to this section :)

Add a skip link demo. Fixes #458.

---

content/fast/reduce-javascript-payloads-with-code-splitting/codelab-code-splitting.md
content/fast/reduce-network-payloads-using-text-compression/codelab-text-compression.md
content/fast/remove-unused-code/codelab-remove-unused-code.md
content/fast/serve-modern-code-to-modern-browsers/codelab-serve-modern-code.md

For #88 
Just added a single `aside` after the `Measure` section for each codelab with webpack. Happy to move/adjust if anyone things I should 🕺

Adds note on webpack build times

---

lib/config/contributors.js
package-lock.json

If authors do not want their picture shown on the website,
they can set `picture: no-photo` in the `_contributors.yaml`.
This would prevent issues like #570

Enforce that the author image actually exists

---

content/reliable/http-cache/index.md

Fixes #608 by adding an aside about the `immutable` property.
CC: @Malvoz

Adds a note about the Cache-Control property "immutable"

---

CODEOWNERS

Removed the `/content/` section because it doesn't actually do anything.

Tidy owners file.

---

content/fast/use-lazysizes-to-lazyload-images/index.md

This PR will:
- Add new content about `pictures` to the lazysizes section

Extend lazysizes doc with pictures

---

content/learn.html

Rationale at go/web.dev-uxwaudit-learn (Googlers-only link)

UXW audit proposal for learn.html

---

content/about.html

@meggin @meggynw @harleenkbatra08 please take a look.

Add new ux copy. Fixes #597.

---

content/fast/replace-gifs-with-videos/codelab-replace-gifs-with-video.md

Remove screenshot and update text to match Glitch UI.
Separately, I completed the codelab and kept getting an error when trying to run LH:
At first I thought it was related to my Chrome extensions (was getting a warning earlier), but even in the incognito window it wasn't workng.

Update instructions in "Replace GIFs with video"

---

content/fast/use-lazysizes-to-lazyload-images/codelab-use-lazysizes-to-lazyload-images.md

1. Updates Glitch UI text.
2. Makes the "Verify with Lighthouse" section consistent with the same section in "Replace GIFs with video."  (Feel free to revert this change if it's not appropriate.  Mostly changed because I wasn't sure where the Lighthouse > Options > Performance flow was coming from.)

Update Lazysizes codelab

---

content/fast/use-imagemin-to-compress-images/codelab-imagemin-grunt.md
content/fast/use-imagemin-to-compress-images/codelab-imagemin-gulp.md
content/fast/use-imagemin-to-compress-images/codelab-imagemin-webpack.md

Removes steps for installing imagemin and its associated plugins via the Console.
Adds text explaining what has already been installed and moves the Console instructions accordingly.

Update Imagemin Configuration text

---

content/index.html

For rationale, see go/web.dev-uxwaudit-home (Googlers-only link)

UXW audit proposal for index.html

---

content/fast/preload-critical-assets/codelab-preload-critical-assets.md

@housseindjirdeh just an fyi that I added this.

Add rel preload audit to guide

---

content/_redirects.yaml

- Add a redirect for /subscribe so it points at our formbox for folks to sign up for our newsletter.

Add a redirect test for /subscribe.

---

content/fast/preload-critical-assets/codelab-preload-web-fonts.md

Fix broken image paths in font preload codelab.

---

src/site/_data/authors.json

Fixes # .
- Adds me to the authors.json file. 
---
If this PR adds **new content** please fill out the form below.
If this PR changes existing content you can delete the form.
---
👋 Thanks for submitting this PR! Please take a moment to let us know what's been added.
To mark a box as done, add an x like so:
This pull request adds a **new**:
Have you read the wiki on writing [a guide](https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-guide) or [a codelab](https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-codelab)?
Does your content tell a user how to fix a Lighthouse audit?
Have you added [the Lighthouse audit ID to your YAML](https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-guide#lighthouse-audits)?
Does your content …

Add Joe Medley to authors.

---

src/site/_includes/components/Compare.js
src/site/content/sandbox/compare/index.md

- Make Compare widget labels configurable.
- Fix markdown rendering in Compare widgets.

Add label overrides to Compare widget and fix markdown rendering.

---

src/site/content/en/react/accessibility-auditing-react/index.md
src/site/content/en/react/add-manifest-react/index.md
src/site/content/en/react/code-splitting-suspense/index.md
src/site/content/en/react/get-started-optimize-react/index.md
src/site/content/en/react/precache-with-workbox-react/index.md
src/site/content/en/react/prerender-with-react-snap/index.md
src/site/content/en/react/virtualize-long-lists-react-window/index.md

Minor edits/fixes to the React guides ✨

Some finishing touches to React docs

---

src/site/_includes/layout.njk
src/site/_includes/sandbox/layout.njk
src/site/_includes/styles.njk

Adds a new include which can be injected into every page. This include has an style element which we can use to sneak in last minute style changes while we wait on devsite releases.

Add style overrides.

---

src/site/content/en/blog/hands-on-portals/index.md

Small fixes to the blog to clean up syntax and some verb tense.
---
If this PR adds **new content** please fill out the form below.
If this PR changes existing content you can delete the form.
---
👋 Thanks for submitting this PR! Please take a moment to let us know what's been added.
To mark a box as done, add an x like so:
This pull request adds a **new**:
Have you read the wiki on writing [a guide](https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-post) or [a codelab](https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-codelab)?
- [ x] Done! 🍰
Does your content tell a user how to fix a Lighthouse audit?
Have you added [the Lighthouse audit ID to your YAML](https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-guide#lighthouse …

Blog: Portals hands-on syntax clean-up

---

src/site/content/en/blog/how-to-report-metrics/index.md

Minor tweaks

---

src/site/content/en/measure/index.njk

Fix spelling in measure/index.njk

---

src/site/content/en/blog/hands-on-portals/index.md

@uskay @Meggin I removed the paragraph referring to the manga viewer in the video and updated the intro paragraph because it felt a little too short.
What do y'all think?

Rephrase portals intro and remove extra paragraph.

---

src/site/content/en/lighthouse-accessibility/list/index.md

Fixes # .
- 
- 
- 
---
If this PR adds **new content** please fill out the form below.
If this PR changes existing content you can delete the form.
---
👋 Thanks for submitting this PR! Please take a moment to let us know what's been added.
To mark a box as done, add an x like so:
This pull request adds a **new**:
Have you read the wiki on writing [a guide](https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-post) or [a codelab](https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-codelab)?
Does your content tell a user how to fix a Lighthouse audit?
Have you added [the Lighthouse audit ID to your YAML](https://github.com/GoogleChrome/web.dev/wiki/How-to-write-a-guide#lighthouse-audits)?
Does your content reference any Glitch projects? …

Fixed typo

---

src/site/content/en/blog/hands-on-portals/index.md

Tiny change on Adam's twitter link

Fixes Adam's twitter link

---

gulpfile.js
package-lock.json
package.json
src/styles/all.scss

- Adds support for publishing our scss to devsite.

Add gulp task so we can deploy styles.

---

src/site/content/en/react/code-splitting-suspense/index.md
src/site/content/en/react/virtualize-long-lists-react-window/index.md

Changes proposed in this pull request per feedback from React team:
- Adds overscanning section for virtualized list guide
- Removes unclear aside on suspense
Additional:
- Adds @developit as co-author of virtualized list guide

Updates to React docs

---

package-lock.json
package.json

- Rev eleventy to 0.8.3
- Rev elventy-syntax-highliter to 2.0.3
- Should fix issues with multiline comments in code blocks.
cc @tomayac

Rev eleventy to 0.8.3 and rev syntax highlighter.

---

README.md

This is a small pull request to help test our automation setup in https://github.com/GoogleChrome/web.dev/projects/7

Add note to readme.

---

src/site/content/en/blog/long-tasks-devtools/index.md

Fixes #954 
- Minor edits to address Phil's feedback

Address Phil Walton's feedback (fixes #954)

---

src/site/content/en/lighthouse-performance/mainthread-work-breakdown/index.md

Fixes # .
- Fixed typo for `JavaSdcript`

Fix for typo

---

src/site/content/en/blog/service-worker-mindset/index.md

- Fixes minor editorial issues in Service Workies blog post.

Editorial fixes to Service Workies post

---

src/site/content/en/fast/extract-critical-css/index.md

Fixes # .
- fix grunt-critical link
- fix html-critical-webpack-plugin link

Fix link of extract-critical-css

---

src/site/content/en/fast/codelab-extract-and-inline-critical-css/index.md

- Fix broken links
- Rewrite Glitch instructions to match the UI update

[Fix] Critical CSS codelab

---

.eleventy.js
src/site/_includes/components/YouTube.js
src/site/content/en/sandbox/index.md
src/site/content/en/sandbox/youtube/index.md
src/styles/components/_all.scss
src/styles/components/_youtube.scss

- Add YouTube and native video examples to sandbox.

Add YouTube shortcode.

---

src/site/content/en/blog/value-of-speed/index.md

Works around CSS bug with nested lists (nested list items are included in the count of the parent list) in "Value of speed" post.
- Convert parent list in "Value of speed" to numbered paragraphs.

Stopgap for nested list CSS bug

---

src/site/content/en/fast/use-lighthouse-for-performance-budgets/index.md

Just a minor edit to a link. This is great stuff Katie!

fix: link to Lighthouse GitHub repo

---

src/site/content/en/blog/use-srcset-to-automatically-choose-the-right-image/index.md

...which doesn't make sense on mobile.
See https://twitter.com/nhoizey/status/1143563196474822659.

Avoid 'the one on the left'

---

src/site/_drafts/_template-codelab/index.md
src/site/_drafts/_template-post/index.md
src/site/_includes/codelab.njk
src/site/_includes/partials/post.njk

Fixes #1036.
- Adds supports for an `updated` field in YAML.

Show updates on posts/codelabs. Fixes #1036.

---

src/site/_includes/codelab.njk

Fixes #972 .
- Authors can use the path YAML field to specify which file a Glitch should start on.

Let authors specify Glitch path.

---

src/site/content/en/blog/opensooq-case-study/index.md

- Updates title, subtitle, and one image caption.

content: Updates to OpenSooq post

---

src/site/content/en/blog/hands-on-portals/index.md

Modified the code snippet to support `perfers-reduced-motion` to achieve better accessibility.
Fixes #909

Adding `perfers-reduced-motion` support

---

src/site/_includes/content/origin-trials.njk

Fixes #1163
- Some standard language that could be pulled in to posts explaining what Origin Trials is.
CC: @petele

Origin Trials explainer include

---

src/site/content/en/angular/route-preloading-in-angular/index.md

- Fixed issue where the install instructions left out ngx-quicklink

docs: update route-preloading-in-angular

---

.eleventy.js
src/site/_includes/components/Banner.js
src/site/_includes/partials/post.njk
src/site/_includes/styles.njk
src/site/content/en/about/index.njk
src/site/content/en/blog/index.njk
src/site/content/en/handbook/web-dev-components/index.md
src/site/content/en/learn/index.njk
src/site/content/en/measure/index.njk
src/styles/components/_all.scss
src/styles/components/_banner.scss

Fixes #1177 
- Adds a new Banner paired shortcode 
- Adds a banner to all blog pages to ask folks to fill out our images survey.
- Adds gnarly devsite hackery to make banner work while we wait for the next release build.

Add Banner component and add banner to all blog pages.

---

src/lib/fb.js
src/lib/store.js

Experiments with using Firestore for user data.
I can't actually set up Firestore @robdodson, can you add me as an owner of the project?

basic Firestore use

---

src/lib/app.js

Simple addition to set `lh-signedin` as per previous codebase.

add global signin class to page

---

src/site/content/en/handbook/markup-code/index.md

- Adds additional info to the handbook about escaping code.

Add note about raw and verbatim tags to handbook.

---

src/lib/app.js
src/lib/components/LighthouseGauge/_styles.scss
src/lib/components/LighthouseGauge/index.js
src/lib/components/_all.scss
src/site/content/en/measure/index.njk

🤔 (...technically the old one does this too—it fits to size).

Adds web-lighthouse-gauge

---

src/site/content/en/blog/backdrop-filter/index.md

see userland comment https://twitter.com/simevidas/status/1154960320487727105?s=20
having -webkit- in the code examples creates more questions than it helps answer

remove -webkit- references

---

src/site/content/en/about/index.njk
src/site/content/en/blog/index.njk
src/site/content/en/learn/index.njk
src/site/content/en/measure/index.njk

Planning to merge this on Monday unless @samdutton has any objections.
- Disables banner added in #1178

Disable image survey banner.

---

src/site/_includes/styles.njk

Note this is a patch fix for the current live site because devsite is on release freeze. samthor@ is also fixing these issues in our v2 branch.
- Inline styles for some quick /measure page fixes.

Improve /measure spacing. Temporary fix for #1181 and #1206

---

src/site/content/en/secure/cross-origin-resource-sharing/index.md

-just a few typos on the CORS instructional page

Fixing some typos

---

src/site/_includes/components/Instruction.js

Fixes #1133
- Add new Glitch instruction
- Add separate instructions for reloading an app and a simple page
- Add DevTools Command menu instruction

Add new cases for the Instruction component

---

package.json
src/lib/components/LighthouseScoresContainer/index.js

Attempt to make Travis happy

---

src/site/content/en/blog/native-lazy-loading/index.md

- Per discussion with @scott-little, removing feature policy section as it is still being worked on
- Update date
CC @addyosmani

Finishing touches to lazy load post

---

src/site/content/en/blog/native-lazy-loading/index.md

- Includes an FAQ on future plans to expand this feature for Lite Mode
- Updates bug link
CC @addyosmani @bengreenstein

Includes mention of auto lazy-loading with Lite Mode and updates bug link

---

src/site/content/en/blog/native-lazy-loading/index.md

- Updates auto lazy load description in FAQ
CC @scott-little

Updates auto lazy loading description in faq - native lazy loading

---

src/site/content/en/handbook/word-list/index.md

Update word list

---

src/site/_includes/components/Actions.js

- Adds missing analytics events for our share and subscribe buttons.

Add analytics for sharing and tweeting articles.

---

src/lib/components/ProfileSwitcherContainer/index.js
src/lib/components/UrlChooserContainer/index.js

move state subscription to connected/disconnected

---

src/site/content/en/blog/prefers-color-scheme/index.md

Makes a header with inline code linkable.

Add an ID to a manual `<h3>` header

---

src/site/content/en/blog/install-thumbor/index.md

Remove link to non existant codelab

---

CONTRIBUTING.md

CONTRIBUTING.md linked to Google/WebFundamentals instead of this repo.

Fix contributing issues link

---

src/lib/app.js
src/lib/components/Codelab/_styles.scss
src/lib/components/Codelab/index.js
src/lib/components/_all.scss
src/site/_drafts/_template-codelab/index.md
src/site/_includes/codelab.njk
src/styles/pages/_codelab.scss

Fixes #1374
- Adds `web-codelab` element.
- Updated `codelab.njk` to use web-codelab instead of local dev version.
-

Migrate web-codelab element.

---

.github/ISSUE_TEMPLATE/collection_proposal.md
.github/ISSUE_TEMPLATE/content_proposal.md

- Adds a new issue template for proposing new collections.

Add collection proposal template.

---

src/site/content/en/accessible/index.njk
src/site/content/en/angular/index.njk
src/site/content/en/blog/index.njk
src/site/content/en/discoverable/index.njk
src/site/content/en/fast/index.njk
src/site/content/en/handbook/handbook.11tydata.js
src/site/content/en/installable/index.njk
src/site/content/en/lighthouse-accessibility/index.njk
src/site/content/en/lighthouse-best-practices/index.njk
src/site/content/en/lighthouse-performance/index.njk
src/site/content/en/lighthouse-pwa/index.njk
src/site/content/en/lighthouse-seo/index.njk
src/site/content/en/react/index.njk
src/site/content/en/reliable/index.njk
src/site/content/en/secure/index.njk

Add tag overrides to prevent landing pages from being indexed by algolia.

---

package.json

watch scss for changes

---

src/site/content/en/angular/creating-pwa-with-angular-cli/index.md

This changes an ordered list to an unordered list per the handbook.

Make a list not appear as a procedure.

---

src/site/content/en/handbook/word-list/index.md

Fixes #1406 .
- Added home screen to word list

Added home screen to word list

---

src/site/content/en/about/index.njk
src/site/content/en/blog/index.njk
src/site/content/en/learn/index.njk
src/site/content/en/measure/index.njk

- Remove the AskChrome banner since the campaign is over.

Remove AskChrome banner.

---

src/site/content/en/blog/speed-at-scale/index.md

Here's what's on the [published page](https://web.dev/speed-at-scale/).

Remove unrendered character entity

---

package-lock.json
package.json
rollup.config.js
src/lib/actions.js
src/lib/app.js
src/lib/components/Header/_styles.scss
src/lib/components/Header/index.js
src/lib/components/SideNav/_styles.scss
src/lib/components/SideNav/index.js
src/lib/components/_all.scss
src/lib/store.js
src/site/_includes/layout.njk
src/styles/all.scss
src/styles/components/_actions.scss
src/styles/generic/_all.scss
src/styles/generic/_main.scss
src/styles/generic/_shared.scss

Fixes #1371
- Adds a Header component.
- Adds a SideNav component.
- Adds wicg-inert polyfill.
- Adds :focus-visible polyfill.
- Defines actions for opening and closing the SideNav, as well as inerting other parts of the page.

Responsive side nav

---

src/site/content/en/blog/video-basics/index.md

- fix confusing file names in the example
- fix codec names

update basic video article

---

.eleventy.js

Fixes #
- fix comments typo in .eleventy.js

Fix comments typo in eleventy config

---

src/styles/pages/_path.scss

- Reduce assertiveness of code font styling in path links on collection landing pages so they're not so intrusive.
- Match code font color in path links so it matches rest of link.

Update path link code styling

---

package.json

I have been recommended to use this for a sharable preview of my article. Not sure the name is necessarily the best, tho.

Add personal staging npm script

---

src/site/content/en/lighthouse-performance/time-to-first-byte/index.md

Fixes #1537.
- Change the word "effect" to "affect".

Fix typo in the word "affect"

---

src/site/content/en/blog/hands-on-portals/index.md

[web.dev/hands-on-portals/] Add info about --user-data-dir recommendation

---

src/site/content/en/handbook/content-checklist/index.md
src/site/content/en/handbook/handbook.11tydata.js
src/site/content/en/handbook/quality/index.md
src/site/content/en/handbook/style/index.md

Changes proposed:
* Renames the [Style](https://web.dev/handbook/style/) guide to "content quality guidelines"
* Michael reminded me that the writers had planned on doing this after our brainstorming in August
* Clarifies the purpose of the [checklist](https://web.dev/handbook/content-checklist/) and the "content quality guidelines" in the introduction of each section to keep web.dev authors and reviewers aligned on the purpose of each doc
* I realized that Michael's original approach was better, but felt that we needed to be explicit in the beginning of the doc to keep us all aligned on the purpose of each doc
* Adds canonical examples to the "content quality guidelines"
* Kinlan suggested that this would be an easier way for non-writers to grok the ideas
*Note: The text below is …

Update content quality checklist

---

server.js

Fixes image loading. The regexp here was too aggressive.

fix image loading

---

src/site/content/en/lighthouse-pwa/redirects-http/index.md
src/site/content/en/lighthouse-pwa/themed-omnibox/index.md

Fixes a couple minor issues in the main PWA audit update PR.

PWA audit fixes

---

src/site/content/en/react/get-started-optimize-react/index.md

- Added a missing comma.
- Added a missing closing parenthesis.
- Added a missing "the" before "actual web page".

Fixes to Get started: optimize your React app

---

src/site/_includes/components/PathCard.js
src/site/_includes/components/PostCard.js

- Adds `loading="lazy"` to our /learn and /blog pages.

Quick addition to make images lazy load.

---

src/site/_includes/partials/post.njk

- Add Markdown support in post subheads. (Doesn't affect path cards.)

Add Markdown to post subheads

---

src/styles/generic/_code.scss

Don't let code in headings break.

---

src/site/_includes/codelab.njk
src/site/_includes/partials/post.njk

Show a banner on draft posts in dev mode.

Show banner for draft posts in dev mode.

---

src/lib/app.js
src/lib/router.js
src/lib/store.js
src/site/_includes/layout.njk
src/styles/components/_all.scss
src/styles/components/_progress.scss

Adds loading bar for slow loads. No particular issue.
Slightly diverges (simplified) from DevSite styles.

Adds loading bar to v2

---

src/site/content/en/react/performance-as-a-default-with-nextjs/index.md

Fixes #1658 
- Addresses Rob's last feedback from #1658. I guess I forgot to push the last commit before merging.

Update Next.js intro

---

src/lib/components/SideNav/index.js

Fixes #1692 
- Tried to add a big comment so folks can know what's going on here. Happy to tweak if it's still unclear.

Fix router issue with SideNav links

---

src/lib/router.js

cc @robdodson 
going to TBR this. Fixes a bug with measure JS loading.

catch /measure properly

---

src/lib/components/BaseStateElement/index.js
src/lib/components/SigninButton/index.js
src/lib/pages/measure.js
src/site/content/en/measure/index.njk

Adds `web-signin-button`, which displays the giant sign in button for the Measure page. This previously wasn't hooked up.
Also adds `BaseStateElement`. If you like it, I'll migrate all the state-subscribing elements to listen to it.

make Measure signin button work

---

src/site/content/en/lighthouse-accessibility/meta-refresh/index.md
src/site/content/en/lighthouse-accessibility/meta-viewport/index.md

Partially fixes #1687.
- Update posts in "Best practices" section of `lighthouse-accessibility` .

Lighthouse a11y best practices audit post updates

---

build.js
package-lock.json
package.json

Helps bring our JS size down. Currently it gives an output bundle which is ~37% of the previous size.

Adds Terser minification for prod

---

src/site/content/en/blog/prefers-color-scheme/index.md

- Improve compatibility of fallback script

[prefers-color-scheme article] Improve compatibility of fallback script

---

src/lib/sw.js

Add other boring Service Worker things.

add fonts and analytics to SW

---

src/site/_utils/get-image-path.js

This was the wrong way around. Going to force submit :)

invert imgix condition

---

package-lock.json
package.json
server.js

Related to #1757
- Add compression to dev server. This will benefit Lighthouse CI since it uses our dev server to audit the site.

Use compression on dev server.

---

src/site/content/en/feed.njk

- Fixes a bug where authors weren't displaying in the RSS feed.

Fix RSS authors.

---

build.js
src/lib/fb.js
src/site/_data/site.js

- Add firebase config to site.js and make it a virtual import for fb.js

Add firebase config to build.js

---

src/lib/fb.js

don't fetch results for empty URL

---

src/lib/components/Header/index.js

Add `aria-current` for better screen reader support.

Add aria-current to active page.

---

src/lib/store.js

- Disable unistore devtools in prod.

Don't use unistore devtools in prod.

---

package.json

- Make deploy command use our cloud project.

Update deploy command.

---

entrypoint.hashmanifest.json
src/site/_includes/layout.njk

- Add missing favicon.
- Remove entrypoint.hashmanifest.json. This is an old file I previously experimented with but am no longer using.

Clean up layout template. Add favicon. Remove outdated hash file.

---

src/site/content/en/accessible/semantics-and-screen-readers/index.md

Fixes #1641 
- Replicate the text from the custom-controls-roles audit in the semantics-and-screen-readers post. This patches over our broken Glitch example.

Quick fix for semantics-and-screen-readers post.

---

src/lib/components/LighthouseScoresStats/_styles.scss

Fixes 1772 - removes extra styles in LighthouseScores

Fixes 1772 - removes extra styles in LighthouseScores

---

src/lib/utils/router.js

Fixes #1811 because I am a dolt.

dedup scroll handler

---

.remarkignore
CODE_OF_CONDUCT.md

- Add a link to Google's open source CoC
- Also adds a .remarklintignore file. It was grumping about the fact that this file name contains underscores.

Add code of conduct.

---

src/site/content/en/lighthouse-performance/resource-summary/index.md

/resource-summary/

---

src/site/content/en/lighthouse-pwa/installable-manifest/index.md

Fixes #1797 
- Update `/installable-manifest` to more accurately reflect the associated Lighthouse audit.

Update installable-manifest post

---

package.json

- Use `dev` flag for staging, otherwise images won't show up.

#1840 is a lie. This is the real fix.

---

src/site/content/en/blog/oyo-lite-twa/index.md

Fixes incorrect browser name in browser support aside

Fix browser support in OYO post

---

src/site/content/en/blog/vr-comes-to-the-web/index.md

This is just something we found lacking when we started to write part II.

Add some extra information around views.

---

src/site/content/en/secure/security-not-scary/index.md

A few things I found while reading the introduction.
- 
- 
-

Writing teacher fixes.

---

src/site/_includes/components/YouTube.js
src/site/content/en/index.njk

Add CDS day 1 livestream; YouTube lazy load iframe

---

src/site/content/en/blog/perception-toolkit/index.md

- Fixes a few typos in the perception-toolkit post

Fix typos in perception-toolkit

---

src/site/content/en/metrics/cls/index.md
src/site/content/en/metrics/user-centric-performance-metrics/index.md

Fix a few editorial issues in the metrics docs

---

src/site/content/en/blog/web-bundles/index.md

Typo fix in blog/web-bundles

---

src/site/content/en/index.njk

- Take down day 2 livestream
- Add some replacement copy for CDS on the homagepage.
@harleenkbatra08 fyi

Add wrap up text for CDS

---

server.js
src/misc/nuke-sw.js

Fixes #1833. Serves a dummy SW that nukes any clients.

disallow www.web.dev, redirect to naked domain

---

src/site/content/en/metrics/tbt/index.md

This seems like a more appropriate heading for this section.

Change "What is a good TTI" to "What is a good TBT"

---

src/site/content/en/blog/ready-player-web/index.md

@tcmg As mentioned over e-mail as well :)
- Made Poki.com link to Poki
- Adjusted text slightly to avoid confusion (Poki releases games more often than monthly) and to include Subway Surfers.

Update Poki description

---

src/site/content/en/react/code-splitting-suspense/index.md

- Added a missing comma.
- Changed an unordered list to an ordered list when listing the step-by-step instructions to enable throttling to demonstrate slow loading.

Fixes to Code splitting w/ React.lazy and Suspense

---

src/site/content/en/react/precache-with-workbox-react/index.md

- Added a missing "in".
- Changed unordered lists to ordered lists when listing step-by-step instructions.

Fixes to Precaching in Create React App w/ Workbox

---

src/site/content/en/blog/badging-api/index.md

Fixes #1736 
- Denotes end of first origin trial and start of second
- Adds details on how to provide backwards compat between old/new
- Additional fixes as requested by engineering

Updates Badging API article for new origin trial

---

src/site/content/en/fast/image-cdns/index.md

Remove list of image CDNs

---

src/styles/components/_footer.scss

Fixes #1767
Increase padding of links in the footer, also break out the padding into a mixin to keep them consistent.

fix(footer): increase footer links' padding to 100% SEO on LH, fixes #1767

---

src/site/content/en/blog/stale-while-revalidate/index.md

Fixes a 404 link that is no longer there.

Remove link that 404s

---

src/site/content/en/blog/badging-api/index.md

Spelling error: change recevied to received

---

src/site/content/en/blog/wakelock/index.md

[Wake Lock article] Add origin trial info

---

src/site/content/en/lighthouse-performance/font-display/index.md

Fixes #1901.
- Explain how to fix FOIT with Google fonts

Explain how to fix FOIT with Google fonts

---

src/site/content/en/blog/backdrop-filter/index.md

Make cross-origin links safe

---

src/site/content/en/blog/periodic-background-sync/index.md

Update periodic bckgrnd article for Chrome 80.

---

src/site/content/en/blog/off-main-thread/index.md

Fixes #1924.
- Add companion blog post for "Main thread is overworked" CDS '19 talk.

Content: Main thread is overworked companion post

---

src/lib/components/CopyCode/index.js
src/lib/components/CopyCode/styles.scss
src/styles/components/_compare.scss
src/styles/devsite/_app.scss

fix(CopyCode): fix style issues, fixes #2010 & fixes #2011

---

src/site/content/en/handbook/content-checklist/index.md
src/site/content/en/handbook/markup-post-codelab/index.md
src/site/content/en/handbook/web-dev-components/index.md
src/styles/generic/_links.scss

- Add styling for links with a [rel=noopener] attribute.
- Add guidance to handbook to help ensure rel=noopener is used for external links.

Add styling for external links

---

src/site/_includes/components/Instruction.js
src/site/content/en/notifications/codelab-notifications-get-started/index.md
src/site/content/en/notifications/codelab-notifications-service-worker/index.md

Fixes #1662.
- Add codelab-notifications-service-worker

Add notifications service worker codelab

---

README.md

- Update readme so it's more accurate. The notes I've removed are from back when our js lived inside of google's source control.

Some small language updates to the readme.

---

src/lib/sw.js

Fixes #2069
- Changes most sw fetches to be NetworkFirst
- Leaves Google fonts as StaleWhileRevalidate

Switch to NetworkFirst sw strategy.

---

src/site/content/en/blog/contact-picker/index.md
src/site/content/en/blog/shape-detection/index.md

- Update of Shape Detection article
- Update of Contact Picker article

Update Contact Picker and Shape Detection origin trial information

---

src/site/content/en/blog/native-lazy-loading/index.md

Fixes #1850.
- Adds FAQ on lazy-loading onscreen images
CC @bazzadp

Update FAQ section in native lazy loading article

---

src/site/_includes/path.njk

Fixes #1290 
- Changed what you'll learn section into in-page links

Issue 1290

---

src/site/content/en/index.njk

- Remove CDS promo banner and reinstate the old about copy.

Remove CDS banner from homepage.

---

src/site/content/en/blog/content-indexing-api/index.md

- Centers an image that was left aligned.

Center misaligned image

---

src/site/content/en/blog/multi-origin-pwas/index.md

Update the link pointing to the solution for Multi origin TWAs, since @andreban just released a new standalone guide covering that:
https://developers.google.com/web/updates/2020/01/twa-multi-origin

Update link to multi-origin TWA solution

---

src/site/content/en/progressive-web-apps/progressive-web-apps.11tydata.js
src/site/content/en/progressive-web-apps/pwa-checklist/index.md

Fixes #1349 
- Adds **PWA Check List** to PWA folder
- Has been edited/reviewed/approved by @jpmedley 
Note: Doc is currently marked *DRAFT* so that it is not accidentally published before we publish the PWA section

PWA Check List

---

src/lib/components/SideNav/_styles.scss
src/lib/components/SideNav/index.js
src/site/_includes/layout.njk

fix(web-side-nav): add signal for current page in side nav, fixes #1784

---

src/site/content/en/fast/codelab-serve-images-correct-dimensions/index.md

Fix math error

---

src/site/content/en/blog/web-ar/index.md

Fixes #2143
- Fixes accidental publication of the commit listed at the top.

Hide AR article temporarily.

---

src/site/_includes/components/Meta.js

fix(Meta): use `path.title` and `path.description` in `getMetaByPlatform`, fixes #2002

---

.github/workflows/snapshot-firestore.yml

(It's apparently not implied by the GCLOUD_KEY).

Add explicit --project to gcloud run

---

src/lib/components/Actions/index.js

make subscribe link open in new window

---

src/site/content/en/progressive-web-apps/install-criteria/index.md
src/site/content/en/progressive-web-apps/progressive-web-apps.11tydata.js
src/site/content/en/progressive-web-apps/what-are-pwas/index.md

Fixes #1353 
- Adds the installability core criteria

content: PWA installable criteria

---

src/site/_drafts/_template-case-study/index.md

Add case study template

---

src/site/_data/site.js
src/styles/components/_banner.scss
src/styles/components/_images.scss

Fixes #1745
- Reduce banner padding on mobile.
- Hide hero image on mobile.

Remove UI cruft on mobile.

---

src/site/_data/contributors.js

- Updates bio in `contributors.js` for me 
- Updates URL to personal website for me

Update bio for petele

---

src/site/_data/postTags.js

Add 'fugu' to tags file.

---

src/site/content/en/blog/ar-hit-test/index.md

Fix a few items.

---

.eleventy.js
src/site/_filters/console-dump.js

- Adds a `consoleDump` filter. https://twitter.com/eleven_ty/status/1227229750747389952
@MichaelSolati @devnook I was wondering if y'all might find this useful?

Add a console dump filter.

---

src/lib/sw.js

Fixes #2033.
Jeffy, let me know if I'm doing this right. I'm surprised (but I'm sure there's a valid reason) that `registerRoute` doesn't take an extra arg allowing me to ignore params.
But I'm also surprised at how expressive `registerRoute` allows me to be. For instance, our `contentHrefRe` (on line 122), when passed to Workbox, matches anywhere in the URL, so I can e.g. load something like: https://web.dev/$@not-valid-slug@$/valid-slug/
Is the right idea to actually build a regexp that contains the hostname on the left (including escaping)? e.g.: `/$https?:\/\/web\/.dev\/([\\w-]+/)*(|index.html)(\\?|$)/`

strip utm_ from Workbox

---

src/site/content/en/metrics/cls/index.md
src/site/content/en/metrics/fcp/index.md
src/site/content/en/metrics/fid/index.md
src/site/content/en/metrics/lcp/index.md
src/site/content/en/metrics/tbt/index.md
src/site/content/en/metrics/tti/index.md

This PR adds clearer and more consistent threshold recommendations to all the metrics articles.

Update all metrics docs with threshold guidance

---

src/site/content/en/blog/web-ar/index.md

- Link fixed to article  https://web.dev/ar-hit-test/

Link update

---

build.js
package-lock.json
package.json
src/lib/sw.js

Part of #1370.
Upgrades to Workbox 5, and inlines the code.

workbox to 5.0.0, inline

---

src/lib/bootstrap.js
src/lib/sw.js

I broke the SW in #2246.
I returned an undefined variable at the bottom of the catch handler.

fix broken sw

---

src/site/_data/site.js

Take down mdn banner.

---

src/site/content/en/metrics/cls/index.md
src/site/content/en/metrics/fcp/index.md
src/site/content/en/metrics/fid/index.md
src/site/content/en/metrics/lcp/index.md
src/site/content/en/metrics/tbt/index.md
src/site/content/en/metrics/tti/index.md

Update the `updated` field for docs revved in #2271 
@PaulKinlan @philipwalton fyi

Rev updated fields for metrics docs.

---

src/lib/sw.js

We were growing our caches forever. Let's not do that.

Make caches named & bounded

---

src/styles/components/_header.scss

fix hamburger shift on desktop

---

src/site/content/en/lighthouse-pwa/apple-touch-icon/index.md

- Update outdated link URL to point to a right article

Update outdated link URL

---

src/site/content/en/blog/get-installed-related-apps/index.md

Fixes #2289.
- Adds note about only testing the first three apps
- Adds info about testing for installed PWA
cc: @rayankans

Updates to getInstalledRelatedApps for m81 and 82

---

src/site/content/en/blog/native-file-system/index.md

@petele Please review and merge

Add missing "await" to chooseFileSystemEntries

---

src/site/content/en/metrics/fcp/index.md

The link is currently broken on web.dev

Fix 404 in first contentful paint article

---

src/site/_data/contributors.js

Pushing always fixes the formatting in the contributors file. I'm pushing a PR just to fix it.

fix autoformat

---

package-lock.json
package.json
src/lib/components/Search/index.js

Fixes #1879.
Reduces the total amount of JS we build by 10%! Woop.

upgrade to Algolia SDK 4+

---

src/lib/components/LighthouseScoresMeta/index.js

Fixes #1105. We don't need to encode everything but this definitely works.

encode url

---

build.js

Fixes #1900.
We literally were not caching the JS in precache or runtime—oops. Turns out we didn't notice on Desktop as offline pages were still being served or generated by the SW, but JS is needed to navigate on mobile (... which is an issue in itself, but irrelevant here).

cache JS in SW payload

---

.eleventy.js
src/site/_filters/strip-title.js
src/site/_filters/strip.js
src/site/_includes/components/Meta.js
src/site/_utils/build-partial.js

Fixes #1993
Add filter that removes forbidden characters/whatever from titles.
@samthor if I can get a LGTM that'd be dope!

feat(stripTitle): add filter to remove forbidden characters from string, fixes #1993

---

build.js
index-algolia.js
package-lock.json
package.json
src/lib/components/Search/index.js

Revert revert in #2373 of #2348.
Adds fix for indexing pipeline.

upgrade Algolia in search and index

---

src/site/content/en/blog/media-session/index.md

Just remove a superfluous word…

[Media Session API article] Fix typo

---

src/lib/loader.js

Fixes #2392, Fixes #2395
- Move call site of partial update function so it uses the correct route.
- Fix missing variable so focus mgmt works.

Fix images and focus management in loader.js

---

src/site/content/en/fast/fast.11tydata.js

Small change to make prettier chill.

Fix formatting of 11ty file to make prettier happy.

---

build.js
karma.conf.js
src/lib/components/LighthouseGauge/test.js
src/lib/test/index.js

Felt like working on tests for a bit. Just tests a single WC right now.

actually test WC, switch to karma TDD

---

.eleventy.js
build.js
karma.conf.js
src/lib/components/LighthouseGauge/test.js
src/lib/test/index.js
src/site/_data/site.js
src/site/_includes/partials/post.njk
src/site/_includes/partials/translation-disclaimer.njk
src/site/content/en/handbook/markup-post-codelab/index.md
src/site/content/en/handbook/web-dev-components/index.md
src/site/content/pl/accessible/control-focus-with-tabindex/index.md
src/site/content/pl/pl.11tydata.js
src/styles/components/_banner.scss

Brings back the translations banner which was rolled back due to backend issues.

Readd translations banner

---

src/site/content/en/blog/web-otp/index.md

Fixes a broken closing `figure` tag.

Fix broken HTML

---

src/lib/utils/router.js

Fixes #2450
Links are opening but _retaining_ the existing hash.

fix not clearing hash on nav

---

src/site/content/en/blog/read-files/index.md

Fixes #2439
Staged page: https://deploy-preview-2438--web-dev-staging.netlify.com/read-files/

Migrate the "Read local files" guide from H5R

---

.github/workflows/continuous-integration-workflow.yml

Revive #2425 
Giving this another shot but currently only running it as a blocker to the actual deploy step.

Add staging check to ci.

---

src/site/content/en/blog/shape-detection/index.md

[Shape Detection] Update launch info: 82 → 83

---

src/site/content/en/blog/fugu-status/index.md

- Fix 'September' typo on Fugu Status page

Fix 'September' typo

---

src/site/content/en/blog/module-workers/index.md

Changes Module Workers release version from m82 to m83.

Module Workers release: m82 -> m83

---

src/site/content/en/blog/covid19/index.md

See https://github.com/GoogleChrome/web.dev/commit/95bae8735e7e547d5a8d678fb9434bdc747b86ac for more context about the comment

Mention Lighthouse SEO audits and remove comment

---

src/site/content/en/blog/preload-optional-fonts/index.md

- Fix release version since M82 is cancelled

Update release version for optional fonts article

---

src/site/content/en/blog/get-installed-related-apps/index.md

Change Chrome 82 to Chrome 83 in getInstalledRelatedApps article.

---

src/site/content/en/blog/native-file-system/index.md
src/site/content/en/blog/read-files/index.md

- Add pointer to Native File System API article to H5R File article.
- Add pointer to browser-nativefs to Native File System article.

[H5R File article, Native File System article] Add pointers to new features

---

src/site/content/en/blog/digging-into-the-privacy-sandbox/index.md

Fixes to 'Find out more' links

---

src/site/content/en/blog/color-scheme/index.md

Addendum to #2481
- Remove the `draft` bit
- Tweak the title

[color-scheme Article] Publish it

---

src/site/content/en/fast/serve-images-webp/index.md
src/site/content/en/fast/use-imagemin-to-compress-images/index.md

Fixes #2523
- update imagemin code samples to match current API

Update imagemin code samples

---

.github/workflows/continuous-integration-workflow.yml

- linter was blowing up on ci cuz I didn't run install :P

Install deps for ci workflow.

---

src/site/content/en/reliable/codelab-http-cache/codelab-http-cache.md

Fixes #2409 by correcting the Glitch id.

Fix a HTTP caching codelab Glitch embed

---

src/site/content/en/blog/websocketstream/index.md

Replace placeholder with actual name of the API

---

src/site/content/en/handbook/content-checklist/index.md
src/site/content/en/handbook/web-dev-components/index.md

Add Glitch guidance to handbook

---

src/site/content/en/fast/serve-images-webp/index.md
src/site/content/en/fast/use-imagemin-to-compress-images/index.md

Fixes #2547
- add `updated` frontmatter attribute to two recently updated Markdown files

Add `updated` field to markdown frontmatter

---

src/site/_includes/layout.njk

- Adds missing preconnects that Lighthouse was grumping about.

Add preconnects to firebase.

---

src/site/_data/podcasts.js

Fix typo, designer vs developer

---

src/site/content/en/fast/use-lazysizes-to-lazyload-images/index.md

Remove mention of Intersection Observer

---

src/site/content/en/lighthouse-performance/performance-scoring/index.md

Fixes #2286
- add CLS to table

performance-scoring: add CLS into lh v6 scores

---

src/site/content/en/blog/nfc/index.md

Clarify P2P is not supported in Web NFC

---

src/site/content/en/blog/how-to-set-up-signed-http-exchanges/index.md

Google Chrome, Samsung Internet, and Microsoft Edge, in particular.
Fixes #2452.

SXG: mention support from other Chromium browsers

---

src/site/content/en/blog/wakelock/index.md

- `s/wake lock/screen wake lock/gi` essentially
- OT update

[Wake Lock article] Incorporate latest spec changes

---

src/site/content/en/blog/digging-into-the-privacy-sandbox/index.md

• Updated text.
• Removed broken Tor link.
• Added Advertising Use Cases link.

Updates to Privacy Sandbox post

---

server.js

disable iframing

---

.github/stale.yml

Tell stalebot to ignore issues with an assignee

Exempt issues with assignees from stalebot.

---

src/site/_includes/partials/subscribe.njk
src/styles/components/_subscribe.scss
src/styles/overrides/_display.scss

Update copy based on feedback from Harleen.

fix(newsletter): update copy

---

.github/stale.yml

- Tell stalebot to ignore Epics

Exempt epics from stalebot.

---

src/site/content/en/blog/vr-comes-to-the-web/index.md
src/site/content/en/blog/web-otp/index.md

I found there are two articles that has metadata of `update` instead of `updated`. This causes the article missing updated date.

Change `update` to `updated`

---

src/styles/generic/_code.scss

Fixes #2622
- Sets code in headings to use `normal` wrapping.

Wrap code in headings.

---

src/site/content/en/blog/monitor-total-page-memory-usage/index.md

- Shorten long code title for post that was overflowing card.
Before:
After:

Shorten performance.measureMemory title.

---

src/site/_data/contributors.js

- Add glitch link for petele in contributors.js

Add glitch link for petele in contributors.js

---

src/site/_includes/components/Meta.js

[Based on feedback from ](https://github.com/GoogleChrome/web.dev/commit/5a2924cc6a543a4a48a96d3ec14bb4e01ceda54c#r38627115)@agektmr

refactor(meta): use `&quot;` replaceValue for `"`

---

src/site/content/en/blog/monitor-total-page-memory-usage/index.md

This adds a person in Acknowledgements that I missed initially.

Fix acknowledgements section in measureMemory

---

.huskyrc

- Add instruction for folks who want to bypass husky on git commits.

Update husky comment.

---

src/site/_data/podcasts.js

Fixes #2655 
- update SotW podcast link
- ?
- profit

Update SotW podcast link

---

test/integration/partials-test.js

Based on feedback given to me from @robdodson

test(partial): test a fully generated partial json against the HTML

---

src/site/content/en/fast/use-lighthouse-for-performance-budgets/index.md

Fixing typo in "first-meaningful-paint" metric

---

src/site/_data/contributors.js

- Add tomayac's Glitch account.

Add tomayac's Glitch

---

src/site/content/en/lighthouse-performance/font-display/index.md

Mention preload in FOIT audit guide

---

src/site/content/en/lighthouse-best-practices/image-aspect-ratio/index.md

Link to aspect ratio explanation and mention image CDNs

---

src/site/content/en/lighthouse-pwa/offline-start-url/index.md

Mention Workbox in offline audit guide

---

src/site/content/en/blog/prefers-color-scheme/index.md

[prefers-color-scheme Article] Add CSS tag

---

src/site/content/en/blog/get-installed-related-apps/index.md

Fixes #2663
- Small doc fix in sample code

Tiny fix to getInstalledRelatedApps sample code

---

src/site/content/en/progressive-web-apps/using-a-pwa-in-your-android-app/index.md

- Adds not on Play for Family policy for TWAs
@b1tr0t PTAL
@tomayac FYI

Adds note on Play for Family policy for Trusted Web Activity

---

src/site/content/en/progressive-web-apps/customize-install/index.md

- Add aside about `beforeinstallprompt` event still being supported

Add aside beforeinstallprompt event is still recommended

---

src/site/content/en/blog/web-bundles/index.md

Fixes #1943
- Adds browser compatibility section to top of page
@uskay is this browser compatibility information up-to-date?
For more context, we know that browser compatibility is web developers number 1 frustration (page 19 of [DNA report](https://mdn-web-dna.s3-us-west-2.amazonaws.com/MDN-Web-DNA-Report-2019.pdf)) so I've been making sure that all web.dev pages quickly and clearly list cross-browser compatibility at the start of the page (in order to save the time for those web developers where lack of support across browsers is a blocker)

Mention browser compatibility for Bundles

---

src/site/content/en/blog/storage-for-the-web/index.md

- Clarify storage limits in Safari

Clarify storage limits in Safari

---

src/site/content/en/blog/storage-for-the-web/index.md

navigator.storage might not be defined

Properly feature-detect StorageManager

---

build.js

Adds some more chunks for the regular build to avoid unnecessary JS reparsing, and makes the Service Worker chunking _slightly_ more sane (checking for `/node_modules/${chunkName}`).

use more chunks so we do less JS parsing on update

---

src/lib/app.js

add missing localStorage import

---

src/site/_filters/expand-contributors.js
src/site/_includes/components/Author.js
src/site/_includes/components/BaseCard.js

Fixes #2786
Throw an error when a contributor is not found, and explain where the contributor should be added.

feat(contributors): give better feedback when contributor not in `_data/contributors.js`, fixes #2786

---

src/lib/components/UrlChooser/index.js

- Add missing analytics events for measure tool. Should now track when someone switches url, runs an audit, or clears the url.

Add analytics events to measure tool.

---

src/site/content/en/blog/coop-coep/index.md

Fixes #2792
- fix a 404'ing link

Fix broken link.

---

src/site/content/en/blog/covid19/index.md

- SpecialAnnouncement structured data specifications from Google
- A tool to help Gov and health organizations to create SpecialAnnouncement markup

Added Google specifications for the SpecialAnnouncement

---

src/site/content/en/blog/optimize-lcp/index.md

[Optimize Largest Contentful Paint article] Fix link

---

src/site/content/en/blog/promises/index.md

Related to #2807 
- Fixes broken relative svg path.

Fix broken svg path in promises post.

---

src/site/content/en/blog/content-indexing-api/index.md

[Content Index article] Fix links

---

src/site/content/en/blog/web-share/index.md

Add feature support information.

---

.github/workflows/required-checks-workflow.yml

- Try to be more aggressive about running this check. For whatever reason it seems to be missing some new PRs.

Add synchronize to required checks event types.

---

src/site/content/en/blog/prefers-color-scheme/index.md

[prefers-color-scheme article] Fix /color-scheme/ link

---

src/site/content/en/blog/idle-detection/index.md

- Explicitly call out top-level secure context requirement

[Idle Detection article] Explicitly call out top-level secure context requirement

---

src/site/content/en/blog/idle-detection/index.md

[Idle Detection article] Update tag

---

src/site/content/en/blog/shape-detection/index.md

- This has launched, but only on certified devices with
[Google Play Services](https://play.google.com/store/apps/details?id=com.google.android.gms&hl=en_US)
installed.

[Shape Detection article] Make compatibility clearer

---

src/site/content/en/live/index.njk
src/styles/pages/_live.scss

Related to #2899 (Although doesn't solve it).
There's too much discussion about what a share button's code looks like, but the visual design is pretty finalized so I just want to add the section in.

add share area to web.dev/live

---

src/site/_data/event.js

Update opener copy

---

src/site/content/en/live/index.njk

Update Subscribe copy

---

src/site/_data/event.js

Updates session titles copy

---

src/site/_data/event.js

Session copy update

---

src/site/_data/event.js

Add Maud to privacy talk.

---

src/site/content/en/live/index.njk

- Makes the text a little more obvious otherwise the times in the tabs seem like mistakes.

Make that time travel more obvious!

---

src/lib/components/EventTime/_styles.scss
src/site/_includes/partials/subscribe.njk
src/site/content/en/live/index.njk
src/styles/components/_subscribe.scss

Small changes to get our LH scores up. 
- Adds rel=noopener to links with _blank
- Adds empty `alt`s to hide presentational images
- Improves contrast on timezone text
- Adds a touch of left padding to the subscribe country picker so it lines up with other form fields

Get those LH scores up!

---

src/site/content/en/blog/more-variable-font-options-in-chromium-83/index.md

use playsinline attribute on video elements

---

src/site/_data/contributors.js
src/site/content/en/blog/more-variable-font-options-in-chromium-83/index.md

fixes edits requested at https://github.com/GoogleChrome/web.dev/pull/2961#pullrequestreview-417569082

post patch: system ui

---

src/site/content/en/blog/native-file-system/index.md

- Fixes a simple typo in NativeFS

Fix serlializing typo in NativeFS

---

src/site/content/en/progressive-web-apps/customize-install/index.md

- Tweak display mode tracking at launch
- Adds display mode changes

Analytics for PWA tweak

---

src/site/content/en/blog/resize-observer/index.md

* Monospace shouldn't be in titles
* Rulebook says don't capitalize after a colon

Correct title

---

src/site/_collections/authors.js
src/site/_data/contributors.js
src/site/_data/event.js
src/site/_filters/live-posts.js
test/unit/src/site/_filters/live-posts.js

Fixes #3010
Fixes #3016 
Fixes #3018 
Fixes #3019

fix data issues and validate social link

---

src/site/_data/contributors.js

Change my name back

---

src/site/_data/event.js

Fix Jake's talk title, add Surma as co-speaker.

fix data web.dev/live

---

package-lock.json
package.json

- Just a little update to eleventy to unlock some new features. I tested dev and prod builds and they seem to work just fine and don't require any changes.

Upgrade to eleventy v0.11

---

src/site/content/en/blog/wakelock/index.md

[Wake Lock article] Add feature detection

---

src/site/content/en/blog/monitor-total-page-memory-usage/index.md

An origin trial extension was approved [eight days ago](https://groups.google.com/a/chromium.org/g/blink-dev/c/LuoryMqT7wQ/m/OxY4caxCAgAJ).

Update OT info in measureMemory() article.

---

src/site/content/en/blog/vitals-tools/index.md

Add additional note to vitals-tools post

---

src/site/content/en/blog/web-animations/index.md

Updates for "Web Animations API improvements in Chromium 84"
- Updated links for Web Animations post 
- Switch order of a video and demo for better flow

[Web Animations Post] Update demo links from Codepen to Glitch

---

src/site/content/en/fast/preload-critical-assets/index.md

- Adds note on preload bug
CC @yoavweiss @spanicker

Adds note on preload bug in "Preload critical assets"

---

src/site/content/en/vitals/index.md

@robdodson and @kaycebasques  PTAL

feat(vitals): include feedback form, fixes #3062

---

src/site/content/en/lighthouse-performance/offscreen-images/index.md
src/site/content/en/lighthouse-performance/total-byte-weight/index.md
src/site/content/en/lighthouse-performance/unminified-css/index.md
src/site/content/en/lighthouse-performance/unminified-javascript/index.md
src/site/content/en/lighthouse-performance/unused-css-rules/index.md
src/site/content/en/lighthouse-performance/uses-optimized-images/index.md
src/site/content/en/lighthouse-performance/uses-responsive-images/index.md
src/site/content/en/lighthouse-performance/uses-text-compression/index.md
src/site/content/en/lighthouse-performance/uses-webp-images/index.md
src/site/content/en/lighthouse-seo/robots-txt/index.md

Relevant Lighthouse change: 
https://github.com/GoogleChrome/lighthouse/pull/10870

Lighthouse docs: switch from kilobytes to kibibytes

---

server.js

- Turn the service worker back on.

Turn off the service worker kill switch.

---

src/site/content/en/blog/app-shortcuts/index.md

This PR adds a quality measure for app shortcut icons on Android.
Live preview: https://deploy-preview-3091--web-dev-staging.netlify.app/app-shortcuts/#icons-(optional)

Added app shortcut icon quality measure on Android

---

src/site/content/en/metrics/lcp/index.md

- Fix usage example link in LCP article

Fix broken link in LCP article

---

src/site/content/_redirects.yaml

Fixes #3109
- Redirect broken LH report link.

Fixes #3109. Redirect 404ing LH learn more link.

---

src/site/content/en/live/index.njk

Fixes #3102
- Update language in 'what to expect' section of web.dev/live

Update "What to expect" language.

---

src/site/content/en/lighthouse-performance/uses-text-compression/index.md

- Updates browser compatibility information
- Mentions `Accept-Encoding` and `Content-Encoding`

Update the text compression guidance

---

src/site/_includes/partials/subscribe-action.njk
src/site/content/en/live/index.njk

feat(subscribe-analytics): add tracking for clicking subscribe/newsletter buttons, fixes #3106

---

src/site/content/en/live/index.njk

Fixes #3071
- Added link to community guidelines

[Pre-event] Add link to community guidelines

---

src/site/_includes/codelab.njk
src/site/_includes/components/ArticleNavigation.js
src/site/_includes/partials/post.njk

I remove the "next" link on ArticleNavigation, as it is scarcely used & complicated the code quite a lot.

Simplify ArticleNavigation

---

src/site/content/en/vitals/index.md

- Adds web-vitals tag to /vitals/ landing page so it shows up on /tags/web-vitals

Add web-vitals tag to landing page.

---

src/site/content/en/blog/optimize-lcp/index.md

Fixes Chrome version mention

---

src/site/content/en/fast/using-lighthouse-bot-to-set-a-performance-budget/index.md

- npm script needs the `--` to pass arguments

docs: add missing param in script

---

src/site/content/en/blog/prefers-color-scheme/index.md

- Remove references to `no-preference`.

[prefers-color-scheme article] Remove references to `no-preference`

---

src/site/content/en/blog/app-shortcuts/index.md

This PR simply adds app shortcuts icons requirement for bubblewrap.

Add icon requirement for bubblewrap

---

src/site/content/en/lighthouse-pwa/redirects-http/index.md

- Provides links to Stack Overflow questions or official documentation that seem to answer how to set up HTTP=>HTTPS redirects in various popular servers

Add links for servers

---

src/site/content/en/blog/fetch-metadata/index.md

[Fetch Metadata article] Improve typography

---

src/site/content/en/secure/same-site-same-origin/index.md

- An additional note and a link to clarify what is "schemeful same-site".

Update same-site/same-origin article

---

src/site/_data/paths/fast.js

- Links /fast to the CommonJS overview on the blog

Add CommonJS overview to /fast

---

src/site/_data/event.js

Fixes #3204
- Changed the talk title

Fixes #3204

---

src/site/_data/event.js

Fixes #3208
- Removed the talk from Day 1 - AMPs Performance Secrets

Remove talk #3208

---

src/site/content/en/handbook/markup-media/index.md
src/site/content/en/handbook/web-dev-components/index.md

Fixes #3112
- Adds YouTube component example to handbook.

Update handbook guidance for YouTube component.

---

src/site/content/en/metrics/lcp/index.md

Fixed the in-the-field link

---

src/site/content/en/progressive-web-apps/app-like-pwas/index.md

[App-like PWAs] Fix title bar link

---

src/site/_includes/layout.njk

Related to #3243 
- Throw in a query string to cache bust sw css cache.

Cache bust css.

---

src/lib/app.js

- Let our SW install on our staging server.

Allow staging our sw.

---

src/site/content/en/live/index.njk
src/styles/pages/_live.scss

Fixes #3075
- Adds `.w-event-carousel` for the overflow scrolling video thumbnails thinger

Add overflowing thumbnail carousel.

---

src/site/content/en/reliable/service-workers-cache-storage/index.md

-  Update service workies game link

Update service workies game link

---

src/lib/components/EventTime/index.js
tools/percy/.percy.conf.yml
tools/percy/snapshots.js

- Fixes broken EventTime widget
- Adds snapshot testing to the live page
- Adds percy specific CSS to hide iframes since they're unstable

Fix EventTime. Add percy to live page.

---

src/site/content/en/blog/optimize-cls/index.md

- Fixed URL of serve-responsive-images

Fixed URL of serve-responsive-images

---

src/lib/components/EventStore/index.js

missed unistore cleanup

---

src/site/content/en/blog/origin-trials/index.md

@samdutton I've made a few suggestions based on my own experience with and knowledge of origin trials.

Additions and clarifications to the origin trial article.

---

src/site/content/en/reliable/adaptive-loading-with-service-workers/index.md
src/site/content/en/reliable/app-shell-ux-with-service-workers/index.md
src/site/content/en/reliable/codelab-building-resilient-search-experiences/index.md
src/site/content/en/reliable/instant-navigation-experiences/index.md
src/site/content/en/reliable/resilient-search-experiences/index.md

- Adds relevant tags
- Adds `blog` tag so that they show up on the blog
- Sets date to today for all of these posts so that they show up on the top of the blog

Add tags and fix date for advanced PWA collection

---

src/site/content/en/blog/trust-tokens/index.md

Updates from team, and some minor wording team.

Update Trust Tokens article

---

src/site/_data/event.js

Fixes #3348
- Update day 3 to be 4 hours

Update time for day 3.

---

src/site/_includes/content/metrics/performance-observer-init.njk
src/site/content/en/metrics/cls/index.md
src/site/content/en/metrics/custom-metrics/index.md
src/site/content/en/metrics/fcp/index.md
src/site/content/en/metrics/fid/index.md
src/site/content/en/metrics/lcp/index.md
src/site/content/en/metrics/tbt/index.md
src/site/content/en/metrics/tti/index.md

This PR fixes or addresses a number of recent issues in the metrics documentation:
- Fixes #3065
- Addresses #3067
- Addresses #3068
- Fixes #3108
- Fixes #3197
- Fixes #3157
- Fixes #3237
cc: @npm1, @anniesullie, @robdodson

Metrics updates

---

src/site/content/en/blog/flexbox-gap/index.md

Restoring article with minor edits to tense. 
Confirmed release for chrome 85, let's launch the article same day 👍 
cc @davidsgrogan

Flex gap proper release

---

src/site/content/en/blog/wakelock/index.md

[Wake Lock article] Add launched info

---

src/site/content/en/blog/fugu-status/index.md

- Move wake lock to launched section

[Fugu Status] Move wake lock to launched section

---

src/site/content/en/blog/origin-trials/index.md

One spelling error also fixed.

Origin Trials wording tweaks

---

src/site/_transforms/service-worker-partials/index.js
test/integration/build-test.js

As PR. This will force the SW to always go to the network.

disable web.dev/LIVE partial to force online-only

---

compile-css.js

Works around #3363 by writing the old file name too.

always write dist/app.css

---

src/site/content/en/blog/wakelock/index.md

Fixes #3355
- Add link to Betty Crocker case study

[Wake Lock article] Add link to Betty Crocker case study

---

src/site/content/en/authors/feed.njk
src/site/content/en/feed.njk
src/site/content/en/tags/feed.njk

fix(rss): fix author title in feeds, fixes #3365

---

src/lib/components/EventMap/_styles.scss
src/lib/components/EventQandA/_styles.scss
src/lib/components/EventQandA/index.js
src/lib/pages/live.js
src/site/_data/event.js
src/site/content/en/live/index.njk
src/styles/pages/_live.scss

Fixes #3338, Fixes #3121
- Add Q&A section
Leaving placeholder data in so folks can preview but will remove before merging.

Add q and a section.

---

src/site/_data/paths/fast.js

- list the CrUX API guide/blog post on the /fast page

List CrUX API guide on /fast

---

src/site/_data/event.js

Rev vitals talk title.

---

src/lib/components/EventTime/_styles.scss
src/lib/components/LivestreamContainer/index.js
src/site/content/en/live/index.njk
src/styles/components/_subscribe.scss

- improve contrast on subscribe form and web.dev/live timezones
- add missing rel=noopener attribute
- add missing title attributes to iframes

Small improvements to get our lh scores up.

---

server.js

If anyone is seeing this problem I'm concerned because it means that Workbox is not always correctly precaching assets. And the real challenge there is they'll never upgrade their SW since the registration code is inside our JS.
To be fair, the lifetime of cached assets is not guaranteed inside `Cache`.
The simpler way to solve this is to go back to "?v=...." search params.

fallback to loading other css/js

---

src/site/content/en/live/index.njk

This is a small test to check our server and sw caching.

Tweak html to test caching.

---

src/site/content/en/blog/commonjs-larger-bundles/index.md

Fix Typo - add missing space

---

src/site/content/en/blog/optimize-fid/index.md

- Updates "Optimize First Input Delay" guide:
- Removes the [Minify and compress JavaScript files](https://web.dev/optimize-fid/#minify-and-compress-javascript-files) section
- Moves the entire [Reduce JavaScript](https://web.dev/optimize-fid/#reduce-javascript-execution) section to the end of the article
Note: It may look like a lot of text was changed, but it's mostly sections being re-arranged. Going through each of the commits will show the changes easier.

Update Optimize FID guide

---

src/lib/components/LivestreamContainer/_styles.scss
src/lib/components/LivestreamContainer/index.js
src/site/_data/event.js
src/styles/components/_livestream-container.scss

- Add a close/open chat button
- Improve CLS when the player loads in

Add button to let folks collapse the live chat. Also improve some CLS issues.

---

src/site/_data/event.js

Add premiere links.

---

src/site/content/en/blog/progressively-enhance-your-pwa/index.md

This PR fixes some formatting issues with block quotes in https://web.dev/progressively-enhance-your-pwa/#progressive-enhancement
@tomayac

Fix links in article blockquote

---

src/site/_data/site.js
src/site/content/en/index.njk

- Add some 'day of' banners :)

Add updated banners for live event..

---

src/site/content/en/live/index.njk

Update anchor on regional-events section

---

src/lib/components/EventCarousel/index.js
src/site/_data/event.js

Force playlist to be clickable

---

src/lib/components/EventMap/index.js
src/site/_data/event.js

+ Adapt EventMap to real data
+ Add data to event.js

Update regional events for /live

---

src/site/content/en/index.njk
src/styles/components/_all.scss
src/styles/components/_hero-banner.scss

Instructions from marketing are that this should go live later this week. Adding the DO NOT MERGE flag till then.
- Add a custom hero banner component.

Add hero banner.

---

src/lib/components/EventSchedule/index.js

Fixes #3423
- Only switch the active tab if the active day changes.

Only update active tab if it's different.

---

src/lib/components/EventMap/_styles.scss
src/lib/components/EventMap/index.js
src/site/_data/event.js
src/site/content/en/live/index.njk

Change EventMap's display so that it includes the event's country as well as city.

 Add country to eventMap

---

src/site/_data/event.js
src/site/content/en/live/index.njk

Got a bit confused as to who was supposed to ship this so I did a quick PR this morning.
Fixes #3428
- Ships post event phase 
- Enables Q&A
- Adds note to Q&A section

Ship post event flag. Add note to Q&A

---

.github/workflows/cleanup-versions-workflow.yml
package-lock.json
package.json
tools/cleanup-versions/index.js

Fixes #2696.
I haven't tested the workflows—I do think that GitHub will pass through the environment variables (as our other scripts which run `gcloud` work fine, and the internal call to `gcloud` in the script by default also passes through `process.env`), but basically I'd like to commit and fix if there's some problem.

add cleanup versions script and workflow

---

src/lib/components/EventScheduleModal/index.js
src/lib/components/EventStore/index.js
src/site/_data/event.js
src/site/_data/site.js
src/site/_includes/components/EventTable.js
src/site/content/en/index.njk
src/styles/pages/_live.scss

Fixes #3439
Fixes #3438
Fixes #3421
This should probably be multiple PRs. I can make that so if it's important, but otherwise this just resolves all the current outstanding post-event stuff.
Some screenshots:
We place the "Watch on YouTube" to the right, unless it overflows.

post-event cleanup

---

src/site/content/en/live/index.njk

Fixes issue [noted here](https://github.com/GoogleChrome/web.dev/pull/3434#issuecomment-654145194) by @harleenkbatra08 
Removes duplicate copy.

fix wdl copy

---

src/site/content/en/blog/get-installed-related-apps/index.md

Reverts GoogleChrome/web.dev#3388

Revert "Update getInstalledRelatedApps() for Windows support."

---

src/site/content/en/blog/one-line-layouts/index.md

Add playsinline attribute to videos and fix indentation

---

src/site/content/en/blog/disallow-synchronous-xhr/index.md

https://groups.google.com/a/chromium.org/g/blink-dev/c/Ubh0hXsM2_o/m/0aOCdlCaAQAJ

Update origin trial end dates.

---

src/site/content/en/fast/native-lazy-loading/index.md

- Re-focus this guide around native image lazy-loading (we'll cover iframes in more detail separately)
- Expand guidance to better capture nuance about the Chromium implementation
- Revise some of the FAQs and best practices 
FYIs: @scott-little @domfarolino
There are still some changes I would like to land here covering CMS, but sharing progress so far.

Updates to native lazy-loading guide

---

src/site/content/en/blog/hands-on-portals/index.md

Fixing origin trial links

---

src/site/_includes/partials/post.njk

fix(feedback): move feedback widget after codelab callout, fixes #3189

---

.github/workflows/cleanup-versions-workflow.yml
.github/workflows/snapshot-firestore-workflow.yml

🤦 
I forgot the misc setup steps—clone, setup NPM, etc. Of course the script wasn't running.

Add missing obvious steps to cleanup workflow

---

.github/CODEOWNERS

chore: add more codeowners

---

src/site/content/en/payments/life-of-a-payment-transaction/index.md

Let me send this separate from the other batch pull request as this is an important change.

Small but important update to a payment article

---

src/site/_data/paths/handbook.js
src/site/content/en/handbook/pull-requests/index.md

Adds https://web.dev/handbook/pull-requests

Add content PR guidelines

---

src/site/content/en/react/accessibility-auditing-react/index.md

Fixes #1651 
- Small tweak to fix some broken syntax

Fixes #1651. Add missing syntax.

---

src/site/content/en/handbook/word-list/index.md

Because I would have expected three words or one camel case word, not the mix that it is.

Add PageSpeed Insights

---

locale-handler.js
src/lib/actions.js
src/lib/app.js
src/lib/components/LanguageSelect/index.js
src/lib/loader.js
src/lib/store.js
src/lib/urls.js
src/lib/utils/language.js
src/lib/utils/router.js
src/site/_includes/layout.njk
src/site/_includes/partials/post.njk
src/site/content/en/en.11tydata.js
src/site/content/pl/pl.11tydata.js

This reverts commit ffd2a79fd1116d9d22b7a1a78d39069ed248295d.
Fixes #3519 
- Revert #3503

Revert "Add language routing to internal navigation in SPA (#3503)"

---

src/site/_collections/authors.js
src/site/_collections/hooks/authors.js
src/site/_collections/hooks/newsletter.js
src/site/_collections/hooks/tags.js
src/site/_collections/hooks/utils.js
src/site/_collections/tags.js
src/site/content/en/authors/individual.11tydata.js
src/site/content/en/newsletter/index.11tydata.js
src/site/content/en/tags/individual.11tydata.js

Similar filtering as in /blog, used to filter authors, tags and newsletters pages.

Filter by lang tags and authors collections

---

src/site/content/en/blog/app-shortcuts/index.md

This PR simply mentions Windows stable support for app shortcuts in https://web.dev/app-shortcuts
FIX: https://github.com/GoogleChrome/web.dev/issues/3228
Live preview at https://deploy-preview-3408--web-dev-staging.netlify.app/app-shortcuts/
FYI @jungkees @jgw96

Add Windows stable support for app shortcuts

---

src/site/content/en/blog/vitals-field-measurement-best-practices/index.md
src/site/content/en/vitals/index.md

This PR:
- Adds a note about how tools should assess Core Web Vitals compliance for a page (fixes b/158817700).
- Fixes a broken link.

Clarify CWV assessment compliance

---

src/site/content/en/blog/get-installed-related-apps/index.md

DO NOT MERGE UNTIL: July 22, 2020

Update getInstalledRelatedApps() for Windows support

---

src/site/content/en/blog/at-property/index.md

Use GIFs as temporary workaround for Safari issue

---

src/site/content/en/blog/at-property/index.md

chore(typo): megenta -> magenta

---

src/lib/components/EventQandA/index.js
src/site/_data/event.js

Fixes #3511
Just added some more questions. However the list is getting crazy long, maybe a bit unruly... Maybe we can add a starred questions so we can limit the list on load? So instead of seeing all qs at first, you see starred qs (which would be much shorter).
@harleenkbatra08 thoughts?

feat(q-and-a): add questions from day 2, fixes #3511

---

src/site/content/en/blog/text-fragments/index.md

- Add documentation how people can opt out of this feature.

[Text Fragments article] Add opt-out steps

---

src/site/content/en/progressive-web-apps/app-like-pwas/index.md

[App-like PWAs article] Add Vibration API idea

---

test/unit/src/lib/components/LivestreamContainer/index.js

- Disable a flaky test. #3585 was getting tripped up by the test and I've seen it happen to other PRs.

Disable flaky test.

---

src/site/content/en/blog/keyboard-lock/index.md

- Add feature detection
- Add missing closing code marks

[Keyboard Lock article] Fix issues

---

src/site/content/en/blog/drag-and-drop/index.md

Fixes #3457
- Adds updated content based on https://html5rocks.com/en/tutorials/dnd/basics/

Migrate Drag and Drop guide

---

src/site/content/en/blog/building-a-pwa-at-google-part-1/index.md

- Direct source link for Safari policy

[Building PWAs at Google] Direct source link for Safari policy

---

src/site/content/en/blog/referrer-best-practices/index.md

[Referrer best practices article] Inclusive language fix

---

src/site/content/en/blog/text-fragments/index.md

- Add link to https://crbug.com/1055455.

[Text Fragments URL] Add bug link

---

src/site/content/en/blog/idle-detection/index.md

- Fix the OT end date: 86, not 87.

[Idle Detection article] Fix OT end date

---

src/site/content/en/blog/referrer-best-practices/index.md

Fixes: N/A
- Changed the link to point to the now-published WebFu article
- Made clearer that Chrome is planning this change

Small fix: referrer best practices article

---

src/site/content/en/blog/web-on-android/index.md
src/site/content/en/progressive-web-apps/web-on-android/index.md

- Adds the Web on Android blogpost
@jpmedley This is sitting inside the `progressive-web-apps` folder, but I'm not sure if that's the best place for it. I have added a `DO NOT MERGE` label just to make sure we confirm the appropriate place before merging. Let me know what you think.
Closes #1313

Adds the Web on Android blogpost

---

src/site/_data/site.js

- Adds a survey banner for @harleenkbatra08

Add survey banner.

---

src/site/_data/paths/secure.json

Fixes #3568
This pull request adds aliases to /secure.
cc: @maudnals @rowan-m @samdutton @kaycebasques

Add aliases to /secure as per #3568

---

src/site/content/en/blog/web-share-target/index.md

- Update to Web Share Target article to recommend providing both mime and extension

Update Web Share Target to recommend mime+extension

---

src/site/content/en/blog/text-fragments/index.md

[Text Fragments article] Add `noopener` details

---

src/site/content/en/blog/get-installed-related-apps/index.md

- Clarifies native vs Android app 
- More explicit supported features/platforms
- Link to PWA installed sample
- Cleaned up define relationship section
- Updated info about Windows app support

Updates to getInstalledRelatedApps

---

README.md

Update readme with deploy instructions

Add deploy instructions to readme.

---

src/site/_includes/components/AuthorInfo.js
src/site/_includes/components/Breadcrumbs.js
src/styles/components/_breadcrumbs.scss

Fixes #3652, Fixes #3651 
- Replace material icon font with inline svg
- Don't render the `ul` of social accounts if the author doesn't have any.

Fix a11y screen reader issues.

---

src/site/content/_redirects.yaml

Fixes #3657 
- Fix whitespace in _redirects.yaml

Fixes broken redirects.

---

src/site/content/en/blog/get-installed-related-apps/index.md

- Tweak the windows gIRA instructions

tweak to windows App id value

---

src/site/content/en/blog/text-fragments/index.md

- `s/Location.prototype.fragmentDirective/document.fragmentDirective/`

[Text Fragments article] New fragmentDirective location

---

src/site/content/en/blog/shape-detection/index.md

- Barcode is supported w/o flag, so move it first.

[Shape Detection article] Move Barcode Detection up

---

src/site/content/en/lighthouse-performance/render-blocking-resources/index.md

... deprecated since Chrome 80.

Remove references to HTML imports

---

.github/workflows/lint-and-test-workflow.yml

See https://github.com/GoogleChrome/web.dev/issues/3705#issuecomment-673654107

Temporarliy remove path filters from workflow.

---

.github/workflows/lint-and-test-workflow.yml

- Forgot to add the filters back when i revved dorny/path-filters 🤦‍♂️

Add missing filter steps back to workflow.

---

package-lock.json
package.json

I think Percy stopped explicitly depending on Puppeteer.

add puppeteer as explicit dep

---

package-lock.json
package.json

Rebuilds at least for me weren't working as: `-c` took an argument, but `--silent` did not. We had them the wrong way around.

chokidar --silent fix

---

.github/workflows/tranaslation-status-workflow.yml
package.json
src/site/_includes/partials/translation-disclaimer.njk
src/site/content/pl/accessible/control-focus-with-tabindex/index.md
src/site/content/pl/pl.11tydata.js
tools/update-translated/index.js

This adds a Github Action that updates a "translated" field in .md files in directories other than /en/ on every push to i18n-gitlocalize branch (a target branch for the gitlocalize service).

Add a "translated" Github action

---

test/integration/src/site/_collections/index.js
test/integration/src/site/_collections/recent-blog-posts/dev.js

Integration tests seemed to be bottlenecking lately, so this should help.

Fix flaky test

---

src/site/content/en/blog/progressively-enhance-your-pwa/index.md

[Progressively enhance your PWA article] Add YouTube video link

---

src/site/content/en/blog/preload-optional-fonts/index.md

Everytime I read this post I am dying to find the commits. So.. yah. This links them up.
💅

preload-optional-fonts: link up relevant crbug

---

src/site/_data/site.js

- Take down survey banner because the timeline is finished

Take down survey banner.

---

src/site/content/sitemap.xml.njk

Related to #3632
- Add full paths to sitemap.xml to fix it.

Fix broken sitemap.

---

src/site/content/en/blog/origin-trials/index.md

- Adds a warning about downtime.

[Origin Trials article] 2nd attempt: add downtime warning

---

src/site/content/en/blog/serial/index.md

- Just some minor things here and there.

[Serial API article] Minor refinements

---

src/site/content/en/blog/media-session/index.md
src/site/content/en/blog/web-animations/index.md

In response to a valid point raised on [Twitter](https://twitter.com/brianskold/status/1295943386092826625) on the perception of this article, I've updated the title and copy to better reflect the state of the web community.
- Change title to "Using the full power of the Web Animations API"
- Update paragraph to show primary/immediate adoption from Mozilla and Safari
- Update caption to specify Chromium

[Update] WAAPI Post

---

src/site/content/en/blog/fugu-status/index.md

- Add Idle Detection API to the list of Fugu APIs
- Consolidate dates

Add Idle Detection to the Fugu list

---

src/site/content/en/blog/local-fonts/index.md

[Local Font Access] Character case fixes

---

src/site/_data/authorsData.json
src/site/content/en/blog/aria-poison-or-antidote/index.md

Some nits and removal of statement that Firefox is more mature, no longer true.

Update ARIA blog post

---

.github/workflows/alex-workflow.yml

Add missing alex steps.

---

src/site/content/en/secure/same-site-same-origin/index.md

Fix a typo and add a bit about eTLD

Fix a typo and add a bit about eTLD

---

src/site/content/en/blog/referrer-best-practices/index.md

Fixes #3782
- Added payment paragraph, as approved [in this draft](https://docs.google.com/document/d/105DB_zyv9PZ9Bd4zwRHa5AdRC0wxluwXzgZkKYyol_Q/edit#)

Add payments section to referrer best practices guide

---

src/lib/components/TableOfContentsButton/index.js

- Tracks ToC interactions via Google Analytics Events

Track Table of Contents (ToC) opens and closes

---

src/site/content/en/blog/css-marker-pseudo-element/index.md

Article has been published early and includes assumptive verbiage that needs corrected.

Fixes ::marker article tense

---

src/site/_includes/feed.njk
src/site/content/en/feed.njk

Moves feed.njk markup to an include for better reusability

Move feed content to an include

---

src/site/content/en/blog/web-otp/index.md

- Replaced with a simpler demo
- Glitch embedded
- Better interoperability guide for Safari users

Update for Web OTP article

---

src/site/content/en/blog/variable-fonts/index.md

- Fix typo in sentence attributing author of Roboto typeface

Fix typo in sentence attributing author of Roboto typeface

---

src/site/content/en/blog/get-installed-related-apps/index.md

@petele Can you review and merge?

Remove "Request an origin trial token" link

---

src/site/content/en/blog/text-fragments/index.md

- Add ModHeader opt-out option.

[Text Fragment article] Add ModHeader opt-out option

---

src/site/content/en/blog/web-otp/index.md

Next step: @samuelgoto to review

One more update to the Web OTP article

---

src/site/content/en/blog/multi-screen-window-placement/index.md

- Add spec draft link at bottom

[Window Placement article] Add spec draft link at bottom

---

src/site/content/en/blog/fugu-status/index.md
src/site/content/en/blog/native-file-system/index.md

Addresses #3663 
**There has been no movement (that I'm aware of) by spec authors to change the name of this API.**

Update Native File System article for stable release.

---

src/site/content/en/blog/periodic-background-sync/index.md

@jeffposnick This needed to be updated now that the feature is out of origin trial. Do you know where to get information on how other Chromium forks, Edge and Samsung, specifically are handling the engagement issues referenced in the section I edited? It would be nice to say something specific.
cc: @Rumyra

Remove reference to ongoing trial.

---

src/site/content/pl/index.md

test conflicts in gitlocalize

---

src/lib/actions.js
src/lib/components/TableOfContentsButton/index.js

This should hopefully address the misfire of the click/open event.

fix(analytics): track `ToC` event from actions rather than button component

---

src/site/content/en/blog/maskable-icon/index.md

Fixes https://bugs.chromium.org/p/chromium/issues/detail?id=1128836#c6
- Update recommendation to not use `any` paired with `maskable`.

Update rec. to not use `any` paired with `maskable`

---

src/site/content/en/blog/css-clipping/index.md

Fixes code example in article "How to use CSS clipping"
P.S. I just use "Improve this article" link. Maybe i doing something wrong...

Fix code example

---

src/site/_data/site.js

- Adds a banner for the MDN compat survey

Add MDN compat survey banner.

---

src/site/content/en/blog/idle-detection/index.md

[Idle Detection article] Add Puppeteer testing info

---

src/site/_includes/homepage.njk
src/site/_includes/layout.njk
src/site/content/en/index.md

- Remove web.dev LIVE from the top nav and the homepage

Remove web.dev LIVE banner

---

src/site/content/en/blog/idle-detection/index.md

- Remove fuzzing mitigation, since we no longer (plan to) do this.

[Idle Detection article] Remove fuzzing mitigation

---

src/site/content/en/blog/trusted-types/index.md

[typo] Add missing bracket

---

src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/index.md

Fix second number in figure caption

Fix figure description in Mercade Libre case study

---

src/site/content/en/blog/notification-triggers/index.md

[Notification Triggers article] Revive Notification Triggers

---

src/site/content/en/blog/notification-triggers/index.md

[Notification Triggers article ] Remove stray ')'

---

src/site/content/en/blog/how-to-distribute-signed-http-exchanges/index.md
src/site/content/en/blog/how-to-set-up-signed-http-exchanges/index.md

Update titles of SXG articles

---

src/site/content/en/blog/declarative-shadow-dom/index.md

I'd meant to correct this earlier, got confirmation from Chris and Mason on the wording.

Declarative Shadow DOM: clarify nature of tentative release

---

src/site/content/en/blog/file-system-access/index.md

- Native File System → File System Access

[File System Access article] Native File System → File System Access

---

src/site/content/en/blog/idle-detection/index.md

- calling permission requires a user gesture. 
@jpmedley, please just merge this once you approve, since I’ll be OoO next week. Thanks!

[Idle Detection article] Add user gesture requirement 

---

src/site/content/en/blog/conversion-measurement/index.md

- One semantic fix
- Cosmetic fixes

Minor fixes on the conversion measurement article

---

src/site/_drafts/_template-post/index.md

This PR adds an acknowledgements section to the post template.

Add Acknowledgements section to post template

---

src/site/content/en/blog/zdf/index.md

- Fix a typo
- Fix a link
- Add a link

[ZDF PWA article] Typo fix and two links

---

src/site/content/en/animations/animations-guide/index.md

- Added some examples
- Moved the comparison of bad and good practice
Not complete yet as I need to do the other DevTools walkthroughs, but wanted to check this was the right direction with @kaycebasques

updates to animations guide

---

src/site/_data/site.js

- Replace the site banner with one for the MDN survey.

Add mdn survey banner.

---

src/site/_data/paths/progressive-web-apps.json
src/site/content/en/progressive-web-apps/manifest-updates/index.md

- Article on how Chrome (browsers) handle updates to the web app manifest.
The long term plan is to include other browsers in this, but in the mean time, it is Chrome specific. See #4038 for additional details.

How browsers handle updates to the web app manifest

---

src/site/content/en/blog/disallow-synchronous-xhr/index.md

Update guidance around unload event

---

src/site/_data/tagsData.json
src/site/content/_redirects.yaml
src/site/content/en/blog/hid-examples/index.md
src/site/content/en/blog/hid/index.md
src/site/content/en/blog/nfc/index.md
src/site/content/en/blog/serial/index.md

This PR is about adding a new "Devices" tag and tagging devices related articles
I'd love to get a nice cover asset for this collection though.
Who should I ping?
Live preview:
- https://deploy-preview-4001--web-dev-staging.netlify.app/tags/devices/

Tag devices related articles

---

src/site/content/en/blog/min-max-clamp/index.md

Fixes code sample typo in min(), max(), clamp() post

[bugfix] Fix typo in min, max, clamp post code sample

---

README.md

Added link of node site so that every time user can check any latest version by checking on it.
- 
- 
-

Added link to check latest

---

src/site/content/en/fast/signed-exchanges/index.md

Add missing word 'of'

---

src/site/content/en/blog/webcodecs/index.md

- update feedback section 
- move frame.destory() till after the frame is no longer used

Webcodecs blogpost minor fixes

---

src/site/_data/site.js

- Replaces MDN banner with CDS banner

Add cds 2020 site banner.

---

src/site/content/en/blog/how-to-file-a-good-bug/index.md

- adds a link to the chromium bisect-builds tool

[file a good bug article] add pointer to bisect-builds.py

---

src/site/content/en/blog/web-otp/index.md

Small changes to the article content to provide more precise information.

Update Web OTP article

---

src/site/content/en/blog/referrer-best-practices/index.md
src/site/content/en/secure/same-site-same-origin/index.md

Fixes #4099
- Added note on WebKit
- Added subtitles for clarity / deep-linking
- Added a tip on how to find the referrer policy of a page

Add note on WebKit to the referrer best practices guide

---

src/site/content/en/blog/file-handling/index.md

- UI>Browser>WebAppInstalls>FileHandling

[File Handling article] More accurate Blink component

---

src/site/content/en/blog/text-fragments/index.md

- Update article now that crbug.com/1055455 is fixed.
CC: @bokand

[Text Fragment article] Update article now that crbug.com/1055455 is fixed

---

src/site/content/en/blog/local-fonts/index.md

- Update now that origin trial has started.

[Local Font Access articlw] Update now that origin trial has started

---

src/site/content/en/reliable/offline-ux-design-guidelines/index.md

[Offline UX Design Guidelines article] Use columns for comparisons

---

src/site/content/en/blog/declarative-shadow-dom/index.md

- Use code font
CC: @developit

[Declarative Shadow Root article] Make adoptedStyleSheets appear in code font

---

src/site/content/en/blog/async-clipboard/index.md

[Clipboard article] Add missing `>`

---

src/site/content/en/blog/file-handling/index.md

Fixes #4144.
- Add an example to the intro.
- Make the *user control* section actionable.

[File Handling article] Content clarity improvements 

---

src/site/content/en/blog/gamepad/index.md

This fixes a build failure. I'm not incredibly happy that we didn't see this on PR submission, it should be more obvious.

fix failure

---

src/site/content/en/blog/text-fragments/index.md

- Add links to all browser versions of the extension.

[Text Fragments article] Add links to all browser versions of the extension

---

src/site/content/en/blog/gamepad/index.md

CC: @PaulKinlan.
- Remove Switch references
- Add iframe embed instead

[Gamepad article] Remove Switch references, add iframe embed instead

---

src/site/content/en/blog/file-system-access/index.md

Thanks, @photopea (https://github.com/photopea/photopea/issues/2118#issuecomment-723442850).
- s/opts/options/

[File System Access article] s/opts/options/

---

src/site/_data/site.js

- Adds a banner for a UX case study. @harleenkbatra08 fyi

Add ux banner

---

src/site/content/en/fast/browser-level-image-lazy-loading/index.md
src/site/content/en/handbook/content-checklist/index.md
src/site/content/en/handbook/pull-requests/index.md
src/site/content/en/media/media-application-basics/index.md
src/site/content/en/media/media-cheat-sheet/index.md
src/site/content/en/media/media-experience/index.md
src/site/content/en/media/video-and-source-tags/index.md
src/site/content/en/notifications/codelab-notifications-push-server/index.md
src/site/content/en/progressive-web-apps/drive-business-success/index.md
src/site/content/en/react/accessibility-auditing-react/index.md
src/site/content/en/react/how-amp-can-guarantee-fastness-in-your-nextjs-app/index.md
src/site/content/en/react/precache-with-workbox-react/index.md
src/site/content/en/react/prerender-with-react-snap/index.md
src/site/content/en/react/virtualize-long-lists-react-window/index.md
src/site/content/en/reliable/instant-navigation-experiences/index.md
src/site/content/en/reliable/resilient-search-experiences/index.md
src/site/content/en/reliable/runtime-caching-with-workbox/index.md
src/site/content/en/secure/codelab-same-origin-iframe/codelab-same-origin-iframe.md

Hi everyone, everything fine? 😉
- Corrects spelling errors in the documentation

Corrects some spelling errors

---

src/site/content/en/fast/publish-modern-javascript/index.md

/cc @kaycebasques @housseindjirdeh

Article: Modern

---

src/site/content/en/blog/file-handling/index.md

Fix the typo in file-handling.md

---

src/site/content/en/blog/app-shortcuts/index.md

This PR is about updating the WebAPK article link and removing a DevTools note.

Update webapk article link & remove DevTools note

---

src/site/content/en/blog/local-fonts/index.md

[Local Fonts article] Correct Blink component

---

.github/workflows/cleanup-versions-workflow.yml
.github/workflows/continuous-integration-workflow.yml
.github/workflows/snapshot-firestore-workflow.yml

Make sure we're pinned to the current stable release of this Action.

pin our gcloud dep in GH Actions

---

src/site/content/en/blog/fugu-status/index.md

- Make this less Google-centric.

[Fugu Status article] Make this less Google-centric

---

src/styles/fonts/_material-icons.scss

This reverts commit 897665da5771ba82ff116fe9bab1731d04245a62.

Revert "Mark font-display:optional for Material Icon font (#4266)"

---

src/site/_data/site.js

Removes UX study banner. Adds CDS banner back.

add cds banner back

---

src/site/_data/authorsData.json

Add my author entry

---

src/site/content/en/blog/using-conversion-measurement/index.md

Fixes #4309 
- Added description
- Added credit
- Fixed a small issue

Add text description to conversion measurement diagram

---

src/site/_data/paths/secure.json

Duplicate of #4237 but this adds more existing contents under /secure

Adds 5 more aliases under /secure

---

src/site/content/en/blog/building-a-stories-component/index.md

adds a community submission to the post

Stories post - community submission

---

src/site/_data/paths/progressive-web-apps.json
src/site/content/en/progressive-web-apps/install-criteria/index.md

- tweak to ordering of items in PWA IA
- Add sentence about installability requirement check changing

Tweak for new PWA installability requirements check.

---

src/site/content/en/blog/idle-detection/index.md

[Idle Detection article] Add info about ended OT (Merge on Nov. 11, 2020)

---

src/site/content/en/blog/sms-otp-form/index.md

Just small changes to bump the SMS OTP form best practices article.

Bump the publish date of SMS OTP form best practices article

---

src/site/content/en/blog/css-clipping/index.md
src/site/content/en/blog/css-masking/index.md

Update titles of clipping and masking guides

---

src/site/content/en/blog/sms-otp-form/index.md
src/site/content/en/blog/web-otp/index.md

Add a video embed. A link from Web OTP API article.

Update SMS OTP form article

---

src/site/_includes/path.njk

Sorry for the mess. This PR makes sure https://github.com/beaufortfrancois/web.dev/commit/34c94b1e878f09e153d774ae8d9a0785cca14679 is applied properly

Removed duplicate youtube video at the bottom

---

src/site/content/en/blog/payment-and-address-form-best-practices/index.md

Add YouTube video: Payment and address form best practices

---

src/site/content/en/fast/publish-modern-javascript/index.md

Fixing a small json example where a string isn't closed.

Syntactically fix json example (modern js article)

---

src/site/content/en/blog/houdini-how/index.md

- Adds Chrome Dev Summit video to post (just went live)

Adds video to Houdini.how post

---

src/site/content/en/blog/shape-detection/index.md

- Better describe feature detection
- Typo fix

[Shape Detection article] Better describe feature detection

---

src/site/content/en/blog/building-a-stories-component/index.md

small patch that adds a 2nd community submission to the end of the article

Building a stories component - community remix patch

---

src/site/content/en/blog/sign-up-form-best-practices/index.md

Add YouTube video:  Sign-up form best practices

---

src/site/content/en/blog/building-a-stories-component/index.md

adds a bullet to the community section 👍🏻

Stories blog post patch: adds community submission

---

src/site/content/en/blog/more-capable-form-controls/index.md

Fixes #3850 
- fix Example code of  `ElementInternals` feature detection

[fix] ElementInternals feature detection

---

src/site/content/en/blog/hid/index.md

This PR adds the blocklist for HID device functionality that was recently added.
Live preview: https://deploy-preview-4415--web-dev-staging.netlify.app/hid/#security-privacy
FYI @nondebug

Add HID blocklist file

---

src/site/content/en/blog/min-max-clamp/index.md

Fix removal of links.

---

src/site/content/en/blog/at-property/index.md

Fixes #4260
- Adds syntax and explainer for multiple property declarations in the same line for `@property` blog post

[Post Update] @property Multiple Declarations

---

src/site/content/en/blog/vitals-field-measurement-best-practices/index.md
src/site/content/en/vitals/index.md

This PR adds links and screenshots for the [Web Vitals Report](https://github.com/GoogleChromeLabs/web-vitals-report) from relevant articles.

Add links to the Web Vitals Report repo

---

src/site/content/en/blog/idle-detection/index.md

- Add info about new origin trial.

[Idle Detection article] Add info about new origin trial

---

src/site/content/en/blog/hid-examples/index.md
src/site/content/en/blog/payment-and-address-form-best-practices/index.md
src/site/content/en/blog/sign-in-form-best-practices/index.md

This PR fixes some duplicate element IDs.

Fix duplicate IDs

---

src/site/content/en/blog/idle-detection/index.md

Change verb tense to match current time.

---

src/site/content/en/blog/idle-detection/index.md

The draft specification has now been written. Update the status and add the URL.

Update Idle Detection explainer and specification URLs

---

src/site/content/en/blog/building-a-sidenav-component/index.md

Article patch that adds the 1st community challenge submission

Sidenav blog post community submission patch

---

src/site/content/en/blog/centering-in-css/index.md

adds the CSS Tricks response article

Centering post community patch

---

src/site/content/en/blog/deprecating-excalidraw-electron/index.md

- Add canonical URL
- Add hero alt text
- Use lowercase web

[Excalidraw article] Add canonical URL, add hero alt text, use lowercase web

---

src/site/_data/site.js

Remove the CDS banner across the site.

Remove cds banner

---

src/site/content/en/blog/better-layout-shift-metric/index.md

Fixes #4530
- Increase heading level in each heading in the blog post, so that &lt;h2&gt; is the largest heading. This is consistent with other blog posts.

Headings start at h2 instead of h1

---

src/site/content/en/metrics/lcp/index.md

Fixes #4457.
@mihajlija I added the language directly from my comment in https://github.com/GoogleChrome/web.dev/pull/4500#issuecomment-766456932. Feel free to reword as necessary.

Update the LCP post for Chrome 88 changes

---

src/site/content/en/blog/how-to-use-local-https/index.md
src/site/content/en/blog/when-to-use-local-https/index.md

- Fixed the install command
- Made links more prominent (based on feedback that the link to "How to use local HTTPS" was easy to miss

Minor fixes to the HTTPS localhost article

---

src/site/content/en/blog/idle-detection/index.md

- Add link to spec at the end.

[Idle Detection article] Add link to spec at end

---

src/site/content/en/blog/hid-examples/index.md

[WebHID examples article] Add Joy-Con WebHID demo

---

src/site/content/en/blog/deprecating-excalidraw-electron/index.md

- Add aside
- Use more inclusive language

[Excalidraw Electron article] Add aside and use more inclusive language

---

src/site/content/en/blog/building-a-sidenav-component/index.md

Adds another bullet to the community section of the sidenav post

Sidenav: community remix addition patch

---

src/site/content/en/blog/building-a-sidenav-component/index.md

Sidenav post: community submission patch #4

---

src/site/content/en/blog/origin-agent-cluster/index.md

- Typo fix.
- The Chrome team, not Chrome loves feedback.

[Origin-Agent-Cluster article] Typo and minor nit fix

---

src/site/content/en/blog/coop-coep/index.md

Clarifies a common pitfall in COOP/COEP article.

Fix the typo in COOP/COEP article

---

src/site/content/en/blog/text-fragments/index.md

[Text Fragments article] Add ::target-text

---

.github/CODEOWNERS

Update codeowners to include new approvers group

update codeowners to include approvers team

---

src/site/content/en/blog/file-system-access/index.md

- Add serialization instructions.

[File System Access article] Add serialization instructions

---

src/site/content/en/animations/animations-examples/index.md

[Animation examples] Fix typo

---

src/site/content/en/lighthouse-performance/uses-responsive-images/index.md

Add instructions for Gatsby stack

---

src/site/content/en/blog/file-system-access/index.md

- Write origin private file system without dash.

[File System Access article] Write origin private file system without dash

---

src/site/_data/paths/progressive-web-apps.json
src/site/content/en/progressive-web-apps/customize-install/index.md
src/site/content/en/progressive-web-apps/install-criteria/index.md

- Minor updates to the PWA landing page TOC
- Update installability code snippets to better reflect best practices
- Update note about changes to installability criteria with link to updated docs
- Update note about manifest changes and how they affect installed PWAs

Minor updates to PWA IA & code cleanup

---

src/site/content/en/progressive-web-apps/offline-fallback-page/index.md

[Offline Fallback Page article] Inclusive language fix 

---

src/site/content/en/blog/get-installed-related-apps/index.md

- Clarifies support matrix for `getInstalledRelatedApps`
- Tells people to ask questions on StackOverflow

Clarify support matrix for `getInstalledRelatedApps`

---

src/site/content/en/blog/sign-in-form-best-practices/index.md
src/site/content/en/blog/sign-up-form-best-practices/index.md

Sign-up and sign-in form articles: added sentence to each

---

src/site/content/en/blog/using-conversion-measurement/index.md

Fixes #4413
- Edited Chrome version number
- Updated guidance to reflect new OT configuration
- Small fixes
CC @samdutton

Updated article "Using conversion measurement"

---

src/site/content/en/blog/building-a-tabs-component/index.md

<details>
<summary>Bug screenshot</summary>
</details>

Fixes missing thumbnail for Tabs post

---

.pullapprove.yml

Updated the conditions a bit based on their feedback. I think I wasn't properly capturing changes made to files in subdirectories and they also recommended combining the exclusions into one big expression.

Refine pullapprove groupings based on feedback from pullapprove team.

---

src/site/content/en/react/add-manifest-react/index.md

This PR fixes some nits in the Create React App article.

Minor updates to the Create React App article

---

src/site/content/en/blog/wake-lock/index.md

- Add task manager video
CC: @limhenry

[Screen Wake Lock article] Add task manager video

---

src/site/content/en/blog/devices-introduction/index.md

- Point to the new article now that https://github.com/GoogleChrome/web.dev/pull/4603 has landed.

[Device Introduction article] Update generic sensor link

---

src/site/content/en/blog/file-system-access/index.md

- Add directory serialization example.

[File System Access API article] Add directory serialization example

---

src/site/content/en/blog/coop-coep/index.md
src/site/content/en/secure/cross-origin-isolation-guide/index.md

Adds an update note about COOP/COEP articles changes

Add an update note about COOP/COEP articles changes

---

src/site/content/en/blog/browser-fs-access/index.md

Updated source link based on changed url structure for caniuse.com

---

src/site/content/en/blog/trusted-types/index.md

Correct a link that 404s

---

src/site/content/en/progressive-web-apps/offline-fallback-page/index.md

- Following @petele's suggestion added automatic reload.

[Offline Fallback Page article] Add automatic reload feature

---

src/site/content/en/blog/file-system-access/index.md

Triggered by https://github.com/WICG/file-system-access/issues/280.
- Document random access.

[File System Access API article] Document random access

---

src/site/_data/authorsData.json

Related to #4517, I added authors for Yahoo! JAPAN case study first, then we would bring the case study itself soon.

Add authors for Y!J case study

---

src/site/content/en/learn/css/css.11tydata.js
src/site/content/en/learn/css/index.md

Adds a quick and dirty eleventyComputed permalink to the course directory which prevents the course from going live during prod builds.

Add course flag

---

src/site/content/en/blog/badging-api/index.md
src/site/content/en/blog/contact-picker/index.md
src/site/content/en/blog/content-indexing-api/index.md
src/site/content/en/blog/file-handling/index.md
src/site/content/en/blog/file-system-access/index.md
src/site/content/en/blog/get-installed-related-apps/index.md
src/site/content/en/blog/hid/index.md
src/site/content/en/blog/idle-detection/index.md
src/site/content/en/blog/local-fonts/index.md
src/site/content/en/blog/multi-screen-window-placement/index.md
src/site/content/en/blog/nfc/index.md
src/site/content/en/blog/notification-triggers/index.md
src/site/content/en/blog/serial/index.md
src/site/content/en/blog/shape-detection/index.md
src/site/content/en/blog/usb/index.md
src/site/content/en/blog/wake-lock/index.md
src/site/content/en/blog/web-otp/index.md
src/site/content/en/blog/webcodecs/index.md
src/site/content/en/blog/websocketstream/index.md
src/site/content/en/blog/webtransport/index.md

- Linkify all hashtags in Capabilities articles.

[Tagged: Capabilities articles] Linkify and check all hashtags

---

src/site/content/en/blog/tabbed-application-mode/index.md

[Tabbed Application Mode article] Linkify the hashtag

---

src/site/content/en/blog/building-a-tabs-component/index.md

Adds link to google developers post

Post: Tabs linkback

---

src/site/content/en/blog/bluetooth/index.md

[Web Bluetooth article] Add hashtag

---

src/site/content/en/lighthouse-performance/performance-scoring/index.md

(via https://twitter.com/jan0711/status/1365040678582054913)
- Prevent horizontal overflow

[Performance Scoring article] Prevent horizontal overflow

---

src/site/content/en/blog/tabbed-application-mode/index.md

[Tabbed Application Mode article] Add missing tag

---

src/site/content/en/blog/sign-in-form-best-practices/index.md

Sign-in best practices: updates and fixes

---

src/site/content/en/blog/hid/index.md

- Use correct character casing for brands

[WebHID article] Use correct character casing for brands

---

src/site/content/en/blog/building-a-tabs-component/index.md

fixes article using a custom cdn

Tabs post: bucket swap patch

---

src/site/content/en/blog/display-override/index.md

Fixes #4818
- Correctly name mode.

[Display Override article] Correctly name mode

---

src/site/content/en/blog/javascript-this/index.md

@mathiasbynens I'd love a review of this if you've got time.
TODOs:

Article on JavaScript `this`

---

src/site/content/en/blog/yahoo-japan-news/index.md

Add Yahoo Japan News case study
