src/site/_data/i18n/learn.yml, src/site/_data/i18n/paths/web-dev-basics-one.yml, src/site/_data/paths/index.js, src/site/_data/paths/web-dev-basics-one.json, src/site/_includes/path.njk, src/site/content/en/learn/learn.11tydata.js, src/site/content/en/web-dev-basics-one/index.njk
=> feat(web-dev-basics): add draft web dev learning path

package-lock.json, package.json
Fixes https://github.com/GoogleChrome/web.dev/issues/7123
=> Bump lighthouse version

src/site/content/en/blog/discover-performance-opportunities-with-lighthouse/index.md
=> Add alt attributes to image

src/site/content/en/blog/centering-in-css/index.md
=> Add alt attribute to main image

src/site/content/en/blog/handwriting-recognition/index.md
=> Update Handwriting Recognition Article for Shipping

src/site/content/en/learn/pwa/installation/index.md, src/site/content/en/learn/pwa/offline-data/index.md, src/site/content/en/learn/pwa/serving/index.md, src/site/content/en/learn/pwa/web-app-manifest/index.md, src/site/content/en/learn/pwa/workbox/index.md
Fixes: #6486 
Fixes: #6487 
Fixes: #6488 
Fixes: #6489 
Fixes: #6490
=> Five more PWA modules

src/site/content/en/blog/vitals-field-measurement-best-practices/index.md, src/site/content/en/blog/vitals-ga4/index.md, src/site/content/en/vitals/index.md
This PR makes some minor fixes to a few incorrect dates in some of the Web Vitals posts.
=> Fix date issues on some Web Vitals content

src/site/content/es/learn/css/box-model/index.md
Corrected orthography error.
- Spelling correction in Spanish.
=> Update index.md to correct ortographic error

src/site/content/en/learn/forms/validation/index.md
=> Fixed pattern regex

src/site/content/en/blog/2d-graphics-in-emscripten/index.md, src/site/content/en/blog/drawing-to-canvas-in-emscripten/index.md
=> Add blog post "Drawing to canvas in Emscripten"

src/site/content/en/blog/http-cache-security/index.md
=> add missing subhead

src/site/content/en/blog/building-an-adaptive-favicon/index.md
=> [post] GUI Challenges - SVG Favicon

src/site/content/en/blog/launch-handler/index.md
=> [Launch Handler article] Fix typo

src/site/content/en/blog/webcodecs/index.md
This PR is about promoting the pattern to call the static method `VideoEncoder.isConfigSupported()` with the config to check before hand whether the config is supported.
FYI @Djuffin @chcunningham
=> Promote isConfigSupported()

src/site/content/en/blog/clipchamp/index.md
=> Uses a more conventional version of an idiom.

src/site/content/en/blog/webcodecs/index.md
This adds a "Dev Tips" section to the WebCodecs article to help developers.
FYI @Djuffin @chcunningham
=> Add Dev Tips section

src/site/content/en/blog/ps-on-the-web/index.md
=> [Photoshop on the Web article] Add missing subhead

src/site/content/en/fast/remove-unused-code/index.md
- Updating docs for better synonyms
=> Update index.md for better wordings

src/site/content/en/blog/web-platform-01-2022/index.md
=> pseudo class > :focus-visible typo

src/site/content/en/blog/storage-for-the-web/index.md
Fixes inconsistent content about Safari's current behaviour
Fixes #5746
=> Fixes #5746 - small content update for Safari & storage

src/site/_data/paths/web-dev-basics-one.json, src/site/content/en/web-dev-basics-one/additional-html-elements/index.md
Fixes #6987 
This is a piece of course material we are hosting, it doesn't need linking from anywhere right now.
=> Add additional html elements course material

src/site/content/en/blog/prefers-reduced-motion/index.md
Fixes: #7356 
In addition to fixing the link I have updated browser support mentions and added the browser compat component.
=> Fix link and update browser mentions

src/site/content/en/blog/url-protocol-handler/index.md
=> [URL Protocol Handler article] Formatting fix 

src/site/content/en/learn/design/responsive-images/index.md
Fixes #7389
- A broken link was reported in #7389 on [this page](http://localhost:8080/learn/design/responsive-images/#constrain-your-images) in the Learn Design course, and has now been fixed.
=> Fixes #7389 for a broken link reported by @MHBahrampour

src/site/content/en/learn/forms/accessibility/index.md
Fixes: #7290 
I've added the information about `aria-live` here as suggested in the ticket.
=> Adding some information about multiple aria-live

src/site/content/en/learn/css/lists/lists.assess.yml
=> fixing lists module assessment

src/site/content/en/blog/isinputpending/index.md
Fixes #6827 
- Change the word "dictionary" with the word "object" in the article.
=> Change the word "dictionary" to "object"

src/site/content/en/learn/pwa/index.md
=> Revise out-of-date statement

src/site/content/en/learn/pwa/assets-and-data/index.md, src/site/content/en/learn/pwa/index.md, src/site/content/en/learn/pwa/installation/index.md, src/site/content/en/learn/pwa/service-workers/index.md, src/site/content/en/learn/pwa/workbox/index.md
=> Fix some typos.

src/scss/web-components/_web-subscribe.scss, src/site/_includes/partials/subscribe.njk
The captcha element on the signup was out of alignment, so this PR fixes that.
=> Fix captcha alignment

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml
=> Add Salvatore Denaro to authors files.

src/site/content/en/learn/pwa/caching/index.md
=> Remove space from URL.

package.json, src/site/content/en/blog/web-platform-02-2022/index.md
Adds the February web platform post and updates BCD.
=> New to the web feb 22 post

src/site/content/en/blog/interop-2022/index.md
=> removing banner

src/site/content/en/blog/periodic-background-sync/index.md
I noticed this typo when revisiting the article.
=> Typo fix for the description

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml
=> Add kbalasub to author's file.

src/site/content/en/blog/interop-2022/index.md
=> fix incorrect image

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml
Added all the authors of the articles labelled as Web.dev in the ContentMigration Sheet
@rachelandrew
=> MigratingAuthors

src/site/content/en/blog/enabling-https-on-your-servers/index.md, src/site/content/en/blog/indexeddb-best-practices/index.md, src/site/content/en/blog/registering-a-custom-protocol-handler/index.md, src/site/content/en/blog/the-amazing-powers-of-css/index.md, src/site/content/en/blog/what-s-the-CSS-scope-pseudo-class-for/index.md
https://developers.google.com/web/fundamentals/instant-and-offline/web-storage/indexeddb-best-practices
https://developers.google.com/web/fundamentals/security/encrypt-in-transit/enable-https
https://developers.google.com/web/updates/2011/06/Registering-a-custom-protocol-handler
https://developers.google.com/web/updates/2012/06/The-amazing-powers-of-CSS
https://developers.google.com/web/updates/2013/03/What-s-the-CSS-scope-pseudo-class-for
@rachelandrew
=> ContentMigrationBatch#S1WD

src/site/content/en/blog/a11y-for-teams/index.md, src/site/content/en/blog/embind/index.md, src/site/content/en/blog/wasm-av1/index.md, src/site/content/en/blog/wasm-threads/index.md, src/site/content/en/blog/web-performance-made-easy/index.md
https://developers.google.com/web/updates/2018/08/embind
https://developers.google.com/web/updates/2018/08/wasm-av1
https://developers.google.com/web/updates/2018/08/web-performance-made-easy
https://developers.google.com/web/updates/2018/10/wasm-threads
https://developers.google.com/web/fundamentals/accessibility/a11y-for-teams
@rachelandrew
=> ContentMigrationBatch#S3WD

src/site/content/en/learn/pwa/installation-prompt/index.md
Fixes #6491 Learn PWA Installation Prompt
=> Learn PWA 13 Installation Prompt

src/site/content/en/learn/pwa/update/index.md
=> Adds Learn PWA 14 Update

src/site/content/en/learn/pwa/enhancements/index.md
=> Learn PWA 15

src/site/content/en/learn/pwa/detection/index.md
=> Learn PWA 16

src/site/content/en/blog/aria-labels-and-relationships/index.md, src/site/content/en/blog/hiding-and-updating-content/index.md, src/site/content/en/blog/navigating-content/index.md, src/site/content/en/blog/semantics-aria/index.md, src/site/content/en/blog/semantics-builtin/index.md
https://developers.google.com/web/fundamentals/accessibility/semantics-aria
https://developers.google.com/web/fundamentals/accessibility/semantics-aria/aria-labels-and-relationships
https://developers.google.com/web/fundamentals/accessibility/semantics-aria/hiding-and-updating-content
https://developers.google.com/web/fundamentals/accessibility/semantics-builtin
https://developers.google.com/web/fundamentals/accessibility/semantics-builtin/navigating-content
=> ContentMigrationBatch#S5WD

src/site/content/en/blog/economic-times-cwv/index.md
Add missing space between words on [Economic Times CWV](https://web.dev/economic-times-cwv) post.
=> Add missing space between words on Economic Times CWV post

src/site/content/en/blog/animating-modal-views/index.md, src/site/content/en/blog/animations-and-performance/index.md, src/site/content/en/blog/asymmetric-animation-timing/index.md, src/site/content/en/blog/choosing-the-right-easing/index.md, src/site/content/en/blog/css-vs-javascript/index.md
https://developers.google.com/web/fundamentals/design-and-ux/animations/animating-modal-views
https://developers.google.com/web/fundamentals/design-and-ux/animations/animations-and-performance
https://developers.google.com/web/fundamentals/design-and-ux/animations/asymmetric-animation-timing
https://developers.google.com/web/fundamentals/design-and-ux/animations/choosing-the-right-easing
https://developers.google.com/web/fundamentals/design-and-ux/animations/css-vs-javascript
@rachelandrew
=> ContentMigrationBatch#S9WD

src/site/content/en/blog/storage-for-the-web/index.md
Adds additional details about the amount of storage quota available to web sites in Chrome.
=> Additional details on Chrome storage availability

src/site/content/en/learn/pwa/detection/index.md, src/site/content/en/learn/pwa/enhancements/index.md, src/site/content/en/learn/pwa/installation-prompt/index.md, src/site/content/en/learn/pwa/update/index.md
Last minute corrections to new content.
=> Minor corrections.

src/site/content/en/blog/custom-easing/index.md, src/site/content/en/blog/responsive-images/index.md, src/site/content/en/blog/the-basics-of-easing/index.md
https://developers.google.com/web/fundamentals/design-and-ux/animations/custom-easing
https://developers.google.com/web/fundamentals/design-and-ux/animations/the-basics-of-easing
https://developers.google.com/web/fundamentals/design-and-ux/responsive/images
@rachelandrew
=> ContentMigrationBatch#S10WD

src/site/content/en/accessible/accessible-tap-targets/index.md
Follow-up to https://github.com/GoogleChrome/web.dev/pull/7496
=> Update front matter for accessible tap targets

src/site/content/en/blog/building-a-loading-bar-component/index.md
=> GUI Challenge - building a loading bar

src/site/content/en/blog/building-a-loading-bar-component/index.md
couple things i noticed when doing a review on mobile
=> GUI Challenges - post patch

src/site/content/en/blog/speculative-prerendering/index.md
The title says it all
Fixes: #7506
cc/ @addyosmani
=> Updating the demo URL

src/site/content/en/blog/launch-handler/index.md
- Reflect changes from https://github.com/WICG/sw-launch/pull/53.
=> [Launch Handler] Reflect recent changes

src/site/content/en/blog/media-recording-audio/index.md, src/site/content/en/blog/media-recording-video/index.md, src/site/content/en/blog/native-hardware-click-to-call/index.md, src/site/content/en/blog/native-hardware-device-orientation/index.md, src/site/content/en/blog/native-hardware-fullscreen/index.md
From: https://developers.google.com/web/fundamentals/media/recording-audio
To: https://web.dev/media-recording-audio
From: https://developers.google.com/web/fundamentals/media/recording-video
To: https://web.dev/media-recording-video
From: https://developers.google.com/web/fundamentals/native-hardware/click-to-call
To: https://web.dev/native-hardware-click-to-call
From: https://developers.google.com/web/fundamentals/native-hardware/device-orientation
To: https://web.dev/native-hardware-device-orientation
From: https://developers.google.com/web/fundamentals/native-hardware/fullscreen
To: https://web.dev/native-hardware-fullscreen
@rachelandrew
=> Content migration batch 4

src/site/content/en/blog/native-hardware-user-location/index.md, src/site/content/en/blog/push-notifications-permissions-ux/index.md, src/site/content/en/blog/push-notifications-subscribing-a-user/index.md, src/site/content/en/blog/push-notifications-web-push-protocol/index.md, src/site/content/en/blog/sending-messages-with-web-push-libraries/index.md
Content migration
From: https://developers.google.com/web/fundamentals/push-notifications/sending-messages-with-web-push-libraries
To: https://web.dev/sending-messages-with-web-push-libraries
From: https://developers.google.com/web/fundamentals/push-notifications/subscribing-a-user
To: https://web.dev/push-notifications-subscribing-a-user
From: https://developers.google.com/web/fundamentals/push-notifications/web-push-protocol
To: https://web.dev/push-notifications-web-push-protocol
From: https://developers.google.com/web/fundamentals/push-notifications/permission-ux
To: https://web.dev/push-notifications-permission-ux
From: https://developers.google.com/web/fundamentals/native-hardware/user-location
To: https://web.dev/native-hardware-user-location
@rachelandrew
=> Content migration batch 5

src/site/content/en/learn/design/ui-patterns/index.md
Fixes #7520 
I also updated the example hosted on CodePen.
=> Fix example for compat reasons

src/site/content/en/blog/performance-audit-next/index.md, src/site/content/en/blog/performance-audit-prework/index.md, src/site/content/en/blog/performance-audit-security/index.md, src/site/content/en/blog/performance-audit-share/index.md, src/site/content/en/blog/performance-audit/index.md
Content migration
From: https://developers.google.com/web/fundamentals/performance/audit
To: https://web.dev/performance-audit
From: https://developers.google.com/web/fundamentals/performance/audit/next
To: https://web.dev/performance-audit-next
From: https://developers.google.com/web/fundamentals/performance/audit/prework
To: https://web.dev/performance-audit-prework
From: https://developers.google.com/web/fundamentals/performance/audit/security
To: https://web.dev/performance-audit-security
From: https://developers.google.com/web/fundamentals/performance/audit/share
To: https://web.dev/performance-audit-share
@rachelandrew
=> Content migration batch 8

src/site/content/en/learn/pwa/index.md
Fixes #7550
CC: @jpmedley as I see he's made a similar change in the past.
=> State that 16 Learn PWA modules are available

src/site/content/en/blog/critical-rendering-path-measure-crp/index.md, src/site/content/en/blog/critical-rendering-path-optimizing-critical-rendering-path/index.md, src/site/content/en/blog/critical-rendering-path-page-speed-rules-and-recommendations/index.md, src/site/content/en/blog/critical-rendering-path-render-blocking-css/index.md, src/site/content/en/blog/critical-rendering-path-render-tree-construction/index.md
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/measure-crp
https://web.dev/critical-rendering-path-measure-crp
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/optimizing-critical-rendering-path
https://web.dev/critical-rendering-path-optimizing-critical-rendering-path
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/page-speed-rules-and-recommendations
https://web.dev/critical-rendering-path-page-speed-rules-and-recommendations
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-blocking-css
https://web.dev/critical-rendering-path-render-blocking-css
https://developers.google.com/web/fundamentals/performance/critical-rendering-path …
=> Content migration batch 10

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml
- Adds "Kevin K. Lee" as an author
=> Add author - Kevin K. Lee

src/site/_data/i18n/authors.yml
- Remove quotation marks for consistency within the file
- Add KO description
=> Add KO description for author kevinkiklee

src/site/content/en/blog/badging-api/index.md, src/site/content/en/progressive-web-apps/app-like-pwas/index.md
=> Fix a few typos in 'app-like' article.

src/site/content/en/handbook/yaml-front-matter/index.md
=> Correct location where tags are updated.

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/mishipay/index.md
Fixes #7410 
- Add the case study.
=> Add Mishipay case study

src/site/content/en/blog/avoid-large-complex-layouts-and-layout-thrashing/index.md, src/site/content/en/blog/debounce-your-input-handlers/index.md, src/site/content/en/blog/optimize-javascript-execution/index.md, src/site/content/en/blog/reduce-the-scope-and-complexity-of-style-calculations/index.md, src/site/content/en/blog/rendering-performance/index.md
https://developers.google.com/web/fundamentals/performance/rendering
https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing
https://developers.google.com/web/fundamentals/performance/rendering/debounce-your-input-handlers
https://developers.google.com/web/fundamentals/performance/rendering/optimize-javascript-execution
https://developers.google.com/web/fundamentals/performance/rendering/reduce-the-scope-and-complexity-of-style-calculations
@rachelandrew
=> ContentMigrationBatch#11WD

src/site/content/en/blog/optimizing-content-efficiency-javascript-startup-optimization/index.md, src/site/content/en/blog/optimizing-content-efficiency-loading-third-party-javascript/index.md, src/site/content/en/blog/optimizing-content-efficiency-optimize-encoding-and-transfer/index.md, src/site/content/en/blog/optimizing-content-efficiency-save-data/index.md, src/site/content/en/blog/performance-poor-connectivity/index.md
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/javascript-startup-optimization
https://web.dev/optimizing-content-efficiency-javascript-startup-optimization
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript
https://web.dev/optimizing-content-efficiency-loading-third-party-javascript
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer
https://web.dev/optimizing-content-efficiency-optimize-encoding-and-transfer
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/save-data
https://web.dev/optimizing-content-efficiency-save-data …
=> Content migration batch 13

src/site/content/en/blog/file-system-access/index.md
=> meta: Test GitHub Actions

src/site/content/en/blog/web-share/index.md
=> Update web share article.

src/site/content/en/blog/mishipay/index.md
- Replace two videos with one side-by-side video.
=> [MishiPay case study] Replace two videos with one side-by-side video

src/site/content/en/learn/pwa/service-workers/index.md
Fixes #7608 
- removes redundant "chapter"
=> fix(gh-7608): remove redundant "chapter"

src/site/content/en/blog/gpu-compute/index.md
This PR updates WebGPU samples in https://web.dev/gpu-compute with latest WebGPU changes in Chrome Canary.
FYI @kangz
=> Update GPU samples with latest WebGPU changes

src/site/content/en/blog/add-touch-to-your-site/index.md, src/site/content/en/blog/downloading-resources-in-html5-a-download/index.md
https://developers.google.com/web/fundamentals/design-and-ux/input/touch
https://developers.google.com/web/updates/2011/08/Downloading-resources-in-HTML5-a-download
@rachelandrew
=> ContentMigrationBatch#14WD

src/site/content/en/metrics/ttfb/index.md
from Timing-Origin-Allow to Timing-Allow-Origin
=> typo:(index.md) Timing-Allow-Origin

src/site/content/en/blog/emscripting-a-c-library/index.md
https://developers.google.com/web/updates/2018/03/emscripting-a-c-library
https://web.dev/emscripting-a-c-library
@rachelandrew
=> Content migration batch 14

src/site/content/en/blog/optimizing-content-efficiency-eliminate-downloads/index.md, src/site/content/en/blog/performance-get-started-wrapup-7/index.md, src/site/content/en/blog/performance-http2/index.md, src/site/content/en/blog/performance-optimizing-content-efficiency-client-hints/index.md, src/site/content/en/blog/performance-optimizing-content-efficiency/index.md
https://developers.google.com/web/fundamentals/performance/get-started/wrapup-7
https://web.dev/performance-get-started-wrapup-7
https://developers.google.com/web/fundamentals/performance/http2
https://web.dev/performance-http2
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency
https://web.dev/performance-optimizing-content-efficiency
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/client-hints
https://web.dev/optimizing-content-efficiency-client-hints
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/eliminate-downloads
https://web.dev/optimizing-content-efficiency-eliminate-downloads
@rachelandrew
=> Content migration batch 12

src/site/content/en/blog/performance-get-started-graphicalcontent-4/index.md, src/site/content/en/blog/performance-get-started-httpcaching-6/index.md, src/site/content/en/blog/performance-get-started-httprequests-5/index.md, src/site/content/en/blog/performance-get-started-textcontent-3/index.md, src/site/content/en/blog/performance-get-started/index.md
https://developers.google.com/web/fundamentals/performance/get-started
https://web.dev/performance-get-started
https://developers.google.com/web/fundamentals/performance/get-started/graphicalcontent-4
https://web.dev/performance/get-started-graphicalcontent-4
https://developers.google.com/web/fundamentals/performance/get-started/httpcaching-6
https://web.dev/performance/get-started-httpcaching-6
https://developers.google.com/web/fundamentals/performance/get-started/httprequests-5
https://web.dev/performance/get-started-httprequests-5
https://developers.google.com/web/fundamentals/performance/get-started/textcontent-3
https://web.dev/performance-get-started-textcontent-3
@rachelandrew
=> Content migration batch 11

src/site/content/en/blog/keyboard-lock/index.md
=> Update Keyboard Lock article.

src/site/content/en/blog/datatransfer/index.md
=> Datatransfer

src/site/content/en/index.md, src/site/content/es/index.md, src/site/content/ja/index.md, src/site/content/ko/index.md, src/site/content/pl/index.md, src/site/content/pt/index.md, src/site/content/ru/index.md, src/site/content/zh/index.md
=> Update case study to mishipay

src/site/content/en/blog/accessibility/index.md, src/site/content/en/blog/intro-to-security-terminology/index.md, src/site/content/en/blog/push-notifications/index.md, src/site/content/en/blog/web-components/index.md
https://developers.google.com/web/fundamentals/push-notifications 
https://developers.google.com/web/fundamentals/security/encrypt-in-transit/intro-to-security-terminology 
https://developers.google.com/web/fundamentals/web-components 
https://developers.google.com/web/fundamentals/accessibility 
@rachelandrew
=> ContentMigrationBatch#S17WD

src/site/content/en/blog/indexeddb-best-practices/index.md
- fix typo in "Best Practices for Using IndexedDB": "visa versa" -> "vice versa"
=> fix: typo "vice versa"

src/site/content/en/blog/csp/index.md
https://developers.google.com/web/fundamentals/security/csp 
@rachelandrew
=> ContentMigrationBatch#S18WD

src/site/content/en/blog/file-system-access/index.md
- Remove param
- Make names more implicit
=> [File System Access article] Remove param and make names more implicit

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/Spooktacular-HTML5-Pumpkin/index.md, src/site/content/en/blog/push-notifications-video/index.md
https://developers.google.com/web/fundamentals/push-notifications/video
https://developers.google.com/web/updates/2011/10/Spooktacular-HTML5-Pumpkin
@rachelandrew
=> ContentMigrationBatch#S19WD

src/site/content/en/blog/speculative-prerendering/index.md
- Minor edits to content introduced in PR 7662
=> Update Speculative Prerendering

src/site/content/en/blog/interop-2022/index.md
=> replace image

src/site/content/en/index.md
=> Fix typo on homepage

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml
=> feat: add jhey to authors list

src/site/content/en/blog/rendering-performance/index.md
=> Fix link with changing compositor-only properties

src/site/_data/authorsData.json
=> Add missing image for AEM article.

src/site/content/en/blog/building-a-dialog-component/index.md
Fixes #7606 
Todo:
https://deploy-preview-7659--web-dev-staging.netlify.app/building-a-dialog-component/
=> New Post - GUI Challenges - Building a dialog component

src/site/content/en/learn/pwa/os-integration/index.md
=> Add Learn PWA: Part 17, OS integration.

src/site/content/en/learn/pwa/windows/index.md
=> Add Learn PWA: Part 18, Window management.

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/rebelmouse/index.md
=> Adds RebelMouse case study.

src/site/content/en/learn/pwa/experimental/index.md
=> Add Learn PWA: Part 19, Experimental.

src/site/content/en/learn/pwa/tools-and-debug/index.md
=> Add Learn PWA: Part 20, Tools and Debug.

src/site/content/en/learn/pwa/architecture/index.md
=> Add Learn PWA: Part 21, Architecture.

src/site/content/en/learn/pwa/complexity/index.md
=> Add Learn PWA: Part 22, Complexity.

src/site/_data/authorsData.json
Just updating my avatar image and homepage.
=> Update jeffposnick authors data

src/site/content/en/blog/optimizing-content-efficiency-loading-third-party-javascript/index.md
Fixes #7732
This article was moved over as part of #7594, but one of the links needed to be remediated.
=> Fix Critical Rendering Path link

src/site/content/en/metrics/ttfb/index.md
Fixes #7600
- Fixes a minor typo where I used `Timing-Origin-Allow` instead of `Timing-Allow-Origin`
=> Fixes a typo in the TTFB article.

src/site/content/en/blog/building-a-dialog-component/index.md
not sure when that regressed, but here's the fix
=> Post Patch: fixes broken link

src/site/content/en/blog/building-a-dialog-component/index.md
adds community submission to the end of the post
=> Post Patch: adds user addition

src/site/content/en/web-dev-basics-one/global-and-local-scope/index.md
Fixes #7577 
This is another piece of content we are hosting for the ETT course, it should not show up in the blog etc.
Preview: https://deploy-preview-7716--web-dev-staging.netlify.app/global-and-local-scope/
=> Adding the ETT scope article

src/site/content/en/learn/pwa/capabilities/index.md
=> Add the capabilities list to 'Learn PWA'.

src/site/content/en/blog/rebelmouse/index.md
Anne from RebelMouse reached out to me directly to correct a couple things in [their case study](https://web.dev/rebelmouse/):
- Updates various links to their website to include UTM stuff in query strings.
- Corrects the company's case in the title (Rebelmouse -> RebelMouse).
=> Implements changes requested by RebelMouse.

src/site/content/en/blog/file-handling/index.md
=> [File Handling article] Update for launch

src/site/content/en/payments/android-payment-apps-developers-guide/index.md, src/site/content/en/payments/empowering-payment-apps-with-web-payments/index.md
Fixes rendering issue on payment pages
* https://web.dev/empowering-payment-apps-with-web-payments/
* https://web.dev/android-payment-apps-developers-guide/
=> Fix unmatching HTML tag

src/site/content/en/blog/new-pwa-training/index.md
Preview: https://deploy-preview-7778--web-dev-staging.netlify.app/new-pwa-training/
=> More Learn PWA linking

src/site/content/en/blog/lighthouse-user-flows/index.md
the writeFileSync gives and error. it needs the result of the awaited promise
-
-
-
=> Update Lighthouse user flows docs

src/site/content/en/blog/local-fonts/index.md
=> [Local Fonts article] Update for shipping

src/site/content/en/blog/file-system-access/index.md
- Add permission persistence bug info.
=> [File System Access article] Add permission persistence bug info

src/site/content/en/blog/async-clipboard/index.md
=> [Async Clipboard article] Fix copy event section

src/site/content/en/blog/url-protocol-handler/index.md
-  Clarify platforms the feature has launched on.
=> [URL Protocol Handling article] Clarify platforms the feature has launched on

src/site/content/en/blog/file-handling/index.md
=> [File Handling article] Remove development note

src/site/content/en/handbook/use-media/index.md
- Note not to use "Image of" or "Screenshot of" in image captions and alt text
=> Handbook: update copy around captions

src/site/content/en/learn/pwa/installation/index.md
- Fixes incorrect instructions to use the apple-touch-icon tag
=> Fix incorrect mention of the manifest for the apple-touch-icon tag

src/site/content/en/blog/css-gradient-generator/index.md
* Adds a new simple "Quick blog post" about the CSS gradient tool.
-
-
-
=> Adding a new quick post blog about a CSS gradient editor tool

src/site/_data/i18n/tags.yml, src/site/content/en/blog/variable-fonts-in-real-life/index.md
Adding a quick post linking to a variable fonts resource.
=> Quick post variable fonts

src/site/content/en/fast/signed-exchanges/index.md
=> Updates to SXG landing page to align with I/O talk narrative 

src/site/content/en/blog/file-handling/index.md
=> [File Handling article] Add spec PR

src/site/_data/i18n/tags.yml, src/site/content/en/blog/community-highlight-bramus/index.md, src/site/content/en/blog/community-highlight-chen-hui-jing/index.md, src/site/content/en/blog/community-highlight-lynn-fisher/index.md, src/site/content/en/blog/community-highlight-miriam-suzanne/index.md, src/site/content/en/blog/gde-focus-nishu-goel/index.md, src/site/content/en/blog/gde-mentoring/index.md
A post about mentoring featuring 3 GDEs. I also added a community tag, and added that to some related posts.
=> Adds new GDE post and community tag

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/yahoo-japan-identity-case-study/index.md
Fixes #7392 
- New case study for Yahoo! JAPAN
Awaiting final confirmation from partners and @agektmr, after the [Golden Week](https://en.wikipedia.org/wiki/Golden_Week_(Japan)). PR opened for preview.
=> [Case study] Identity and Yahoo! JAPAN

src/site/content/en/blog/building-a-dialog-component/index.md
Adds user contributed Remix to the Dialog post
=> GUI Challenges - Dialog post patch

src/site/content/en/blog/bridging-the-gap/index.md
To publish the 11th, then add the video on the 12th.
=> Adding the Bridging the gap post

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/mobile-optimization-and-performance/index.md, src/site/content/en/blog/mobile-profiling/index.md, src/site/content/en/blog/mobile-touch/index.md, src/site/content/en/blog/mobile-touchandmouse/index.md, src/site/content/en/blog/nativedebate/index.md, src/site/content/en/blog/workingoffthegrid/index.md
https://www.html5rocks.com/en/mobile/nativedebate/
https://www.html5rocks.com/en/mobile/optimization-and-performance/
https://www.html5rocks.com/en/mobile/profiling/
https://www.html5rocks.com/en/mobile/touch/
https://www.html5rocks.com/en/mobile/touchandmouse/
https://www.html5rocks.com/en/mobile/workingoffthegrid/
@rachelandrew
=> ContentMigrationBatch#SH5R4

src/site/content/en/blog/local-fonts/index.md
- Update method names for launch.
- Add new filter option.
=> [Local Fonts article] Update method names for launch

src/site/content/en/metrics/inp/index.md
- Removes quotes from the "what is a good INP value" heading.
- Adds CHANGELOG link.
=> Minor INP doc tweaks.

src/site/content/en/blog/async-clipboard/index.md
@tomayac I thought we should make these a little easier to play with. Do you agree?
=> Let readers see the demo sources.

src/site/content/en/blog/bridging-the-gap/index.md, src/site/content/en/blog/state-of-css-2022/index.md
Video for State of CSS and Bridging the Gap.
=> video embeds

src/site/content/en/blog/optimize-lcp/index.md
A continuation of the changes from #7883. This PR adds an embed of the companion I/O session for this post.
=> Add Optimize LCP companion video

src/site/content/en/blog/state-of-css-2022/index.md
Changes a couple links to be more direct.
=> 2022 CSS - patch

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/100000stars/index.md, src/site/content/en/blog/20things-pageflip/index.md, src/site/content/en/blog/box-dnd-download/index.md, src/site/content/en/blog/buildwithchrome/index.md, src/site/content/en/blog/entanglement/index.md
https://www.html5rocks.com/en/tutorials/casestudies/100000stars/
https://www.html5rocks.com/en/tutorials/casestudies/20things_pageflip/
https://www.html5rocks.com/en/tutorials/casestudies/box_dnd_download/
https://www.html5rocks.com/en/tutorials/casestudies/buildwithchrome/
https://www.html5rocks.com/en/tutorials/casestudies/entanglement/
@rachelandrew
=> ContentMigrationBatch#SH5R5

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/google-io-2013/index.md, src/site/content/en/blog/gopherwoord-studios-resizing-html5-games/index.md, src/site/content/en/blog/hobbit-front-end/index.md, src/site/content/en/blog/hobbit/index.md, src/site/content/en/blog/hobbit2014/index.md
https://www.html5rocks.com/en/tutorials/casestudies/google-io-2013/
https://www.html5rocks.com/en/tutorials/casestudies/gopherwoord-studios-resizing-html5-games/
https://www.html5rocks.com/en/tutorials/casestudies/hobbit-front-end/
https://www.html5rocks.com/en/tutorials/casestudies/hobbit/
https://www.html5rocks.com/en/tutorials/casestudies/hobbit2014/
@rachelandrew
=> ContentMigrationBatch#SH5R6

src/site/_data/i18n/paths/identity.yml, src/site/_data/paths/identity.json
With updates to identity related contents, renewing /identity index.
=> Update /identity content

src/site/content/en/blog/preload-scanner/index.md
Fixes #7534 
- Adds the post about the browser preload scanner.
=> Adds preload scanner post.

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/inp-in-frameworks/index.md
Fixes #7871
- New post for INP for frameworks
- New author information
=> Blog inp frameworks

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/centering-in-css/index.md, src/site/content/en/blog/html5-in-deviantart-muro/index.md, src/site/content/en/blog/jamwithchrome-audio/index.md, src/site/content/en/blog/jamwithchrome-interaction/index.md, src/site/content/en/blog/mathboard/index.md, src/site/content/en/blog/movikantirevo/index.md
https://www.html5rocks.com/en/tutorials/casestudies/html5_in_deviantart_muro/
https://www.html5rocks.com/en/tutorials/casestudies/jamwithchrome-audio/
https://www.html5rocks.com/en/tutorials/casestudies/jamwithchrome-interaction/
https://www.html5rocks.com/en/tutorials/casestudies/mathboard/
https://www.html5rocks.com/en/tutorials/casestudies/movikantirevo/
@rachelandrew
=> ContentMigrationBatch#SH5R8

src/site/content/en/blog/custom-elements-best-practices/index.md, src/site/content/en/blog/web-components/index.md
Fixes some breakage due to migrating the web components articles.
=> Fix custom elements pages

src/site/content/en/blog/local-fonts/index.md
=> [Local Font article] Add desktop-only

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/racer/index.md, src/site/content/en/blog/roll-it/index.md, src/site/content/en/blog/subsonic/index.md, src/site/content/en/blog/sunlight-streamcongress/index.md
https://www.html5rocks.com/en/tutorials/casestudies/racer/
https://www.html5rocks.com/en/tutorials/casestudies/roll-it/
https://www.html5rocks.com/en/tutorials/casestudies/subsonic/
https://www.html5rocks.com/en/tutorials/casestudies/sunlight_streamcongress/
@rachelandrew
=> ContentMigrationBatch#SH5R9

src/site/content/en/blog/requestvideoframecallback-rvfc/index.md
- Add polyfill link
- Add compat widget
=> [requestVideoFrameCallback] Add polyfill link and add compat widget

src/site/content/en/blog/building-a-button-component/index.md
=> [post] GUI Challenges - Buttons

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/antialiasing-101/index.md, src/site/content/en/blog/getusermedia-intro/index.md, src/site/content/en/blog/google-chrome-frame/index.md, src/site/content/en/blog/indexeddb-uidatabinding/index.md, src/site/content/en/blog/trip-meter/index.md
https://www.html5rocks.com/en/tutorials/geolocation/trip_meter/
https://www.html5rocks.com/en/tutorials/getusermedia/intro/
https://www.html5rocks.com/en/tutorials/google-chrome-frame/
https://www.html5rocks.com/en/tutorials/indexeddb/uidatabinding/
https://www.html5rocks.com/en/tutorials/internals/antialiasing-101/
@rachelandrew
=> ContentMigrationBatch#SH5R12

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/gov-uk-drops-jquery/index.md
- Adds a quick post about GOV.UK dropping their jQuery dependency on their front end.
=> Adds quick GOV.UK post.

src/site/content/en/blog/building-a-button-component/index.md
=> [Button GUI challenge article] Fix link in `figcaption`

src/site/content/en/blog/terminal-for-js-devs/index.md
Another quick post, linking to a guide to the terminal for frontend devs.
=> Quick post terminal guide

src/site/content/en/blog/csp/index.md
- Fix the dead link to Handlebars precompliation documentation in CSP article
=> Fix dead Handlebars link

src/site/content/en/blog/building-a-button-component/index.md
buttons dont/shouldnt need focus-within
=> Patch - GUI Challenges Buttons - removes `button:focus-within` references

src/site/content/en/blog/building-a-button-component/index.md
=> [Button component article] Fix name issue

src/site/content/en/blog/rendering-on-the-web/index.md
- Fix a broken link in [Rendering on the Web](https://web.dev/rendering-on-the-web).
```diff
-https://web.dev/search/docs/guides/dynamic-rendering
+https://developers.google.com/search/docs/guides/rendering
```
=> Fix 404 Not Found

src/site/_includes/partials/head.njk, src/site/_includes/sandbox/layout.njk, src/site/_transforms/minify-html.js
Fixes #7770 
This shouldn't be necessary, but it works around https://github.com/wilsonzlin/minify-html/issues/81 in the HTML minifier we switched to.
=> Explicitly set crossorigin="anonymous"

src/site/content/en/web-dev-basics-one/choose-js-library-or-framework/index.md
Fixes #7842 
Preview: https://deploy-preview-7977--web-dev-staging.netlify.app/choose-js-library-or-framework/
=> ETT article choose a library or framework

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/3d-css/index.md, src/site/content/en/blog/doodles-gamepad/index.md, src/site/content/en/blog/doodles-lem/index.md, src/site/content/en/blog/eme-basics/index.md, src/site/content/en/blog/es7-observe/index.md
https://www.html5rocks.com/en/tutorials/3d/css/
https://www.html5rocks.com/en/tutorials/doodles/gamepad/
https://www.html5rocks.com/en/tutorials/doodles/lem/
https://www.html5rocks.com/en/tutorials/eme/basics/
https://www.html5rocks.com/en/tutorials/es7/observe/
@rachelandrew
=> ContentMigrationBatch#SH5R15

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/speed-html5/index.md, src/site/content/en/blog/speed-layers/index.md, src/site/content/en/blog/speed-parallax/index.md, src/site/content/en/blog/speed-quick/index.md, src/site/content/en/blog/speed-rendering/index.md
https://www.html5rocks.com/en/tutorials/speed/html5/
https://www.html5rocks.com/en/tutorials/speed/layers/
https://www.html5rocks.com/en/tutorials/speed/parallax/
https://www.html5rocks.com/en/tutorials/speed/quick/
https://www.html5rocks.com/en/tutorials/speed/rendering/
@rachelandrew
=> ContentMigrationBatch#SH5R17

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/speed-script-loading/index.md, src/site/content/en/blog/speed-scrolling/index.md, src/site/content/en/blog/speed-static-mem-pools/index.md, src/site/content/en/blog/speed-txt-compression/index.md, src/site/content/en/blog/speed-unnecessary-paints/index.md
https://www.html5rocks.com/en/tutorials/speed/script-loading/
https://www.html5rocks.com/en/tutorials/speed/scrolling/
https://www.html5rocks.com/en/tutorials/speed/static-mem-pools/
https://www.html5rocks.com/en/tutorials/speed/txt-compression/
https://www.html5rocks.com/en/tutorials/speed/unnecessary-paints/
@rachelandrew
=> ContentMigrationBatch#SH5R18

src/site/content/en/blog/speed-v8/index.md, src/site/content/en/blog/streaming-screenshare/index.md, src/site/content/en/blog/supercharging-your-gruntfile/index.md, src/site/content/en/blog/svg-mobile-fundamentals/index.md, src/site/content/en/blog/three-intro/index.md
https://www.html5rocks.com/en/tutorials/speed/v8/
https://www.html5rocks.com/en/tutorials/streaming/screenshare/
https://www.html5rocks.com/en/tutorials/svg/mobile_fundamentals/
https://www.html5rocks.com/en/tutorials/three/intro/
https://www.html5rocks.com/en/tutorials/tooling/supercharging-your-gruntfile/
@rachelandrew
=> ContentMigrationBatch#SH5R19

src/site/content/en/blog/conic-gradient-border/index.md
A quick post about conic gradients.
(also using as a demo of this type of post).
=> Conic gradient quick post

src/site/_data/i18n/paths/payments.yml, src/site/_data/paths/payments.json
This PR is most certainly not going to work. It's a placeholder for updates, per https://github.com/GoogleChrome/developer.chrome.com/pull/2906
AI: Get documentation for handbook on how to create and add new items to a collection.
=> Add SPC to payments collection

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/synchronized-cross-device-testing/index.md, src/site/content/en/blog/webaudio-fieldrunners/index.md, src/site/content/en/blog/webaudio-games/index.md, src/site/content/en/blog/webaudio-intro/index.md, src/site/content/en/blog/webaudio-positional-audio/index.md
https://www.html5rocks.com/en/tutorials/tooling/synchronized-cross-device-testing/
https://www.html5rocks.com/en/tutorials/webaudio/fieldrunners/
https://www.html5rocks.com/en/tutorials/webaudio/games/
https://www.html5rocks.com/en/tutorials/webaudio/intro/
https://www.html5rocks.com/en/tutorials/webaudio/positional_audio/
@rachelandrew
=> ContentMigrationBatch#SH5R20

src/site/content/en/web-dev-basics-one/fetch-api-error-handling/index.md
Fixes #7841 
Another ETT course article. 
Preview: https://deploy-preview-7976--web-dev-staging.netlify.app/fetch-api-error-handling/
=> ETT Fetch API lesson

src/site/_includes/components/BrowserCompat.js
Reverts GoogleChrome/web.dev#7455
=> Revert "Update the BrowserCompat component to filter against stable browsers"

src/site/content/en/blog/web-platform-05-2022/index.md
=> Web platform may

src/site/content/en/blog/aliexpress/index.md, src/site/content/en/blog/asda-george/index.md, src/site/content/en/blog/googleplus/index.md, src/site/content/en/blog/nikkei/index.md, src/site/content/en/blog/twitter/index.md
https://developers.google.com/web/showcase/2015/googleplus
https://developers.google.com/web/showcase/2018/nikkei
https://developers.google.com/web/showcase/2016/aliexpress
https://developers.google.com/web/showcase/2018/asda-george
https://developers.google.com/web/showcase/2017/twitter
@rachelandrew
=> ContentMigrationBatch#SC1

src/site/content/en/blog/alibaba/index.md, src/site/content/en/blog/bookmyshow/index.md, src/site/content/en/blog/flipkart/index.md, src/site/content/en/blog/land-lines/index.md, src/site/content/en/blog/service-worker-perf/index.md
https://developers.google.com/web/showcase/2017/bookmyshow
https://developers.google.com/web/showcase/2016/flipkart
https://developers.google.com/web/showcase/2016/service-worker-perf
https://developers.google.com/web/showcase/2016/alibaba
https://developers.google.com/web/showcase/2016/land-lines
@rachelandrew
=> ContentMigrationBatch#SC2

src/site/content/en/blog/eleme/index.md, src/site/content/en/blog/forbes/index.md, src/site/content/en/blog/lancome/index.md, src/site/content/en/blog/make-my-trip/index.md, src/site/content/en/blog/suumo/index.md
https://developers.google.com/web/showcase/2016/suumo
https://developers.google.com/web/showcase/2017/forbes
https://developers.google.com/web/showcase/2017/eleme
https://developers.google.com/web/showcase/2017/lancome
https://developers.google.com/web/showcase/2017/make-my-trip
@rachelandrew
=> ContentMigrationBatch#SC3

src/site/content/en/blog/dance-tonite/index.md, src/site/content/en/blog/iowa2016/index.md, src/site/content/en/blog/jumia/index.md, src/site/content/en/blog/service-workers-iowa/index.md, src/site/content/en/blog/weather-channel/index.md
https://developers.google.com/web/showcase/2016/jumia
https://developers.google.com/web/showcase/2015/service-workers-iowa
https://developers.google.com/web/showcase/2016/iowa2016
https://developers.google.com/web/showcase/2016/weather-channel
https://developers.google.com/web/showcase/2017/dance-tonite
@rachelandrew
=> ContentMigrationBatch#SC4

src/site/content/en/blog/5miles/index.md, src/site/content/en/blog/beyond-the-rack/index.md, src/site/content/en/blog/extra/index.md, src/site/content/en/blog/net-a-porter/index.md, src/site/content/en/blog/svgomg/index.md
https://developers.google.com/web/showcase/2015/svgomg
https://developers.google.com/web/showcase/2016/extra
https://developers.google.com/web/showcase/2015/beyond-the-rack
https://developers.google.com/web/showcase/2016/5miles
https://developers.google.com/web/showcase/2016/net-a-porter
@rachelandrew
=> ContentMigrationBatch#SC6

src/site/content/en/blog/airhorner/index.md, src/site/content/en/blog/infobae/index.md, src/site/content/en/blog/little-alchemy/index.md, src/site/content/en/blog/olx/index.md, src/site/content/en/blog/within/index.md
https://developers.google.com/web/showcase/2017/olx
https://developers.google.com/web/showcase/2015/airhorner
https://developers.google.com/web/showcase/2015/little_alchemy
https://developers.google.com/web/showcase/2017/within
https://developers.google.com/web/showcase/2017/infobae
@rachelandrew
=> ContentMigrationBatch#SC5

src/site/content/en/blog/babe/index.md, src/site/content/en/blog/jumia2016/index.md, src/site/content/en/blog/konga/index.md, src/site/content/en/blog/santa/index.md, src/site/content/en/blog/wapo/index.md
https://developers.google.com/web/showcase/2016/babe
https://developers.google.com/web/showcase/2016/konga
https://developers.google.com/web/showcase/2016/wapo
https://developers.google.com/web/showcase/2016/jumia
https://developers.google.com/web/showcase/2017/santa
@rachelandrew
=> ContentMigrationBatch#SC7

src/site/content/en/blog/pwas-on-oculus-2/index.md
=> Add "Virtual Reality" and "WebXR" tags to "PWAs on Oculus 2" blog post

src/site/content/en/blog/guardian-smart-lock/index.md, src/site/content/en/blog/hn-premii/index.md, src/site/content/en/blog/hummingbirdlibrary/index.md, src/site/content/en/blog/merry-pixmas/index.md, src/site/content/en/blog/playcanvas/index.md, src/site/content/en/blog/voot/index.md
https://developers.google.com/web/showcase/2017/playcanvas
https://developers.google.com/web/showcase/2017/voot
https://developers.google.com/web/showcase/2015/hummingbirdlibrary
https://developers.google.com/web/showcase/2016/guardian-smart-lock
https://developers.google.com/web/showcase/2015/hn_premii
https://developers.google.com/web/showcase/2015/merry_pixmas
@rachelandrew
=> ContentMigrationBatch#SC11

src/site/content/en/blog/adventuremachine/index.md, src/site/content/en/blog/ali-express-smart-lock/index.md, src/site/content/en/blog/art-sessions/index.md, src/site/content/en/blog/chrome-dev-summit/index.md, src/site/content/en/blog/housing/index.md
https://developers.google.com/web/showcase/2016/art-sessions
https://developers.google.com/web/showcase/2015/adventuremachine
https://developers.google.com/web/showcase/2015/chrome-dev-summit
https://developers.google.com/web/showcase/2016/ali-express-smart-lock
https://developers.google.com/web/showcase/2016/housing
@rachelandrew
=> ContentMigrationBatch#SC10

src/site/content/en/blog/file-system-access/index.md
=> [File System Access article] Update OT date

src/site/content/en/blog/telegraph/index.md
=> Fix closing tag

src/site/content/en/blog/smoothness/index.md
Fixes #8102
- Fixes text contrast issue in Animation Smoothness Metric doc.
=> Fixes text contrast issue in Animation Smoothness Metric doc.

src/site/_data/paths/secure.json, src/site/content/en/secure/first-party-cookie-recipes/index.md
Changes:
- Add First party cookie recipes post
- Add it to /secure
=> Add First party cookie recipes

src/site/content/en/blog/streams/index.md
Thanks, @rauschma.
- Add polyfill
=> Add polyfill

src/site/content/en/secure/same-site-same-origin/index.md
Added link to Mozilla docs
Fixes #8072
- Update state of Sec-Fetch-Site
- Add link to Mozilla docs.
=> Sec-Fetch-Site is supported by all modern browsers

src/site/content/en/secure/same-site-same-origin/index.md
Add a note about `Sec-Fetch-Site` to same-site same-origin article
This resolves the feedback at #8072 
cc: @mhoad @guettli
Preview: https://deploy-preview-8113--web-dev-staging.netlify.app/same-site-same-origin/#how-to-check-if-a-request-is-%22same-site%22-%22same-origin%22-or-%22cross-site%22
=> Add a note about `Sec-Fetch-Site` to same-site same-origin article

src/site/content/en/blog/sanitizer/index.md
Fixes #8093 
- remove `sanitize()` from article
- remove `sanitizeFor()` too
- update status table
CC: @otherdaniel
=> update sanitizer api article align with current release plan

src/site/content/en/blog/multi-screen-window-placement/index.md
- Add distinction what this API is not.
=> [Multi-Screen Window Placement article] Add distinction what this API is not

src/site/content/en/progressive-web-apps/install-criteria/index.md
=> Fix typos.

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/fast/signed-exchanges/index.md
Both features are now launched.
=> Update SXG doc per desktop and `Vary: Cookie`.

src/site/content/en/index.md
=> Shorten a title work better with an image.

src/site/content/en/blog/conic-gradient-border/index.md
- adds reference to the original CodePen demo and embeds a sample of the basic conic-gradient border
=> Post Patch: updates to show the teamwork leading to the demo

src/site/content/en/progressive-web-apps/offline-fallback-page/index.md
=> Review 'Offline Fallback'.

src/site/content/en/learn/pwa/progressive-web-apps/index.md
Fixes #8163 by correcting an existing link, and adding a new link in the Learn PWA docs.
=> Fix two links in Learn PWA docs

src/site/content/en/blog/window-controls-overlay/index.md
@tomayac, to be consistent with other articles, I've added captions to the images. Change them if you have better ideas.
=> Review 'Window Controls Overlay'.

src/site/_data/site.js
=> Remove GDG DevFest banner

src/site/content/en/blog/maskable-icon/index.md
=> Review 'Maskable icons'.

src/site/content/en/blog/file-system-access/index.md
Guys,
This article had much out of date information. I think I got all the low hanging fruit. But I need a serious reality check on the work.
Thanks,
Joe
=> Review 'File System Access'.

src/site/content/en/blog/optimize-lcp/index.md
- Adds lazy loading guidance to Optimize LCP guide.
=> Adds lazy loading guidance to Optimize LCP guide.

src/site/content/en/blog/decrease-frontend-size/index.md
- Close block code to fix Markdown syntax error
=> Close block code to fix Markdown syntax error

src/site/content/en/learn/design/theming/index.md
=> Updated grammar

src/site/content/en/blog/preload-responsive-images/index.md
=> fix: image name inconsistency

src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
- Added a new section on the new DevTools extension for Web Audio.
- Fixed outdated information.
=> Article Update: Profiling Web Audio apps in Chrome 

src/site/content/en/progressive-web-apps/promote-install/index.md
=> Review 'Promote installation'.

src/site/content/en/blog/text-fragments/index.md
=> [Text Fragments article] Fix nested markup

src/site/content/en/blog/window-controls-overlay/index.md
=> [Window Controls Overlay article] Correct ship date

src/site/content/en/patterns/layout/aspect-ratio-image-card/demo.md, src/site/content/en/patterns/layout/clamping-card/demo.md, src/site/content/en/patterns/layout/container-query-card/demo.md, src/site/content/en/patterns/layout/deconstructed-pancake/demo.md, src/site/content/en/patterns/layout/holy-grail/demo.md, src/site/content/en/patterns/layout/line-up/demo.md, src/site/content/en/patterns/layout/pancake-stack/demo.md, src/site/content/en/patterns/layout/repeat-auto-minmax/demo.md, src/site/content/en/patterns/layout/sidebar-says/demo.md, src/site/content/en/patterns/layout/super-centered/demo.md, src/site/content/en/patterns/layout/twelve-span-grid/demo.md
Styles were broken in https://web.dev/patterns/layout due to a broken external link.
This PR applies explicit styles to prevent further issues.
=> [bugfix] CSS for Layout Patterns

src/site/_data/site.js
Create a banner to publicize  the PWASummit22 call for speakers.
=> adding a banner for pwasummit22

src/site/content/en/blog/web-platform-06-2022/index.md
Adds the June web platform post.
=> New on the web June

src/site/content/en/blog/local-fonts/index.md, src/site/content/en/blog/web-platform-06-2022/index.md
=> [Local Fonts article] Clarify permissions

src/site/_data/i18n/tags.yml
=> Add cross-browser tag

src/site/content/en/blog/transformstream/index.md
=> [TransformStream article] Use new tag and aside

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml
Adding my author profile, in preparation of some blogposts that will follow later on.
=> Add author profile for bramus

src/site/content/en/metrics/inp/index.md
- This introduces a revamped INP guide, which is considerably shorter and adds clarity to respond to developer feedback.
=> Revamps the INP metric guide

src/site/content/en/blog/gde-focus-helpdev/index.md
Another in the series of GDE focus interviews.
=> GDE HelpDev article

src/site/content/en/blog/use-long-term-caching/index.md
=> Fix the end tag of the code block

src/site/content/ja/vitals/index.md
Fixes #8271
- Enable link jump
reason:
In this case, there is little need to use Japanese for the title of the heading.
=> Solved by putting the problem part into English.

src/site/content/en/fast/replace-gifs-with-videos/index.md
- Adds a section at the end of the article discussing the effects of autoplaying videos on LCP.
=> Addresses LCP concerns for autoplaying video as animated GIF replacement.

src/site/content/en/blog/webtransport/index.md
=> [WebTransport article] Add ponyfill

src/site/content/en/blog/better-responsiveness-metric/index.md
- Adds aside to Better Responsiveness metric doc clarifying what events qualify for INP.
=> Adds aside to Better Responsiveness metric doc clarifying what events qualify for INP.

src/site/content/en/progressive-web-apps/what-are-pwas/index.md
- Removal of an improper comma
=> Small grammar fix

.cloudbuild/deploy.yaml
=> Is this breaking the build?

.cloudbuild/deploy.yaml
Another attempt to fix the build
=> Keep trying!

src/site/content/de/secure/cross-origin-isolation-guide/index.md, src/site/content/en/secure/cross-origin-isolation-guide/index.md, src/site/content/en/secure/security-headers/index.md, src/site/content/es/secure/cross-origin-isolation-guide/index.md, src/site/content/es/secure/security-headers/index.md, src/site/content/fr/secure/cross-origin-isolation-guide/index.md, src/site/content/ja/blog/coop-coep/index.md, src/site/content/ja/secure/cross-origin-isolation-guide/index.md, src/site/content/ko/blog/coop-coep/index.md, src/site/content/ko/secure/cross-origin-isolation-guide/index.md, src/site/content/pt/secure/cross-origin-isolation-guide/index.md, src/site/content/pt/secure/security-headers/index.md, src/site/content/ru/blog/coop-coep/index.md, src/site/content/ru/secure/cross-origin-isolation-guide/index.md, src/site/content/zh/blog/coop-coep/index.md, src/site/content/zh/secure/cross-origin-isolation-guide/index.md
Replace all occurrence of `first-party-test.glitch.me` to `cross-origin-isolation.glitch.me`.
=> Update demo URL for cross-origin isolation

.cloudbuild/deploy.yaml
=> Another try

src/site/_includes/spaces.njk, src/site/content/en/spaces/_example_ended/index.md
This is a second attempt at https://github.com/GoogleChrome/web.dev/pull/8353, now that https://github.com/GoogleChrome/web.dev/pull/8374 is merged.
=> [Re-submission] Use authors data for Spaces hosts

src/scss/pages/_spaces.scss, src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/_includes/spaces.njk, src/site/content/en/spaces/2022-08-04-ui-ama/index.md, src/site/content/en/spaces/2022-08-09-new-on-web/index.md, src/site/content/en/spaces/2022-08-11-feature-fundamentals/index.md, src/site/content/en/spaces/2022-08-16-devs-telling-us/index.md, src/site/content/en/spaces/2022-08-18-web-perf-ama/index.md, src/site/content/en/spaces/2022-08-23-modern-web/index.md, src/site/content/en/spaces/2022-08-25-/index.md, src/site/content/en/spaces/2022-08-25-identity/index.md, src/site/content/en/spaces/index.md
=> Twitter Spaces Series

src/site/content/en/blog/farfetch/index.md
Add hero image, fix link and replace calculator image for Farfetch case study
=> Edit Farfetch case study

src/site/content/en/blog/farfetch/index.md
- The title case for the Farfetch case study is improper, and should be (mostly) lowercase.
=> Fixes Farfetch case study's title case.

src/site/content/en/metrics/inp/index.md
Fixes #8395
- Updates the INP documentation to link to the INP-to-TBT correlation study.
=> Updates INP doc to link to TBT correlation study.

src/site/content/en/blog/bbc-hsts/index.md
- Adds a short blog post that discusses how BBC rolled out a new HSTS policy, as well as some info on HSTS itself.
=> Adds BBC HSTS short post

src/site/content/en/blog/accent-color/index.md, src/site/content/en/blog/css-is-and-where/index.md, src/site/content/en/blog/css-size-adjust/index.md, src/site/content/en/blog/min-max-clamp/index.md, src/site/content/en/blog/structured-clone/index.md
A bunch of updates for browser compat mentions, adding the compat component and removing outdated info.
=> Some browser compat updates

src/site/content/en/metrics/ttfb/index.md
Fixing build breakage introduced in #8414
=> fix the build

src/site/content/en/secure/same-site-same-origin/index.md
=> fix markup

src/site/content/en/blog/webdatabase-todo/index.md
- Strengthen regular aside to warning aside
- Update link
=> [WebSQL article] Strengthen regular aside to warning aside, update link

src/site/content/en/blog/multi-screen-window-placement/index.md
=> [Multi-Screen Window Placement article] Update label

src/site/_data/paths/progressive-web-apps.json
- Add Window Controls Overlay to PWA-exclusive list
=> [PWA overview landing page] Add Window Controls Overlay to PWA-exclusive list

src/site/content/en/accessible/color-and-contrast-accessibility/index.md
Corrected a link regarding APCA, which pointed to a very incorrect and obsolete document.
-
-
-
=> Fix link to obsolete document

src/site/content/en/fast/compress-images/index.md
- Adds guidance on image compression effects on LCP.
- Adds a mention of the AVIF format.
=> Adds LCP guidance to the image compression guidance.

src/site/content/en/fast/choose-the-right-image-format/index.md
This is a refiling of #8349. It addresses feedback from @tunetheweb, but forgoes using my own fork.
- Updates guidance on choosing the right image format to add AVIF information as well as impacts on Core Web Vitals.
=> Adds advice per @tunetheweb from #8349.

src/site/content/en/patterns/theming/color-schemes/demo.njk
This PR makes sure the inline script gets a proper hash for CSP so that users can play with it on https://web.dev/new-patterns-july-2022/
=> Fix CSP issue in theming/color-schemes demo

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/mainline-mensware/index.md
=> Rename Charis to Harry

src/site/content/en/blog/new-patterns-july-2022/index.md
=> Updated the proper link

src/site/content/en/blog/tabbed-application-mode/index.md
=> [Tabbed Application Mode article] Add `"tab_strip"` details 

src/site/content/en/fast/signed-exchanges/index.md
=> SXG: Mention `Vary: Cookie` and Cloudflare study.

src/site/content/en/blog/preconnect-and-dns-prefetch/index.md
- Adds guidance around LCP for `preconnect`.
=> Adds guidance around LCP for preconnects.

src/site/content/en/blog/preconnect-and-dns-prefetch/index.md
- Fixes bad link introduced in #8454 - I missed the hash when suggesting that link during PR review. Oops!
=> Fix fetchpriority link on preconnect article

src/site/content/en/blog/svgcode/index.md
=> [SVGcode article] Add `case-study` tag

src/site/content/en/blog/new-patterns-july-2022/index.md
=> Fixed links which were broken

src/site/content/en/blog/indexeddb-best-practices/index.md
-  Minor fixes in preparation of the ETT session.
=> [IDB Best practices articles] Minor fixes in preparation of the ETT session

src/site/content/en/blog/url-protocol-handler/index.md
- Remove pre-launch artifacts. 
=> [Protocol Handler article] Remove pre-launch artifacts

src/site/content/en/blog/optimize-lcp/index.md
This PR adds two additional factors now previously discussed in the Optimize LCP post.
=> Update Optimize LCP with additional guidance

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/spaces/2022-08-16-devs-telling-us/index.md
Updates speakers for Twitter Space on "What developers are telling us"
=> Speaker update: What developers are telling us

src/site/content/en/spaces/2022-08-04-ui-ama/index.md
Adds audio file from Modern UI AMA Twitter Space
=> Adds audio from modern UI AMA space

src/site/content/en/learn/css/overflow/index.md
=> Adds section on scrolling and accessibility

src/site/content/ja/blog/payment-and-address-form-best-practices/index.md
- There was a missing closing backquotes, that was messing up the formatting.
=> fix broken markup on blog about payment in ja

src/site/content/en/fast/lazy-loading/index.md
- Adds a small note in the conclusion about Core Web Vitals. The note is a bit on the short side, since this is an introductory article to the lazy loading concept.
=> Adds small note about Core Web Vitals.

src/site/content/en/identity/web-otp/index.md
Update WebOTP article to cover cross-device story
=> Update WebOTP article to cover cross-device story

src/site/content/ko/accessible/labels-and-text-alternatives/index.md
- There are duplicate Self-assessment in this page so i removed one
=> Remove Duplicate Self-Assessment

src/site/content/en/fast/lazy-loading-video/index.md
- Adds guidance around LCP for lazy loading video `poster` images.
=> Adds LCP guidance for video poster images.

src/site/content/en/fast/optimize-css-background-images-with-media-queries/index.md
- The [optimize CSS background images with media queries](https://web.dev/optimize-css-background-images-with-media-queries/) post has been updated with notes on LCP, and the role of the browser preload scanner and `<link>` preloads.
=> Adds LCP guidance on CSS background images.

src/site/_data/i18n/paths/react.yml
- `React` and `Create React App` are translated in some languages (which should not be),this PR fixes them.
=> Fix mistranslated strings in react.yml

src/site/content/en/spaces/2022-08-09-new-on-web/index.md, src/site/content/en/spaces/2022-08-11-feature-fundamentals/index.md, src/site/content/en/spaces/2022-08-16-devs-telling-us/index.md, src/site/content/en/spaces/2022-08-18-web-perf-ama/index.md
Audio files for spaces series.
=> Adds audio for Twitter Spaces

src/site/_includes/partials/post-next.njk
This PR updates one missed (in #8576) legacy occurance of the importance attribute.
=> Update missed legacy importance attribute

src/site/content/en/learn/css/pseudo-elements/index.md
=> Fix spelling mistake

src/site/content/en/learn/css/grid/grid.assess.yml
- Change two instances of the word "it's" to "its."
-
-
=> Fix two spelling mistakes

src/site/content/en/blog/tag-best-practices/index.md
Following on from analysis showing tag managers have an impact on INP I've reviewed and updated this post.
- Added Impact to CWV section
- Updated pixelly screenshots
- Other misc updates from my own experience using tag managers
=> Tag manager web vital review

src/site/_includes/item-page.njk, src/site/_includes/spaces.njk
Couple more fetchpriority fixes for hero images:
- https://web.dev/spaces/ (see https://deploy-preview-8587--web-dev-staging.netlify.app/spaces/ for fixed version)
- https://web.dev/authors/tunetheweb/ (see https://deploy-preview-8587--web-dev-staging.netlify.app/authors/tunetheweb/ for fixed version)
=> Fix fetchpriorty on some more hero images

src/site/content/en/blog/building-a-crooked-grid-illusion/index.md
=> New Post - `GUI Challenges` crooked grid illusion

src/site/content/en/fast/use-imagemin-to-compress-images/index.md
- Adds LCP guidance to the imagemin guide preamble.
=> Adds LCP guidance to imagemin guide.

package-lock.json, package.json, src/lib/analytics.js, src/site/_data/site.js, types/modules/webdev_analytics/index.d.ts
- Upgrade to the new 3.0.0 web-vitals library
- Switch to the preferred `onXXX` syntax
- Add onINP monitoring
@philipwalton should we add attribution tracking? Would be good to have a reference implementation to points to. Just need a Custom Dimension set up in GA.
=> Upgrade web-vitals to 3.0.0 and add INP monitoring

src/site/content/en/blog/window-controls-overlay/index.md
- Add `display-mode` media query.
=> [Window Controls Overlay article] Add `display-mode` media query

src/site/content/en/blog/url-protocol-handler/index.md
=> [URL protocol handler article] Add DevTools info

redirects.yaml
- Fixes redirect as noticed in https://github.com/GoogleChrome/web.dev/pull/8608/files#r956761733
=> Fix working offline redirect

src/site/content/zh/blog/webtransport/index.md
=> docs: add webtransport.day

src/site/content/en/blog/serial/index.md
Following https://bugs.chromium.org/p/chromium/issues/detail?id=1182905#c11, this PR documents BYOB readers in the web.dev/serial article.
@reillyeon Please have a look
=> Support BYOB reader for SerialPort's ReadableStreams

src/site/content/en/blog/window-controls-overlay/index.md
=> [Window Controls Overaly article] Add CSS

src/site/content/en/blog/new-responsive/index.md, src/site/content/ja/blog/new-responsive/index.md, src/site/content/ru/blog/new-responsive/index.md
Updates CQ syntax to current `container-type` instead of `contain` to create containers
=> Updates cq syntax in articles

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/is-it-modal/index.md, src/site/content/en/spaces/2022-08-04-ui-ama/index.md
Fixes #8626
- Article introducing CSS :modal pseudo-selector
cc @rachelandrew
=> feat: is it :modal article

src/site/content/en/blog/prefers-reduced-motion/index.md
=> [Prefers-Reduced-Motion article] Add nyan cat example

src/site/content/en/blog/website-navigation/index.md
"Accessible" instead of "Advanced".
=> Fixed ARIA ref

src/site/content/en/blog/website-navigation/index.md
- Correct code style in blockquote
=> [Website Navigation article] Correct code style in blockquote

src/site/_data/i18n/subscribe.yml
邮件列表 is the common translation of the term "mailing list".
Ref:
* https://zh.wikipedia.org/wiki/%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8
* https://www.zhihu.com/question/23757640
=> Fix Chinese translation

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/spaces/2022-09-16-subgrid/index.md
Drafting this for the content calendar. Open to suggestions, fixed, enhancements, etc.
todo:
=> Add Twitter space on CSS Subgrid

src/site/content/en/blog/ps-on-the-web/index.md
- Try if adding a paragraph fixes the link. It does!
=> [PS on the Web article] Try if adding a paragraph fixes the link

src/site/content/en/progressive-web-apps/add-manifest/index.md
@petele Please review content.
FYI @tropicadri
=> Add id manifest property

src/site/content/en/blog/file-system-access/index.md
- Say Android support for OPFS is coming.
=> [File System Access article] Say Android support for OPFS is coming

src/site/content/en/blog/speedy-css-tip-animated-loader/index.md
Short form post for Speedy CSS animated loader ⚡
=> feat: speedy css tip animated loader post

src/site/content/en/blog/responsive-web-design-basics/index.md
Reported in email, the lack of a description for a video on this page.
=> Adding a video caption, and other fixes

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/testing-web-design-color-contrast/index.md
=> New Post - Testing web design color contrast

src/site/content/en/blog/preload-responsive-images/index.md
- Adds a small section on preloading and LCP in the [Preload responsive images](https://web.dev/preload-responsive-images/) guide.
=> Adds LCP info to the preload responsive images guide.

src/site/content/en/blog/introducing-learn-html/index.md
To merge after landing the course PR.
=> add Learn HTML launch post

src/site/content/en/blog/farfetch/index.md
- Updated copy in article after request from Farfetch.
=> Updated copy of Farfetch case study.

src/site/content/en/learn/html/headings-and-sections/index.md
Looked like it was a typo
-
-
-
=> Changed from </nav> to <nav>

src/site/content/en/learn/accessibility/color-contrast/index.md, src/site/content/en/learn/accessibility/typography/index.md
- Tweak color / contrast codepen size
- Update typography date
=> Tweaks to Learn A11y

src/site/_data/authorsData.json, src/site/content/en/blog/optimize-long-tasks/index.md
- Adds a new guide for optimizing long tasks to the blog.
=> Adds the optimize long tasks guide.

src/site/content/en/blog/optimize-long-tasks/index.md
- Tweaks language, fixes a figure in the optimize long tasks post.
=> Tweaks language, fixes a figure in the optimize long tasks post.

src/site/content/en/learn/accessibility/why/index.md
Minor edits and a new quote for the speech impairment section.
=> Updates for "Why Accessibility" page

src/site/content/en/learn/accessibility/aria-html/index.md
Fix for typo: conent -> content
Fixes #8774
- fix typo: 'conent' -> 'content'
=> fix: a typo in the word content

src/site/content/en/learn/accessibility/aria-html/aria.assess.yml
=> fix the aria quiz

src/site/content/en/fast/rail/index.md
=> Moved the bullet points to next line

src/site/content/en/learn/accessibility/color-contrast/color.assess.yml
Fix #8779 
https://deploy-preview-8785--web-dev-staging.netlify.app/learn/accessibility/color-contrast/
=> Color contrast quiz

src/site/content/en/learn/pwa/web-app-manifest/index.md
=> Updated link in the warning section

src/site/content/en/blog/codelab-sign-in-form-best-practices/index.md
Fixes #8744 (Partially)
- Ensure label and id attributes match for password field
- Ensure using correct value for autocomplete
=> Partial bug fix for issue #8744

src/site/content/en/learn/accessibility/measure/index.md, src/site/content/en/learn/accessibility/motion/motion.assess.yml
=> Learn A11y fixes, ongoing

src/site/_data/site.js
I'll remove the banner at the end of today.
=> adding pwa livestream

src/site/_data/site.js, src/site/_includes/partials/analytics.njk
As discussed in https://github.com/GoogleChrome/developer.chrome.com/pull/3907#discussion_r987393074
=> Standardise navigation type by using dashes

src/site/content/en/learn/pwa/assets-and-data/index.md
Fixes #8748 
- Update the link for "[caching](https://web.dev/learn/pwa/assets-and-data/learn/pwa/caching)" on https://web.dev//learn/pwa/assets-and-data/#frequently-used-cache-approaches
=> Add missing forward slash to fix broken link

src/site/content/en/blog/community-highlight-melanie/index.md
https://deploy-preview-8794--web-dev-staging.netlify.app/community-highlight-melanie/
=> Community highlight: Melanie Sumner

src/site/content/en/blog/building-a-fab-component/index.md
=> New Post - Building a FAB component

src/site/content/en/learn/html/document-structure/index.md
Fixes https://github.com/GoogleChrome/web.dev/issues/8751
=> Learn HTML: DTD clarification

src/site/content/en/learn/html/document-structure/index.md
I called UTF-8 a character set, it really is a character encoding.
Fixes #8753
=> Learn HTML: character encoding

src/site/content/en/blog/mobile-touch/index.md
=> Fix anchor

src/site/content/en/blog/new-patterns-for-amazing-apps/index.md
- Fix typo clipbaord to clipboard
=> Fix typo clipbaord to clipboard

src/site/content/en/patterns/files/open-a-directory/assets/script.js, src/site/content/en/patterns/files/open-a-directory/demo.njk, src/site/content/en/patterns/files/open-a-directory/index.md, src/site/content/en/patterns/files/open-one-or-multiple-files/assets/script.js, src/site/content/en/patterns/files/open-one-or-multiple-files/demo.njk, src/site/content/en/patterns/files/open-one-or-multiple-files/index.md, src/site/content/en/patterns/files/save-a-file/index.md
- [Use showPicker() if possible](https://github.com/GoogleChrome/web.dev/commit/4742e7d5aba7a80e5cd7be60b0acb7138912b3fa).
=> [How to? pattern articles] Use `showPicker()` if possible

src/site/content/en/blog/new-patterns-for-amazing-apps/index.md
=> [How to? patterns articles] Thank Ken and Matthias

src/site/content/en/spaces/2022-10-13-chrometober/index.md
=> Adds twitter space for chrometober

src/site/content/en/index.md
Adds Chrometober card to homepage. Requires #8699 merge
=> Adds Chrometober card to homepage

src/site/content/en/fast/publish-modern-javascript/index.md
Removes link to archived site/repo.
=> Remove link to estimator.dev

src/site/content/en/learn/html/document-structure/index.md
Fixes #8751
- Remove reference of DTD in favor of doctype.
=> Learn HTML: Tweak text for doctypes

src/site/content/en/spaces/2022-08-23-modern-web/index.md, src/site/content/en/spaces/2022-08-25-identity/index.md
Adds missing audio to two Twitter Spaces
=> Adds missing audio from web identity and modern web capabilities

src/site/_includes/about-next.njk
Follow-up to #8847, fixes #8868.
=> Add missing Recaptcha script to about page

src/site/content/en/patterns/advanced-apps/share/index.md
- Remove erroneous URL encoding.
=> [Share website pattern] Remove erroneous URL encoding

src/site/_data/site.js
Adding the chrometober banner to direct people to the content.
=> Adding chrometober banner

src/site/content/en/patterns/media/screen-record/assets/body.html, src/site/content/en/patterns/media/screen-record/assets/script.js, src/site/content/en/patterns/media/screen-record/assets/style.css, src/site/content/en/patterns/media/screen-record/demo.njk, src/site/content/en/patterns/media/screen-record/index.md
@tomayac Please have a look. Is this what you had in mind?
Live previews:
https://deploy-preview-8889--web-dev-staging.netlify.app/patterns/media/
https://deploy-preview-8889--web-dev-staging.netlify.app/patterns/media/screen-record/
=> [How to? pattern articles] Add record screen article

src/site/content/en/patterns/files/save-a-file/assets/script.js, src/site/content/en/patterns/files/save-a-file/demo.njk, src/site/content/en/patterns/files/save-a-file/index.md
=> [Save a file pattern] Improve execution order

src/site/content/en/blog/tabbed-application-mode/index.md
=> [Tabbed Application Mode article] Add explainer link

src/site/content/en/patterns/media/microphone-record/assets/body.html, src/site/content/en/patterns/media/microphone-record/assets/script.js, src/site/content/en/patterns/media/microphone-record/assets/style.css, src/site/content/en/patterns/media/microphone-record/demo.njk, src/site/content/en/patterns/media/microphone-record/index.md, src/site/content/en/patterns/media/screen-record/assets/script.js
@tomayac Please have a look.
Live previews:
https://deploy-preview-8890--web-dev-staging.netlify.app/patterns/media/
https://deploy-preview-8890--web-dev-staging.netlify.app/patterns/media/microphone-record/
=> [How to? pattern articles] Add record microphone article

src/site/content/en/patterns/media/index.md
This PR is about adding some blurb to the media patterns to avoid the current weird "All" link. See https://web.dev/patterns/media/
Live preview: https://deploy-preview-8900--web-dev-staging.netlify.app/patterns/media
@tomayac PTAL
=> Add media patterns blurb

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/better-youtube-web-part1/index.md
This draft has been iterated on as part of https://github.com/GoogleChrome/developer.chrome.com/pull/4049 and we are now moving it over to web.dev with a view to publishing here instead.
Draft previously reviewed by Phil Walton, Lauren, Harleen, Jeremy and reps from both YT and Chrome. 
Changes:
- Adds co-author to our authors
- Adds the case study
Before publishing:
- Update the publish date (likely to the 20th)
=> Adds YT Web case study - Part 1

src/site/content/en/learn/accessibility/why/why.assess.yml
Fixes #8798.
https://deploy-preview-8853--web-dev-staging.netlify.app/learn/accessibility/why/#web-assessment-0
=> [Learn A11y] Module 1 assessment updates

src/site/content/en/blog/state-of-css-2022/index.md
- Fix anchor links on [state-of-css-2022](https://web.dev/state-of-css-2022/#css-can't-help-users-reduce-data)
=> Fix broken anchor links in TOC

src/site/content/en/blog/css-animated-grid-layouts/index.md
Fixes #8691
Feel free to adjust the publication date should it be a busy day to schedule – it’s currently set to `2022-10-25` which is the M107 release date
=> Add css-animated-grid-layouts blogpost (#8691)

src/site/content/en/blog/building-a-tooltip-component/index.md
=> `New Post` GUI Challenges - Building a tooltip component

src/site/content/en/blog/building-a-tooltip-component/index.md
=> fixes markdown syntax issue

src/site/content/en/blog/building-a-tooltip-component/index.md
The URL was missing an 's'.
-
-
-
=> Fixed the demo 404

src/site/content/en/blog/web-platform-10-2022/index.md
=> Web platform oct22

src/site/content/en/blog/carousel-best-practices/index.md
- Typo fix at Line 167. (dependng ---> depending)
=> Typo fixed

src/site/content/en/blog/building-a-tooltip-component/index.md
adds controls for inline video 👍🏻
=> GUI Challenges - inline video patch

src/site/content/en/blog/critical-rendering-path-constructing-the-object-model/index.md
Fixes #7637
- Adding missing image / removing duplicate image
=> Missing image

src/site/content/en/fast/signed-exchanges/index.md
=> Document SXG update cache API

src/site/content/en/learn/html/document-structure/index.md, src/site/content/en/learn/html/headings-and-sections/headings-and-sections.assess.yml
=> Typo fixing

src/site/content/en/learn/pwa/enhancements/index.md
- Deleted incorrect character in code snippet from the PWA course
=> Fix typo in code snippet

src/site/content/en/blog/file-system-access/index.md
- Reflect what is currently implemented ([staging preview](https://deploy-preview-8984--web-dev-staging.netlify.app/file-system-access/#accessing-files-optimized-for-performance-from-the-origin-private-file-system)).
=> [OPFS article] Reflect what is currently implemented

src/site/content/en/patterns/media/media-session/assets/body.html, src/site/content/en/patterns/media/media-session/assets/script.js, src/site/content/en/patterns/media/media-session/assets/style.css, src/site/content/en/patterns/media/media-session/demo.njk, src/site/content/en/patterns/media/media-session/index.md
I've tried to keep this one short to fit with other how-to patterns.
@tomayac Please have a look.
I've tested it on Desktop and Mobile.
Live previews:
https://deploy-preview-8993--web-dev-staging.netlify.app/patterns/media/
https://deploy-preview-8993--web-dev-staging.netlify.app/patterns/media/media-session/
=> [How to? pattern articles] Add media session article

src/site/content/en/blog/new-patterns-for-media-apps/index.md
@tomayac Please review
Live preview: https://deploy-preview-8996--web-dev-staging.netlify.app/new-patterns-for-media-apps/
=> Add New patterns for media apps blog post

src/site/content/en/learn/accessibility/structure/index.md
https://deploy-preview-8986--web-dev-staging.netlify.app/learn/accessibility/structure/#headings
=> Learn Accessibility: add designed headings example

src/site/content/en/blog/speedy-css-tip-animated-gradient-text/index.md, src/site/content/en/blog/speedy-css-tip-animated-loader/index.md
- Speedy post for a Speedy video
=> feat: speedy css tip gradient text post

src/site/content/en/learn/accessibility/typography/index.md
Issue: #8982
- Directly link to Google Fonts
=> learn/accessibility/typography Directly link Google Fonts

src/site/content/en/blog/async-clipboard/index.md
=> [Async Clipboard API article] Update the article

src/site/content/en/blog/multi-screen-window-placement/index.md
- Rename permission (https://crbug.com/1328581).
=> [Multi-Screen Window Placement API article] Rename permission

src/site/content/en/reliable/offline-cookbook/index.md
=> Tweak service worker reference. Fixes #4978

src/site/content/en/learn/accessibility/typography/index.md
Update typography page per @cehfisher's suggestion in https://github.com/GoogleChrome/web.dev/pull/8981#issuecomment-1302633202
=> Language around fonts

src/site/content/en/blog/security-credential-management/index.md
=> Update broken link

src/site/_data/design/components.js
- Replaces hard coded path separator with path.sep so that the build works on Windows.
=> Fixes build on windows

src/scss/pages/_homepage.scss, src/scss/pages/_measure.scss, src/site/_data/design/components.js, src/site/_includes/homepage-next.njk, src/site/content/en/blog/website-navigation/index.md, src/site/content/en/index.md, src/site/content/en/measure/index.njk
=> Consolidation of /measure and PSI

src/site/content/en/learn/accessibility/images/index.md, src/site/content/en/learn/accessibility/more-html/index.md
=> Learn Accessibility markdown fix

src/site/content/en/learn/forms/internationalization/index.md
Fixes #8377
- replace broken link with a url that provides relevant content
=> fix: #8377

src/site/content/en/learn/html/semantic-html/index.md
Fixes #8734
- implementing the proposed grammar fix by @cynthiateeters
=> fix: #8734

src/site/content/en/blog/content-visibility/index.md
=> Fix typo visibilty -> visibiltiy

src/site/content/en/blog/service-worker-mindset/index.md
=> Service worker mindset missing images

src/site/content/en/learn/css/pseudo-classes/index.md
=> Learn CSS header error

src/site/_data/site.js
=> removing chrometober badge

src/site/content/en/blog/file-system-access/index.md
=> [File System Access article] Fix heading nesting

src/site/content/en/blog/new-patterns-for-media-apps/index.md
@beaufortfrancois, @tomayac PTAL. :wink:
=> Fix mixed up links

src/site/content/en/blog/datatransfer/index.md, src/site/content/en/blog/device-pixel-content-box/index.md, src/site/content/en/blog/disable-mouse-acceleration/index.md, src/site/content/en/blog/display-override/index.md, src/site/content/en/blog/doodles-gamepad/index.md, src/site/content/en/blog/es-modules-in-sw/index.md, src/site/content/en/blog/fetch-metadata/index.md, src/site/content/en/blog/flexbox-gap/index.md, src/site/content/en/blog/generic-sensor/index.md, src/site/content/en/blog/hid/index.md, src/site/content/en/blog/idle-detection/index.md, src/site/content/en/blog/introduction-to-fetch/index.md, src/site/content/en/blog/keyboard-lock/index.md, src/site/content/en/blog/media-capturing-images/index.md, src/site/content/en/blog/more-capable-form-controls/index.md, src/site/content/en/blog/notifications-quick/index.md, src/site/content/en/blog/pagevisibility-intro/index.md, src/site/content/en/blog/persistent-storage/index.md, src/site/content/en/blog/pointerlock-intro/index.md, src/site/content/en/blog/push-notifications-common-notification-patterns/index.md, src/site/content/en/blog/push-notifications-how-push-works/index.md, src/site/content/en/blog/push-notifications-subscribing-a-user/index.md, src/site/content/en/blog/reporting-observer/index.md, src/site/content/en/blog/resize-observer/index.md, src/site/content/en/blog/sanitizer/index.md
=> Adding compat widget 2

src/site/content/en/learn/pwa/serving/index.md
Removes outdated link
Fixes #9002
=> Fixes #9002 - Removes outdated link

src/site/content/en/blog/animating-modal-views/index.md
Fixes #9029
Subheading is my own but both sentences are pulled directly from the article
=> Animating modal views: subheading

src/site/content/en/blog/accessibility-week-2022/index.md
https://deploy-preview-9087--web-dev-staging.netlify.app/accessibility-week-2022/
=> A11y Week blog post

src/site/content/en/blog/color-scheme/index.md, src/site/content/en/blog/content-indexing-api/index.md, src/site/content/en/learn/pwa/detection/index.md, src/site/content/en/learn/pwa/offline-data/index.md, src/site/content/en/learn/pwa/os-integration/index.md, src/site/content/en/learn/pwa/serving/index.md, src/site/content/en/learn/pwa/windows/index.md, src/site/content/en/lighthouse-best-practices/appcache-manifest/index.md, src/site/content/en/lighthouse-best-practices/uses-passive-event-listeners/index.md, src/site/content/en/lighthouse-performance/uses-rel-preconnect/index.md, src/site/content/en/lighthouse-performance/uses-rel-preload/index.md, src/site/content/en/lighthouse-pwa/service-worker/index.md, src/site/content/en/lighthouse-pwa/themed-omnibox/index.md, src/site/content/en/metrics/custom-metrics/index.md, src/site/content/en/notifications/codelab-notifications-get-started/index.md, src/site/content/en/payments/android-payment-apps-developers-guide/index.md, src/site/content/en/progressive-web-apps/add-manifest/index.md, src/site/content/en/reliable/service-workers-cache-storage/index.md, src/site/content/en/reliable/two-way-communication-guide/index.md, src/site/content/en/secure/assess-spam-damage/index.md, src/site/content/en/secure/fixing-mixed-content/index.md, src/site/content/en/secure/fixing-the-cloaked-keywords-hack/index.md
=> Adding compat widget 5

src/site/content/es/blog/variable-fonts/index.md
- Add oldschool hacks tip (verified by native speaker).
=> [Variable Fonts article] Add oldschool hacks tip

src/site/_data/i18n/footer.yml
=> Internalization: 'Contribute' in footer

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/pwas-on-oculus-2/index.md
=> Update "PWAs on Oculus 2" blog post

src/site/content/en/learn/pwa/windows/index.md
=> [Learn][PWA] Replacing WebM with iOS-friendly MP4

src/site/content/es/blog/variable-fonts/index.md
Via:
- https://github.com/GoogleChrome/web.dev/pull/9096#discussion_r1028072206
- https://github.com/GoogleChrome/web.dev/pull/9096#discussion_r1028076779
=> [Variable Fonts article] More Spanish language refinements

src/site/content/en/blog/add-touch-to-your-site/index.md
Fixes #9122
- Close unclosed css code block
- Fix 2 typos in the css code block
=> Close code block

src/site/content/en/blog/registering-a-custom-protocol-handler/index.md
Fixes #9068
- broken MDN link is fixed
=> Fix link to mdn on custom protocol handler page

src/site/content/en/fast/use-lighthouse-for-performance-budgets/index.md
- Adds an aside to the top of the [Lighthouse perf budgets guide](https://web.dev/use-lighthouse-for-performance-budgets/) to emphasize the importance of field data.
=> Adds aside on the importance of field data.

src/site/content/en/blog/viewport-units/index.md
Fixes #8864.
Feel free to adjust the publication date, as long as it’s before/around the M108 release date _(2022-11-29)_.
=> Add viewport-units blogpost (#8864)

src/site/content/en/fast/serve-responsive-images/index.md
- Adds guidance around LCP on the [serve responsive images guide](https://web.dev/serve-responsive-images/).
=> Adds LCP guidance.

src/site/content/en/blog/iframe-lazy-loading/index.md
- Adds an additional paragraph about the effects of lazy loading offscreen iframes and bandwidth contention, and possible effects on LCP.
=> Adds note about LCP.

src/site/content/en/blog/long-tasks-devtools/index.md
- Adds a note about INP thresholds vs RAIL thresholds and a link to the optimize long tasks guide in [this guide about long tasks](https://web.dev/long-tasks-devtools/).
=> Adds INP note, links to optimize long tasks guide.

src/site/content/en/blog/tabbed-application-mode/index.md
=> [Tabbed Application Mode article] Update demo

redirects.yaml
=> Add redirect for `/webgpu`

src/site/content/en/blog/content-visibility/index.md
- The `content-visibility` property as discussed in [this article](https://web.dev/content-visibility/) has the potential to affect a page's INP. This PR adds a note on that possibility.
=> Adds guidance around content-visibility per INP.

src/site/content/zh/blog/trusted-types/index.md
=> Fix the entity symbols of code, which has been sanitized

src/site/content/en/learn/accessibility/design-ux/index.md, src/site/content/en/learn/accessibility/javascript/index.md
- Adds additional code styling + explainer links
https://deploy-preview-9181--web-dev-staging.netlify.app/learn/accessibility/javascript/
Updates PNG for venn diagram
https://deploy-preview-9181--web-dev-staging.netlify.app/learn/accessibility/design-ux/
=> Learn A11y JS module nits

src/site/content/en/progressive-web-apps/add-manifest/index.md
@tropicadri Please review content.
Live preview: https://deploy-preview-8677--web-dev-staging.netlify.app/add-manifest/#screenshots
=> Add form_factor manifest property

src/site/content/en/animations/animations-guide/index.md, src/site/content/en/blog/animations-and-performance/index.md, src/site/content/en/blog/optimize-cls/index.md, src/site/content/en/blog/rendering-performance/index.md, src/site/content/es/blog/optimize-cls/index.md, src/site/content/pt/blog/optimize-cls/index.md
Domain was bought so content is now outdated
Fixes #9182
=> Remove csstriggers.com links

src/site/content/en/blog/squoosh-v2/index.md
These changes come to fix the command to install squoosh
- fixes the documentation command responsable of installing squoosh
=> Fix install command for squoosh in announcement blog article

src/site/content/en/blog/components-howto-checkbox/index.md, src/site/content/en/blog/service-workers-registration/index.md
From PRs with unsigned CLAs:
#9103 
#8668
=> Community typo fixes 

src/site/content/en/learn/accessibility/javascript/index.md
=> Broken links learn/accessibility

src/site/content/en/blog/optimize-inp/index.md
- The subhead in the [Optimize INP guide](https://web.dev/optimize-inp/) incorrectly references LCP.
=> Corrects optimize INP subheader.

src/site/content/en/learn/html/index.md
I have switched to Mastodon and no longer use Twitter; so if people have questions....
=> Updated bio: Twitter URL to Mastodon URL

src/site/content/en/learn/html/navigation/index.md
=> Fix some images

src/site/content/en/blog/webpack/index.md
Fixes #9218 
-Update 404 broken links
=> Fix broken links

src/site/content/en/learn/accessibility/color-contrast/index.md
I noticed an oversight about font sizes and ratios in the color contrast module. This should help fill in some gaps related to the upcoming testing module. Tagging @heyawhite on this PR.
=> Learn accessibility course - color contrast module

src/site/content/en/learn/html/attributes/index.md
Fixes: https://github.com/GoogleChrome/web.dev/issues/9237
=> fix: dataset key typo

src/site/content/en/identity/passkey-form-autofill/index.md
Update passkey form autofill article with more detailed contents.
=> Update passkey form autofill article

src/site/content/en/identity/passkey-form-autofill/index.md, src/site/content/en/identity/passkey-registration/index.md
Update create a passkey article
=> Update create a passkey article

src/site/content/en/blog/howbrowserswork/index.md
This just adds a space between chrome and all, which helps reading better even for screen readers.
=> Adds a space between chrome and all

src/site/content/en/blog/interop-2022-wrapup/index.md
Preview: https://deploy-preview-9267--web-dev-staging.netlify.app/interop-2022-wrapup/
=> Interop 2022 EOY post.

src/site/content/en/blog/interop-2022-wrapup/index.md
=> Fixing a date

src/site/content/en/learn/html/navigation/navigation.assess.yml
Fixes a small typo within navigation assessment.
=> fix: typo within navigation assessment

src/site/content/en/blog/web-platform-12-2022/index.md
=> December web platform post

src/site/content/en/fast/navigation-and-resource-timing/index.md
"If you want measure" => "if you want to measure"
=> Fix simple typo

src/site/content/en/blog/async-functions/index.md
Just a quick example improvement.
=> Simplify markHandled code in async functions article

src/site/content/en/blog/top-cwv-2023/index.md
Fixes https://github.com/GoogleChrome/web.dev/issues/8928
Staging: https://deploy-preview-9374--web-dev-staging.netlify.app/top-cwv-2023/
=> Top CWV recommendations blog post

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml
=> Author profile: Aaron Forinton

src/site/content/en/patterns/animation/animated-letters/assets/body.html
Fixes #9389
- change example html text to to matched rendered animation
=> fixed example html to correctly reflect animation

src/site/content/ru/blog/text-fragments/index.md
=> Update text-fragments image

src/site/content/en/learn/accessibility/test-assistive-technology/index.md, src/site/content/en/learn/accessibility/test-automated/index.md, src/site/content/en/learn/accessibility/test-manual/index.md
https://deploy-preview-9392--web-dev-staging.netlify.app/learn/accessibility/test-manual/
=> Fix spacing for Learn A11y modules

src/scss/pages/_about.scss, src/scss/utilities/_wrapper.scss
Fixes #9334
- Fix minor styling broken on 'On this site' and The team' sections
=> Fix: minor styling broken on the about page

src/site/content/en/learn/html/headings-and-sections/index.md
The table of contents showed that the heading levels were off. this should fix it.
=> Learning HTML: heading levels

src/site/content/en/blog/nikkei/index.md, src/site/content/en/fast/how-to-measure-speed/index.md, src/site/content/en/learn/accessibility/more-html/index.md
=> Community issue fixes

.github/workflows/percy-workflow.yml, redirects.yaml, src/site/_collections/blog-posts-descending.js, src/site/_collections/hooks/authors.js, src/site/_collections/hooks/utils.js, src/site/content/en/handbook/content-types/content-types.11tydata.js, src/site/content/en/handbook/content-types/example-landing-page/index.njk, src/site/content/en/handbook/content-types/example-post/index.md, src/site/content/en/handbook/content-types/index.md, src/site/content/en/metrics/inp/index.md, tools/percy/snapshots.js
First steps towards: #9369 
- Adds new pages to handbook/content-types
- Uses the new pages for visual testing.
=> Percy revamp.

package-lock.json, src/site/_data/paths/fast.json, src/site/content/en/blog/optimize-ttfb/index.md, src/site/content/en/metrics/ttfb/index.md
- Adds the Optimize Time to First Byte guide.
=> Adds the optimize time to first byte guide.

src/site/content/en/blog/web-share/index.md
- Fix typo
- Remove unneeded punctuation
=> Fix minor errors in web share article

src/site/content/en/blog/optimize-ttfb/index.md
- Adjusts copy in the [Optimize TTFB guide](https://web.dev/optimize-ttfb/) per [this tweet](https://twitter.com/simevidas/status/1616208190483402782).
cc: @simevidas
=> Tweaks language around relative TTFB values.

src/site/content/en/blog/gpu-compute/index.md
This PR Updates WGSL shader module code with new WGSL aliases:
- https://www.w3.org/TR/WGSL/#vec3u
- https://www.w3.org/TR/WGSL/#vec2f
@Kangz Please review.
=> Update WGSL shader module code

src/site/content/en/blog/webtransport/index.md
This PR aims to fix issues with the "Using WebTransport" article that had arisen due to spec changes after the article was originally written.  In this PR, the following changes have been performed:
- Update all interface names to retain parity with spec
- Fix all examples to use the correct method names
- Fix spec links to point to current specs (or correct parts of specs)
- Correct formatting in select locations
- Update the "last updated" date (has not been changed within the last few commits)
See https://github.com/mdn/browser-compat-data/pull/18638 for the inspiration and research behind these changes.
=> Fix "Using WebTransport" article

src/site/content/en/blog/optimizing-content-efficiency-loading-third-party-javascript/index.md
=> Update load third-party JavaScript page

src/site/content/en/identity/passkey-registration/index.md
- turn html entities into human-readable characters at https://web.dev/passkey-registration/
=> fix(content): turn html entities into human-readable characters

src/site/content/en/blog/optimize-inp/index.md
- One of the action items for the Optimize INP doc was to add a workflow on using Lighthouse's timespan mode to diagnose slow interactions. This PR adds that info.
=> Updates the Optimize INP guide with info on Lighthouse's timespan mode.

src/site/content/en/metrics/ttfb/index.md
Ports changes in #9429 to the other reference of this.
=> Syncs TTFB aside

src/site/content/en/blog/optimize-inp/index.md
Also fixes a stray open bracket.
=> Tweak tag manager wording for optimizing INP post

src/site/content/en/secure/same-site-same-origin/index.md
Fixes #9241 
Clarify that "same-site" is now schemeful rather than schemeless.
cc: @domenic @recvfrom
=> Same site same origin update

src/site/content/en/blog/web-platform-01-2023/index.md
Adds the web platform post for January.
=> web platform january post

src/site/content/en/blog/critical-rendering-path/index.md
- Add links to web.dev and MDN articles about Critical Rendering Path
=> Add links to related web.dev and MDN articles

src/site/content/en/mini-apps/mini-app-alternative-runtime-environments/index.md
=> Update VK Mini Apps docs link

src/site/content/en/blog/interop-2023/index.md
=> Interop 2023 post

src/site/content/en/blog/web-share/index.md
- Add new third-party requirements
=> [Web Share article] Add new third-party requirements

src/site/content/en/blog/gamepad/index.md
=> [Gamepad article] Better function name

src/site/content/en/blog/interop-2023/index.md
Updates to the interop 2023 blog post, additional detail on category "Fonts".
=> Differentiate "fonts" topic, add links

README.md
=> Removing broken image from readme

src/scss/blocks/_site-footer.scss, src/site/_data/i18n/footer.yml, src/site/_includes/partials/site-footer.njk
Fixes https://github.com/GoogleChrome/web.dev/issues/9372
- Update site footer following the design provided by Dan
=> feat: update site footer

src/site/content/en/blog/bfcache/index.md
- Adds note about new lighthouse bfcache audit to the doc
=> bfcache doc update to mention Lighthouse audit

src/site/content/en/learn/design/responsive-images/index.md
=> Fixing minor typos in Responsive Images section

src/site/content/en/learn/design/theming/index.md
=> Fixing minor typo

src/site/content/en/blog/websockets-basics/index.md
=> Fix outdated reference links for WebSockets API 

src/site/content/en/blog/cq-stable/index.md
Article on size container query and container query unit values going stable
=> CQ Stable Post

src/site/content/en/blog/workers-basics/index.md
Fixes #9549 
Janitorial (page is 10+ years old)
=> Update broken reference links in Web Workers intro

src/site/content/en/learn/accessibility/structure/index.md
=> Fix broken link to W3 in Learn Accessibility

src/site/content/en/learn/forms/security-privacy/index.md
=> Remove aside from Learn Forms about aria-hidden

src/site/content/en/learn/images/performance-issues/index.md
=> Fixing minor typos

src/site/_data/courses/html/toc.yml, src/site/content/en/blog/learn-html-available/index.md, src/site/content/en/learn/html/apis/apis.assess.yml, src/site/content/en/learn/html/apis/index.md, src/site/content/en/learn/html/audio-video/audio-video.assess.yml, src/site/content/en/learn/html/audio-video/index.md, src/site/content/en/learn/html/conclusion/index.md, src/site/content/en/learn/html/details/details.assess.yml, src/site/content/en/learn/html/details/index.md, src/site/content/en/learn/html/dialog/dialog.assess.yml, src/site/content/en/learn/html/dialog/index.md, src/site/content/en/learn/html/focus/focus.assess.yml, src/site/content/en/learn/html/focus/index.md, src/site/content/en/learn/html/forms/forms.assess.yml, src/site/content/en/learn/html/forms/index.md, src/site/content/en/learn/html/images/images.assess.yml, src/site/content/en/learn/html/images/index.md, src/site/content/en/learn/html/inline-text/index.md, src/site/content/en/learn/html/inline-text/inline-text.assess.yml, src/site/content/en/learn/html/template/index.md, src/site/content/en/learn/html/template/template.assess.yml
Includes:
Chapter 12 - Forms
Chapter 13 - Images
Chapter 14 - Video and audio
Chapter 15 - `<template>,` `<slot>`, and `<shadow>`
Chapter 16 - The DOM tree and APIs
Chapter 17 - Focus order
Chapter 18 - Other inline text elements
Chapter 19 - Details and summary
Chapter 20 - Dialog
=> Learn HTML (modules 12-20)

src/site/content/en/learn/html/images/index.md
Fixes two typos (no issue number)
- Added a missing quote character
- Removed duplicate text
=> Fixed two typos

src/site/content/en/blog/lighthouse-ci/index.md
Fixes #9360 
- Updated instructions to add the repository secret into the github workflow file
Individual CLA signed, Mark Vogelgesang
=> Added step to place secret within workflow

src/site/content/en/learn/css/animations/index.md, src/site/content/en/learn/css/backgrounds/index.md, src/site/content/en/learn/css/blend-modes/index.md, src/site/content/en/learn/css/borders/index.md, src/site/content/en/learn/css/filters/index.md, src/site/content/en/learn/css/flexbox/index.md, src/site/content/en/learn/css/focus/index.md, src/site/content/en/learn/css/functions/index.md, src/site/content/en/learn/css/gradients/index.md, src/site/content/en/learn/css/grid/index.md, src/site/content/en/learn/css/layout/index.md, src/site/content/en/learn/css/lists/index.md, src/site/content/en/learn/css/logical-properties/index.md, src/site/content/en/learn/css/overflow/index.md, src/site/content/en/learn/css/pseudo-classes/index.md, src/site/content/en/learn/css/pseudo-elements/index.md, src/site/content/en/learn/css/selectors/index.md, src/site/content/en/learn/css/shadows/index.md, src/site/content/en/learn/css/spacing/index.md, src/site/content/en/learn/css/transitions/index.md, src/site/content/en/learn/css/typography/index.md, src/site/content/en/learn/css/z-index/index.md
=> consistency, linking

src/site/content/en/blog/pwa-install-addressbar/index.md
Sorry, but didn't read any contributing guidelines … just spotted this typo and would like to see it fixed 🙈
=> Just a tiny typo

redirects.yaml
- Adds a redirect (mostly as a short URL).
=> Add Fugu Showcase redirect

src/site/content/en/learn/html/document-structure/index.md
Fixing a broken link.
Fixes #9641
=> Fixing Broken Link (#9641)

src/site/content/pt/fast/browser-level-image-lazy-loading/index.md
- Correction of typo in the portuguese version of the article
=> Typo fixes

src/site/content/en/learn/pwa/service-workers/index.md
Fix two typos, one of which is critical.
-
-
-
=> Fix typos in service worker article.

src/site/content/en/learn/html/attributes/index.md
=> Learn HTML minor fixes

src/site/content/en/learn/pwa/complexity/index.md
=> Fix Learn PWA typo

src/site/content/en/learn/html/document-structure/index.md
=> Fix learn HTML documents typo

src/site/content/ja/blog/coop-coep/index.md
=> Add closing "`"

src/site/content/en/learn/images/descriptive/index.md
- Update text describing x descriptor to match the preceding code example.
=> Match x descriptor explanation with code snippet

src/site/_data/i18n/header.yml
=> fixing a typo in spanish

src/site/content/en/learn/html/text-basics/index.md
- Fix a few minor errors of the html entities
=> Fix the html number of some html entities

src/site/content/en/blog/media-session/index.md
This PR adds presenting slides actions to the media session API article. This article needs to be published when ~~Chrome 110 reaches Beta channel (January 12nd, 2023)~~ Chrome 111 reaches Beta channel (Thu, Feb 9, 2023)  
Live preview: https://deploy-preview-9210--web-dev-staging.netlify.app/media-session/#presenting-slides-actions
See https://chromestatus.com/feature/5090980649238528
=> Add presenting slides actions to media session article

src/site/content/en/learn/html/forms/index.md
Fixes #9708
- Aligns the working example with the written example
=> Fix form example

src/site/_includes/components/Instruction.js
Fixes #8319
- Looks like the Glitch UI has changed a bit so updating the instructions
=> Update Glitch console instructions

src/site/content/en/metrics/lcp/index.md
=> Clarify svg and video support for LCP

src/site/content/en/fast/defer-non-critical-css/index.md
Fixes #8108
- Adds note about CSP
- Adds not about end of body CSS links
=> Clarify async CSS and CSP support

src/site/content/en/blog/css-trig-functions/index.md
=> Add css-trig-functions blog post

src/site/content/en/learn/pwa/serving/index.md
=> fixing code snippet in learn/PWA

src/site/content/en/blog/variable-fonts/index.md
=> Correct --GRAD variable case

src/site/content/en/learn/html/apis/index.md, src/site/content/en/learn/html/audio-video/index.md, src/site/content/en/learn/html/conclusion/index.md, src/site/content/en/learn/html/details/index.md, src/site/content/en/learn/html/dialog/index.md, src/site/content/en/learn/html/focus/index.md, src/site/content/en/learn/html/forms/index.md, src/site/content/en/learn/html/images/index.md, src/site/content/en/learn/html/inline-text/index.md, src/site/content/en/learn/html/navigation/index.md, src/site/content/en/learn/html/template/index.md
=> Fix Learn HTML dates

src/site/content/en/learn/css/flexbox/index.md
=> Add `flex-basis` link 

src/lib/components/LearnFilter/index.js, src/lib/components/ProfileSwitcher/_styles.scss, src/lib/components/ProfileSwitcher/index.js, src/lib/components/ProfileSwitcherContainer/index.js, src/site/_includes/macros/tag-chips.njk, src/site/_includes/partials/footer.njk, src/site/_includes/partials/site-footer.njk, src/styles/components/_chips.scss, src/styles/components/_footer.scss
Fixes #9706 
- Rename all class names from `w-chips` to `chips`
- Rename all class names from `w-footer` to `site-footer`
- Rename all class names from `w-profile-` to `profile-`
=> feat: rename existing w- prefixed class name

src/site/content/en/blog/6-css-snippets-every-front-end-developer-should-know-in-2023/index.md
=> New post - 6 CSS snippets

src/site/content/en/learn/design/responsive-images/index.md
- Fixes the markdown link syntax
=> Fix Markdown link

src/site/content/en/metrics/lcp/index.md
=> Correct LCP last updated date

src/site/content/en/blog/import-maps-in-all-modern-browsers/index.md
=> Add import maps on all modern browsers article

src/site/content/en/blog/push-notifications-in-all-modern-browsers/index.md
=> Fix compat

src/site/content/en/blog/push-notifications-in-all-modern-browsers/index.md
=> [Push notifications article] Split aside in two

.eleventy.js, package-lock.json, package.json, src/site/_transforms/minify-html.js
Reverts GoogleChrome/web.dev#9833
=> Revert "fix: space missing between two HTML tags on the aside component"

src/site/_includes/homepage.njk, src/site/content/en/index.md
- Adds a newline to featured card title to appease @samdutton 's nits
=> Fix Featured Card title

src/site/_data/paths/progressive-web-apps.json, src/site/content/en/progressive-web-apps/pwas-in-app-stores/index.md
=> Add PWABuilder article

src/site/content/en/blog/wasm-libraries/index.md
- Fixes link to Chromium dev blog post in WASM libraries post.
=> Fixes link to Chromium dev blog post in WASM libraries post.

src/site/content/en/learn/html/audio-video/index.md
Fixes: #9819 by removing extra quote.
=> Remove misplaced quote.

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/slow-roads/index.md
Blog post on slowroads.io by [https://anslo.dev/](https://anslo.dev/)
=> Slow Roads post

src/site/content/en/learn/css/borders/index.md
Added inline codeblock around a border property for better readability.
=> Added inline codeblock for a border property

src/site/content/en/blog/wasm-libraries/index.md
- Simple text edit to correct Universal Scene Description text
=> Fix Universal Scene Description header

src/site/content/en/blog/css-props-and-vals/index.md
=> Remove an extra comma from CSS `--stop-color` code sample

src/site/content/en/learn/accessibility/structure/index.md
=> Fix learn accessibility code marks

src/site/content/en/learn/css/color/index.md
first step towards learn css offering a wide gamut color module
=> adds HD color guide from DCC to learn/css/color resource list

src/site/content/en/metrics/cls/index.md
Fixes #9329 
- Fixes screenshot and calc as discussed in #9329
=> Fix cls example

src/site/content/en/blog/browser-level-lazy-loading-for-cmss/index.md
- Just fixing a broken link on /browser-level-lazy-loading-for-cmss/
=> Updated broken link

src/site/content/en/blog/custom-elements-v1/index.md, src/site/content/en/blog/web-animations/index.md, src/site/content/en/blog/webcomponents-org/index.md
=> Fix broken links to Mozilla Specification Positions

src/site/content/en/fast/chrome-ux-report/index.md
Updates the CrUX references on web.dev as requested by @powdercloud
=> CrUX doc updates

src/site/content/en/blog/wasm-av1/index.md
=> Extending the browser with WebAssembly article: Fix links

src/site/content/en/blog/service-worker-perf/index.md, src/site/content/en/blog/world-wide-maze/index.md, src/site/content/ja/blog/bfcache/index.md
Follow up to #9956 
- Fix links with backticks.
=> Fix more backtick links

src/site/content/en/blog/emscripting-a-c-library/index.md, src/site/content/en/blog/optimizing-content-efficiency-save-data/index.md, src/site/content/en/blog/performance-audit-tools/index.md, src/site/content/en/blog/performance-audit/index.md, src/site/content/en/blog/performance-optimizing-content-efficiency-client-hints/index.md
Supercedes #9958 
- Fixes links
=> Fix speed links

src/site/content/en/blog/loading-wasm/index.md
- Remove mention of webassembly.studio, since it is no more.
=> Remove mention of webassembly.studio

src/site/content/en/fast/use-imagemin-to-compress-images/index.md, src/site/content/es/fast/use-imagemin-to-compress-images/index.md, src/site/content/ja/fast/use-imagemin-to-compress-images/index.md, src/site/content/ko/fast/use-imagemin-to-compress-images/index.md, src/site/content/pt/fast/use-imagemin-to-compress-images/index.md, src/site/content/ru/fast/use-imagemin-to-compress-images/index.md, src/site/content/zh/fast/use-imagemin-to-compress-images/index.md
Imagemin-svgo -> imagemin-svgo
=> use-imagemin-to-compress-images: normalize plugin case

src/site/content/en/learn/html/navigation/index.md
=> `aria` typo fix

src/site/content/en/fast/use-imagemin-to-compress-images/index.md, src/site/content/es/fast/use-imagemin-to-compress-images/index.md, src/site/content/ja/fast/use-imagemin-to-compress-images/index.md, src/site/content/ko/fast/use-imagemin-to-compress-images/index.md, src/site/content/pt/fast/use-imagemin-to-compress-images/index.md, src/site/content/ru/fast/use-imagemin-to-compress-images/index.md, src/site/content/zh/fast/use-imagemin-to-compress-images/index.md
imagemin-webp supports both lossy and lossless encodes since version
2.0.0
=> use-imagemin-to-compress-images: add imagemin-webp to lossless

src/site/content/en/learn/html/document-structure/index.md
=> Learn HTML `alternate stylesheet` typo

src/site/content/en/secure/build-a-support-team/index.md, src/site/content/en/secure/clean-and-maintain-your-site/index.md, src/site/content/en/secure/request-a-review/index.md
=> Remove StopBadware.org links

src/site/content/en/blog/debug-cwvs-with-web-vitals-extension/index.md
=> Missed subtitle in CWV extension post

src/site/content/en/blog/optimize-inp/index.md
https://web.dev/optimize-inp/#conclusion
=> Italicize hero image credit on Optimize INP

src/site/content/en/blog/inp-cwv/index.md
- Adds link to the search console blog post in the INP announcement.
=> Adds link to the search console blog post in the INP announcement.

src/site/_data/site.js, src/site/content/en/baseline/index.md, src/site/content/en/index.md
=> Links and banners

src/site/content/en/vitals/index.md
Call out to the INP announcement at the top of the Web Vitals page.
=> Update /vitals "new" aside

src/site/content/en/how-to-optimize-inp/client-side-rendering-of-html-and-interactivity/index.md
Found the image via unsplashs image search.
=> fix: add hero image source

src/lib/analytics.js, src/site/_data/site.js, types/modules/webdev_analytics/index.d.ts
Noticed a bug in our move to GTM.
- Fix Navigation Type by pushing to data layer instead of using custom dimension
- Remove Custom Dimensions as no longer used
=> Fix back/forward cache analytics

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/economic-times-inp/index.md
- Adds coauthors (`daya`, `barunkumar`) to [Economic Times INP case study](https://web.dev/economic-times-inp/).
=> Adds coauthors to Economic Times INP case study.

src/site/content/en/blog/optimizing-content-efficiency-javascript-startup-optimization/index.md
- Fix `memory-leaks` link on this page https://web.dev/optimizing-content-efficiency-javascript-startup-optimization/
=> Fix broken link `memory-leaks`

src/site/content/en/blog/avoid-large-complex-layouts-and-layout-thrashing/index.md, src/site/content/en/blog/optimize-inp/index.md, src/site/content/en/how-to-optimize-inp/client-side-rendering-of-html-and-interactivity/index.md, src/site/content/en/how-to-optimize-inp/dom-size-and-interactivity/index.md, src/site/content/en/how-to-optimize-inp/script-evaluation-and-long-tasks/index.md
- There were a few unsightly spacing issues in the objective asides for the new INP docs. This makes a few cosmetic changes to fix those issues.
=> Fixes spacing issues in objective asides in INP docs.

src/site/_includes/partials/toc-inner.njk, src/site/_includes/partials/toc-side.njk
=> Activate side nav on lg breakpoint

src/site/content/en/learn-core-web-vitals/crux-and-rum-differences/index.md
It appears I'm date dyslexic.
Got this wrong in #9514
=> Fix (another) date

src/site/content/en/blog/baseline-features/index.md
Fixes #10078
- Add missing space between words
=> Baseline features: Add missing space

src/site/_data/authorsData.json
Adding rviscomi.dev to my author metadata
=> Add my website to author metadata

src/site/content/en/blog/media-capturing-images/index.md
Change proposed in this pull request:
- fix misleading error in code snippet
not sure what the `<strong>` element was intended for
=> docs: fix misleading error in code snippet

src/scss/next.scss
Fixes #10103 - looks like this was broken by #10083 at my request :-(
- Sets a max width on content to prevent it overflow.
=> Fix menu on Courses

src/site/content/en/blog/text-fragments/index.md
- Fix code sample while https://github.com/GoogleChromeLabs/text-fragments-polyfill/pull/148 is still pending.
=> [Text Fragments article] Fix code sample

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/_data/paths/secure.json, src/site/content/en/secure/securely-hosting-user-data/index.md
Preview: https://deploy-preview-10134--web-dev-staging.netlify.app/securely-hosting-user-data/
https://deploy-preview-10134--web-dev-staging.netlify.app/secure/#protect-websites-from-xss
=> Securely hosting data article

.eleventy.js
=> Download hero images to dist

src/site/_data/authorsData.json, src/site/content/en/blog/goibibo/index.md
=> Author fixes

src/site/content/en/index.md
=> Update homepage to redbus case study

src/site/content/en/metrics/tti/index.md
- Fixes spelling in TTI web metric
=> Fix spelling in TTI metric

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml
=> [ta] Add Ramona as an author

src/site/content/es/blog/optimize-fid/index.md
- Fix the Spanish typo on Optimize FID post.
=> Fix Spanish typo

src/site/content/en/blog/optimize-lcp/index.md
- Adds an initial workflow to check LCP before launching into the detailed LCP breakdown (similar to recent Optimize CLS updates)
- Notes a couple of common causes for slow TTFB in an otherwise fast site.
=> Update Optimize LCP guide with details on checking your LCP

src/site/content/en/blog/ta-strategies/index.md
=> [ta] 02 - Pyramid or Crab? Find a testing strategy that fits 

src/site/content/en/blog/variable-fonts/index.md
=> Fix syntax of variable fonts article

src/site/_data/paths/webassembly.json
- Add WebGPU article to Wasm collection
=> Add WebGPU article to Wasm collection

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/blog/yahoo-japan-news-bfcache/index.md
- Adds bfcache case study for Yahoo JAPAN News
- Removes Twitter link for author `jlwagner`.
=> Adds bfcache case study for Yahoo JAPAN News

src/site/content/en/blog/yahoo-japan-news-bfcache/index.md
- Spruces up the [bfcache case study article](https://web.dev/yahoo-japan-news-bfcache/)
=> Fixes up some copy, and a video display issue for the bfcache case study

src/site/content/en/blog/ta-strategies/index.md
Merge directly to main after approval
=> Remove schedule flag

redirects.yaml
Redirect /opfs to /origin-private-file-system/.
=> Add opfs redirect

src/site/_data/authorsData.json, src/site/_data/i18n/authors.yml, src/site/content/en/identity/passkey-google-ux/index.md
Add a new article about passkeys UX at Google.
Add new authors: mitchgalavan, cjacinic and silviaconvento.
=> Add an article about passkeys UX at Google

src/site/content/en/blog/adapting-typography-to-user-preferences-with-css/index.md
To do:
- get final review(s)
- consider a better link to the font file
- update publish date
=> Post - Adapting typography to user preferences with CSS

src/site/content/en/blog/ta-types/index.md
=> Edits for Test automation post 1

src/site/content/en/learn-core-web-vitals/crux-and-rum-differences/index.md, src/site/content/en/learn-core-web-vitals/lab-and-field-data-differences/index.md, src/site/content/en/metrics/lcp/index.md
- Adds information on newly supported use cases for LCP.
=> Adds new element candidates for the LCP metric doc.

src/site/content/en/blog/ta-strategies/index.md
Tiny bugfix for the table in the 'Pyramid or Crab? Find a testing strategy that fits' article
=> Fix table in 'ta-strategies' blog article

src/site/content/en/handbook/case-study-guidelines/index.md
- We currently lack cross-posting guidelines on case studies. This adds new guidelines on that particular problem.
=> Adds new case study guidelines on cross-posting.

src/site/content/en/blog/ta-test-cases/index.md
@jecfish, is the hero image ok? Feel free to suggest a better one.
Fixes #10227
=> [ta] 03 - Defining test cases and priorities

src/site/content/en/blog/ta-what-to-test/index.md
This is LGTM'ed and approved, only needs a rubber stamp. To be published today.
=> Test Automation article 4: To test or not to test, a technical perspective

src/site/content/en/blog/terra-prefetching-case-study/index.md
- Adds engineer names from Terra in footnote.
=> Adds engineer names from Terra in footnote.

src/site/_data/authorsData.json
- Update authorsData.json for Nandu Nair
=> Update authorsData.json for Nandu Nair

src/site/_includes/partials/head.njk
Web.dev equivalent of https://github.com/GoogleChrome/developer.chrome.com/pull/7361
=> Renew prerender OT token

package-lock.json, package.json
=> Bump Web Vitals to 3.5.0

src/site/_data/paths/fast.json, src/site/_data/paths/learn-core-web-vitals.json, src/site/content/en/blog/vitals-tools/index.md
- Updates [Web Vitals tools post](https://web.dev/vitals-tools/) with latest changes and guidance
- Links from Fast collection and also adds INP to Core Web Vitals section now it is a pending CWV.
- Adds INP to Core Web Vitals section of Learn Core Web Vitals now it is a pending CWV.
=> Update Web Vitals tool post with latest changes and guidance

src/site/content/en/blog/ta-code-coverage/index.md
Address https://twitter.com/HCornflower/status/1699809944697008427
=> [ta] Fix typo
